### ISSUE TITLE
GNOME's Screenshot tool doesn't make sound

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/cinnamon#10046]
```
 * Cinnamon version 4.8.6
 * Distribution - Ubuntu Cinnamon Remix 21.04 Hirsute Hippo (development branch: RC stage)
 * Intel i5-7200U, Intel HD Graphics 620
 * Sound if curious: Corsair HS35 headset. Bug reproduced on with/without it.
 * 64 bit
 * syslog: https://termbin.com/l638
 * xsession errors: https://termbin.com/i8it
 ```

**Issue**
When taking a screenshot using gnome-screenshot, selected or fullscreen, no sound plays.

**Steps to reproduce**
Take a screenshot in Cinnamon.

**Expected behaviour**
A sound *should* hopefully be able to play? I remember it doing so in GNOME. I'll have to look at screenshot's source code.

**Other information**
None should be required.

**Comment by mtwebster** [comment]
This is governed by the 'event-sounds' key:
![image](https://user-images.githubusercontent.com/262776/114881457-0a367980-9dd1-11eb-94d5-2dcedd58eb96.png)

It's off by default, because it's mainly intended for accessibility helpers (it gets turned on, for instance, if you 'enable audio alerts' in cinnamon's accessibility settings.

**Comment by ItzSwirlz** [comment]
Okay then; so i'll close this issue I guess? maybe i'll just be overriding event-sounds for gnome-screenshot but that may not be the best option.. I'll reopen if I can find a doable solution.
