### ISSUE TITLE
[Feature request] Bluetooth applet

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/cinnamon#10068]
As of version 4.8.6 there seems to be no Bluetooth applet. Left-clicking on the Bluetooth tray icon opens a blueberry window. Right-clicking opens a very limited menu.

It seems that there used to be an applet, but it was removed for some reason (for example see screenshot in #3602).

I believe having an applet (similar to the `network@cinnamon.org` applet) would make the interface a lot easier to use. For the same reasons that `network@cinnamon.org` exists. Less mouse travel, automatic closing when you click outside the applet, visual consistency.

**Comment by ItzSwirlz** [comment]
Just use blueberry, bluez and/or gnome-bluetooth

**Comment by NikoKrause** [comment]
You are right. There was a Cinnamon Applet in the past. It was dropped/removed in favor of a cross-DE solution, i.e. the applet only worked in Cinnamon. But Mint ships also with other desktop environments as MATE and Xfce. 

Since there's a solution, which works in all 3 DEs, the Cinnamon applet was just extra work to maintain.

https://github.com/linuxmint/blueberry/commit/4f42d0466aaebbb446a4eaff85b71bced7e7d8d2
