### ISSUE TITLE
New Menu breaks some search providers

### ISSUE THREAD

**Issue by gkatev** [linuxmint/cinnamon#10145]
```
Cinnamon 5.0.2
Arch Linux
 ```

Hi, after upgrading from 4.8.6, I've noticed that my calculator search provider has not been working correctly.
(docs/search-providers-examples/calc@cinnamon.org)

From a quick look-around, it seems that it might be due to commit 841b47ec044cfa2933a01c4548bebdc9c226ba4c. 
I've also seen via debug prints, that for a query of "1+2", "12" is passed to the provider's code, which corresponds to the attached commit's message (strips non alpha-numeric characters; do correct me if that's not what it does).

I deemed it not necessary to attach an image/video of the problem, but if the problem I'm describing is not clear, please let me know and I will do so.

**Comment by mtwebster** [comment]
That regex has been replaced since that commit;
https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L66-L68

Could you try changing the pattern from:
```/[^\p{L}\p{N}]/gu```
to:
```/[^\p{L}\p{N}\p{S}]/gu```

In the file `/usr/share/cinnamon/applets/menu@cinnamon.org/applet.js` - you'll need to open as root, or make a copy, edit then copy back over the original.

If that works, I'll add it to the pattern.

**Comment by gkatev** [comment]
So with the new regex the "1+2" works, but other symbols like [-*/] get stripped (even though the pattern looks like they shoud be included?).

Furthermore, I'd like to make a case about having the search term passed to the providers without any modification at all, if possible. Stripping symbols breaks the calculator, stripping spaces breaks a google search provider (and the wikipedia one?). De-capitalizing all characters, which I've also observed, could potentially break a hypothetical future provider.

**Comment by mtwebster** [comment]
I've restored the old behavior for now for search providers - I'd also rather leave it as is than remove the lower-casing - maybe that ends up breaking other users' providers.
