### ISSUE TITLE
blur and/or similar effects as an option for transparent themes (feature request)

### ISSUE THREAD

**Issue by akirapink** [linuxmint/cinnamon#10261]
many DE's have effects like blurring anything behind a transparent window, and it would be nice to have this as an option on cinnamon too
given modern hardware, this wouldn't have that bad of a performance impact either

**Comment by fredcw** [comment]
#9174

**Comment by TPO100Cofficial** [comment]
oh my bad
thanks

**Comment by TPO100Cofficial** [comment]
hey it's been a while
has there really not been any progress on that?

**Comment by mfreeman72** [comment]
This has been on my "wish list" for Cinnamon since day one. Some had succeeded to a certain extent with tweaking earlier versions of Cinnamon, but their method had some problems with rounded corners and slowing things down quite a bit. With an update, that method seems to have been eliminated, and nothing has come up since.

Blur is absolutely necessary if transparency is in place. Any text or hard-lined pattern behind a transparent element (menu, panel, window, whatever) makes any text on that element nearly impossible to read. Blur fixes that problem beautifully, and is rather nice to look at in its own right. Sadly, nothing official has been released on this front in 10 years. Still wishing... :(

**Comment by Secret-chest** [comment]
> Blur is absolutely necessary if transparency is in place. Any text or hard-lined pattern behind a transparent element (menu, panel, window, whatever) makes any text on that element nearly impossible to read. Blur fixes that problem beautifully, and is rather nice to look at in its own right. Sadly, nothing official has been released on this front in 10 years. Still wishing... :(

No, it isn't. If the element is > 75% opaque, it isn't. If it is less than that, it only needs 2px or so, like Windows 7 did.

**Comment by mfreeman72** [comment]
> No, it isn't. If the element is > 75% opaque, it isn't. If it is less than that, it only needs 2px or so, like Windows 7 did.

Yes, it does. Unless the transparency is nearly undetectable, text can get very difficult to read if there is something like a busy background or an open browser window with lots of text on it behind the transparent bit, even at fairly high opacity. At least to my 50-year-old eyes. I cannot use any theme that has any noticeable transparency because of this.

**Comment by JosephMcc** [comment]
As pointed out above there is already an open issue for this. We don't need multiple open for the same thing.
