### ISSUE TITLE
cinnamon is dead or dying?

### ISSUE THREAD

**Issue by Bill-ColeUS** [linuxmint/cinnamon#10305]
I see very little development going into cinnamon, I also see 800+ issues in github that nobody bothers to answer or solve. So...

1) Is cinnamon dead or dying?

2) Too few developers?

3) No interest to maintain Cinnamon?

4) All of the above?

I am using Fedora 34 with cinnamon 5.0.5 and cinnamon is crashing weekly :(  but I see no real point in opening crash issues here, since they seem to go completely unnoticed.

**Comment by ItzSwirlz** [comment]
Currently Cinnamon has active developers, so this shouldn't be an issue.

**Comment by mtwebster** [comment]
- Mint (and cinnamon) is largely developed by volunteers. We do our best. [Feel free to contribute](https://linuxmint-developer-guide.readthedocs.io/en/latest/).
- Cinnamon is primarily meant for Linux Mint, it's not an independent DE, though we make sure it works elsewhere.
- Do you want us to post on these issues daily "Still not fixed sorry" just to put you at ease? We update the status when we feel it's appropriate. Just because you don't see updates doesn't mean there's no progress. One current issue (possibly the crash you're experiencing) is actively being worked on. It's not trivial.
- Are posts like this helpful? No.

**Comment by leigh123linux** [comment]
> I see very little development going into cinnamon, I also see 800+ issues in github that nobody bothers to answer or solve. So...
> 
The bug count means nothing, a lot of them are old or incomplete info provided.

> 1. Is cinnamon dead or dying?
No.

> 2. Too few developers?
Yes.

> 3. No interest to maintain Cinnamon?
No.
> 4. All of the above?
No.

> 
> I am using Fedora 34 with cinnamon 5.0.5 and cinnamon is crashing weekly :( but I see no real point in opening crash issues here, since they seem to go completely unnoticed.
If you want to be completly ignored try filing the issue at redhat bugzilla, All bugs marked private are deleted by my spam filter :-) and the rest are barely looked at.

Try this update.

https://bodhi.fedoraproject.org/updates/FEDORA-2021-9e03a5a4be
