### ISSUE TITLE
Workspace switching is very slow

### ISSUE THREAD

**Issue by mondalaci** [linuxmint/Cinnamon#1037]
I couldn't help myself but notice that workspace switching is very slow in Cinnamon.  Often times it takes about a second to switch workspaces.  This may be fine for most users but for someone like me who uses hotkeys to switch workspaces hundreds or thousands of times a day this is a serious productivity problem.

On Gnome Shell I noticed that switching is instantaneous.  My guess is that Cinnamon forces windows to always re-render their content upon workspace switching while Gnome Shell remembers their content and doesn't make them re-render if not necessary.

As for now I'm back to Gnome Shell until this gets resolved.

**Comment by mhagger** [comment]
I'm using GNOME 3.14 on Debian Jessie rather than Cinnamon, so I don't know if this is relevant. But the [suggestion of a connection with the "Window list" extension](https://github.com/linuxmint/Cinnamon/issues/1037#issuecomment-7851585) above was a useful clue to me, so maybe the problem is in some code that is shared between these systems.

I was suffering from really annoying slow workspace switching and made the following discovery today: workspace switching is pretty reliably slow if **all** of the following are true:

* The "Window list" extension is enabled
* The "Window list" preference "Window grouping options" is set to "Group windows when space is limited"
* At least one window (it doesn't seem to matter which window) is configured to appear on all workspaces

If I change any of these conditions, desktop switching immediately becomes fast again and seems to stay fast.

**Comment by oxysoft** [comment]
> I'm using GNOME 3.14 on Debian Jessie rather than Cinnamon, so I don't know if this is relevant. But the [suggestion of a connection with the "Window list" extension](https://github.com/linuxmint/Cinnamon/issues/1037#issuecomment-7851585) above was a useful clue to me, so maybe the problem is in some code that is shared between these systems.
> 
> I was suffering from really annoying slow workspace switching and made the following discovery today: workspace switching is pretty reliably slow if **all** of the following are true:
> 
>     * The "Window list" extension is enabled
> 
>     * The "Window list" preference "Window grouping options" is set to "Group windows when space is limited"
> 
>     * At least one window (it doesn't seem to matter which window) is configured to appear on all workspaces
> 
> 
> If I change any of these conditions, desktop switching immediately becomes fast again and seems to stay fast.

In 2023 we are still experiencing super laggy workspace switching. As described up there, starts out fast after a reboot and seems to slow down depending on what apps are open and stuff like that. Your comment was invaluable - I just removed the window list applet from my panel and all lag disappeared. It seems that disabling grouping of applications increased the performance as well, but definitely not as speedy as removing the applet entirely.
