### ISSUE TITLE
Taking a screenshot with a dropdownmenu/contextmenu open in LMDE4 doesn't work

### ISSUE THREAD

**Issue by Wallby** [linuxmint/cinnamon#10394]
```
 * Cinnamon version (cinnamon --version).. Cinnamon 5.0.5 (daily builds PPA.. no) <- are there even daily builds for LMDE4..?
 * Distribution.. LMDE 4 Debbie
 * Graphics hardware *and* driver used.. -
 * 32 or 64 bit.. 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog.. ask if relevant and I'll update this post
 ```

**Issue**
Pressing shift+prtsc allows me to specify a region to take a screenshot of.
In firefox.. trying to take a screenshot when a contextmenu is open closes the context menu first.
In nemo.. trying to take a screenshot when a contextmenu is open doesn't work
In the screenshot application.. trying to take a screenshot when a dropdownmenu is open doesn't work

**Steps to reproduce**
See **Issue**

**Expected behaviour**
The issues mentioned in **issues** don't appear (i.e. taking a screenshot of a contextmenu/dropdownmenu should be possible..?).

**Other information**
-

**Configuration info, if applicable**
-

**Comment by spamegg1** [comment]
I believe that is actually expected behavior. Taking a screenshot launches the `gnome-screenshot` program, which either opens a window (if you used Print or Alt+Print), or takes control of your mouse pointer to select an area (Shift+Print), both of which take focus away from the context menu, which causes the context menu to close.

I agree it is very inconvenient though. I also take a lot of context menu screenshots to help out folks on Mint forums. It would be nice if context menus could magically remain open for our convenience... but that's not how context menus work unfortunately. Whenever focus goes elsewhere, context menus close.

I think it's more of an issue with the way `gnome-screenshot` works rather than Cinnamon. The `gnome-screenshot` developers would have to make it, so that focus is not stolen upon using a keyboard shortcut to take a screenshot. I'm not sure if that's even possible, or desirable though.

Here's the solution I found: in order to take screenshot of a context menu, launch the Screenshot app from the Menu, and use the option "Grab after a delay of _ seconds". Use something like 5 seconds, enough time for you to get into position, open the context menu you need, and wait. This way the screenshot is taken without focus being lost.

Unfortunately this cannot be used together with "Select area to grab". So it will grab either the current window or the whole screen, so I then edit that image in the Drawing app. Here is an example:
![Untitled](https://user-images.githubusercontent.com/4255997/145729165-9bb05a26-0cd2-4d16-891b-1956ae7111a0.png)

**Comment by spamegg1** [comment]
> In nemo.. trying to take a screenshot when a contextmenu is open doesn't work
In the screenshot application.. trying to take a screenshot when a dropdownmenu is open doesn't work

I believe that is also expected behavior. Nemo context menus temporarily disallow global keyboard shortcuts until the context menu is closed, because the context menus have their own keyboard shortcuts (which you can see as underlined _), so the keyboard focus is "hooked" to the Nemo context menu.

**Comment by ThiloteE** [comment]
@spamegg1 I also stumbled across this issue when I tried to provide screenshots for an Issue I raised. If I may ask, have you raised this issue at gnome-screenshot? Would be nice to have this fixed somehow.

**Comment by mtwebster** [comment]
This is not application-specific but a global behavior that affects anything that grabs input in this manner - two things cannot enter this state at the same time.
