### ISSUE TITLE
Chrome window is shifted down and right on maximize

### ISSUE THREAD

**Issue by vushe** [linuxmint/cinnamon#10419]
```
 * Cinnamon version (cinnamon --version): 5.0.6
 * Distribution - Mint 20.2
 * 64 bit
 * Google Chrome: Version 94.0.4606.71 (Official Build) (64-bit)
 ```

**Issue**

Sometimes Chrome window is shifted down and right on maximize. Doesn't happen with other applications.

**Steps to reproduce**
Please check video attached. I assume unmaximized window position is reset on action 2.

1. Unmaximize window
2. Drag window to top edge of the display
3. Double click on titlebar to maximize window
4. Double click to unmaximize
5. Double click to maximize -> window is shifted

**Expected behaviour**
* No window shift on last maximize in "Steps to reproduce" section

**Other information**
* The video is taken in virtual box in live CD mode.
* A workaround is to turn off Window Effects in System Settings -> Enable Effects tab. So it can be related to effects, however, effects customization didn't help.

https://user-images.githubusercontent.com/15868217/138608693-bf461aac-1a91-476b-ac1a-f6fb9d368188.mp4

Found this somewhat annoying.

**Comment by vushe** [comment]
Yes, definitely I also had this problem on a few computers and have to workaround it everytime, remembering that "maximizing" button may close the window.
But well, no hopes anyone is going to pay attention to it, unless people start shouting more. 
Apparently, Cinnamon is such an environment that Google has to fix it's products for it. Or DIY, dunno which is faster ¯\_(ツ)_/¯

**Comment by mtwebster** [comment]
These look related:
https://bugs.chromium.org/p/chromium/issues/detail?id=1261797
https://bugs.chromium.org/p/chromium/issues/detail?id=1260821

Large companies release software with bugs, too. They did a lot of work with how their custom frame is handled between 93 and 94 - this is not the only issue that's been found. We were patching a different, but related bug in chromium 94 for mint.

If you're using ubuntu using a 'wayland' session, it may not occur, because frames and shadows work differently there. The fact it occurs on other desktops besides cinnamon makes me inclined to wait and see what they end up doing. There are also multiple workarounds, as mentioned above.

**Comment by vushe** [comment]
Actually, tested latest development `Version 97.0.4692.20 (Official Build) dev (64-bit)` and issue in question seems to be fixed there. So, hopefully, it's okay soon. Fingers crossed.
