### ISSUE TITLE
Stick a window to a particular workspace

### ISSUE THREAD

**Issue by wrouesnel** [linuxmint/Cinnamon#1052]
There are some programs or windows you always want on every workspace, and some which you only want on a specific one. Or programs which you'd like to automatically open on a specific workspace.

It would be really great if Cinnamon had an interface for configuring something like this and remembering it in a user session.

A classic example for me would be using VLC player - generally, I always want this to be visible on all workspaces. Same with IM windows from family.

Conversely one could imagine a use case where they wanted a certain set of windows to always open on workspace N+1 or N+2 from the current one.

It would be great if we could setup "window filters" to handle all these sorts of cases.

**Comment by cipri-tom** [comment]
2017, and I still want these features. At least the first point, with defining windows always visible on all workspaces

**Comment by mainmachine** [comment]
I had to do a double take before responding to this, because you can right click a window's title bar and check "Always on Visible Workspace", so that exists today...

But it seems maybe the request is for having that stored on a per-application basis, so from a fresh login these settings are applied...?

**Comment by JosephMcc** [comment]
This would require some sort of session saving which isn't simple to do right. There are quite a few other requests related to do this.

**Comment by cipri-tom** [comment]
@mainmachine yes, checking that is an option. But having to do it for multiple windows on every login is indeed a bit painful. So yes, that would be the point. 

@JosephMcc session saving would be difficult, I imagine because it requires the enumeration of windows with their current properties, along with crash recovery and stuff like that.
However, it may be easier to have a "window config" file which sets some parameters on windows, regardless of their state before quitting. I believe something similar is achieved by `DevilsPie`, but I'm not sure it works with cinnamon

**Comment by mainmachine** [comment]
@cipri-tom I could see this creating window settings that could get broken. Consider the case where someone connects an external monitor to a laptop - what happens when a window is saved as mapped to the external monitor from the previous boot, and that monitor is disconnected on next boot?

It's not impossible, but you've got a lot of different logic that's needed for it to work and not break in many common use cases.

**Comment by cipri-tom** [comment]
Yet still, until this will be implemented (if at all), can anyone point in a direction for associating Firefox with "Visible on all workspaces" ? Even a small script that is executed before / after Firefox (`alias Firefox="Firefox && show_on_all.sh"`) would be good. 

In other words, how can we programatically set that flag ?

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.

**Comment by igorsantos07** [comment]
I don't mind having to move my few leisure windows around whenever I restart my computer, but GOD PLEASE, allow us to at least set Spotify as showing everywhere!!

This issue has AGES and it's one of the biggest downsides of having upgraded from Mate+Compiz to Cinnamon 😞
