### ISSUE TITLE
Settings for the dark mode in the X-apps difficult to find

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/cinnamon#10539]
Mint 20.3 Cinnamon: 

**Feature Request**
The settings for activating the dark mode in the X-apps are not consistent and therefore difficult to find. In Pix and in the Terminal this option is under "General", in Xviewer under "Modules".

**Comment by JosephMcc** [comment]
Thanks for the feedback. I'm going to close this here since it isn't really a Cinnamon specific issue but we can keep it in mind for the future. Keep in mind though that we can only control this for apps which are actually developed by Mint. We don't have control over apps like the terminal which come from upstream.
