### ISSUE TITLE
Refresh wireless list

### ISSUE THREAD

**Issue by jackalsh** [linuxmint/Cinnamon#1054]
I really lack the feature of refreshing wireless network list within the panel widget. Please add this to cinnamon. Thanks.

**Comment by spdionis** [comment]
@AlbertJP this is still a problem. It still takes a lot of time for new networks to appear. I use my tablet as a wireless hotspot and, especially if the pc had already connected to another wifi, it takes 1-2 minutes of (painful) waiting before the new network appears. Compare this to windows (7) where this takes 5-10 seconds at most.

The solution I use for now is turning off and on wireless. This is mildly annoying.

**Comment by rellieberman** [comment]
Still a problem on 18.1. I usually run `service network-manager restart` too speed up the process and immediately see the new available networks.

**Comment by harryio** [comment]
The wifi does not automatically connect to the previously connected network after i resume from suspend. When I check available network list it shows 1 or 2 nearby networks and in some cases shows no networks at all. Have to use `sudo iwlist scan` to get around this problem.

**Comment by glitchsys** [comment]
Can't believe this is 2017 and this is still an issue. I needed to disconnect from my wireless and reconnect to get a new DHCP IP and as soon as I turned off Wireless and turned it back on, some random weak signaled SSID showed up but none of the 8 or 9 other SSID's in my area showed up. I sat there for a good minute waiting for the list to populate but nothing, just that one SSID I have nothing to do with.  I eventually had to run "sudo service network-manager restart"  to get the list to update.  I love Linux Mint, don't get me wrong, but scanning for wireless networks shouldn't be so difficult.

**Comment by matas-zanevicius** [comment]
When I'm on the road I usually turn my phone into a hotspot and access 4G+ network through it. Since SSID and password are always the same, my laptop connects  automatically. But if I turn on the computer first, I either have to wait few minutes, after enabling AP, before before I'm connected, or turn wifi off and then back on again. If refreshing the list is really that difficult to do, perhaps adding a button that kind of refreshes by doing off/on is not such a bad idea?

**Comment by mscheper** [comment]
I'm just adding another use case here, to explain the relative urgency of this problem. (Call it a rant if you like, but if it expresses the frustration that we travelling Cinnamon lovers experience, it serves its purpose.)

My home broadband connection has been acting up a lot lately (Comcast is a rant in itself), so I often want to switch to my phone's wifi hotspot. Pursuant to Murphy's Law, this typically happens when I'm in a net meeting or some other time-critical client-facing situation, so it's important for me to be able to switch networks quickly. But since my actual wifi connection is fine (the uplink is the problem), the network manager doesn't rescan very often, so it can take the full two minutes or whatever for my phone's access point to appear and be selectable. (I'm also usually in a densely populated area, with scores of wifi networks, so it's not always clear when the rescanning has happened.)

I deal with this particularly often while I'm travelling. Public wifi on trains and in cafés and airports is often really bad, so I want to be able to switch to my phone's wifi access point. But it always takes painfully long for it to appear.

It might be hard for developers with solid network connections to imagine why this is a big deal, but in all seriousness, the time I've spent waiting for wifi networks to appear has probably added up to an hour in the past year... a minute or two, once or twice each week, sounds about right. And clients are more forgiving about one- or two-minute connection drop-outs than three- or four-minute drop-outs, and this issue makes that difference.

**Comment by mtwebster** [comment]
No one doubts the usefulness of this, but often times, we are at the mercy of the libraries we use or inherit using.  If you read above, there was no reliable way of doing this in the past.  It was added later but clearly no one raised enough noise to make me go and check again - until now ;)

I've added a pull request for a very simple implementation of it - https://github.com/linuxmint/Cinnamon/pull/6614 - if we weren't currently in a feature freeze for an imminent release, I'd simply commit it, but it may have to wait.  It appears to function as it should, though due to how the applet is constructed, it's not simple to do what I had wanted, that is having a small refresh icon at the heading of the access point list, and that can be something for a later date.

If you're on the latest Cinnamon (probably at least 3.2 would be ok,) you could simply edit your existing applet, at least until this gets merged - it's just a text file if you'd like to test (`/usr/share/cinnamon/applets/network@cinnamon.org/applet.js`)

**Comment by joaoherberto** [comment]
I am all for this fix/upgrade. But if I may ask a silly question, why not refresh the list every time the wireless network list is accessed, why else would you be there? Seems to me that it should just refresh every time you access wi-fi list. Adding a refresh button will be more overhead that is just not needed.

**Comment by DiegoQueiroz** [comment]
I think both are desirable.

There are several situation where a refresh button is useful:
- when you start to tether the internet from phone;
- when you just turn on a wireless router
- when you are walking randomly searching for an network in range

It would be a pain to request the user to close/open the list several times to see if the network he wants is reachable.

**Comment by joaoherberto** [comment]
> "It would be a pain to request the user to close/open the list several times to see if the network he wants is reachable."

Good point, then you are correct, both are needed.

**Comment by leigh123linux** [comment]
cinnamon-3.6 has wifi rescan

**Comment by digitig** [comment]
Nope. I managed to connect to WiFi once, never managed even to see the network since. Abandoning Mint, trying a different distro.

**Comment by KAMI911** [comment]
+1

**Comment by mscheper** [comment]
> cinnamon-3.6 has wifi rescan

@leigh123linux: I'm on 5.0.7, and I don't see how to do it. I'm using the stock Network Manager Applet (network@cinnamon.org) and I don't see a rescan button in it anywhere. The Network app, which appears when I click 'Network Settings' in the applet, also lacks this feature, and the automatic rescans are still too infrequent.

Can you explain where the 'wifi rescan' is, or reopen this issue, please?

**Comment by KAMI911** [comment]
@leigh123linux , please consider to reopen it since now there is no Wifi Rscan button in Network applet. AFAIR there was, but now there aren't. Or this is a problem in my system only?

**Comment by KAMI911** [comment]
It seems it is automatically rescans when the Network applet's menu opened.

**Comment by DirkHaar** [comment]
It does not. At least not immediately.

Am 22.12.21 um 10:04 schrieb KAMI:
