### ISSUE TITLE
Gnome app update

### ISSUE THREAD

**Issue by lzbk** [linuxmint/cinnamon#10645]
```
 * Cinnamon version : 5.2.7 (some ppas, but not for these apps)
 * Distribution : Mint 20.3
 * 64 bit
 ```

Many gnome apps are stuck in 2018, which is mostly OK, but in some cases it creates problems.

## Seahorse
I'm trying to import p12 key to my keyring to sign a document and the import sign remains gray, which is a documented issue (which might be attributed to the oldness of the application) :
* https://bugs.launchpad.net/seahorse/+bug/1771880

## Simplescan
I cannot use the feeder on my scanner with simple scan, which I have filed @ gnome, and they tell me that my version is too old :
* https://gitlab.gnome.org/GNOME/simple-scan/-/issues/279#note_1322143

Some of these bugs might be corrected by updating the apps…

**Comment by mtwebster** [comment]
Hi, this is because the package base (Ubuntu 20.04) is rather old (though generally more like 2019-2020 really).

The next release of mint (21) will be based on the 22.04 release of Ubuntu, which means it will have more recent versions of pretty much everything.  The versions for the ones you mentioned will be:

simple-scan - 40.6
seahorse - 41.0
