### ISSUE TITLE
Incorrect locale when installing with location "Brussels" (for all versions of Mint Cinnamon) 

### ISSUE THREAD

**Issue by ngaro** [linuxmint/cinnamon#10662]
**Issue**

All versions of Mint use the locale `de_BE` when you choose _Brussels_ (or any other location in Belgium) in the installer which is completely wrong (see **Other information**)

**Steps to reproduce**
- Try installing it with _Brussels_ as location (I also tried it with _Antwerpen_ : same result)

**Systems with this issue**
* Distribution : All Mint versions starting from (at least) 17.0 _(I never tried older ones but they probably have the same problem)_
* Desktop environment: Cinnamon, but  probably also Mate, Xfce and whatever LMDE uses. _(I only tried Cinnamon)_
* Hardware: Everything

**Other information**

Note that there [german-speaking community in Belgium](https://en.wikipedia.org/wiki/German-speaking_Community_of_Belgium) (`de_BE`) has a population of barely 78 000 people<br>In comparison:<br>
* The[ Flemish region](https://en.wikipedia.org/wiki/Flemish_Region) (`nl_BE`) : ~6 600 000
* The[ French speaking community](https://en.wikipedia.org/wiki/French_Community_of_Belgium) (`fr_BE`) : ~4 500 000

Feel free to send me a list with all possible locations (in Belgium) you can choose in the installer.<br>I'll send back a list with which locale is appropriate for that location.<br>_Brussels itself is a edge-case: ~50% of the population there will want `nl_BE` and the other ~50% will want `fr_BE` (but nobody there will use `de_BE` for certain)_<br>Note that I also mentioned _Antwerpen_ : This is an example of 100% `nl_BE`

**Expected behaviour**

Either `nl_BE` or `fr_BE` should be used.<br>Preferably the right one for each city but if that's non-trivial to implement: One of these 2 for all locations in Belgium would be a good 2nd choice.

**Comment by clefebvre** [comment]
What language do you choose at the very start?

And what locale in particular are you talking about?

**Comment by ngaro** [comment]
- Chosen language : _English_
- Location: _Brussels_

Result:
`/etc/default/locale` will contain the wrong locales. (Some will be `en_US` but that is wanted behaviour)
Also in `/etc/locale.gen` it will be `de_BE` that is uncommented instead of `nl_BE` (or `fr_BE`)

I (usually) solve this manually by running this as root immediately after the installation:

```
perl -pi -e 's/de_BE/nl_BE/' /etc/default/locale
perl -pi -e 's/^de_BE/nl_BE/' /etc/locale.gen
perl -pi -e 's/^# nl_BE/nl_BE/' /etc/locale.gen
locale-gen
```

**Comment by clefebvre** [comment]
Ok, the language is in `en_US`, which is correct and the region in `de_BE`, which is wrong, but there's no right value for it other than guess work.

I guess what happens here is that it can't find a locale corresponding to your chosen language and region (`en_BE` doesn't exist), so it picks among the available `_BE` locales and finds the first one `de`.

This can't be fixed without the installer asking you to make 4 choices, including 3 locale settings and 1 timezone setting, instead of 2. It's not reasonable for a niche case to make the installer more complicated for most users.

For dates to show up correctly LANG needs to match LC_TIME since one dictates the date format and one the translations of months and week days.

Incidentally, the choice of timezone should have no impact on any of the locale variables.

As it is in Ubiquity currently, you choose a language and then a timezone and that's it. Until the UI is redesigned, selecting a combination which results in an unsupported locale (as listed in /usr/share/i18n/SUPPORTED) will necessarily require settings to be adjusted post-installation.

The installer clearly doesn't support your use case, but I can understand why it's been designed like that. It's the same for our own installed in LMDE (live-installer) and probably the same also in Calamares and other installers. Shortcuts and assumptions are made to simplify the installation.

If you pick a language and a region which don't match you get date format issues. It's easy to adjust though.

![image](https://user-images.githubusercontent.com/1138515/153031569-6b7ffa61-7a53-4afa-9e3d-0befc626ceab.png)
