### ISSUE TITLE
Do only rotate if tablet mode is active

### ISSUE THREAD

**Issue by dreng** [linuxmint/cinnamon#10697]
```
 * Cinnamon version: 5.2.7
 * Distribution - Mint 20.3
 ```

**Sorry for cross posting, but this one is related to cinnamon and cinnamon-settings-daemon. See also https://github.com/linuxmint/cinnamon-settings-daemon/issues/359**

**Issue**
Auto rotate does not honor /sys/bus/platform/drivers/thinkpad_acpi/thinkpad_acpi/hotkey_tablet_mode. The screen rotates even if a Thinkpad Yoga is not in tablet mode (display turned all the way down). The behavior on MS Windows is different and seems to be more logical since automatic rotation does rarely make sense when not in tablet mode.

**Steps to reproduce**
* Take a Lenovo Thinkpad Yoga, e.g. X390 or X13
* Turn Auto Rotate on in display settings
* Have a look at /sys/bus/platform/drivers/thinkpad_acpi/thinkpad_acpi/hotkey_tablet_mode -> 0
* Rotate display and watch the screen rotate automagically
* Rotate back
* Turn display at least 180 degrees down
* Have a look at /sys/bus/platform/drivers/thinkpad_acpi/thinkpad_acpi/hotkey_tablet_mode again -> 1
* Rotate display again -> screen rotates like seen before

**Expected behaviour**

Screen should rotate in tablet mode only (if display is turned down more than 180 degrees, respectively if /sys/bus/platform/drivers/thinkpad_acpi/thinkpad_acpi/hotkey_tablet_mode equals 1).

**Other information**
* The fix has to take place in cinnamon-settings-daemon/plugins/orientation/csd-orientation-manager.c
* A new GSettingsSwitch like "orientation-lock-tablet-mode" in org.cinnamon.settings-daemon.peripherals.touchscreen should be implemented
* Display settings: A new switch should be implemented in cinnamon/files/usr/share/cinnamon/cinnamon-settings/modules/cs_display.py like "Rotate in tablet mode only"
* More information about thinkpad-acpi hotkey_tablet_mode: https://www.kernel.org/doc/html/latest/admin-guide/laptops/thinkpad-acpi.html

**Comment by mtwebster** [comment]
I just came across this: https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/

It would probably greatly simplify this implementation - check out https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/plugins/media-keys/gsd-media-keys-manager.c

**Comment by mtwebster** [comment]
I discovered today that in the next release the orientation manager's job will be done by muffin (some of it's being rebased off of upstream changes)  - it  already uses the iio-sensor-proxy interface. We'll hold off on this for now to see if the behavior changes.

https://github.com/linuxmint/muffin/pull/601

**Comment by clefebvre** [comment]
It's sad but it's a bit out of our control. We planned the muffin rebase on mutter 3.36 two cycles ago, it's a huge amount of work. GNOME got rid of the orientation plugin in GSD to put it in mutter, so we're inheriting the same design change here as part of the rebase.

There's no orientation plugin anymore, as a result. Ideally communication would have been much better, your work would have been merged in March but the outcome would have been the same, this plugin, along with the fix would have disappeared.

**Comment by ggiesen** [comment]
The orientation-plugin → Muffin move noted in this thread is done, so I took a run at this **in Muffin**: linuxmint/muffin#832 gates the existing accelerometer auto-rotation on tablet mode, on **both X11 and Wayland**.

How it works: it consults `ClutterSeat:touch-mode` (already correct on Wayland via libinput) and teaches the X11 seat to read `SW_TABLET_MODE` so it's correct under X11 too, behind a new `disable-rotation-in-laptop-mode` key. Per @mtwebster's suggestion above, the UI would be a *Disabled / Enabled / Tablet mode only* combobox rather than a second toggle.

Dogfooded on an HP ZBook Studio x360 G5 (Mint 22.3, Cinnamon 6.6.7, X11) — rotation and tablet-mode gating handled entirely by Muffin, no external daemon.

Very happy to take feedback or change direction (UX, key layout, splitting the X11 part, or sending the Wayland gate to Mutter too). Full patch set, udev rule, and build notes: https://gitlab.com/ggiesen/cinnamon-autorotate
