### ISSUE TITLE
Make theme settings allow archive importing from cinnamon-look

### ISSUE THREAD

**Issue by roland3564** [linuxmint/cinnamon#10803]
```
 * Cinnamon 5.2.7
 * Distribution - Arch Rolling Release
 * Intel i5, Geforce MX130
 * 64 bit
 ```

**Issue**
Make the theme settings allow archive importing from cinnamon-look

**Steps to reproduce**
1) Download gtk 3.0 (or any other theme) from https://www.cinnamon-look.org/
2) Open Settings/Theme
3) No option to import downloaded theme
4) User forced to mv archive to /usr/share/themes with root privileges

**Expected behaviour**
1) Download gtk 3.0 (or any other theme) from https://www.cinnamon-look.org/
2) Open Settings/Theme
3) Option to select downloaded theme and import it using the graphical interface.

**Comment by smurphos** [comment]
Forced? - Just stick it it `~/.themes`

**Comment by JosephMcc** [comment]
I don't see this happening. Even our own spices are currently installed as root and I'm not aware of any plans to change that.

**Comment by mfreeman72** [comment]
@roland3564 There's an easy workaround. Install OCS-URL. I believe it can be found in software manager or synaptic. After installing, you can select the Install buttons instead of the Download buttons from your cinnamon-look theme Files page. You may need to give your browser permission to allow it access to OCS-URL when it asks. OCS-URL then downloads the files and installs them in ~/.themes (or wherever they are intended to go) directly from the website. After installing the theme with OCS-URL, the theme is then available through Mint's theme manager.

**Comment by roland3564** [comment]
> @roland3564 There's an easy workaround. Install OCS-URL. I believe it can be found in software manager or synaptic. If not, you can also download it from here: https://www.opendesktop.org/p/1136805/
> 
> After installing, you can select the Install buttons instead of the Download buttons from your cinnamon-look theme Files page. You may need to give your browser permission to allow it access to OCS-URL when it asks. OCS-URL then downloads the files and installs them in ~/.themes (or wherever they are intended to go) directly from the website. After installing the theme with OCS-URL, the theme is then available through Mint's theme manager.

>Forced? - Just stick it it ~/.themes

Thank you for your answers, i changed DE and now I’m using a WM on my laptops, so I don’t have the possibility to try this workaround on my rig, the thread’s officially closed.
