### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon#10915]
```
* Cinnamon 5.2.7
* Linux Mint 20.3
* i3-6006U (Integrated Graphics)
* 64-bits
```
Some system icons don't match the rest, using the old GNOME default, getting inconsistent. Here are some examples:

![batery-settings-icon](https://user-images.githubusercontent.com/108951567/178047239-39a135a5-16e4-4087-b85a-763578521904.png)
_Old GNOME battery Icon._

![gnome-disk-icon](https://user-images.githubusercontent.com/108951567/178047242-7fee6c0e-547d-43e1-8e06-571cdc28fd9b.png)
_GNOME disk with old icon (although I was in doubt about whether it was or not)._

![network-manager-icon](https://user-images.githubusercontent.com/108951567/178047244-555e7b93-af8d-4b64-8e91-c19685835b42.png)
_When you disable the network, the old icon appears._

Is there a simple way to fix it?

**Comment by JosephMcc** [comment]
What icons are you expecting it to use?

**Comment by dneox1** [comment]
> What icons are you expecting it to use?

Something along the same lines as the Mint-Y design, since the battery/network configuration they are not using. If you are asking in relation to the GNOME disk, I don't know if it's correct or it's from Mint-Y anyway, that's why I said I was in doubt.

![image](https://user-images.githubusercontent.com/108951567/178049665-812e44af-8e47-4b37-973e-2af1eb104a93.png)

**Comment by JosephMcc** [comment]
That's really not up to Cinnamon to decide. It's up to the icon theme. Mint-Y, which you are using, doesn't currently override those. That was by choice and currently I don't think there are any plans to change them. If you want different ones, you'd just need to use a different icon theme.
