### ISSUE TITLE
Support Customization of Workspaces with different Backgrounds and Desktop Icons

### ISSUE THREAD

**Issue by dacj1s** [linuxmint/cinnamon#10919]
The default behaviour of Cinnamon is to show the same background and desktop icons for each Workspace. While this is OK for many users, I found that I tend to collect icons over time to the point that it gets messy and confusing. I wished to have different desktops for different occasions. If I wish to work, just show my work related icons. If I wish to engage socially, just show my social icons. If I wish to play, just show my game icons. 

But then naturally, I also wished to have different backgrounds for each of my desktops.

This feature request addresses and provides a solution for the closed Feature Request
https://github.com/linuxmint/cinnamon/issues/1774

I have a solution for this feature request and wrote up a tutorial on how to implement it.
https://forums.linuxmint.com/viewtopic.php?f=42&t=360221
As you can see, it uses scripts, but I am sure the concepts can be incorporated in an elegant way without some of my hacks.

**Comment by JosephMcc** [comment]
This has long been requested by users but it's just not something we've tackled since it's not a simple thing to implement. I don't think constantly changing the gsettings key on workspace switches is a way to implement this on our side.

I'm going to close this issue since it's essentially the same as the one you linked to.

**Comment by dacj1s** [comment]
Well I gave it a shot! But I have to ask, what is the problem with changing the gsettings? I use this all the time and it works fast. Is there a side-effect that I should be made aware of?

⁣Get BlueMail for Android ​

**Comment by JosephMcc** [comment]
On the gsettings thing: The constant changing of backgrounds this way is just asking for memory use issues. You'd be surprised what kinds of issues people run into on various hardware and drivers. I've also seen some settings things people made for cinnamon that do this type of thing actually completely freeze the desktop sometimes.

Your use of gsettings is also ignoring a bunch of other things. Expo for example. In the workspaces view each workspace would have to show it's unique background. Your way doesn't address this at all. And what about multi-monitor setups that only use workspaces on the primary? You changing the backgrounds on all monitors which isn't how this would have to work. Making that happen would require some major work in Cinnamon's code, if it's even possible.

And we haven't even gotten to presenting this all to users in the UI in a way that isn't a mess.  How to set the backgrounds, What happens when you add a new workspace. When you remove one. There is a lot that has to be dealt with to actual implement this sort of functionality as part of Cinnamon.

**Comment by dacj1s** [comment]
With respect, I believe you dismissed my solution too quickly. I have been using it for over two years without problems. 

I rarely use Expo because I use my shortcuts to switch to specific Desktops. However, I looked at it again today in preparing my response to you. I retained all Ctrl-Alt-arrow functionality so a user can navigate between Workspaces and create new Workspaces as they always had. With Expo view, all Workspaces would, as you  predicted, have the same background (and Desktop icons) as the current Desktop. 

Now this may be a benefit for some users. They could switch to a project-specific Desktop with its own dedicated icons and background and have multiple workspaces available, sharing those icons and background. At the end of the day, they could switch to a more personal Desktop. No conflict.

BTW, changing backgrounds is done the exact same way as you would do it without my scripts - via the desk or home menu - I didn't touch the code. The only thing that is required is to use one of my scripts to move away from the current desktop. The action of selecting another Desktop causes the new background to automatically be saved to the former Desktop.

I am not sure what happens on multi-monitor systems but I do know that at least one of my tutorial followers tried it and didn't come back complaining that it didn't work. I suspect that is because I didn't change how gsettings works. Whatever it was designed to do, it still does.

I have written scripts before and I know that developers want immediately to rewrite them in code. I am fine with that.





⁣Get BlueMail for Android ​

**Comment by ItzSwirlz** [comment]
In his defense, I personally doubt constant changing gsettings would be that much of an issue. In fact customization in general should not cause memory issues. This already exists.

Customization with themes: a user can spam change and run through All default themes on LM. Haven't heard of any memory issues.

And to be fair, you closed this issue **and** the previous issue without any input from any other dev.

**Comment by JosephMcc** [comment]
> In his defense, I personally doubt constant changing gsettings would be that much of an issue. In fact customization in general should not cause memory issues. This already exists.

Customization with themes: a user can spam change and run through All default themes on LM. Haven't heard of any memory issues.

Which shows a clear lack of experience working with Cinnamon. I've seen customization apps for Cinnamon completely freeze the desktop changing too many once. And we aren't talking about changing the theme from the menu. We are talking about what can be very quick switching of the desktop background specifically. Maybe it would be fine. Maybe it would be on many machines but I've seen too many weird memory issues with Cinnamon over the years to feel confident about this approach. You are also completely ignoring all the other reasons I pointed out that just changing the key the way his script does is not a real solution for this. I'm glad it works for him but it's not a method we can use to actual implement this. 

> And to be fair, you closed this issue and the previous issue without any input from any other primary dev like Clem or Michael or Leigh.

To be fair, I talk with the other devs multiple times a week. We've also discussed this exact issue in the past. On top of that, I actually wrote some of the background handling code in Cinnamon. Not to mention spent hours on other branches that did things like add support for per monitor backgrounds that just never made it. This is an area I know as much about as anyone else and am confident in my decision to close it.

**Comment by JosephMcc** [comment]
@dacj1s I'm glad it works for you and some other uses. And it's cool you put it together and shared it.

There are clear issues with your method when it comes to Expo and multi-monitor use. And while you and some others may be fine with it, we can't implement that kind of thing in Cinnamon if doesn't all work correctly. And your script simply doesn't in some very obvious cases. That's no offense, it simply isn't possible to do without some major rewriting under the hood in cinnamon. 

> I am not sure what happens on multi-monitor systems but I do know that at least one of my tutorial followers tried it and didn't come back complaining that it didn't work. I suspect that is because I didn't change how gsettings works. Whatever it was designed to do, it still does.

No it does not. It can't. It maybe works the way that user has it setup but that's one user. With multiple monitors and using workspaces only on the primary, the behavior is wrong.

> BTW, changing backgrounds is done the exact same way as you would do it without my scripts - via the desk or home menu - I didn't touch the code. The only thing that is required is to use one of my scripts to move away from the current desktop. The action of selecting another Desktop causes the new background to automatically be saved to the former Desktop.

I understand how it works. And maybe it would not cause an issue on the vast majority of systems. But I've seen things like this cause problems too many times. Constantly redrawing the backgrounds as fast as you can switch through workspaces is just a bad recipe.

**Comment by dacj1s** [comment]
It's not clear whether to let this go or to persist. I am 71 and retired (SW QA Eng) and have no real skin in the game except, perhaps, vicariously improving the Linux Mint experience. Over 5000 views of my tutorial and no unanswered concerns. The referenced Feature Request #1774 was closed 9 years ago. A lot has changed since then. 

I, more than ever, believe that this current Feature Request was closed too quickly. I understand your concern about changing backgrounds too fast, but that concern ought to be tested. If there is a problem then identify it, open a bug report and address the issue.  Maybe you already know what the issue might be, as you claim to have been involved in background handling.

As for Expo, I already explained that there is no conflict. Once a Desktop has been selected, the system sees the background and Desktop exactly as before. 

Semantics and use cases may play a role in the misunderstanding. When I use my scripts, my primary intent is to change the Desktop icons and my secondary intent is to change the background. Your focus seems to be on the background. I still see a win if official support were added for switchable Desktops without backgrounds.

**Comment by JosephMcc** [comment]
> I, more than ever, believe that this current Feature Request was closed too quickly

This first. Feature requests are closed on a regular basis. We don't leave them open forever just because. We are well aware that this would be a feature some users would enjoy.

> I understand your concern about changing backgrounds too fast, but that concern ought to be tested. If there is a problem then identify it, open a bug report and address the issue.

This is a gross oversimplification. You are dealing with a 3d accelerated desktop environment. When you start dealing with hardware and the various drivers around the graphics stack, nothing is that simple. And often not even under our control. I'm not going too much further on this particular point. I can say with quite a lot of confidence that not a single dev that has been working on Cinnamon for a long time is going to be comfortable with this approach. 

>  Maybe you already know what the issue might be, as you claim to have been involved in background handling.

It's not a claim. It's simple fact. But for the moment lets just throw out the whole changing gsettings key issue and we'll ignore it since no one seems to understand we've been dealing with these types of things in Cinnamon for years.

> As for Expo, I already explained that there is no conflict. Once a Desktop has been selected, the system sees the background and Desktop exactly as before.

And obviously I either didn't explain myself well or you just ignored what I said. Maybe I can do better. Let's say I have four workspaces and I want a different background on each of the four. If I open Expo I expect to see my 4 desktops each showing there own individual backgrounds. Your script does not handle that. In fact this was pointed out to you in your forum thread. That has to work properly for this to be considered for actual implementation in Cinnamon. You also ignored what I said about the multi monitor cases which would suffer from the same issue. 

Look, I think your script is a pretty clever workaround for a problem you had. But it it doesn't handle some things that would have to work properly to actually include this feature and ship it to users. That's not your fault. It simply can't because of the way it's handled under the hood by Cinnamon.

**Comment by Secret-chest** [comment]
Then just allow changing the icons.They don't require gsettings and don't show up in expo. They are also already monitor-dependent.

**Comment by dacj1s** [comment]
We all agree that Expo does not have the ability to show backgrounds different from the currently selected desktop. I suggested a use case in which a user, say a developer, selects a project-specific desktop with project-specific icons and background using my solution, and then navigates Workspaces using Expo - Ctrl-Alt-arrow as usual. For each workspace, the developer sees a consistent set of icons and background for each workspace. Switch to a different project and see a different set of icons and background. In this scenario, I see no conflict. Conflict only arises if there is an expectation that Expo - Ctrl-Alt-arrow workspaces works the same way as my solution. They are kind of orthogonal, and I suggest that they can live together. It's a matter of setting and managing expectations.

**Comment by dacj1s** [comment]
Another thing. We talk of desktop icons without commenting what they might be. On one of my desktops, I have mount points that give me access to project-specific files on a NAS. I save files all the time to my desktops and they are only viewable in that desktop. I also have browsers (Firefox) that have distinct project-specific user profiles available in my project desktops. In other words, the icons do not have to be common shortcuts - they really can be project specific.

**Comment by mara004** [comment]
It's a pity that neither KDE Plasma nor Cinnamon support different wallpapers per virtual desktop, for otherwise they're the best desktop envs IMHO.

It remains obscure to me why this is supposed to be so hard to implement, for the idea as such seems really simple: Map `Desktop 1 -> Wallpaper 1` ... `Desktop N -> Wallpaper N` instead of just `Desktop -> Wallpaper`.
As has been noted before, other DEs such as Enlightenment or XFCE are able to provide this feature without problems.

PS: Workaround-ish scripts to change the global wallpaper on desktop change are not a solution because they don't account for Expo rsp. Overview / Desktop Grid effects.
