### ISSUE TITLE
Window menu (alt + space) missing features

### ISSUE THREAD

**Issue by xhpohanka** [linuxmint/cinnamon#10948]
```
 * Cinnamon version (cinnamon --version)  5.4.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Arch
 * Graphics hardware *and* driver used i915
 ```

**Issue**
- I was used to maximize/minimize a window by hitting `alt + space` followed by `x`/`n`. This is no longer possible with 5.4.x.
- There is no maximize option when the window is snapped to any edge of a screen.

**Expected behaviour**
Work same as in previous versions.

**Comment by rado84-github** [comment]
Have you tried "Settings --> Keyboard --> Shortcuts (tab in the middle) --> "Windows" category and then manually setting up shortcuts for maximizing/minimizing?

**Comment by xhpohanka** [comment]
> Have you tried "Settings --> Keyboard --> Shortcuts (tab in the middle) --> "Windows" category and then manually setting up shortcuts for maximizing/minimizing?

:smiley: I knew that someone would mention it :smiley:  
I know that option, but I think that polluting system with another global shortcuts is not very useful. `alt + space` is here for a long time (it even works in Windows) and why to relearn to something different.

**Comment by rado84-github** [comment]
You could always remove the default function for these keys. When 5.4.x arrived, I noticed that they have added the multimedia keys to change the system sound volume which somehow overrided my settings for Audacious with the same keys, thus multimedia volume up and down was changing the whole system sound volume instead of just Audacious' volume. So I removed the default keys and my settings started working again.

Edit: But I just had a look at the default keys for windows and there's no such a combination (alt+space) which means they have removed it by default. All you gotta do is add it manually, there will be no conflicts, so nothing to worry about.

**Comment by xhpohanka** [comment]
`alt+space` still works, it opens the window menu as expected, but until 5.4.x maximize and minimize could be called with `x` and `n` respectively. These shortcuts disappeared from menu window.

**Comment by dingram** [comment]
Piling in on this one — I also use the accelerators all of the time. `Alt-Space` + `a`/`t` is hard-wired into my brain for media playback windows, and `Alt-Space`, `w`, `<digit>` to move a window to a particular workspace. I can't think of any logical global shortcuts for these operations that wouldn't interfere with other programs or be pretty inconvenient to press.

+1 to bring them back, please.

**Comment by awsms** [comment]
I don't know if this is related, but I'm unable to use the "Increase/decrease opacity" shortcut either on 5.4.9.

**Comment by perobertson** [comment]
Im not well enough versed in the code here but it looks like it may be solved with this recent commit https://github.com/linuxmint/cinnamon/commit/325eeb1f332d82b45f33392040213a2d3c73c1ed

**Comment by doug-last** [comment]
Just tested on mint 21.1 Cinnamon 5.6.5
confirm that: 
sequence "alt+space x " maXimizes. 
BUT does not restore (unmaXimize)

expected to do both maXimize and unmaXimize

**Comment by doug-last** [comment]
> Just tested on mint 21.1 Cinnamon 5.6.5 confirm that: sequence "alt+space x " maXimizes. BUT does not restore (unmaXimize)
> 
> expected to do both maXimize and unmaXimize

i just tested during install of 21.2
on live image: alt+space x > maXimizes, and unmaXimezes
after install: alt+space x > maXimes only
The issue is: I install in Brazilian Portuguese, someone translated the keys: maXimizar (maXimize): ok, and unmaXimize (desmaXimizar) got translated to Restaurar (Restore), and translated also the key sequence to alt+space R to unmaXimize(Restore) ..
This got introduced after 21.x how i configure to work as it was in 20.x and before for the sequence alt+space x do both? in my world hotkeys and key sequences must be the same for all languages by default

**Comment by mtwebster** [comment]
To update it you'll need to submit a change to the translation for this language:
https://translations.launchpad.net/linuxmint/latest/+pots/cinnamon/pt_BR/+translate?batch=10&show=all&search=Unma_ximize

For something temporary you could modify the string in `/usr/share/cinnamon/js/ui/windowMenu.js` to how you want it.
