### ISSUE TITLE
screensaver: connecting monitor when locked in screensaver reveals desktop

### ISSUE THREAD

**Issue by xhpohanka** [linuxmint/cinnamon#10942]
```
 * Cinnamon version (cinnamon --version) 5.4.2
 * Distribution - Arch
 * Graphics hardware *and* driver used - i915
 * 64 bit
```

**Issue**
As described in the title. When I connect external monitor while my notebook is locked on screensaver. For me it is happening with USB3 docking station with two monitors connected. Please see the attached photo (screensaver can be seen at the right on notebook lcd)

**Steps to reproduce**
- Start screensaver. 
- Connect docking station with external monitor.

**Expected behaviour**
All screens show screensaver.

**Other information**
![PXL_20220718_053921245](https://user-images.githubusercontent.com/2233252/179452047-20c9b5b8-8d1a-4851-b506-32f130dc9cf3.jpg)

**Comment by robertbyers1111** [comment]
I am seeing this issue in linux mint 21. In my case, I turn off the monitor, then turn it back on (all while the screen is locked). Once the monitor comes back it displays the user's desktop rather than the lockscreen.

I posted many more details here: [Resumption after using an external monitor...](https://github.com/linuxmint/cinnamon-screensaver/issues/406#issuecomment-1251684482)

**Comment by esReh** [comment]
Same here. 
When both my screens are locked with screensaver and I do the following steps: 
- turn off my second screen 
- wait a few seconds 
- turn on the second screen again
... the unlock screen to enter the password appears on the second screen
... and the main screen gets fully revealed/visible. 
... however there is no mouse or keyboard control but still makes everything visible on main screen. 

I also posted this with system information and logs in the linux mint forums here:
https://forums.linuxmint.com/viewtopic.php?p=2243164#p2243164

**Comment by mtwebster** [comment]
Please have a look here:  https://github.com/linuxmint/cinnamon-screensaver/issues/416#issuecomment-1256233029

Thanks

**Comment by esReh** [comment]
> Please have a look here: [linuxmint/cinnamon-screensaver#416 (comment)](https://github.com/linuxmint/cinnamon-screensaver/issues/416#issuecomment-1256233029)
> 
> Thanks

Thanks, I followed your instructions and installed suspend-config-hidpi-fixes.mint21 from releases and it fixed the issue for me. I was not able to reproduce the issue again.

Also added a lot more info to the linux mint forum where I tested and found out it could be caused by my Home-Cinema if somebody wants more info.

**Comment by LinuxOnTheDesktop** [comment]
Should this report be closed-as-fixed?

**Comment by esReh** [comment]
never had the issue in the last year. guess it got fixed.

**Comment by xhpohanka** [comment]
probably fixed, haven't seen for a time...
