### ISSUE TITLE
Cinnamon 5.4.5: Window snapping cannot be disabled

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/cinnamon#10960]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 5.4.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux ArchLinux 5.18.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Jul 2022 13:05:04 +0000 x86_64 GNU/Linux
 * Graphics hardware *and* driver used
Nvidia 515.57
 * 32 or 64 bit
64bit
 ```

**Issue**
I have window tiling and snapping disabled in "Window Tiling" System Settings and yet every time I move a window near the edge of the screen, snapping is enabled.

**Steps to reproduce**
Run 5.4.5 version and move any window to the **top** edge of the screen after disabling Tiling & Snapping in Settings.

**Expected behaviour**
Preference should be respected.

**Comment by JosephMcc** [comment]
I can't reproduce this on Mint21. The preference seems to work as expected. If you run `cinnamon-settings tiling` from a terminal do you see any errors when you change the preference?

**Comment by nick-s-b** [comment]
@JosephMcc Hi, Joseph! I see the following:
````
$  cinnamon-settings tiling
libgoa-1.0.so.0: cannot open shared object file: No such file or directory
Failed to load module: /usr/lib/cinnamon-control-center-1/panels/libonline-accounts.so
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:442: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Tiling module
````
and I get the Settings window:
![Screenshot at 2022-07-24 23-26-59](https://user-images.githubusercontent.com/7957590/180693453-a02ee4dd-fa1d-4203-b31d-4413eb39f38a.png)
 
Here are my findings:
If I disable the "Enable Window Tiling and Snapping" and move any window to the sides or bottom of the screen, nothing happens. If I move it to the top, it wants to `Maximize` the window fully.

If I enable the "Enable Window Tiling and Snapping" and then try to move the window to the top, it wants to tile it in 1/2 a screen tiles. That's the normal behavior.

Notice this "Maximize, instead of tile... to the top edge " setting: 
![Screenshot at 2022-07-24 23-31-05](https://user-images.githubusercontent.com/7957590/180693691-555d83a6-21d0-48b5-b9fd-97f0f43b2749.png)

This settings seems to be **enabled** when I completely disable the tiling and snapping! 

I can reproduce this 100% of the time. This started happening in 5.4.5.

**Comment by JosephMcc** [comment]
That's probably meant to work that way. I'll be honest, I didn't realize that was any sort of new behavior. It works the same for me.

**Comment by nick-s-b** [comment]
I don't quite follow. Why should it maximize when it's disabled in settings? Default behavior was always not to maximize when snapping to the top of the screen.

**Comment by JosephMcc** [comment]
Sorry if I explained that poorly

1) When tiling is enabled, the default is to tile to the top half which you can change in the settings

2) When tiling is disabled, you are still able to maximize by dragging to the top of the screen

It's 2 that I didn't realize had changed. I never turn tiling off and thought that's how it always was.

This is the intentional behavior: https://github.com/linuxmint/muffin/commit/696c587dfef0fb643dd9770bfc69a8cc91b44985

**Comment by nick-s-b** [comment]
Thanks Joseph! Got it. The change in behavior sucks but at least now I know it's intentional :)

**Comment by mtwebster** [comment]
The 'regardless...' bit wasn't  to mean 'you can always maximize by dragging no matter what', it meant that if you have tiling enabled, and you drag a window out of maximized, if you return that window to the top edge of any monitor, it will re-maximize, not tile, even if that 'maximize instead of tile' preference is unchecked.

Like @JosephMcc I never turn tiling off - if this behavior is different from before, I'll fix it.

**Comment by nick-s-b** [comment]
Thank you @mtwebster It's an annoying behavior especially if it can't be disabled.

**Comment by JosephMcc** [comment]
This behavior was changed: https://github.com/linuxmint/muffin/commit/84a91d99c05f335b69d4e147a9644de15f822b90
