### ISSUE TITLE
Regression: key depreciations warnings (that are hard to fix)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon#11020]
```
 * Cinnamon version (cinnamon --version): 5.4.9
   - Please specify if you are using the daily builds PPA: no.
 * Distribution: Mint 21
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 * Attach ~/.xsession-errors, or /var/log/syslog
 
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/9285509/xsession-errors.txt)

 ```

**Issue**

Any one run of `apt` can produce many a warning about keys being stored in a depreciated format. I have fixed the problem now (see below) and I seem to have no record of the exact error messages. Yet, I think that the warnings were of this form:

![image](https://user-images.githubusercontent.com/47056543/183531877-2f142ce1-2365-4469-975a-5c1cf8467f91.png)

([Source](https://www.omgubuntu.co.uk/2022/06/fix-apt-key-deprecation-error-on-ubuntu).)

**Steps to reproduce**

1. Have various PPAs or 'additional repositories' in some (?) old format.
2. Use mintupdate to update Mint 20.3 Cinnamon to Mint 21 Cinnamon.
3. Reboot.
4. `sudo apt upgrade` or use Mint's Update Manager

**Expected behaviour**

No warnings or at least better instructions about how to remove the warnings.

**Other information**

The Ubuntu release notes (at [the location](https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668) that your own release notes point to) seem to say nothing about the matter, but those notes are so poorly presented that it is hard to tell.

I found a solution - an involved one - [here](https://www.omgubuntu.co.uk/2022/06/fix-apt-key-deprecation-error-on-ubuntu).

Probably this bug report does not belong under Cinnamon. If so, please move it.

**Comment by kfeoktistoff** [comment]
Hi @LinuxOnTheDesktop,

Yeah, this is not a Cinnamon issue but it is worth elaborating. The solutions provided by the link are incorrect:

> I found a solution - an involved one - [here](https://www.omgubuntu.co.uk/2022/06/fix-apt-key-deprecation-error-on-ubuntu).

The both instructions by the link will make the warning message disappear, but they will not solve the security problem that causes the warning (and apt-key deprecation).

When `apt` fetches packages from a remote repository, it validates that the repo is signed by _any_ of  apt keys stored in `trusted.pgp`. Imagine that you have a record in `/etc/apt/sources.list` and the according public key in `trusted.pgp`. Now imagine that the private key used to sign this repository was leaked. It can be used, for example, to sign another repository and if you add it into your sources list, apt will be happy to install potentially malicious packages from there. If the original repository is popular (like a distro repo), the blast radius can be huge.

The solution proposed by the link is moving a key from `trusted.pgp` file to `trusted.pgp.d` directory, which does not solve the root problem.

Instead of exporting a key to `trusted.pgp.d` directory, it is better to export it to anywhere else and update the record in `sources.list` (in your case it will presumably be `/etc/apt/sources.list.d/teamviewer.list`) adding `signed-by` parameter like that:

`deb [signed-by=path_to_the_key.pgp] http://linux.teamviewer.com/deb stable main`

Now, when apt will fetch data from this repository, it will use the specific key.

Links:
1. A very comprehensive stackoverflow [answer](https://askubuntu.com/a/1307181/332792) with step-by-step migration instruction
2. A similar attack vector with traffic interception in Cloudflare [blog](https://blog.cloudflare.com/dont-use-apt-key/)

**Comment by LinuxOnTheDesktop** [comment]
@kfeoktistoff

Thanks, but my thrust was as follows.

As a result of upgrading to Mint 21 Cinnamon, (a) I received these warnings (whereas I did not when I was on Mint 20.3) and (b) it was hard to know what to do about the warnings.

What your write confirms _b_. Even if it is not really anything that Mint has done that causes _a_, Mint should try to do something about it, on pain of Mint's users having a bad experience.

**Comment by JosephMcc** [comment]
Closing this since it very clearly isn't a Cinnamon issue.

**Comment by LinuxOnTheDesktop** [comment]
@JosephMcc 

But is it a _Mint_ issue (or, more specifically, something for which the upgrade to Mint 21 is responsible)? If it is a Mint issue (in one way or another) then where should I file the report, please?

**Comment by JosephMcc** [comment]
I'm not sure that it is a Mint issue rather than an upstream issue. At this point it's known and is also only a warning.
