### ISSUE TITLE
Recent upgrade to Mint 21 Cinnamon 64-bit - minor issues

### ISSUE THREAD

**Issue by agreene48** [linuxmint/cinnamon#11041]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
Chrome and Firefox open "maximized" instead of "un-maximized" every time.  Also, after adjusting size and placement of those application windows, they are not "remembered" after closing, re-opening, and un-maximizing.

There does not appear to be a selection under System Settings/Themes for the application window title bar color separate from the "Applications" selection.

**Steps to reproduce**
Open Chrome or Firefox from either control center or taskbar.
Open System Settings from control center.

**Expected behaviour**
Chrome and Firefox should open from any link to last-used placement and size.
There should be an entry in Themes for the Application title bar to set its color

**Other information**

**Configuration info, if applicable**
Dell XPS-13 I-7 processor, 8GB RAM, Intel Video, Mint 21 Cinnamon.
```

**Comment by mtwebster** [comment]
Hi,

The titlebar theme selection has been deliberately removed because the Applications (gtk) theme handles that now. Read under the "Window Manager" section of the Cinnamon [release notes](https://www.linuxmint.com/rel_vanessa_cinnamon_whatsnew.php).

As for the maximize issue, there's a new behavior that will automatically maximize windows that are nearly maximized when starting. Running this from a terminal should take care of it:
```
gsettings set org.cinnamon.muffin auto-maximize false
```
We're still evaluating whether to leave this enabled by default or not.

**Comment by zolstarym** [comment]
> 
> We're still evaluating whether to leave this enabled by default or not.

At least give a gui option in settings and document the change
