### ISSUE TITLE
[BUG] Uninstalling gnome-terminal breaks .desktop files for console applications

### ISSUE THREAD

**Issue by SpinningVinyl** [linuxmint/cinnamon#11104]
```
 * Cinnamon version 5.4.11
   - I am not using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - Mint 21
 * Graphics hardware *and* driver used: Intel UHD 620 with default drivers
 * 64-bit
 * Attach ~/.xsession-errors, or /var/log/syslog: 
 ```

### Issue
After uninstalling gnome-terminal, .desktop files for console applications (e.g. htop, Midnight Commander) fail to launch.

Selecting them from the menu does nothing, and double-clicking the .desktop file results in the following error message:
"Unable to find terminal required for application"

If gnome-terminal is installed, console applications always launch in gnome-terminal, even if a different terminal is selected in "Preferred Applications".

### Steps to reproduce
Uninstall gnome-terminal from the command line: sudo apt remove gnome-terminal
Install any other terminal emulator, e.g. kitty: sudo apt install kitty
Select kitty as the default terminal emulator in "Preferred Applications"
Install a console application, e.g. htop: sudo apt install htop
Try to launch Htop from the the start menu.

### Expected behaviour
Console applications launch in the preferred terminal emulator

### Attached files
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/9394197/xsession-errors.txt)
![Screenshot from 2022-08-22 13-09-11](https://user-images.githubusercontent.com/31886681/185918939-301a6421-0799-4ae6-ba3b-06ae62ee0306.png)
![Screenshot from 2022-08-22 13-16-52](https://user-images.githubusercontent.com/31886681/185919185-327ddf74-da30-4ef9-a6e9-4746ffcd164b.png)

**Comment by randomoOCoder** [comment]
It seems the bug has been fixed, however if gnome-terminal wasn't uninstalled cinnamon still uses it instead of the preferred terminal. The same issue also happens in the nemo file manager when trying to open a file in a CLI app (e.g. A text file in neovim) although a bug report has already been made in the repo https://github.com/linuxmint/nemo/issues/2414.

**Comment by mtwebster** [comment]
The hardcoded terminal issue from #2414 is affecting you because kitty isn't in its list. There isn't anything we can currently do about this (which is why that bug is open still).

A simple workaround would be to use a symbolic link `gnome-terminal->kitty` either in /usr/bin, or (more appropriately) `~/bin` (you may have to log out/in for your environment to pick up that new bin location and add it to the path).
