### ISSUE TITLE
[QUESTION] Replacement of metacity?

### ISSUE THREAD

**Issue by rado84-github** [linuxmint/cinnamon#11126]
Everywhere on forums, on telegram and on Discord I keep seeing posts by people who are unhappy with the removal of metacity and the inability to choose a window decoration of our own. So I have a question: are there any plans for the near future to replace metacity with something else that will allow us to choose decorations of our own?

**Comment by mfreeman72** [comment]
Yeah, so far I'm not impressed with the removal of Metacity. Not only can I not theme windows exactly as I want to theme them, the theming that exists doesn't even work properly on most windows.

**Comment by rado84-github** [comment]
> Yeah, so far I'm not impressed with the removal of Metacity. Not only can I not theme windows exactly as I want to theme them, the theming that exists doesn't even work properly on most windows.

If you're referring to gnome applications, you can install gtk3-nocsd and then edit their .desktop file like this:
"exec=gtk3-nocsd gedit %U". This will remove the gnome decoration and replace it with the decoration you have in Cinnamon.

As for the rest, I agree. I don't like this gnomifying of Cinnamon. I hope someone makes a fork of Cinnamon 5.2 where metacity was available.

**Comment by JosephMcc** [comment]
There are currently no plans to change how window borders are themed.

**Comment by mfreeman72** [comment]
@rado84-github Actually, I'm referring to the opposite. The GTK-3 decorations theme themselves correctly. The normal windows (such as Nemo, for example) do not.

**Comment by mtwebster** [comment]
This isn't 'gnomifying' Cinnamon. This is eliminating an aspect of desktop themes that was incredibly frustrating for theme developers to work with and integrate with the rest of the window and desktop. Just because this originated in gnome doesn't automatically make it a bad idea.

Ask some people who create themes how fun the metacity 'language' was to work with. This change makes it easier to develop nice-looking themes. If you're unsatisfied with the way your windows look, ask them to change things or offer a variation.

This was also explained in the release notes: https://www.linuxmint.com/rel_vanessa_cinnamon_whatsnew.php
