### ISSUE TITLE
[BUG] gnome-terminal-server colors are just dark, unlike configured black on white

### ISSUE THREAD

**Issue by metadings** [linuxmint/cinnamon#11134]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 21, Arch, Fedora 37, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

### Issue
I've recently upgraded to Linux Mint 20.4 Vanessa! Now the titlebar, the registerbar, the scrollbar is just dark, black even with colors from System theme disabled and using black on white (Tango (light)).

### Steps to reproduce
Use Adapta theme, with Windows-10 icons and Adwaita symbols, cursor is XCursor-light in cinnamon-settings.

### Configuration info, if applicable
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

**Comment by clefebvre** [comment]
That's by design. Adapta defines its titlebars as dark.

![image](https://user-images.githubusercontent.com/1138515/188123155-d2ec9424-ef52-4d88-9959-ddd7d6046b72.png)

The GNOME Terminal settings (Tango Light, Use system theme etc..) only affect the inside of the application itself, the VTE.

What's changed between Mint 20.3 and Mint 21 is that in the new Cinnamon 5.4, titlebars are now rendered using the GTK theme (Adapta), whereas in the past they were rendered using the Metacity theme.

**Comment by metadings** [comment]
I'm wondering, just because xed, nemo and evince do have white titlebars. What would you recommend, as a light, white theme I can use, with small and narrow buttons?

**Comment by metadings** [comment]
Now I'm using Mint-Y-Aqua, still gnome-terminal-server is black, dark gray instead of white.

**Comment by metadings** [comment]
Hey, I've edited my answer, read again.
