### ISSUE TITLE
[BUG]  Corners are not activated on the second monitor

### ISSUE THREAD

**Issue by ynoalberto** [linuxmint/cinnamon#11144]
Cinnamon 5.4.11
Linux Mint 21 

Radeon driver - Mesa  22.1.0

Linux Mint 21 with cinnamon desktop does not activate the corners on the second monitor, they are only activated from the main monitor of the laptop

**Comment by Secret-chest** [comment]
I don't use them, but I think it's intended. Try opening the hotcorners menu om the secondary monitor.

**Comment by ynoalberto** [comment]
Ok. I thought that had been a bug in cinnamon desktop. Sorry. I try it now. Thanks for help me

**Comment by mtwebster** [comment]
This is indeed deliberate behavior.

I'm not sure how useful this would be, but there are applets for these actions also (Expo, Scale and Show-Desktop applets), and they can be set to trigger on hover instead of clicking. Unfortunately you can't use them to also exit these modes, like you can with hotcorners.
