### ISSUE TITLE
Mask for shape window improperly scaled on HiDPI

### ISSUE THREAD

**Issue by daniel-stm** [linuxmint/cinnamon#11345]
```
 * Cinnamon version 5.4.8
 * Distribution Mint 21
 * VGA compatible QXL paravirtual (and probably any other)
 * 64 bit 
 ```

### Issue
When connecting to a (high DPI) Linux Mint machine via TeamViewer, it shows a control panel on the right side of the screen, that uses a mask to have a non-rectangular shape.
The mask is applied via QWindow::setMask() and has the same pixel dimensions as the window.
On HiDPI, it appears that the mask is scaled (doubled) before being applied to the window.
(Works properly in Gnome / KDE)
![image](https://user-images.githubusercontent.com/108475773/209171252-6d3a8e06-6ab0-4a93-b447-1656f501a167.png)

### Steps to reproduce
 * Install TeamViewer (deb), or just run without installation (tar package).
 * make a connection (Hint: with incoming LAN connections enabled in the Extra/Options/General, you can connect to "localhost" instead of an ID, so only one machine is needed)
 * use the password displayed in the main dialog
 * when the connection is established, a shaped control panel window appears on the right screen edge
 * with a high DPI setting, it looks odd, as the mask is apparently scaled before being applied.

### Expected behaviour
Control panel window doesn't look odd, mask is applied properly

**Comment by mtwebster** [comment]
Hi, I tried connecting using localhost like you described - maybe I'm misunderstanding something (though it *was* entertaining).

[cinnamon-2022-12-22T121607-0500.webm](https://user-images.githubusercontent.com/262776/209190944-4e5b5fd8-a4e0-4da1-9411-3919f240d144.webm)


I'll try it with virtualbox.

**Comment by mtwebster** [comment]
Ok, I can reproduce - a couple of observations:

- connecting to a hdpi guest shows the results in the same issue as your screenshot.
- connecting to an Ubuntu 22.04 guest which also had hidpi enabled - same result - *X11 session*
- for kicks I connected those two guests, same result.

I'm guessing you maybe were using wayland when you tested gnome? I don't think they use any sort of scaling at the toolkit level so there shouldn't be any issue with it here - I'm not surprised it worked fine.. if you weren't using wayland then I'm more puzzled. I don't have a KDE machine readily available to experiment on.

I created a simple test window using Python QT:
```
#!/usr/bin/env python3

# install python3-qtpy

import sys

from PyQt5.QtCore import QSize, Qt, QSize
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton
from PyQt5.QtGui import QRegion

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.resize(QSize(600, 400))
        
        self.setMask(QRegion(0, 0, 600, 400, QRegion.Ellipse))

        self.setWindowTitle("Test setRegion")
        button = QPushButton("button")

        self.setCentralWidget(button)

app = QApplication(sys.argv)
window = MainWindow()
window.show()

app.exec()

```

Setting both the window and mask size to the same value works as I'd expect:
![image](https://user-images.githubusercontent.com/262776/209211865-1fea25de-fb03-4ac4-a521-6074042c57e7.png)

Adding `QT_SCALE_FACTOR=2` to the environment when starting it doubles the size of both the window and mask

You mentioned the mask boundary was being set to the _pixel_ size of the window, but since setMask is a *toolkit* call, it would get scaled automatically before it went to the x server, so you end up applying a mask that's been scaled twice.

I don't have much experience with qt, and I'm assuming hidpi for X11 is being handled similarly to how Gtk does it.

**Comment by daniel-stm** [comment]
Thank you very much for your detailed response and sorry for the late reply.
You are absolutely right. For some reason I ended up thinking this was cinnamon specific, but it's not.
And thus, of course, scaling the mask is the proper solution.
I just assumed this would break the other DEs, but as all behave the same, that's obviously not the case.
So, this can be closed. Sorry for the noise.
