### ISSUE TITLE
Minimizing windows leaves window inactive but visible, overlaying the desktop

### ISSUE THREAD

**Issue by qwertfisch** [linuxmint/cinnamon#11409]
```
 * Cinnamon version 5.6.5
 * Distribution: Linux Mint 21.1
 * Graphics hardware:   Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Lenovo
    driver: i915 v: kernel ports: active: LVDS-1
 * 64 bit
 ```

### Issue

Whenever I minimize a window, it does not minimize completely. Its _status_ is minimized, and I am able to restore them, but the window _content_ and all decorations including minimize/close buttons will stay visible on the screen, if no other active window is (partially) overlaying it. I am not able to see the desktop behind the minimized window. I cannot interact with the window, instead I would interact with the desktop _behind_, without seeing with what I am interacting.

This error is especially annoying when trying to show the desktop. All windows will minimize but no window content is cleared, so this function becomes effectively useless.

### Steps to reproduce

Two cases:

1. Initially no windows are open. Open any window, e.g. start a Terminal or a Nemo instance. Then click on the minimize button.
1. At least two windows are opened. Click on the minimize button on the window in foreground/focus.

### Expected behaviour

1. The window should minimize and the desktop background become visible. Instead the window is still visible, though I cannot interact with it anymore (its logical status is indeed minimized).
2. The window should minimize, other windows should come into foreground, if they have been overlayed before. This is happening but the window is still visible where no other active window is overlaying.

### Other information

I found #11005 when searching for the bug, but as this is already fixed (with the bugfixed code active in my system), I decided to open another issue.

**Comment by qwertfisch** [comment]
Today an update for Cinnamon 5.6.6 was available. After installation I am able to properly minimize applicatoin windows again.

Thank you very much. :smiley:

**Comment by sirg** [comment]
Running Mint 21.1/Cinnamon 5.6.8. Saw this behavior today: windows drop to background (even behind conky's output) when minimize button is clicked. Clicking on the windows' title bar does not raise them, but clicking on the corresponding panel tile does. But the titlebar is active: double-click shades up the window. Windows' contents are not active: when there are no other windows between a "minimized" window and the desktop, desktop icons can be manipulated, even though they are not visible until selected. Freaky.

Restarting Cinnamon removes the problem. Don't have a clue how to reproduce.

Possible culprit: multiple Chrome windows. No basis for this, except all I have on the desktop is conky, a gnome-terminal and several Chrome windows. Also, sat in on a zoom meeting earlier (but exited zoom afterwards).

**Comment by mtwebster** [comment]
@sirg Do you have any downloaded extensions/applets that maybe causing issues? Try disabling them (typically extensions are more problematic than applets).

Chrome can be a bit strange - I've had the transparent windows thing before, but, at least for me, it usually only happens after waking from suspend.

**Comment by dentex** [comment]
I have the same problem since some time... maybe a week. I cannot identify what update introduces it.

```
System:
  Host: N751JK Kernel: 5.15.0-69-generic x86_64 bits: 64
    Desktop: Cinnamon 5.6.8 Distro: Linux Mint 21.1 Vera
Machine:
  Type: Laptop System: ASUSTeK product: N751JK v: 1.0
    serial: <superuser required>
  Mobo: ASUSTeK model: N751JK v: 1.0 serial: <superuser required>
    UEFI: American Megatrends v: N751JK.205 date: 03/11/2015
CPU:
  Info: quad core Intel Core i7-4710HQ [MT MCP] speed (MHz): avg: 862
    min/max: 800/3500
Graphics:
  Device-1: Intel 4th Gen Core Processor Integrated Graphics driver: i915
    v: kernel
  Device-2: NVIDIA GM107M [GeForce GTX 850M] driver: nvidia v: 510.108.03
  Device-3: Chicony HD WebCam (Asus N-series) type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,vesa gpu: i915
    resolution: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 850M/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.108.03
```

**Comment by darnrain** [comment]
I have been working on this issue, but I cant find a solution. I did find a work around. Restarting cinnamon fixes the issue temporarily. I am running Cinnamon 5.8.4

cinnamon-dbus-command RestartCinnamon 1

**Comment by Hraefin** [comment]
Cinnamon Desktop:  6.4.8+xia
Linux:  Mint 22.2 Zara

Having this exact issue.  When I minimize any window the system thinks it's minimized.  E.g. I can right click the tray icon and select restore and the window functions, but it is never "erased" from the screen.  

Is there any known work around or fix for this?  I did have an odd occurrence where cinnamon "disappeared" from mint (e.g. no option from login screen) and I had to do a manual re-install.  Everything else seems to be working perfectly.

If anyone can recommend a fix for this, it would be greatly appreciated.

**Comment by mtwebster** [comment]
@Hraefin please attach your session log (`.xsession-errors` in your home folder).

Disable any third-party applets or extensions you may have installed, then restart cinnamon (or log out/in).

Another thing to try is create a new user (start menu -> Users and Groups) and log in there to see if the issue occurs.

**Comment by niko3x** [comment]
> [@Hraefin](https://github.com/Hraefin) please attach your session log (`.xsession-errors` in your home folder).
> 
> Disable any third-party applets or extensions you may have installed, then restart cinnamon (or log out/in).
> 
> Another thing to try is create a new user (start menu -> Users and Groups) and log in there to see if the issue occurs.

Still experiencing this bug on Linux Mint 22.3 Zena (Cinnamon 6.6.5) with Intel UHD Graphics (i5-10210U) using i915 driver.

After reviewing all the reports in this issue, I noticed a pattern: every person experiencing this bug is using Intel integrated graphics with the i915 driver (at least as i saw). This appears to be Intel iGPU-specific.
The bug still persists in 2026 on the latest Mint Zena release.

System info:

┌─[~]
└─➜ fastfetch

ahmet@ahmet-BOHB-WAX9
---------------------
OS: Linux Mint 22.3 x86_64
Host: BOHB-WAX9 (M1060)
Kernel: Linux 6.8.0-90-generic
Uptime: 30 mins
Packages: 4379 (dpkg), 37 (flatpak)
Shell: bash 5.2.21
Display (BOE0872): 1920x1080 @ 1.2x
DE: Cinnamon 6.6.5
WM: Muffin (X11)
WM Theme: Mint-Y-Dark (Mint-Y)
Theme: Mint-Y-Dark [GTK2/3/4]
Icons: Mint-L-Grey [GTK2/3/4]
Font: Ubuntu (10pt) [GTK2/3/4]
Cursor: Bibata-Modern-Classic (24px)
Terminal: GNOME Terminal 3.52.0
Terminal Font: DejaVu Sans Mono (10)
CPU: Intel(R) Core(TM) i5-10210U (8)
GPU: Intel UHD Graphics @ 1.10 GHz
Memory: 5.45 GiB / 7.50 GiB (73%)
Swap: 38.75 MiB / 3.75 GiB (1%)
Disk (/): 165.56 GiB / 233.18 GiB (71%)
Local IP (wlp0s20f3): 192.168.1.146
Battery (HB4692J5ECW-31): 65% (1 hour)
Locale: en_US.UTF-8


Symptoms: When using Super+D (show desktop) or minimizing windows, the window state changes correctly (windows are functionally minimized and desktop is clickable), but the compositor fails to clear the screen - minimized windows remain visually displayed. This makes the show desktop function effectively useless.
Given the consistent Intel i915 pattern across multiple reports spanning several years, this should probably be tagged as an Intel iGPU-specific issue and investigated accordingly to that.
