### ISSUE TITLE
Add some Blur options

### ISSUE THREAD

**Issue by Jrgels** [linuxmint/cinnamon#11430]
Can be a good implementation if we can have a blurry panel like in KDE, its pretty cool.
Inside the settings of corner bar there is already a blur effect option so I think the implementation in other components should not be very difficult.

**Comment by mfreeman72** [comment]
This has been requested (by me and others) for about the last decade or so, and I totally agree! In my opinion, any transparency underneath text is useless without a blur effect, because background text or complex high-contrast hard-line images makes the text over the transparency difficult to read. Please implement a blur effect for transparent backgrounds in Cinnamon!

**Comment by JosephMcc** [comment]
We don't need another open issue for this same thing. https://github.com/linuxmint/cinnamon/issues/9174
