### ISSUE TITLE
Cinnamon 1.6.0: constantly high CPU load

### ISSUE THREAD

**Issue by autarkper** [linuxmint/Cinnamon#1154]
I notice that Cinnamon 1.6.0 (built from source) constantly uses a lot more CPU than it should be using, typically between 15 and 25 percent when supposedly idle. I have a fairly minimal install, only with a few stock applets enabled.

I don't see any messages in the console that would point to some misbehaving component.

Update: I have done some limited regression testing, and I can't see that this would be a recent regression. Could it be that my graphics system is not up to Cinnamon's high demands? Should I switch from the Nouveau driver to Intel?

**Comment by cweiske** [comment]
I'm also experiencing this problem. The desktop becomes unusable after ~10 minutes. Restarting cinnamon with Alt+F2, then `r` makes the desktop responsive again for some minutes.

I upgraded from Ubuntu 14.04 to 16.04, and upgraded my graphics card. Unity desktop has no problems, only cinnamon on this computer. I'll switch away to Mate now.

**Comment by mlda065** [comment]
I'm having similar issues.

Cinnamon is hitting 90% CPU.  I can't watch videos of GIFs, because the image stutters. When typing text, often the screen is several words behind what I see.

I've tried:
 * using one monitor instead of two
* disabling most of my background startup applications (even though the System Monitor is attributing the CPU to cinnamon)
* removing most of my widgets

Whenever the CPU is high, if I restart cinnamon (right click on panel > troubleshooting > restart cinnamon), then it goes down to <10%. (After a few seconds, since restarting cinnamon would of course use lots of CPU.)

I even did a clean install of my entire operating system (Mint 17.3). No improvement.
I'm using a Toshiba Kira, which is a fairly high end laptop, so there should be no issues. 

3 weeks ago there were no issues. Have there been any big changes to cinnamon recently?

**Comment by mlda065** [comment]
Does anyone else having this problem use the Owncloud desktop client?
I quit mine and now things seem to be fine. But that was an hour ago, and the problem is intermittent, so I'm not certain yet that Owncloud is responsible.
The System Monitor blames cinnamon. Perhaps it's an issue with the Owncloud panel icon? (Which might count towards Cinnamon's CPU usage and not Owncloud.)

**Comment by cweiske** [comment]
yes, I am using the owncloud desktop client.

**Comment by mlda065** [comment]
I lodged [a bug](https://github.com/owncloud/client/issues/4990#issuecomment-229226354) with the Owncloud team. They think it might be an issue with cinnamon.

> In the end, this is probably a bug in cinnamon. Yes, the client re-setups the tray menu several times per minute (to work around other tray menu bugs...) but doing so shouldn't cause excessive CPU use.
