### ISSUE TITLE
Add scalable icons to categories in Adwaita.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/cinnamon#11587]
Other distributions like EndevouOS, Manjaro and Arch Adwaita lack many icons. I know it's the responsibility of the GNOME team and Linux Mint maintains icon version 41, but I reported this issue and they told me that the DE developers should address this issue. The solution would be to include scalable category icons and generic icons in apps with missing icons in the hicolor icon folder. The example of the problem shows the image below:
![Captura de tela de 2023-03-25 06-07-19](https://user-images.githubusercontent.com/59381215/227735290-fd85f5db-fedb-45a7-a488-0093885fb56d.png)

**Comment by JosephMcc** [comment]
I'm a little confused. In areas like menu that you show in your screenshot, None of those icons like Multimedia or the power icons should even be symbolic. So I don't know how distributing any symbolic icons would help here.

**Comment by Initu-Castilhos** [comment]
As shown in the image below:
![captura-de-tela-de-2023-03-11-22-35-36](https://user-images.githubusercontent.com/59381215/227748647-dddd772a-4af3-42ab-91ef-6031d1a491aa.png)

**Comment by Initu-Castilhos** [comment]
> I'm a little confused. In areas like menu that you show in your screenshot, None of those icons like Multimedia or the power icons should even be symbolic. So I don't know how distributing any symbolic icons would help here.

I changed the request from symbolic icon to scalable. Rolling release distributions will soon have Adwaita icons in version 44, which uses scalable icons in svg.
https://github.com/GNOME/adwaita-icon-theme

**Comment by Initu-Castilhos** [comment]
> Estou um pouco confuso. Em áreas como o menu que você mostra na captura de tela, nenhum desses ícones, como multimídia ou ícones de energia, deve ser simbólico. Portanto, não sei como a distribuição de ícones simbólicos ajudaria aqui.

I hope I've been more clear now.

**Comment by SparkyBluefang** [comment]
Put a different way, newer versions of `adwaita-icon-theme` have removed a number of what they consider "legacy" icons, starting around version `41`. Since then, Debian had been maintaining a 'patched' version of their package to restore these removed icons, and other distros had followed suit. However it doesn't look like they've published updated packages for version `44`.

Gentoo just stabilized and switched to version `44` without these "legacy" icons present.

![Screenshot from 2023-05-08 00-01-13](https://user-images.githubusercontent.com/3150882/236732192-a0340cee-fabb-46c6-bada-475cab7b0727.png)

Notice the category icons missing. The `System Settings` menu item icon (`preferences-desktop`) is also missing.

See
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/merge_requests/34
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/136
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/163
https://gitlab.gnome.org/GNOME/evolution/-/issues/1698

"Regressions"
https://gitlab.gnome.org/GNOME/evolution/-/issues/1848
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/171
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/166
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/216
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/238

I can understand the GNOME developers wanting to strip down the theme and not include application specific icons, but this does seem to be contrary to the FDO Icon Theme Specification. At the very least I would argue that category icons belong in the icon set. But this seems to be yet another instance of the GNOME devs doing whatever they please, the rest of the ecosystem/specs be damned.

https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

There is a MR in `gnome-themes-extra` to ship the legacy icons, but it's been ignored for a year.
https://gitlab.gnome.org/GNOME/gnome-themes-extra/-/merge_requests/9

Not sure where we can go from here, since Adwaita no longer appears to be an FDO conformant icon theme, and I doubt any level of push-back is going to get GNOME to change course.

Does Cinnamon/Mint have a preferred/recommended alternate icon theme? Or is this one of those "up to the distro" packaging decisions?

**Comment by Initu-Castilhos** [comment]
> Em outras palavras, as versões mais recentes do `adwaita-icon-theme`removeram vários ícones que consideram "herdados", começando em torno da versão `41`. Desde então, o Debian manteve uma versão 'corrigida' de seu pacote para restaurar esses ícones removidos, e outras distros seguiram o exemplo. No entanto, não parece que eles publicaram pacotes atualizados para a versão `44`.
> 
> O Gentoo apenas se estabilizou e mudou para a versão `44`sem esses ícones "legados" presentes.
> 
> ![Captura de tela de 2023-05-08 00-01-13](https://user-images.githubusercontent.com/3150882/236732192-a0340cee-fabb-46c6-bada-475cab7b0727.png)
> 
> Observe que os ícones de categoria estão ausentes. O `System Settings`ícone do item de menu ( `preferences-desktop`) também está ausente.
> 
> Consulte [https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/merge_requests/34 ](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/merge_requests/34) [https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/136 ](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/136) [https:/ /gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/163 ](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/163) https://gitlab.gnome.org/GNOME/evolution/-/issues/1698
> 
> "Regressões" [https://gitlab.gnome.org/GNOME/evolution/-/issues/1848 ](https://gitlab.gnome.org/GNOME/evolution/-/issues/1848) [https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/171 ](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/171) [https://gitlab .gnome.org/GNOME/adwaita-icon-theme/-/issues/166 ](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/166) [https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/216 ](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/216) [https://gitlab.gnome.org /GNOME/adwaita-icon-theme/-/issues/238](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/238)
> 
> Eu posso entender os desenvolvedores do GNOME querendo despir o tema e não incluir ícones específicos de aplicativos, mas isso parece ser contrário à Especificação do Tema de Ícones do FDO. No mínimo, eu diria que os ícones de categoria pertencem ao conjunto de ícones. Mas esta parece ser mais uma instância dos desenvolvedores do GNOME fazendo o que bem entendem, o resto do ecossistema/especificações que se dane.
> 
> https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
> 
> Há um MR `gnome-themes-extra`para enviar os ícones legados, mas foi ignorado por um ano. https://gitlab.gnome.org/GNOME/gnome-themes-extra/-/merge_requests/9
> 
> Não tenho certeza de onde podemos ir a partir daqui, já que Adwaita não parece mais ser um tema de ícone compatível com FDO, e duvido que qualquer nível de resistência faça com que o GNOME mude de rumo.
> 
> O Cinnamon/Mint tem um tema de ícone alternativo preferido/recomendado? Ou essa é uma daquelas decisões de embalagem "até a distro"?

Thank you for reporting this issue in more detail.

**Comment by Initu-Castilhos** [comment]
I think it would be better for the Mint team to create a m for Adwaita icons from version 41 and rename it to Adwaita-Legacy and already take advantage and solve this problem too #11588

**Comment by EarldridgeJazzedPineda** [comment]
adwaita-icon-theme-legacy is a thing now: https://gitlab.gnome.org/GNOME/adwaita-icon-theme-legacy

**Comment by leigh123linux** [comment]
This is no longer relevant as adwaita is blacklisted. 

https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py#L37

**Comment by EarldridgeJazzedPineda** [comment]
Adwaita is blacklisted, sure, but AdwaitaLegacy (the theme provided by adwaita-icon-theme-legacy) isn't. In fact, it provides the same set of icons as and can be used as a drop-in replacement for gnome-icon-theme.
