### ISSUE TITLE
Rename "master" to "main" branch

### ISSUE THREAD

**Issue by danimesq** [linuxmint/cinnamon#11655]

**Comment by danimesq** [comment]
@clefebvre "completed" where?

**Comment by Secret-chest** [comment]
Does it matter? Having the master branch does not imply we call the other ones slaves.

**Comment by JosephMcc** [comment]
@danimesq when you close an issue on github it automatically adds that "closed as completed" bit.

**Comment by clefebvre** [comment]
Sorry, I didn't mean for it to look like it was completed. The issue is closed, i.e. rejected.

We don't agree or disagree. As a project we keep away from politics, ideology, religion, or anything that divides people and has nothing to do with us. Some projects take sides and like to mix everything. We don't, we're only interested in what we're doing. That's what unites us.
