### ISSUE TITLE
Alt+f2 launcher background gradient has visible banding

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/cinnamon#11753]
### Distribution

Arch

### Package version

5.8.4

### Frequency

Always

### Bug description

![Tooltip_001](https://github.com/linuxmint/cinnamon/assets/2271906/2fd24ce1-798b-4e37-a419-863a2ffc6e79)

The background gradient shows visible elliptical bands centered around the Alt+F2 dialog. I'm not sure if this is intentional, but can it be replaced by a continuous gradient?

### Steps to reproduce

Press Alt+F2

### Expected behavior

The background has a flat semi-opaque overlay, or a smooth gradient with no visible bands.

**Comment by gauravjuvekar** [comment]
The width of the bands is inconsistent and seems to depend on the color of the background. 

![Tooltip_002](https://github.com/linuxmint/cinnamon/assets/2271906/bc2709bb-4100-4ad0-9854-3e45be39ea3c)

**Comment by fredcw** [comment]
If you use a color picker to examine the color codes, the bands are actually only 1 color code difference between them. e.g. #272727 next to #282828 next to #292929. So this must be due to the way your monitor is displaying the colors. I think it's also partly an optical illusion where your eyes see a greater difference of shade at the boundary between different shades. The way to fix this is either to adjust the monitor brightness or contrast, or to not have such a gradual change in shade so that the bands are closer together but that means darker at the edges of the screen and lighter in the middle.

**Comment by gauravjuvekar** [comment]
Right, 8bit (256 gray shades) is not enough to display a smooth-enough gradient on a high resolution display. In that case, it would look less distracting to have a simple flat alpha filter instead of a radial gradient.

**Comment by fredcw** [comment]
The pattern is in effect an alpha filter because it's gradually mixing black with the background picture. Ultimately every pixel must be some color code value #000000 to #ffffff so I don't see any way around this except for dithering (introducing random noise).
