### ISSUE TITLE
workspace-switcher ignores monitor/xrandr events, should refresh self on changes

### ISSUE THREAD

**Issue by Fry-kun** [linuxmint/cinnamon#11812]
### Distribution

Debian GNU/Linux rodete

### Package version

5.6.8

### Frequency

Always

### Bug description

`workspace-switcher@cinnamon.org` does not react properly to monitor changes.
It's set to "visual representation" and works right most of the time -- but when re-plugging the monitors and/or using xrandr to change orientations, the switcher doesn't show the correct new desktop representation.

### Steps to reproduce

* Set workspace-switcher@cinnamon.org to "visual representation"
* Plug in extra monitor
* make a significant resolution change with xrandr (maybe rotate the 2nd monitor sideways?)

### Expected behavior

workspace-switcher should show the new aspect ratio correctly

**Comment by anaximeno** [comment]
I believe this is already fixed in Cinnamon 5.8, if you want you can try the fix and see if it works. To test, download this [file](https://github.com/linuxmint/cinnamon/blob/master/files/usr/share/cinnamon/applets/workspace-switcher%40cinnamon.org/applet.js) and move it to `/usr/share/cinnamon/applets/workspace-switcher@cinnamon.org/` and reload cinnamon.

If it works close this issue, else, specify if it is doesn't work when re-plugging the monitors or using xrandr to change orientations.

**Comment by mtwebster** [comment]
Confirmed fixed in 835b7c5c2ec7fb8090183c00bfe8a26ee9856d2c

**Comment by Fry-kun** [comment]
Thanks so much for linking the fix! Maybe I can patch it into my 5.6.8 too :)
