### ISSUE TITLE
Cannot use Google Online Accounts in LMDE 6 with Nvidia driver

### ISSUE THREAD

**Issue by mrguyperson** [linuxmint/cinnamon#11881]
### Distribution

LMDE 6

### Package version

5.8.4

### Graphics hardware in use

GeForce RTX 3080 Mobile

### Frequency

Always

### Bug description

I am using a fresh install of LMDE 6.When I try to set up a Google Online Account, the log in page opens like it usually does in Gnome/Cinnamon. When I open online accounts and click Google, I am met with an empty window. I've not experienced this on Gnome (Fedora and openSUSE Tumbleweed) or Cinnamon (standard Mint edition). 

### Steps to reproduce

Running the Debian 12 backports kernel 6.4 and Nvidia driver (nvidia-driver meta package, version 525). Open Online Accounts. Click 'Google'.

### Expected behavior

I should see a Google accounts log in page where I can provide my credentials.

### Additional information

I ran online accounts using `cinnamon-settings online-accounts`. The initial output is:

`
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:442: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)
Loading Online Account module
`

Clicking 'Google' provides additional interesting output:
`
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)
`

`
Failed to create GBM buffer of size 600x500: Invalid argument
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)
`

`
Failed to create GBM buffer of size 600x500: Invalid argument
src/nv_gbm.c:100: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)
`

`
Failed to create GBM buffer of size 600x500: Invalid argument
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
`

It seems there is some squirrely interaction with the Nvidia driver, but it's beyond my pay-grade to figure out.

Thanks for your time.

**Comment by RandomlyHuman** [comment]
I have the same problem

**Comment by therealrem** [comment]
Same problem here with LMDE 6 upgraded from LMDE 5 on a desktop with a GTX 1080 and Nvidia driver 525.125.06 (driver package installed with apt from debian repository).

On the other side, this issue does not occur on my laptop (Intel Core i7-10510U) with Intel UHD Graphics and i915 driver running LMDE 6 (upgraded from LMDE 5 as well).

**Comment by mtwebster** [comment]
This looks like an nvidia issue, not limited to a particular desktop:

https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2498
https://forum.manjaro.org/t/cant-add-google-account-on-gnome-online-accounts-a-bug-related-to-nvidia-drivers/145794
https://www.mail-archive.com/slackbuilds-users@slackbuilds.org/msg25815.html

Here's a bug report  for webkit (which renders the google accounts page):
https://bugs.webkit.org/show_bug.cgi?id=261874

Comment [#20](https://bugs.webkit.org/show_bug.cgi?id=261874#c20) mentions a workaround -

try:
```
WEBKIT_DISABLE_DMABUF_RENDERER=1 cinnamon-settings
```

**Comment by therealrem** [comment]
Yes this is a bug that already seems to be corrected in Webkit 2.42.0 published in Debian testing : https://bugs.webkit.org/show_bug.cgi?id=258831#c16

**Comment by therealrem** [comment]
As per this thread (https://bugs.webkit.org/show_bug.cgi?id=261874#c27) /sys/module/nvidia_drm/parameters/modeset has to be enabled to workaround this issue.

So I created a new zz-nvidia.conf file into /etc/modprobe.d/ (new file to avoid adding customizations in other conf files) and put in it the line `options nvidia_drm modeset=1`

Then saved it and triggered a new initramfs image with `sudo update-initramfs -u`

Reboot

Now the `cinnamon-settings online-accounts` does NOT return any error in the terminal when setting up a Google account but the process is not going far further : one can see the moving blue lines after clicked on "next" button in the username screen and I have even reached the password screen once but not more. Still stuck :/

I am going to uninstall the nvidia driver the time to set up my google account then reinstall it.

**Comment by therealrem** [comment]
Okay, a bad then a good news ;-)

AFTER uninstalled the nvidia driver with `sudo apt remove nvidia-driver` and `sudo apt autoremove` then reboot... I got... a black screen when trying to set a google account. In the terminal one can see `libEGL warning: DRI3: Screen seems not DRI3 capable` and 'libEGL warning: DRI2: failed to authenticate'.

BUT the following command allowed me to successfull set the google despite the same error messages : `WEBKIT_DISABLE_COMPOSITING_MODE=1 cinnamon-settings online-accounts`

Btw, this last command was not solving the problem when the nvidia driver was used.

Well that's a temporary solution just to set the Google Online Account...

Problem solved

**Comment by XxJooO** [comment]
> Okay, a bad then a good news ;-)

Ok, thank you for this solution, at least good news for me: it worked, and I was not in need to reinstall!

Greetings
Jo

**Comment by therealrem** [comment]
Hello,

This morning the WebKit rendering engine has been updated to 2.42.1-1~deb12u1.

I then gave another try with setting up a Google Online Account with the Nvidia proprietary driver running : the problem is solved.

This thread should be considered as solved :)

**Comment by mrguyperson** [comment]
Looks like we can close this one. Thanks everyone for the input.

**Comment by teriodore** [comment]
I am seeing what looks like the same or a closely related issue on Linux Mint 21.3 Cinnamon with NVIDIA 470.

This is **not currently a total blocker for me**, because the Google account eventually saved after repeated attempts/workarounds. However, the normal Online Accounts flow was broken: the Google login webview initially rendered blank/stuck, produced GBM/KMS/EGL errors, and the Settings window behaved unreliably.

## Environment

* OS: Linux Mint 21.3 Virginia
* Cinnamon: 6.0.4
* Session: X11
* Kernel: 5.15.0-179-generic
* GPU: NVIDIA GeForce GTX 760
* NVIDIA driver: 470.256.02
* Xorg NVIDIA package: xserver-xorg-video-nvidia-470 470.256.02-0ubuntu0.22.04.1
* Architecture: amd64

## Steps taken

1. Opened System Settings.
2. Went to Online Accounts.
3. Chose Google.
4. Attempted to sign in / add the Google account.

## Observed behavior

The Google login / Online Accounts webview became blank or got stuck. In some cases the Settings window did not close cleanly.

Running from terminal showed graphics/WebKit/GBM-related errors.

Relevant terminal output:

```text
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1000x800: Permission denied
Segmentation fault (core dumped)
```

When launching with:

```bash
WEBKIT_DISABLE_COMPOSITING_MODE=1 cinnamon-settings online-accounts
```

I still saw:

```text
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
```

I also tried launching with:

```bash
WEBKIT_DISABLE_DMABUF_RENDERER=1 \
WEBKIT_DISABLE_COMPOSITING_MODE=1 \
cinnamon-settings online-accounts
```

This helped get further, but the Online Accounts UI still behaved unreliably/stayed stuck.

## Final outcome

After repeated attempts/workarounds, the Google account eventually did save. Afterward, `~/.config/goa-1.0/accounts.conf` contained:

```text
Provider=google
Identity=alexander.aumar@gmail.com
PresentationIdentity=alexander.aumar@gmail.com
MailEnabled=true
CalendarEnabled=true
ContactsEnabled=true
PhotosEnabled=true
FilesEnabled=true
PrintersEnabled=true
```

Google Drive then mounted successfully through GVfs/GOA:

```text
Mount(1): alexander.aumar@gmail.com -> google-drive://alexander.aumar@gmail.com/
Type: GDaemonMount
default_location=google-drive://alexander.aumar@gmail.com/0AG9n90reHvh6Uk9PVA
```

So the Google account itself and credentials were not the problem. The issue appears to be the embedded WebKit/GOA login UI rendering/crashing or becoming blank on this Cinnamon/NVIDIA/X11 setup.

## Expected behavior

The Google login webview should render normally and allow the account to be added without blank windows, crashes, or needing WebKit/NVIDIA-related environment workarounds.

## Actual behavior

The Google Online Accounts webview was initially blank/stuck and terminal output showed GBM/KMS/EGL-related errors. The account did eventually save, but the normal UI flow was unreliable.

## Possible upstream relation

This looks similar to WebKitGTK/NVIDIA/GBM issues where embedded webviews fail with messages like:

```text
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer
```

I am not sure whether this should be fixed in Cinnamon, GNOME Online Accounts, WebKitGTK, or NVIDIA handling, but the user-visible failure happened in Cinnamon’s Online Accounts panel.
