### ISSUE TITLE
File editing without root password by "Open as system administrator" the second time.

### ISSUE THREAD

**Issue by Endorphas** [linuxmint/cinnamon#12235]
### Distribution

Mint 21.3

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

MX150 / dual system

### Frequency

Always

### Bug description

File editing without root password by "Open as system administrator" the second time.

### Steps to reproduce

Right-click on a free area of ​​the desktop and select "Open as system administrator".

You will then have the option of handling files in Dolphin as an administrator.

After closing Dolphin, it is possible - within 5 minutes - to start Dolphin again with root rights, but without entering a root password.

Additional information:

The case described refers to the desktop! The option is also available directly in Dolphin, accessible by right-clicking. But if Dolphin is closed here, a root password must be entered again, as you would expect.

### Expected behavior

After closing Dolphin, automatic root access should not be possible??

**Comment by fredcw** [comment]
This is deliberate. It's so you don't have to keep entering your password in a short space of time.

**Comment by mtwebster** [comment]
I don't know much about Dolphin, but in the past, our file manager (Nemo) would always be running, managing the desktop icons as well as windows, so even with all windows closed, the process continued.

It's also not unheard of for file managers to remain running for some amount of time after the last window closes, to make it quicker to open a new one a short time later.

I have no idea if this is the case here - you're running Cinnamon but using Dolphin - does it manager your desktop, or does nemo still?  There's no 'Open as system administrator' option in nemo, it's 'Open as Root'.

This seems like a Dolphin issue either way (and probably isn't a bug).

**Comment by Endorphas** [comment]
Dear "fredcw" and "mtwebster",

thanks for the answer! I made a mistake - thanks for the tip about Dolphin. I meant Nemo, of course!! I had Debian for a long time and mixed up the names. Sorry!

I have a German interface, and the translation for "Open as system administrator" is "Open as system administrator".

As already mentioned in the report, the root password must be re-entered - without any time delay - within the NEMO interface after Nemo has been closed and restarted (right click -> "open as root" (correct translation)).

But if you open Nemo via the desktop and then close the program, the root rights remain for 5 minutes.

I just wanted to take a screenshot, but if the context menu is open, you can no longer take screenshots. Then I noticed that not a single keyboard shortcut works as long as any context menu is visible. But that's a different bug and I'll create a report (but maybe that's intentional)

Best wishes

**Comment by mtwebster** [comment]
Ah ok, so the password issue:

- There are two nemo 'apps' - the windowed 'nemo' and 'nemo-desktop'.
- Running 'nemo' launches nemo as a window (or another window if one is already open). These all share the same process. As long as at least a single nemo window exists, the same nemo process is running. Once you close the last one, nemo exits.
- The 'nemo-desktop' app runs at startup and remains running the entire session. So, if you open-as-root on the desktop, the process continues. You'll be able to open other folders without a password until the root timeout occurs (normally around 5 or 10 minutes after the last root command, the same as if using sudo in a terminal). After that timeout it will ask you for a password again.

Not being able to take a screenshot with a context menu open is 'normal' - when the menu is open, it also 'grabs' the keyboard, so any shortcut keys go to the menu instead of being caught globally. This is mainly a limitation with the display server (x11).

You can launch the screenshot app from the menu instead, and set a delay. Then you'll have time to open the menu yourself before the screenshot triggers.

**Comment by Endorphas** [comment]
Thank you for the wonderful and understandable description!
Everything is clear for me now.

Have a nice day and best wishes from Vienna
