### ISSUE TITLE
[grouped-window-list@cinnamon.org] recents not show in applets

### ISSUE THREAD

**Issue by ScarletEmanu** [linuxmint/cinnamon#12342]
### Distribution

Mint 22.1

### Package version

6.2.7

### Graphics hardware in use

AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

### Frequency

Always

### Bug description

In the context menu of some icons, like VSCodium and Firefox, there no sub-menu for Recent items. In other icons, like Files and Text Editor, this sub-menu is there.
![Screenshot](https://github.com/user-attachments/assets/bd892701-7073-4313-852d-405471f38458)

![Screenshot from 2024-08-06 18-47-08 -1](https://github.com/user-attachments/assets/594ce797-7a36-44f4-b480-8df92e8c18f2)

### Steps to reproduce

No steps to reproduce. I only checked the option "Show recent items" in Context Menu of the applet.

### Expected behavior

I expect that in the context menu of all icons there is the sub-menu Recent.

**Comment by fredcw** [comment]
The "recent" menu item is only shown if there are recent files of which that application is the default application for opening that type of file.

For instance: If you open a text (.txt) file in LibreOffice Writer, the file will only appear in the recents list of Xed because Xed is the default application for opening text files.

Perhaps this is not the behaviour that should be expected?

**Comment by ScarletEmanu** [comment]
> The "recent" menu item is only shown if there are recent files of which that application is the default application for opening that type of file.

Ok, I don't know that. Thanks
