### ISSUE TITLE
Washed out colors in gtk4 apps

### ISSUE THREAD

**Issue by Rippanda12** [linuxmint/cinnamon#12436]
### Distribution

BredOS (ArchLinux ARM based)

### Package version

6.2.9

### Graphics hardware in use

Mali G610 - Panfork driver

### Frequency

Always

### Bug description

Recently under cinnamon gtk4 apps lost their color in white theme and on dark theme they look gray even

### Steps to reproduce

1. Get cinnamon??? (installed by default on BredOS)
2. Open any gtk4 app

### Expected behavior

GTK4 Apps should look normal

### Additional information

Doesn't happen on my x86 AMD based PC 
Heres some images that will show what im seeing
![image](https://github.com/user-attachments/assets/1c224b29-c8d5-4286-bdbd-0b6d3b593bcd)
![image](https://github.com/user-attachments/assets/d0b0d066-0553-4dc3-91d6-900083203060)
![image](https://github.com/user-attachments/assets/ff2807ec-a21c-4ec7-8316-68acd6e230e2)
![image](https://github.com/user-attachments/assets/15429e2b-6f16-4415-988a-7a82ab02f858)

**Comment by JosephMcc** [comment]
We don't currently build or support ARM based versions of Cinnamon. If your OS is including these, you should probably take the problem to them. Since the issue is only affecting Gtk4 app, my first guess is that it's some sort of gtk4/graphics driver issue but I really don't know.

**Comment by clefebvre** [comment]
Cinnamon should support all architectures. That said, there's nothing specific to GTK4 and/or libAdwaita in Cinnamon..

To make sure, I'd suggest installing another DE on this computer to see if the problem persists.

GTK4 uses hardware acceleration in a very different way than GTK3. It's known to create issues in virtual machines so I imagine it can also create issues on specific graphic chipsets.

The theme used in libAdwaita also dims when the window isn't focused. It's possible this is by design and it just doesn't look nice on your screen.

After testing this with other Xorg DEs (Xfce, MATE for instance) please reopen the issue if you find that it is specific to Cinnamon.
