### ISSUE TITLE
Is there a reason for using Clutter dialogues?

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/cinnamon#12548]
I'm trying to be respectful. What advantages do they bring?

**Comment by 5BNeumann** [comment]
They want the dialogue to stand out more from other apps and It's meant to be an improvement of cinnamon's base theme, well, at least it's what it's meant to be if I understood correctly...

**Comment by mtwebster** [comment]
For Wayland support, the normal Gtk authentication dialogs from an outside process (like pkexec) no longer work - we have no choice but to bring them into Cinnamon. This also removed a dependency on a retired package. The same goes for the network dialogs (another dependency removed also).

It doesn't really make sense *not* to port the remaining dialogs for a consistent experience.

They may look bad/out-of-place because Cinnamon themes have not caught up to these new dialogs, so they fall back to using the default (but newly re-designed) theme. That catching-up will likely happen during beta.

**Comment by Secret-chest** [comment]
It's not your fault, but I see that with wayland doing this for "security", GNU/Linux is turning into Android.

**Comment by Gravarty** [comment]
I'm really not a fan of this. It tries to be minimal but achieves the exact opposite. The original dialog was clean, small and working.. Clutter on other hand feels bigger, more clunky and has no space for longer text.

Would be nice to keep the OG dialogs for X11.

![Bildschirmfoto zu 2024-12-08 10-33-48](https://github.com/user-attachments/assets/2d9b1b75-4968-4625-aa56-c4d464688ccc)

**Comment by Secret-chest** [comment]
Don't they also work in Wayland? I know Wayfire even allows the user to change the dialogues.

**Comment by tutralex** [comment]
It looks terrible and alien!

**Comment by M0JXD** [comment]
I understand these are required for improved Wayland support but is there any way these clutter dialogs can be themed to match the rest of the desktop environment? The button styles, window shades and shapes are completely different.
