### ISSUE TITLE
GTK4 theme not loaded

### ISSUE THREAD

**Issue by PowaBanga** [linuxmint/cinnamon#12551]
### Distribution

Archlinux

### Package version

6.4.0

### Graphics hardware in use

integrated

### Frequency

Always

### Bug description

When i set Arc-Dark in themes, it is not applied to gtk4 applications

### Steps to reproduce

change the theme via the theme manager application of cinnamon

### Expected behavior

The environment variable GTK_THEME should be set to Arc-Dark, but it's not the case....

**Comment by fredcw** [comment]
Gtk4 apps are themed correctly according to the theme set in theme settings. However, almost all gtk4 apps are also libadwaita apps and libadwaita is not supported by any Mint themes and there's no intention to. See [Monthly News – April 2024](https://blog.linuxmint.com/?p=4675)

**Comment by clefebvre** [comment]
wait... it's not that Mint themes don't support libadwaita.

It's that libAdwaita apps, by design, don't follow the system theme.

**Comment by clefebvre** [comment]
Mint themes do support GTK4.

LibAdwaita apps don't follow the system theme, by design.

**Comment by fredcw** [comment]
>It's that libAdwaita apps, by design, don't follow the system theme.

Yes, that's what I meant to say. xD

**Comment by PowaBanga** [comment]
thanks for the link, it's very well explained !
I will change my desktops applications when it's possible

**Comment by fredcw** [comment]
@PowaBanga Not sure how you add an environment variable but since you're using arch, the easiest way is probably to replace libadwaita package with AUR package libadwaita-without-adwaita. This is not a long term solution though because most people won't resort to hacks and most theme designers won't bother to support libadwaita for this reason.

Btw, I'm curious, what libadwaita apps are you using because I'd hope that there's a good replacement for each of them?
