### ISSUE TITLE
Taskbar on second monitor

### ISSUE THREAD

**Issue by tbekolay** [linuxmint/Cinnamon#130]
Really loving Mint 12 with Cinnamon. One feature that would be great for the future would be to allow a second taskbar on a second monitor, listing the windows currently showing on that monitor, as was possible in Gnome 2.

**Comment by mdsitton** [comment]
So just got back, and im playing with it a bit more. Another issue that im seeing quite a lot are ghost panels. Panels with nothing on them that with varying levels on interactivity. Some of them i can right click on and get that context menu. Others don't do anything. On the ones that do give me a context menu being in edit mode, and selecting remove panel does nothing.

**Comment by dalcde** [comment]
You're getting weird issues that neither I nor JosephM has experienced. Just to make things clear, this is how add/move panels work:

When you click the add/move panels button, dummy panels will appear in possible locations of the new panel (they can be seen if and only if you are using the default theme). You click on one of theme to select where you want the panel to be. If you change your mind, you can press Esc to cancel the action.

**Comment by mdsitton** [comment]
That would explain why It was hard to figure out how to move panels. I wasn't using the default theme.

Still getting those ghost panels though. However i have figured out when they start happening.

Seems that moving any blank panel works perfectly. However when moving panels with the default applet configuration on it things, they create ghost panels.

Haven't tested with alternative panel configurations to see if there is any specific applet that is causing it though. 

Also here is a bit of clarification with what I'm calling ghost panels, and how they behave.

They basically seem to reference the panel that left it behind. So if i select move on a ghost panel it moves the original panel that created it.

Selecting remove panel on a ghost panel removes neither the ghost panel nor the original panel. However it does break the original panel. When the original panel gets broken like that it cannot be moved or  removed, and copying the applets on it seems to crash everything.

Also another issue i came across when trying to track this down, removing a panel doesn't remove the applets from that panel. So whenever you add a new panel it recycles previous panel configurations. Also because of that applets will show as still on a panel, but they have an error status(in the applet settings menu).

All my previous posts are basically invalid :P

**Comment by dalcde** [comment]
Do you get errors in .xsession-errors/lg?

The retaining of applets is intentional (and was the default behaviour with the old hardcoded 2-panels iirc). It would be annoying if you accidentally removed a panel and have to add all the applets back. However, I also see cases where the user would expect the applets to disappear. It wouldn't be difficult to change this behaviour, so I guess we can sort all bugs out before going into these design decisions.

**Comment by mdsitton** [comment]
I'm on arch, and don't use a login manager or anything. But yeah there are errors in what would i'm assuming is normally output to .xsession-errors

Here is what i have if it is of any help.

https://gist.github.com/mdsitton/bfa119ba361adbcbf3af

**Comment by dalcde** [comment]
Try again

**Comment by mdsitton** [comment]
Try what again?

**Comment by mdsitton** [comment]
Oh alright

**Comment by mdsitton** [comment]
Seems to be fixed, awesome.

**Comment by mdsitton** [comment]
Now the only complaint i really have is that pressing the super key doesn't open a menu located on the monitor your focused on at that time. Then a feature request: add the ability to show only the applications on a monitor in the window list. Not really sure how difficult those will end up being.

Great job so far though.

**Comment by JosephMcc** [comment]
For now for the window list applet you can use this: http://cinnamon-spices.linuxmint.com/applets/view/181

**Comment by anibyl** [comment]
+1

**Comment by AnatolyRugalev** [comment]
+1

**Comment by nutztherookie** [comment]
+1

**Comment by amochumber** [comment]
+1

**Comment by cristiklein** [comment]
+1

**Comment by cavb** [comment]
+1

**Comment by anandrkris** [comment]
Guys, it is known fact that this is a much needed feature. There is a PR already so please dont bump. Its bumped hard enough already. :stuck_out_tongue_winking_eye:

**Comment by artem-sidorenko** [comment]
@dalcde are there any special backgrounds for closing this?

**Comment by mtwebster** [comment]
This work was merged last night:

https://github.com/linuxmint/Cinnamon/compare/23befb8d7cbda36f5f1425edc1dbb88155fc1115...a60fc6c1365cf1417087d04410f208d976adc2c9

Big thanks to @dalcde 

There *will* be bugs - please file new reports for any issues discovered.

Known issues:

- If you have adjacent monitors with different heights (for example, a 1050 and a 1080), even if you disable the 'pointer barrier' you will have an issue with moving from one lower panel to the next, as the 30 pixel shortfall creates its own barrier.  We're waiting to see if this is a concern before trying to do anything about it.
- There are panel highlight styles that let you know which panel you're configuring, that currently only exist in the default Cinnamon theme - we're looking at ways to make this universally visible, regardless of theme.
- Our stock applets have not been adapted to understand multiple monitors yet (like the window list) - we'll be going through all of them shortly to a) enable multiple instances where possible, and b) make them work properly if/when there are multiple instances on multiple monitors.

Can we worry about world peace now? :)

**Comment by Garibaldo** [comment]
Many thanks to @dalcde and @mtwebster ; you guys are really great!

**Comment by mazzarito** [comment]
@dalcde @mtwebster thanks for all your hard work this is awesome. The solution I hacked together around a year ago included a version of window list applet which allowed for choosing which monitor to show the window list from, should work temporarily for anyone who needs it until the extensions can be worked on:

http://cinnamon-spices.linuxmint.com/applets/view/181

**Comment by DDarko** [comment]
+1

**Comment by taquangtrung** [comment]
+1 from me. I really miss this feature after switch from Xfce to Cinnamon
