### ISSUE TITLE
intelligent search in mintMenu

### ISSUE THREAD

**Issue by PatriciaMoeller** [linuxmint/Cinnamon#1320]
It would be great if the search function in mintMenu would remember which application has been selected on a search, and offer this one in a preffered order as primary option, on the next search.

The GNOME Shell search function behaves like that, too.

**Comment by ManIVIctorious** [comment]
related to #1220

**Comment by abdupattoh** [comment]
I still use gnome-do a lot just because of the intelligent search capabilities.  It also has the ability to learn what your preferences are, and choose the right one.  For example, after selecting "Emacs GUI" instead of "Emacs Text" a couple times, it always presents that option first.

Customization universal search is a very strong feature that Gnome Do seems to get better than just about anybody else I guess.  

If Mint menu added some of those capabilities I would really like it - right now I hide the activation key sequence for the mint menu because it gets in the way of Gnome-Do right now...

**Comment by janw-oostendorp** [comment]
I It saddens me to see that this issue has been open for 5 years. And a bunch of related like requests also going nowhere. :(

**Comment by JosephMcc** [comment]
Alright, lets keep this all in one place. I don't need notifications from all these related issues when people feel the need to copy/paste a response in them.

https://github.com/linuxmint/Cinnamon/issues/4053#issuecomment-307473584
