### ISSUE TITLE
Adjusting mouse wheel scroll rate

### ISSUE THREAD

**Issue by randomizer101** [linuxmint/Cinnamon#1361]
It would be nice if there was a way to adjust the number of lines scrolled per "notch" of the scroll wheel on the mouse, or some similar metric (even a multiplier on top of the base number of lines?). I don't think GNOME has ever included such an option, at least since 2.x, while KDE has had it for a long time, so I think it would be a welcome addition to Cinnamon. This might be a difficult task though if the limitations are in GTK and can't be worked around at a higher level.

I know that you can set the scroll rate in Firefox which is fantastic. That doesn't help other applications like LibreOffice though. Scrolling through a 60 page document 3 lines at a time is painful.

**Comment by dalcde** [comment]
afaik individual applications decide what to do with scroll events. I can write an application that totally ignores scroll events. It works with Qt applications since Qt applications let Qt to decide what to do, and Qt allows you to change the behaviour. Sometimes you can change it via some xorg settings, but depends a lot on exactly what input device you are using. Closing unless there is a valid universal solution.
