### ISSUE TITLE
multiple monitors above each other - windows can't be moved

### ISSUE THREAD

**Issue by kaefert** [linuxmint/Cinnamon#1437]
I have a Zenbook UX32VD running Linux Mint 14 Cinnamon 64bit Edition.

With one external monitor connected and configured in a way that the external monitor is placed exactly above the internal one, I cannot move windows to the external monitor, since they always "keep hanging" with the last 50 pixels (or so) on the internal monitor. I also cannot maximize windows to the external monitor and if I try to resize that window it gets moved automatically so that at least those 50 pixels are kept in view of the internal monitor.

On a different setup, if I have 2 external monitors beside each other and the internal monitor configured to be below those two, but in the middle, so not exactly below one of those monitors, I can move windows as expected. However maximising does work but not as expected, and the moving has some restrictions.

I've first filed this bug there: https://bugs.launchpad.net/cinnamon-desktop/+bug/1083127
But since I got no response I did a little googling on cinnamon bugtracker and found this here. Over in the launchpad bugtracker I've also attached a few screenshots to make the issue clearer.

**Comment by StanSvec** [comment]
On Linux Mint 17.2 / Cinnamon 2.6.13 I cannot move any window from my primary display to my secondary display located above. This issue is only presented when Cinnamon panel is placed at top which is my case. Very annoying issue. :( Could somebody please look at it?

**Comment by KOLEGA007** [comment]
@StanSvec Its working for me :( https://youtu.be/OyNwjGUgcTc

Do you have clean instalation of LM? or upgraded?

**Comment by kaefert** [comment]
@KOLEGA007 the video shows that the pointer can move to the screen above the one with the top-panel - can you also move windows there?

**Comment by KOLEGA007** [comment]
Damn ... I have pretty bad reading skills ... 

The draging windows works only if the panel is auto-hide or inteligent autohide ...

**Comment by kaefert** [comment]
ah. yes. I can remember that behavior. well that's not really too nice
mostly if you have multiple screens you have enough space on them that you would want to have your panels not on auto-hide.

**Comment by mscheper** [comment]
Still present in Cinnamon 64b 2.6.13 under Mint 17.2 Rafaela.

A few things I've noticed:
* If the external, upper monitor is *wider* than the laptop monitor (in my case, 1920 wide and 1600 wide), there are parts of the middle of the external monitor where you can't drag windows.
* If the external, upper monitor is *narrower* than the laptop monitor (in my case, 1280 wide and 1600 wide), and the external monitor is entirely on top of the laptop monitor in the Display Settings, you can't really drag the window anywhere on the external monitor
* *Partial workaround*: If the external, upper monitor is narrower than the laptop monitor, but the right edge of the external monitor is significantly to the right of the right edge of the internal monitor (see screenshot), it's possible to drag windows to part of the external monitor, but not the left edge of the screen
![verandering-window-2015-09-29-122614](https://cloud.githubusercontent.com/assets/366599/10153985/58d3bec2-66a5-11e5-844b-4007979c36ed.png)
* *Partial workaround*: In some cases, you can still position window where you want by resizing an edge where you want it. But this often causes the opposite edge to behave erratically.

I've been frustrated by this bug for years, since Mint 11. Let me know what I can contribute to help fix it. I'm using a Lenovo T430s, and various external monitors, with VGA connections.

**Comment by g2kokaro** [comment]
I'm experiencing this as well. When I have a panel at the bottom of the top monitor, I can't drag windows down to the bottom monitor. It seems like the panel is blocking the window from being dragged down (it won't let the title bar of the window go past it). Placing the panel elsewhere works around the problem. Interestingly, having a panel at the top of the bottom monitor does not inhibit moving windows between monitors.

**Comment by JosephMcc** [comment]
This should now be fixed in git master by 
https://github.com/linuxmint/muffin/commit/72dacf50548811f3ff5f91ec1ebdc4f71e6d1450
and
https://github.com/linuxmint/Cinnamon/commit/c77685b1e584ef83a75d35cc073e0b2f7762f4dd

**Comment by kaefert** [comment]
will this fix be included in mint 17.3?
Or what is the most sensible way to get a system with this fix?

**Comment by AlbertJP** [comment]
No release of muffin has been done yet since the fix. You could build muffin from source (http://segfault.linuxmint.com/2013/10/how-to-build-and-install-the-latest-cinnamon-from-git/) or wait for a new release of muffin. As I have not been involved with Cinnamon development recently I don't know when one will come.

**Comment by JosephMcc** [comment]
I should be part of 17.3. During the first month or two after a Cinnamon release there are usually several point releases that are done once a few bug fixes have built up. Probably the easiest way to get this now is the Cinnamon nightly builds PPA.

**Comment by binarymist** [comment]
This is still in 18.

**Comment by binarymist** [comment]
Yeah, I remember having this issue years ago, but it seems that in mint 18 it's back. If the top monitor is directly centered above the laptop screen, then it seems any window on the top screen can not cross over  a section in the middle of the screen. If the top screen is moved slightly left or right (not physically) then that seems to fix the issue. It also seems fine when the screen are horisontally adjacent.

Cheers.

**Comment by fmgj** [comment]
There's a workaround. Assume the secondary screen is on the bottom. If you move the window as far down as possible, then resize from the top of the window to below the screen boundary, the window will now be entirely on the new screen. You can then maximize and it will fill the new screen. Admittedly, it's a pain, but it does work.

**Comment by curiousb** [comment]
It's still there in cinnamon 4.4.8 under Pop!_OS 20.04 focal (x86-64).
with internal laptop monitor under and 2 external monitors split above in shape of T, it's not possible to place some windows at the top of the external monitors (30px zone unusable) but can place system windows there ie: settings.
Cannot place interactive brokers trader work station windows at top of external monitors neither with autohide nor intelligent autohide enabled.

**Comment by OoDeLally** [comment]
I still have this issue with cinnamon 4.6.7.

I have a small fullhd monitor on top of a bigger 4k monitor.
The user interface scale is `Double (Hi-DPI)`. 
The small display uses a `125%` fractional scaling, while the big display does not use any.
I've played around with various settings, and I can tell this issue only happens if all the following conditions are true:
- Monitors are on top of eachother.
- At least one monitor uses fractional scaling.

Something I've noticed in this situation is that there is a one-pixel row of overlap between the monitors. I can see the bottom of the top monitor overlapping the top of the bottom monitor. This overlap is correlated with the window-moving bug.
