### ISSUE TITLE
Alert user with sound/notification when battery is critically low

### ISSUE THREAD

**Issue by dalcde** [linuxmint/Cinnamon#1519]
http://community.linuxmint.com/idea/view/3441

**Comment by plagasul** [comment]
+ 1 to this feature, it would be very useful

**Comment by A-Shahbazi** [comment]
I wanted to add something relevant to this bug:

I took a look at [here](http://www.wired.com/2013/09/laptop-battery/), [here](http://batteryuniversity.com/learn/article/do_and_dont_battery_table), and [here](http://www.howtogeek.com/124715/should-i-leave-my-laptop-plugged-in-all-the-time/). It seems that if one does not “deep-cycle”(fully discharge and recharge) a Lithium-ion battery the battery life will be prolonged substantially. So it is a good idea to notify the user to plug in when the battery is discharged to a user-set lower battery level and notify to unplug charger when the battery level reaches to a user-preferred level.

**Comment by Vahan86** [comment]
Now the system alerts user with notification when the battery is critically low.

![untitled](https://cloud.githubusercontent.com/assets/12819058/18029985/c9fc05d6-6cb8-11e6-9f1d-0ea0fb23350c.png)

@JosephMcc can we close this issue?

**Comment by JosephMcc** [comment]
Yeah I think so. Currently sound effects for notifications aren't enabled by default but can be turned on Cinnamon Settings->Sound on the sound effects tab.

**Comment by pdcurtis** [comment]
I believe this issue was closed to early and it happened just as I was about to put in an input as I have written a simple applet as suggested by anandkris. It was provoked because I have recently had a couple of times where I have missed the notifications about low battery. My latest version of Cinnamon also seems to have lost the setting to specify the action when the battery is critical. In any case there is no easy way I  have found to set the 'critically low' level in Mint 18 Sarah/Cinnamon 3.0 which seems to be far too low.
This applet allows one to set a level at which the machine starts to shutdown (Suspend to Memory as currently set up) with plenty of warning - the shutdown level is 2/3 of the initial alert level.
The applet normally shows the percentage charge on a colored background which is:
    Green when above the alert level (set currently to 1.5 times the 'shutdown' level.)
    Orange between the warning and shutdown level
    Red and flashing at and below the Shutdown level (even when charging).
  When the Alert level is reached a modal alert is put up which can not be missed as no input can be made until it is cleared.
   When the shutdown level is reached a normal alert box is put up with options of an immediate suspend or cancel - if nothing is done it suspends 30 seconds latter.
The alert level can be set to between 10% and 40% of full by a slider on the left click menu or in the configuration screen. The refresh rate can also be set in the configuration screen.
The intention is to allow the possibility of leaving suspend with enough battery to close programs and shut down after powering up from suspend without a charger after an accidental unattended suspend.

The Battery Applet with Monitoring and Shutdown (BAMS) can be found at https://cinnamon-spices.linuxmint.com/applets/view/255
