### ISSUE TITLE
notifications not displayed when fullscreen

### ISSUE THREAD

**Issue by jlongster** [linuxmint/Cinnamon#1646]
Is this intended? I'm using the latest Cinnamon with Arch Linux. When I have Emacs in full screen mode, notifications don't show up (I'm assuming they are underneath Emacs).

**Comment by mkjois** [comment]
Old but still relevant. I'm having the same issue and still can't find out whether this is intended or changeable.

**Comment by SunRed** [comment]
This is still relevant. This is annoying especially if you gonna watch something in full screen on low battery and you don't see the notification warning because of this bug. I don't think this is intended since other DEs like KDE and Gnome also support this feature.
I would like to refer to [launchpad](https://bugs.launchpad.net/linuxmint/+bug/1162198). If more people subscribe maybe the developers will take note and fix this.

**Comment by donquixote** [comment]
Absolutely +1.
Low battery use case, as mentioned by SunRed.

**Comment by plagasul** [comment]
I find this very relevant, in particular in combination with not being able to see the low battery warning
