### ISSUE TITLE
I can't manage the brightness level

### ISSUE THREAD

**Issue by I-sty** [linuxmint/Cinnamon#1671]
I can't manage my brightness level. Nothing with brigtness applet, not with function keys (Dell inspiron 5520)
With brightness applet I have alway 100%. I manage by: echo "xxx" > /sys/class/backlight/intel_blacklight/brightness
If I set 20% in applet when the popup closed, I click the brightness icon and the level is 100%. I can't manage.
But with Function keys, when I press the popup brigtness level not changed (or max level, or (max-1)level) always 100% if I press more brightness if I press less brightness.

<img src="http://kepfeltoltes.hu/130124/Screenshot_from_2013-01-24_15_09_13_www.kepfeltoltes.hu_.png" />

**Comment by JosephMcc** [comment]
Can any of you still reproduce this on Cinnamon3?

**Comment by Enkouyami** [comment]
I can't reproduce it anymore on any of my laptops.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by CottonEaster** [comment]
@JosephMcc, sorry to be a pain, but might you point me towards Mint's code (or, if it s not Mint's code, whoever's code) for adjusting the brightness via the function keys? For, that code works on my systems, but I can't - on one Dell system - adjust the brightness via script. That's why I like to see how Mint manages to make it work. Thanks.
