### ISSUE TITLE
Make applets scrubbable

### ISSUE THREAD

**Issue by ryanrms** [linuxmint/Cinnamon#1732]
In Unity, the app indicators allow you to "scrub" between them.  That is, you can simply move your mouse to the next applet and it will be selected and the menu for it will open.  In Cinnamon, you have to click each individual applet.  

Say if I have Menu and the Places applet next to each other, when I click menu, I should be able to switch to places simply by hovering over it, instead of having to click like I do now.

**Comment by Vahan86** [comment]
Looking forward to have this feature implemented.

**Comment by mtwebster** [comment]
Not all applets have anything to open up - many of them say everything they need to say right on the panel.  Panels are not menu bars in Cinnamon - I think it would be confusing to roll across the panel, and some things open, some don't.

**Comment by Vahan86** [comment]
It works in Unity and though it is a little thing, but super user-friendly feature. It's pity that there is no plans, as I understood, to implement it.

**Comment by ManIVIctorious** [comment]
I would like to see this feature too, i also don't unterstand your argumentation here, if an applet doesn't have anything to open it wouldn't have to with this feature either

**Comment by JosephMcc** [comment]
I don't see where this would add some fantastic new usability to Cinnamon. In some cases applets even have tooltips that display the info you want to see on hover. This would not be as simple and clean with applets as it is in unity either since many applets contain multiple children with their own menus like the panel launchers and window list.

This would add a lot of complication to our code along with all the potential bugs it would bring for very little usefulness.

**Comment by Vahan86** [comment]
@JosephMcc , this is not about window list, but rather about indicators. I agree with you that in case of window list the requested feature won' t work as we expect.
