### ISSUE TITLE
Hypersensitive dragging in window list and panel launchers

### ISSUE THREAD

**Issue by Martinique** [linuxmint/Cinnamon#1748]
When I click a button on the window list applet, very often the click is interpreted as a drag event instead. The same also happens in the panel launcher applet, but less often, it seems.

At first I thought my mouse was buggy, but then I saw this happening on other workstations as well. This slows down work quite a bit, as I always stop to wait for the window to open, thinking the OS is just busy, so I decided to report the issue.

Looks like heavy CPU load makes the problem worse, as this happens less often on fast hardware. It's as if the button release event gets to Cinnamon long after it actually happens or not at all, and by that time the mouse has probably moved, making it look like dragging.

Sensitivity does not seem to be affected by mouse drag preference in org.gnome.settings-daemon.peripherals.mouse/drag-threshold.

I'm running Cinnamon 1.6.7 on Ubuntu 12.04.

**Comment by jlynch1** [comment]
t-oster, I can confirm the exact same issue on Ubuntu 14.04.4 LTS with cinnamon  2.6.12ubuntu1 as in your youtube video.  Always happens to the first window in the  that was opened and **only** the first window. (when you hover, without clicking, on that window in the panel, it is automatically goes into drag mode, and the only way to release the drag is to move outside of the panel with the mouse and hit escape button on keypad). If I close the first window (gnome terminal this time) and re-open it, this dragging issue does not happen to gnome terminal or any other windows in the panel.

I adjusted the drag and drop threshold from 8 to 100 which seems to work around the issue, but it is not fixing the root cause of the issue.

**Comment by JamesVStone** [comment]
Same. I now just use hot corners insted

**Comment by wearefridayhutber** [comment]
I can't for the life of me work out how I control the drag and drop threshold

**Comment by karlmortensen** [comment]
@wearefridayhutber It's in the Mouse and Touchpad settings, under General.
