### ISSUE TITLE
Menu panel doesn't work properly in VirtualBox seamless mode

### ISSUE THREAD

**Issue by hayounav** [linuxmint/cinnamon#1770]
This might be a VirtualBox issue. If so, I'll post on their bug tracker.

I am running linux mint 14 32-bit with Cinnamon 1.6.7 as a guest in Windows 7 SP1 64-bit.

When entering seamless mode, the bottom panel disappears and whatever's in the background in windows 7 environment is show instead (see attached image).

Choosing the "Auto hide" setting in Cinnamon Settings > Panel fixes the issue (the panel is now visible while hovering over the bottom of the screen with the mouse), but disabling the option brings back the same issue again.

This happened with VirtualBox 4.2.6 and now with 4.2.8 as well (latest extensions and guest additions installed).

The guest Mint is running with 2GB RAM, 4 CPUs, hardware virtualization, 128MB VRAM and 3D acceleration enabled.

The host GPU is an nVidia GeForce GT 650M with 2GB dedicated memory, running the latest stable drivers (310.90).
![Capture](https://f.cloud.github.com/assets/3761885/215961/d9421dcc-84af-11e2-88d4-4206f1b2f106.PNG)

**Comment by xeros** [comment]
This issue still persists in Cinnamon 2.6.11 on Mint 17.2 32-bit running as a guest in VirtualBox 4.3.28 & 5.0-rc3 (tested both versions) on Windows 8.1 64-bit host.
Tried with VirtualBox addons:
- stock, packaged in Mint 4.3.10-dfsg-1 (from multiverse repo)
- 4.3.28
- 5.0-rc3
In every combination there's the same problem.
MATE doesn't have such problem, only Cinnamon.
Workaround proposed here doesn't work reliable - there are just rare cases where it works (need to open any window in Mint, click it to get focus, then hover on taskbar to show, otherwise it's not showing).
Even in such cases there only 30-50% chance to get panel to show.

Lack of support here since two years as I see forced me to switch back to MATE (even that I like much more design of Cinnamon).

**Comment by jonespm** [comment]
Just as an update, I also tried out Linux Mint but the lack of support for this made it unusable for me since I rely so much on Seamless mode. The space where the menu should be just is just empty and you see right through to the host background. No options in the panel menu (which are a little different than 2013) make a difference for me.

Linux Mint 17.3 on Virtualbox 5.0.10

It works fine with MATE and Xfce, but those aren't as nice as Cinnamon.

**Comment by danielbair** [comment]
Also a problem on Wasta Linux 16.04 and the above proposed enabling of "Auto Hide" panel doesn't work anymore.

This problem shows up in both VirtualBox when the guest utils are installed, and also in Parallels when the parallels tools are installed. Disabling 3D Acceleration on the virtual box guest restores the panel, but there is a warning saying "cinnamon is currently running without video hardware acceleration" that keeps showing up with no way to disable.

**Comment by solarjoe** [comment]
I have a similar issue. 

Host: Windows 64-bit, Virtualbox 5.2.2 
Guest: Linux Mint 18.3 Sylvia 64-bit Cinnamon

When I enable 3d acceleration in Virtualbox (after installing the guest additions)
the task bar at the bottom as well as some of the windows decorations are missing.

![cinna](https://user-images.githubusercontent.com/10460113/34200398-40c13cea-e571-11e7-934f-150eab21e1b0.PNG)


The command `/usr/lib/nux/unity_support_test -p` used to check if 3d acceleration works shows
```
OpenGL Warning: vboxCall failed with VBox status code VERR_BUFFER_OVERFLOW
OpenGL Warning: SHCRGL_GUEST_FN_WRITE_READ (64) failed with ffffffd7 ffffffd7
OpenGL Warning: vboxCall failed with VBox status code VERR_BUFFER_OVERFLOW
OpenGL Warning: vboxCall failed with VBox status code VERR_BUFFER_OVERFLOW
```

It seems like it does not depend on if the guest additions are installed or not. Disabling 3D acceleration in the VM settings restores the panel and shows the message that software rendering is used.
The "auto hide" workaround does not seem to work anymore.

**Comment by Vahan86** [comment]
@hayounav, is this still an issue in Cinnamon 4.2?

**Comment by hayounav** [comment]
Unfortunately, I have no idea. I haven't used VirtualBox in years.

**Comment by Vahan86** [comment]
@hayounav, thank you for your reply.

@icarter09, can we close this issue?

**Comment by greyltc** [comment]
Yes. This is still an issue on Cinnamon 4.6.6

**Comment by glonguetaud** [comment]
Hi, 
This is still an issue in Cinnamon 4.8.6 on Linux Mint 20.1 / VirtualBox  6.1.22 Windows 10 host. 

Thanks !
