### ISSUE TITLE
Sound applet volume tooltip doesn't disappear after mouse pointer moves away (Video included)

### ISSUE THREAD

**Issue by Lodorand** [linuxmint/Cinnamon#1833]
Video: http://www.youtube.com/watch?v=6iTmtdTwkN4&hd=1

When you mouse over the sound applet a volume tooltip shows up. When the mouse moves away, the tooltip is supposed to disappear. Most of the time it works correctly, however there is one case when the tooltip fails to disappear after the mouse has moved away, and that's after using the scroll wheel over the applet to change the volume. Here's how to reproduce:

1. Place mouse pointer over the sound applet, do not click.
2. Scroll the pointer while it's above the applet to change the volume.
3. Quickly move the mouse pointer away, right after you're done scrolling.

Expected behaviour: The tooltip should disappear.
Actual behaviour: The tooltip remains until the mouse is hovered over the applet again.

This bug has been in Cinnamon ever since I started using it a year ago. And since this is by far the most used and convenient way for me to change the volume, I find myself facing it on a daily basis. Would be great if devs can find time to fix it. Thanks!

**Comment by jomo** [comment]
This issue is almost 2 years old and I'm still having it.

To clarify my comment from last year:
I think that there is a `mouse-out` event on the button and/or tooltip that fades out the tooltip. But the tooltip fades in a little delayed, so it actually shows up (think: binds the event) when the mouse has *already* moved out so the event does never trigger.

At least that what's I remember from last when I searched the code back then.

**Comment by pixunil** [comment]
As #4808 got merged, and I don't experienced this since a while, I think this is solved.
