### ISSUE TITLE
Nothing is clickable in the panel on startup

### ISSUE THREAD

**Issue by dtrunk90** [linuxmint/Cinnamon#1843]
It's due to the notification bubble (I guess it's coming from Jupiter):
![Bildschirmfoto vom 2013-04-04 21:21:51](https://f.cloud.github.com/assets/636557/340836/664693ea-9d5d-11e2-8191-5ea7f82bbaa9.png)

As long as this bubble is visible I can't click anything on the panel.
It doesn't affect the desktop. This issue only affects the panel!

**Comment by ZamanOof** [comment]
I have the same problem plus the applets and notification when start Cinnamon show this message
![selection_091](https://cloud.githubusercontent.com/assets/9051946/15455984/b55eeca4-206b-11e6-9c85-bb38736ecd68.png)
regards

**Comment by JosephMcc** [comment]
@ZamanOof your issue is different. Open Cinnamon Settings and check your installed applets, desklets and extensions. Whichever one is causing the issue should show with a red dot next to it. Disable it and the restart Cinnamon or log out and back in. Make sure you report the issue to the xlet developer.
