### ISSUE TITLE
extra pixel/dot at my screen also in menu items

### ISSUE THREAD

**Issue by BullShark** [linuxmint/Cinnamon#1896]
i have installed mint cinnamon at my Toshiba Satellite® L650 Laptop
i have problem with my GUI
pixel/dot at my screen also in menu items.
my System work good with windows 7.

you can see screenshot
https://imageshack.us/a/img132/8244/workspaces013.png
https://imageshack.us/a/img716/668/workspaces007.png

some other information maybe you want to see
http://vpaste.net/4or0e

i have installed fglrx according to this post
http://askubuntu.com/questions/124292/what-is-the-correct-way-to-install-ati-catalyst-video-drivers-fglrx/129200#129200

but my system was unstable and crashing again again yesterday i have removed fglrx.

**Comment by pierreduchemin** [comment]
@anandrkris  Yes, I am still experiencing this issue with 2.8.8 on Linux Mint 17.3 with 
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Turks PRO [Radeon HD 7570].
My current driver is xserver-xorg-video-ati Version 1:7.3.0-1ubuntu3.1 (recommanded Linux Mint driver, flgrx does not work).

Here are the inxi -Gx results:
Graphics:  Card-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller
           bus-ID: 00:02.0
           Card-2: Advanced Micro Devices [AMD/ATI] Turks PRO [Radeon HD 7570]
           bus-ID: 01:00.0
           Display Server: X.Org 1.17.1 drivers: ati,radeon,intel (unloaded: fbdev,vesa)
           Resolution: 1366x768@59.8hz, 1920x1080@60.0hz
           GLX Renderer: Mesa DRI Intel Ivybridge Desktop
           GLX Version: 3.0 Mesa 10.5.9 Direct Rendering: Yes

Thank for your help

**Comment by JosephMcc** [comment]
Could you post a screenshot please? The original ones are dead links.

**Comment by pierreduchemin** [comment]
Here it is. Sorry for awful quality, I had use a smartphone to take these pictures since screenshots where not showing anything wrong.
![img_20160523_134649_269](https://cloud.githubusercontent.com/assets/7585909/15469838/1bc00862-20ed-11e6-9a3c-cdb9028ffa09.jpg)
![img_20160523_134634_255](https://cloud.githubusercontent.com/assets/7585909/15469837/1bb26914-20ed-11e6-90c3-17c3166d9c82.jpg)

Additional info : 
- the cursor seem to refresh displayed screen as shown on first picture (I was switching tabs).
- I am using 2 monitors and the problem only appear on the bigger one.
![capture du 2016-05-23 13 53 27](https://cloud.githubusercontent.com/assets/7585909/15469975/d8eac260-20ed-11e6-894c-c073d0988a1e.png)

**Comment by f2404** [comment]
A silly guess - is the DVI cable plugged in and fixed properly? Can you try another cable?

**Comment by pierreduchemin** [comment]
@f2404 just checked the cable, I don't have any other, sorry.
This computer was under win7 and everything was fine.

**Comment by Vahan86** [comment]
@BullShark, is this still an issue for you in Cinnamon 3.4?

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue since there is no response from OP for 3 months?
