### ISSUE TITLE
Add new hot-corner options

### ISSUE THREAD

**Issue by mdchaves** [linuxmint/Cinnamon#2117]
Now that Cinnamon has enhanced its hot corner functionality, why not expand it in order to take better advantage of this amazing feature? So I suggest to include some more hot corner options, such as:

Show Desktop
Minimize current window
Maximize current window
Show all the windows - current application
Show all the windows - windows from all desktops on a single desktop view (different from expo)
Open Main Menu
Lock Screen
Edge Flip
and so on...

**Comment by gordon-morehouse** [comment]
I'd personally love to see #1050 implemented before further bindings are considered. Just my 2¢, but for me, this would be nice but #1050 is a far bigger pain point.

**Comment by theoar** [comment]
@gordon-morehouse
bump

**Comment by nyeates** [comment]
Lock Screen can be implemented with command 
`cinnamon-screensaver-command --lock`

**Comment by nyeates** [comment]
I've looked into how we could add a "Lock Screen" dropdown option, or any other additional hardcoded options for that matter, instead of typing in the above command. 

**Why?**
I think that the Lock Screen option is needed in the UI, because Mac's have this setting and many people use it to lock their computers before they leave it behind on a desk. A friend asks you to lunch and you start to get up, and you can simply swipe to the lower left to quick lock it up. Also, ive read win8 users do this too now. Cinnamon users shouldn't have to hunt and peck around for a command to run it manually. Only super-power users will seek this out, and it should be available to everyday GUI-based power users :-)

**Hints I found for implementing this:**
Note: these are notes to my future self or any other adventurous unfamiliar soul who might be wishing to attempt implementing this.

I believe you would be editing the 

- `    runAction: function(){`  
- inside the https://github.com/linuxmint/Cinnamon/blob/master/js/ui/hotCorner.js file

in addition to adding an entry to the drop down in
- https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_hotcorner.py

**Other possible files needing editing could be seen here:**
- https://github.com/linuxmint/Cinnamon/pull/1175/files
- Though, note that the above is a old pull and some of the file locations and names may have changed.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
