### ISSUE TITLE
Remove window shadows

### ISSUE THREAD

**Issue by arfett** [linuxmint/Cinnamon#2285]
I think cinnamon should allow users to remove the shadows that surround windows. To me it is an annoyance and I can turn it off in Windows. It is just more wasted screen real estate that actually gets in my way from time to time.

**Comment by likevinyl** [comment]
:+1:

**Comment by Zer0t3ch** [comment]
Has this still not been implemented?

**Comment by crydalch** [comment]
For anyone who, like me, found this issue long before finding a solution, here is one that worked on my system: as root, edit */etc/environment* and add **MUFFIN_NO_SHADOWS=1**  and save. Then log out, and log back in. Tada!

Here is a screenshot of a window and menu w/out shadows, along with my system for reference:

![screenshot-area-2015-11-25-210605](https://cloud.githubusercontent.com/assets/458856/11413576/6a0a6d5e-93b8-11e5-88c3-57694c44f5d6.png)

I agree, it'd be nice if this were a preference exposed in the settings, but here's a work-around for now!

**Comment by dmitry** [comment]
Seems logical to add it to the `Appearance preferences` in `Interface`.

**Comment by aesedepece** [comment]
:+1:

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by kokbira** [comment]
I have Cinnamon on Fedora29. There is no /etc/environment :(

**Comment by smurphos** [comment]
Do you have ~/.profile (in your user's home)?

You should be able to add the environment variable there in this format.

`export MUFFIN_NO_SHADOWS=1`

**Comment by leigh123linux** [comment]
@kokbira Did you even look properly?

```
$ rpm -qf '/etc/environment' 
setup-2.12.1-1.fc29.noarch
```

**Comment by kokbira** [comment]
Short answer:

Sorry every one!

When I installed Cinnamon on Fedora 29, did not change Display Manager, that was Gdm3.

I have heard that Cinnamon appears to do not work well with other Display Manager than Lightdm.

So I changed it to Lighdm on Monday and ♪♫♬everything is going alright, don't worry about a thing ♪♫♬ ;)

Detailed answer:

I was confused with the issue, because when I used Linux Mint 19 Cinnamon that shadow issue happened and without knowing solution I survived with it.

But some other system crashes let me to use Fedora 29. And other system crashes later, I decided to change Gnome to Cinnamon on Fedora, and so I become a happier officer except for the display issues.

That display issues were forcing me to login system with only VGA display turned on and only after that I would turn on the DisplayPort display, elsewhere I cannot see menus, toolbars etc. of desktop or windows. Also, after the logon on that way, the wallpaper of VGA display became blinking and also that shadow issues happened together. So I thought the root cause was the same of that shadow issue.

After I fixed my issues using Lightdm substitution, I saw that MUFFIN_NO_SHADOWS=1 on a created /etc/environment only with that clause worked, but removing limits from a window to other ones. So I do MUFFIN_NO_SHADOWS=0 and the same happened. So I remove that clause and all is ok. Thanks!

**Comment by teddytwist** [comment]
Hi All, is there an easy-ish fix for this? I'm new to linux and have managed some simple terminal commands, and have my windows looking and behaving as I want, with the exception of the removal of the shade. Same as the OP - I prefer the real estate on my small screen rather than a band telling me the title of the webpage i am on. Any easy way to get rid of it? I saw the comment above which mentions "root" in the command... not sure if i should be messing with those settings as a newbie.

**Comment by HolyPolyRoly** [comment]
> For anyone who, like me, found this issue long before finding a solution, here is one that worked on my system: as root, edit _/etc/environment_ and add **MUFFIN_NO_SHADOWS=1** and save. Then log out, and log back in. Tada!
> 
> Here is a screenshot of a window and menu w/out shadows, along with my system for reference:
> 
> ![screenshot-area-2015-11-25-210605](https://cloud.githubusercontent.com/assets/458856/11413576/6a0a6d5e-93b8-11e5-88c3-57694c44f5d6.png)
> 
> I agree, it'd be nice if this were a preference exposed in the settings, but here's a work-around for now!

What theme is that, crydalch?
