### ISSUE TITLE
New windows are opened do not appear.

### ISSUE THREAD

**Issue by Charles-Mejia-Cruz** [linuxmint/Cinnamon#2304]
Using the latest nightly in the Cinnamon Ubuntu PPA. For some reason, newly opened do not show up at all unless I restart Cinnamon. However, it seems that the UI elements are still as things in the newly opened window seem to change when I view it in Alt+tab in Coverflow. But the actual window doesn't appear at all. Doing Alt+tab shows the window briefly before showing the latest window that can show properly or the desktop.

**Comment by gaborlaszlo** [comment]
That sounds just like what I'm seeing in Cinnamon 2.8.4+betsy on LMDE in a VirtualBox, with all effects disabled.
Easiest way to trigger this for me is to delete a file with Shift+Del. The Nemo window will become transparent/invisible, but still completely functional otherwise (it can happen to any other program, trigger seems to be a dialog popping up and disappearing too fast). 
Alt-Tab and panel preview will show the phantom window normally, mouse and keyboard input are honored when it is focused, but it does not get drawn. 
Restarting Cinnamon with Ctrl-Alt-Esc restores the window to normal.

**Comment by gaborlaszlo** [comment]
That sounds just like what I'm seeing in Cinnamon 2.8.4+betsy on LMDE in a VirtualBox, with all effects disabled.
Easiest way to trigger this for me is to delete a file with Shift+Del. The Nemo window will become transparent/invisible, but still completely functional otherwise (it can happen to any other program, trigger seems to be a dialog popping up and disappearing too fast). 
Alt-Tab and panel preview will show the phantom window normally, mouse and keyboard input are honored when it is focused, but it does not get drawn. 
Restarting Cinnamon with Ctrl-Alt-Esc restores the window to normal.

Update: turning off 'Attach dialog windows to the parent window' in SystemSettings -> Window -> Behavior avoids this failure mode.

**Comment by GreenBeard** [comment]
I can confirm having this issue. It only happens when a program opens the window. (If I as a user open the window it shows). If I reload cinnamon with Troubleshoot->Restart Cinnamon, the windows will appear.

**Comment by Vahan86** [comment]
@JosepMcc, can we mark this issue as a bug?

**Comment by JosephMcc** [comment]
There isn't enough relevant info here to troubleshoot this.
