### ISSUE TITLE
Is OpenCV an unnecessary dependency?

### ISSUE THREAD

**Issue by krasnoglaz** [linuxmint/Cinnamon#2453]
I can't imagine why a desktop environment needs a computer vision library.

**Comment by show0k** [comment]
Nice, and if I want to use opencv3 ?

**Comment by tgarc** [comment]
@show0k Don't know what distribution/package manger you're using but in debian/ubuntu `apt` will install packages in `/usr/`. You can install opencv3 (or any other package for that matter) alongside the apt installation without conflict by specifying `/usr/local` as the install prefix. For opencv use the cmake_install_prefix when doing your build e.g., `cmake -D CMAKE_INSTALL_PREFIX=/usr/local`). Python will automatically try to load from `/usr/local` first so as far as I can tell the `/usr/ ` install of opencv should not cause any issues with your local install.

**Comment by show0k** [comment]
The auto-generated CMakeCache.txt is good, the prefix is already set to /usr/local. There is no conflicts, but the '/usr/lib/python2.7/dist-packages/cv2.so' is loaded instead of '/usr/local/lib/python2.7/dist-packages/cv2.so' when I import cv2, because **it's after in the sys.path list**.
The only solution I found, is to **add**  'usr/local/lib/python2.7/dist-packages' **at the beginning** of sys.path 
``` python
import sys
sys.path.insert(1,'/usr/local/lib/python2.7/dist-packages')
```

Btw, I'm running on Linux Mint 17.

**Comment by dralley** [comment]
Considering the code under question uses the OpenCV 1.x API which [is deprecated](http://answers.opencv.org/question/17546/opencv-will-drop-c-api-support-soon/) and has been removed in OpenCV 3.x entirely, would a Pull Request to use the new API be desirable?

It is not likely that the ```python-opencv``` package will switch to OpenCV 3.x soon, however if and when it does happen this code will need to be changed, and I wouldn't mind doing so preemptively.

**Comment by clefebvre** [comment]
Yes, it would be considered for cinnamon 3.0.

PS: In the absence of bindings we can also use gi if available.

**Comment by dralley** [comment]
@clefebvre Fantastic, I'm testing the patch as we speak.

I noticed a potential logic mistake inside the for-loop on [line 127](https://github.com/linuxmint/Cinnamon/blob/9ec0aaade7358e79636285d8cde177288999745f/files/usr/share/cinnamon/cinnamon-settings/modules/cs_user.py#L127) however.  I assume the intention is to check 10 times for camera availability and take a picture once the camera becomes available, however it's actually taking and saving 10 pictures because the loop doesn't terminate once it succeeds the first time.

This can be fixed with a ```break``` inside the if-statement, which I can include in my PR if it was a legitimate oversight.

**Comment by clefebvre** [comment]
I can't remember why we do it 10 times... I should have commented it.. there was a reason though...

Maybe it's because the first pictures although successful don't look good or something.. or maybe it's there to give the user some kind of a delay between the moment the webcam light goes on (for the first picture) and the moment the actual picture of himself (the 10th one) is taken and shown to him.

I can't remember to be honest. Maybe we can get rid of it... only way is to test it with a webcam.

**Comment by clefebvre** [comment]
Oh.. I almost forgot. check that as well: 

https://github.com/linuxmint/live-installer/pull/57

An alternative to openCV.

**Comment by dralley** [comment]
In that case, the delay does makes sense.  I'll leave it be.

The code in the PR you linked has an unlisted dependency on ```imagemagick``` that the author forgot about, but once I figured that out and installed it, it worked fine on my machine.  I'll leave it up to you to decide which would be the better path forward.  ```imagemagick``` and ```streamer``` would still be much lighter dependencies than ```python-opencv``` which weighs in at 3.7 megabytes.

**Comment by clefebvre** [comment]
I've no preference. I didn't get a chance to test streamer yet.

What I don't really like with openCV is that we've no way of detecting the presence of webcam other by actually taking pictures. That results in the little witness light going on by itself in the installer and in the account settings before the user actually takes a picture (cause we take a picture on his/her behalf beforehand.. even though it's not stored permanently... just to know that there's a working webcam here and that we can show the relevant menu items).

If streamer allowed us to detect the fact that there's a working webcam without actually shooting pictures, that would be a plus.

**Comment by dralley** [comment]
So far as I know, there's no option in ```streamer``` to do that.  But according to the [http://linux.die.net/man/1/streamer](manpage) it just reads from ```/dev/video0```, so perhaps it could just check if a video device shows up there?

**Comment by dralley** [comment]
@krasnoglaz @show0k Next release will no longer have ```python-opencv``` as a dependency
