### ISSUE TITLE
Alt+Tab not working during drag-n-drop

### ISSUE THREAD

**Issue by leesei** [linuxmint/Cinnamon#2493]
A scenario for me is dragging a file or url link to Nemo which is on the back of the current window.

**Comment by tp0** [comment]
I can not believe how is this not supported. It's not even something inherited from Gnome, since it does work in Gnome and also works in Unity.

Must popular use case for me would be to drag files between two or more Nemo windows or between Nemo and a browser window.

**Comment by tp0** [comment]
Just noticed that minimize window shortcut key works when dragging. So, this helps a bit to get the active window out of the way of the destination/dropping.

**Comment by tp0** [comment]
Is this on any roadmap or even being looked at all?

**Comment by clefebvre** [comment]
This is being looked at.

Non-constructive comments were removed.

**Comment by nextgensparx** [comment]
@mtwebster This appears to have resurfaced.

With the following specs:

 * **Cinnamon version**: 3.8.8
 * **Distribution**: Linux Mint 19
 * **Graphics**: Intel HD Graphics 4400 (Intel Corporation Haswell-ULT Integrated Graphics Controller)
 * **Architecture**: 64 bit

I get the exact same behaviour as was described here.

Could this issue be re-opened?

**Comment by JosephMcc** [comment]
I was going to reopen this but can't reproduce the issue. It seems to working fine. Which Alt+Tab switcher are you using? Any other info you can add to help reproduce?

**Comment by nextgensparx** [comment]
@JosephMcc I'm such an idiot. 

I forgot that I installed the "Win7 Alt-Tab" extension. When installing it, Mint explicitly told me that it "is not compatible with current version of cinnamon" and that using it "may break your system." 

Sorry for wasting your time.

Side note: The only reason I installed Win7 Alt-Tab was because none of the built in Alt-Tab switcher styles support showing a thumbnail, icon and title. The "Icons and thumbnails" style is pretty close but only shows thumbnails on hover and has huge icons.

**Comment by JosephMcc** [comment]
No problem. That's why I asked :)

**Comment by Meru** [comment]
Somewhat related to this issue.
Open this link in maximised firefox: https://www.linuxmint.com/pictures/screenshots/tessa/cinnamon.png
the goal is to drag-n-drop it to desktop
start drag-n-dropping it
how to proceed after that? In windows you can drag onto "peek" button, which would show the desktop or you can alr-tab during the process.
