### ISSUE TITLE
Removable devices open nautilus window instead of nemo

### ISSUE THREAD

**Issue by grrrrr** [linuxmint/Cinnamon#2532]
Following an upgrade to `cinnamon 2.0.3` any time a removable device (USB Stick, phone) is attached and mounted it opens up a `nautilus` window.

What should happen
  * Connect the removable device
  * either
    * Prompt for action
    * open in `nemo`  

Prior to upgrading to cinnamon 2.0.3 this was working as what was expected above.

update:   Running Ubuntu 12.04.3

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 12.04.3 LTS
    Release:	12.04
    Codename:	precise

**Comment by RalfJung** [comment]
On my system, quite amusingly, Cinnamon is opening Dolphin (the KDE file manager) from that "Removable Devices" menu. Dolphin itself lets me configure the file type associations for all kinds of files, even for folders, so I was able to fix the bug by telling Dolphin to no longer use Dolphin for folders....
Nemo and Nautilus, on the other hand, deliberately do *not* show the "Open With" configuration for folders (I assume there was some reason for this, though I can't see it). If they would have that same UI, the bug could easily be fixed by users from within Cinnamon.

**Comment by Vahan86** [comment]
@JosephMcc, Issue https://github.com/linuxmint/Cinnamon/issues/1274

**Comment by Vahan86** [comment]
@JosephMcc, Issue #1274 .

**Comment by JosephMcc** [comment]
@grrrrr others report this issue being fixed. Does it work for you in Cinnamon 3.0?
