### ISSUE TITLE
remove Cinnamon onscreen keyboard! It is for touchscreen and replace it with onboard

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#2721]
Please remove that Cinnamon onscreen keyboard and replace it with onboard! It is useless and made for touchscreens!

**Comment by Vahan86** [comment]
@JosephMcc, I think this issue is not related to Cinnamon. Can we close it?

**Comment by hoshi411** [comment]
Please get rid of the cinnamon keyboard trash and replace it with onboard. It is not functional for touch devices and tablets. We need onboard because it is the most developed with the most features. Even onboard is barely useable but the cinnamon keyboard is getting in the way. Please Onboard please!!!!

**Comment by freemangilgamesh** [comment]
closed!!!!!but why!!

**Comment by to-ba** [comment]
@hoshi411 you can install Onboard from mintinstall or with »sudo apt-get install onboard«
