### ISSUE TITLE
Touching Hot Corner (Expo) while dragging causes cinnamon to stucks in Expo Mode

### ISSUE THREAD

**Issue by Stichoza** [linuxmint/Cinnamon#2806]
If I'm dragging something (For example desktop icon) and accidentally touch the Hot Corner, I'm unable to leave Expo Mode.

Workspace switching shortcuts works. <kbd>ALT</kbd>+<kbd>Tab</kbd> also works and activates window without leaving Expo.

The only way to exit Expo, is restarting cinnamon by pressing <kbd>ALT</kbd>+<kbd>F2</kbd> and typing 'r' (restart)

**Comment by BonnWarapol** [comment]
Mint 22.3

 I'm not sure I should comment here or making a new issue.

The desktop behaved as if I was permanently stuck on workspace 4 while also appearing visually trapped in Expo/Overview mode.

Symptoms included:

- panel became invisible
- keyboard input stopped working in GUI applications
- mouse still partially worked
- clicking where the panel/menu normally was could still open the application menu
- application search still worked
- newly opened windows appeared on workspace 4
- Cinnamon itself did not appear fully crashed

Because of this behavior, it strongly looked like:

- Expo mode became stuck
- workspace state corruption occurred
- Cinnamon focus handling broke
- or an applet/compositor crash happened

What made this especially confusing

The issue persisted even after:

- switching workspaces
- opening applications
- partially restoring Cinnamon

At one point, applications could launch normally again, but Chrome still refused keyboard input, making it appear that the system was still broken.

This made diagnosis very misleading because the symptoms looked system-wide rather than application-specific.

Recovery attempts

Some things that may help recover without rebooting:

Switch to TTY:

Ctrl + Alt + F1

Then:

DISPLAY=:0 cinnamon --replace &

Possible additional recovery commands:

DISPLAY=:0 XAUTHORITY=/home/$USER/.Xauthority \
gdbus call --session \
--dest org.Cinnamon \
--object-path /org/Cinnamon \
--method org.Cinnamon.Eval \
"Main.expo.hide(); Main.overview.hide();"

If nothing works, the final option is logging out or restarting the display manager, although this will close all applications and potentially lose unsaved work.

Actual cause (possibly)

Later I discovered Chrome had a hidden/stuck modal confirmation dialog open from the previous night.

Something similar to:

- "Are you sure you want to close this window?"
- or another confirmation popup

After dismissing that dialog, everything immediately returned to normal.

Possible explanation

My suspicion is:

- Chrome modal dialog grabbed keyboard focus
- workspace switching or Expo mode occurred during this state
- Cinnamon focus/workspace state became inconsistent
- GUI remained semi-functional but focus never properly recovered

This may be related to existing Cinnamon issues involving:

- modal dialogs
- focus grabs
- Expo stuck states
- workspace focus inconsistencies

Possibly related:

- https://github.com/linuxmint/cinnamon/issues/2806
- https://github.com/linuxmint/cinnamon/issues/3422
- https://github.com/linuxmint/cinnamon/issues/12580

Environment

- Linux Mint Cinnamon
- X11
- Google Chrome
