### ISSUE TITLE
Alt-Tab is window-centric

### ISSUE THREAD

**Issue by alexs77** [linuxmint/Cinnamon#2883]
The Alt-Tab switcher is window-centric. It should be app-centric. 
For cycling between windows of an app, one can also use Alt+^ (key to the left of 1, or above tab). This works in Cinnamon and in Gnome and in Unity.
In Cinnamon, one also sees the full window list of all applications, when pressing Alt+Tab. That's cumbersome, if one has many windows (eg. terminals) open of one application.

**Comment by jeffwildcoast** [comment]
Is there still no fix for this?

I come from a MacOS environment for about the past sixteen years or so. But since they became so extremely fragile and irreparable (not to mention butterfly keyboard design flaws) I've gone back to Linux (Ubuntu 22.04 + Cinnamon DE) on a Dell Precision which feels much like what a MacBook Pro used to. But with replaceable components!

I really miss MacOS. And they had UX nailed with grouped application windows with Alt-Tab. And Alt-Tilda to move between individual application windows.

Cannot understand how anyone would think it could ever be considered to be proper behaviour to cycle through all open windows with Alt-Tab.

![image](https://user-images.githubusercontent.com/105626702/223754622-76e0a2ae-6384-4f52-b406-4f504b4ded78.png)

**Comment by egoarka** [comment]
@jeffwildcoast check this, https://github.com/linuxmint/cinnamon-spices-extensions/issues/462#issuecomment-1869130197

**Comment by tjohnman** [comment]
I too come mainly from macOS (but also from KDE), and I find this behavior very jarring. After a morning coding, I end up with way too many icons to go through when alt-tabbing. It's simply unusable for me. Jeff's screenshot is exactly how my workspace ends up looking on Cinnamon every day.

I'm probably using Cinnamon wrong, because I don't understand how anyone could work like this.

If I had the time right now, I would try learning how to, and developing an applet, but as things are right now, I rather take the other workaround suggested here (ditching Cinnamon).

**Comment by b3rs3rk1ng** [comment]
I've implemented a solution for this in PR #13498.

The PR adds a configurable setting `alttab-switcher-group-by-app` that allows users to choose between window-centric (current behavior) and application-centric (requested behavior).

When enabled:
- Alt+Tab groups windows by application
- Alt+` cycles directly between windows of the same app
- Shows application names instead of window titles

When disabled, Cinnamon behaves exactly as before.

The setting appears in System Settings → Windows → Alt-Tab.

For those who want to try it before the PR is reviewed, the standalone implementation is available at: https://github.com/b3rs3rk1ng/cinnamon-group-windows-by-app

**Comment by oyd11** [comment]
Just do it as "super-tab", I think that's the current gnome configuration, then, users (like me) that hate the 'alt-tab' - can just un(or-re)-assign it
