### ISSUE TITLE
[Cosmetic] Mouse Settings - Cinnamon and GTK Drag Threshold - Friendly Names

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#2937]
![screenshot from 2014-03-14 19 36 20](https://f.cloud.github.com/assets/4663298/2421457/f6d5cc9a-ab81-11e3-90bc-f5b06de845a7.png)
Being a pure desktop user, can not make much sense of options "Cinnamon Drag Threshold" and "GTK Drag Threshold". Appreciate that it is shown only in advanced mode, still user-friendly name could be helpful. Also curious to know what these two options are / their differences. Thanks for your patience.
Also, when mouse settings is started, scrollbar appears, need to resize to view these options.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html

**Comment by d-packs** [comment]
This bug is 7 years old and has been inherited from gnome. The good guys over at gnome-control-center waited until the bug was no longer relevant as they dispensed with that option altogether. 

https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/643825

Here's a good explanation for the feature, in case you need inspiration: 
https://people.gnome.org/~shaunm/mobile-mallard/gnome-help/mouse-drag-threshold.html
