### ISSUE TITLE
Make Alt + F2 accept shell aliases.

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#3130]
Title says it all. Aliases set in `~/.bashrc` are ignored in the alt+f2 dialog.

**Comment by dalcde** [comment]
You can currenlty define user aliases for Alt-F2. These have to be defined explicitly for Alt-F2 instead of using shell aliases because
 - Alt-F2 is not a shell (and definitely not the shell you are using), so it is logically incorrect to use shell aliases
 - You can have many shells with different sets of aliases
 - The set of aliases you would want in your shell is likely to be different from what you want in Alt-F2, since shell aliases are usually for command line programs (eg. ls, grep, ssh), while Alt-F2 will correspond to desktop applications.

**Comment by gauravjuvekar** [comment]
@dalcde 
> You can currenlty define user aliases for Alt-F2. These have to be defined explicitly for Alt-F2 instead of using shell aliases because

How?

**Comment by JosephMcc** [comment]
@gauravjuvekar It's available in git master and you can do it by setting the aliases in the org.cinnamon.run-dialog-aliases gsettings key. Still need to add a way to do this in the cinnamon settings ui.
