### ISSUE TITLE
Better documentation of the Cinnamon API

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/Cinnamon#3186]
A thing I hate about Cinnamon (as a fairly unexerienced developer in this area) is the lack of an API documentation.

Even the most simple applet becomes hard to create - The only thing I could find was the Force Quit/xkill applet tutorial.

I think this is quite a sad fact, because Cinnamon is continuosly gaining popularity. With such a growing community comes a greater amount of developers.

JavaScript itself is easy to learn, but where am I supposed to learn the Cinnamon-specific stuff? Of course I can try to understand the commands and classes from the given applets, but so I will never learn what every specific command exactly does and I will certainly never know what commands exist.

So I think a complete API documentation for Applets, Desklets and Extensions is crucial for Cinnamon.

***
I already filed this at community.linuxmint.com, and they asked me to write this here

**Comment by dalcde** [comment]
This is an experimental attempt at code documentation: http://dec41.user.srcf.net/cinnadoc/

**Comment by dalcde** [comment]
For those interested in contributing to documentation and tutorials, here are the guidelines regarding how to document code and write tutorials under the current system:

http://dec41.user.srcf.net/cinnadoc/cinnamon-js/documenting-source.html
http://dec41.user.srcf.net/cinnadoc/cinnamon-js/documenting-tutorial.html

Code documentation is written inside the code itself with comment blocks, while tutorials are separate .xml files. Currently, all tutorials have to be written in docbook format, which is a bit like html but the tag names are longer.

*NOTE to self: write a docbook crash-course tutorial*

If you don't wish to learn the devious docbook format, there are certain online converters from other languages to docbook, eg. https://foliovision.com/seo-tools/pandoc-online. However, conversion from Markdown is usually not very successful. I suppose more structured formats such as LaTeX will produce better output, but I haven't tried. Regardless, there will always be some need of fine-tuning the sectioning and layering to fit into the general structure.

If anyone writes some tutorial in non-docbook format, I wouldn't mind help converting them to docbook afterwards. After all, it is easier to do the conversion than write one myself :) However, if you plan to write a non-trivial amount of tutorials, it would be a good idea to learn the docbook format.

**Comment by plainas** [comment]
I am sorry I am commenting on this old issue. But I though I would share what I experienced when I tried to develop an extension for cinnamon.

Desktop management APIs have historically been poorly documented. I don't know if it is a tradition, but this can even be observed in projects like Xlib or ncurses. Sadly cinnamon suffers from that condition too.

I wanted to do simple things: grab a list of windows, fire up a notification or a popup from the tray, resize a window... the APIs to do this should be documeted and easily navigable and searchable.
Why don't we have a list of method signatures for things like this?

At my first try, I gave up because there was no documentation and no mailing list nor any forum where I could ask simple things. When I tried again, I was a little bit more determined and eventually got quite a bit of stuff to work by looking at the source code of other extensions and learning from it. But that doesn't work all the time and it was too time consuming.I eventually got bored.

I hate to sound so negative as I appreciate the work of the good people that put cinnamon together. But it is a fact that lack of more and more accessible documentation and a discussion platform is resulting on cinnamon missing out on many potentially interesting contributions.

**Comment by mtwebster** [comment]
http://developer.linuxmint.com/index.html

Not sure how visible that link is publicly - but that's most of *our* API as well as a lot of tutorial info.  It's not everything, however - you'll still want to look at other peoples' work for what's really possible, and libraries we don't control, but utilize (clutter, gio, glib, etc..) aren't included there.

There's no mailing list - your best bet is irc - see the *Contributing* page at that site.

**Comment by lestcape** [comment]
@mtwebster Maybe a link to the documentation inside the cinnamon readme and also inside spices, will be helpful to find easy the documentation. Also a thread in segmentfault to speak about this and a permanent post in mint forums? Is a big work in my opinion and i think also user will want to know that cinnamon devs also provide help to others.

**Comment by JosephMcc** [comment]
As mtwebster pointed out there is now a website that is home to the cinnamon documentation. If you have `cinnamon-doc` installed it will also show up in the devhelp application.

**Comment by IzzySoft** [comment]
@JosephMcc While that is technically true, it's currently rather a "skeleton". Beginners will have issues following the short API reference, and the few examples/tutorials don't go very far. True, it gets you started with a simple applet (like that XKill example). But if I want to implement something beyond that (e.g. show some simple graphs), I'm already lost. So it would be nice to have at least a little list with additional links, which could be wiki-style for folks to add to, and should be linked to from [the main reference](http://developer.linuxmint.com/index.html).

**Comment by attila123** [comment]
I am a total beginner here, just wanted to modify an applet and had trouble with it. First of all, I needed to restart Cinnamon, otherwise the applet did not update even if I removed, added it. I found a "Restart Cinnamon" applet for that (can be downloaded e.g. in the Applets -> Download tab).
What I found useful: the imports.ui. stuff seems to be installed at /usr/share/cinnamon/js/ui
For e.g. 'imports.gi.St': global.log() may be your friend e.g.
const St = imports.gi.St;
global.log(St);
The logs can be followed in the lg (Melange application) (Alt + F2, then type: lg), at the 'Log' tab, or in ~/.cinnamon/glass.log.
Hope it helps someone...

**Comment by mscheper** [comment]
Five years have passed, this issue is closed, but I think it's still relevant. I've got a good 20 years of dev experience, including desktop apps and plenty of JavaScript/ECMAScript, but writing even a basic applet seems daunting and tedious to me at this stage.

From the comments above, it seems people have tried to solve this problem, but any effort has been scrubbed:

> How about here?: https://github.com/linuxmint/cinnamon-spices/wiki

404

> http://linuxmint.github.io/reference/

404

> https://github.com/linuxmint/Cinnamon/wiki/API-reference

Empty page.

> http://developer.linuxmint.com/index.html

Yeah, but there really isn't much there. Honestly, @JosephMcc , the only thing about applets there is the article about x-kill, which was mentioned in the OP. It's not useless, but I've had to do a lot of digging around StackOverflow and Google for what seems essential information, and I'm still feeling quite lost. That article seems to be written for novices, but I doubt any of them have lept into code up to their armpits.

> If you have `cinnamon-doc` installed it will also show up in the devhelp application

True, but the tutorials it has are, again, the same problematic ones mentioned in the OP, and they don't seem to be up-to-date. For example, there's no mention of the `PopupMenu.PopupSliderMenuItem` that I've seen in some applet code. Then again, since a Google search for that came up blank, I don't think there are docs for that anywhere! 😮

I feel bad for just whinging, but since I don't have many answers, I don't feel qualified to write any docs myself. But I'll summarise a few things I _have_ found, for anybody else who finds this page:

- `cinnamon-looking-glass` I a pretty essential debugging tool; just launch it from the command line. You can also log to it from your applets, like this: `global.log('some string', someObject);`—it works similarly to `console.log` in a browser
- To restart your applet, type `dbus-send --session --dest=org.Cinnamon.LookingGlass --type=method_call /org/Cinnamon/LookingGlass org.Cinnamon.LookingGlass.ReloadExtension string:'your-applet-UUID' string:'APPLET'`, where _your-applet-UUID_ is whatever you chose in your metadata.json file ← take note @attila123 
- I've found some rather minimalistic API docs at http://lira.epac.to:8080/doc/cinnamon/cinnamon-js/ but I think it's the same out-of-date stuff as in `devhelp`/`cinnamon-doc`. Also, the promise that 'The latest version of this documentation can be found online at http://developer.linuxmint.com/reference/git/cinnamon-js/' is a lie

Despite all this, enough applets exist to suggest there's a trove of docs _somewhere_… either that, or they're all written by experienced Cinnamon devs, or people a lot more patient than I. 😉 Can anybody point to such a trove? I do love Cinnamon, and would love to contribute to it.

**Comment by IzzySoft** [comment]
@mscheper thanks for summing it up! That reflects exactly my experience. As I got no answer (my post above is more than 2 years old) and neither could find help elsewhere, I meanwhile gave up. I simply lack the time to "play around" for days to find out how to get a simple "hello world" line printed (figuratively spoken). Seeing that, 2 years later, the situation has not changed is not exactly encouraging.

**Comment by jaszhix** [comment]
This is your answer:

> As mtwebster pointed out there is now a website that is home to the cinnamon documentation. If you have cinnamon-doc installed it will **also show up in the devhelp application**.

Install cinnamon-doc and devhelp packages. Run devhelp.

This is the same content that was on the previous developer website, but more complete. 

Despite the word "extension", you really need to be familiar with cinnamon's source to be effective with extending it - you are after all, modifying its running state. There's no sandboxing here, it's just a way to make parts of cinnamon portable. I suggest taking the time to learn how the part of cinnamon you're affecting works. It changes often, and I know we _do_ keep the jsdoc tags updated. The build system for the docs doesn't make them available online, though. Its trivial to get them in devhelp like mentioned above, and I think that is an adequate response.

I've tried to make the developer experience better, with a log function that behaves more like `console.log`, a commonjs-like module importer, for instance. I have definitely documented the latter. Efforts have been made, but they're incomplete, and it is now up to you to want to learn and experiment. To become a developer yourself and help complete the docs. Docs are only one part of a good developer experience, so I disagree with the general sentiment here - nobody is being ignored, and I personally care about cinnamon being easy to develop for. There's just few of us though. 

If you're able to write code, please write code and don't poke a stick at a two year old zombie issue.

**Comment by pdcurtis** [comment]
This is an old problem which keeps coming up in some form or other. The documentation is much much  better than it was and this issue was correctly closed a long while back. In addition there are a number of core team members who have given me considerable help when required, many have contributed to this thread.

The fact that people keep coming back however means that it may not be easy to find the documentation and I wonder if an obvious link is required in some of the git README.mds, in particular or the extensions

**Comment by mscheper** [comment]
> This is your answer:
> 
> > As mtwebster pointed out there is now a website that is home to the cinnamon documentation. If you have cinnamon-doc installed it will **also show up in the devhelp application**.

Thanks, @jaszhix, but did you read my post? I explained the problem I was having with that. I even quoted that exact paragraph.

**Comment by collinss** [comment]
@mscheper we (those of us on the Linux Mint/Cinnamon team) used to all hang out on irc where anyone could drop in and ask questions. I believe the channel is still there, but we switched to Slack a few years ago, so I don't think much happens there these days. Slack was a nice change for the team because it made it easier for us to communicate, but it also made it harder for anyone else to reach us. So more recently we created a second slack workspace so that people who were tangentially related to the project could still communicate (such as applet devs). It's a bit more quiet there than our main workspace, but most of the team is there (and several applet devs too), so if you ask a question, you'll usually get a response pretty quickly. If you want we can send you an invite. We'll just need an email address to get you on. If you don't want to post your email here (can't blame you for that), you can look up one of us and send it to our email.

**Comment by mscheper** [comment]
@collinss Thanks. I, too, eventually jumped on the Slack bandwagon, but it does create somewhat of a community barrier.

If you can create an account for me with the address _cinnamon `0x40` michaelscheper `0x2E` com_ then I'll receive the credentials, and it'll be easy to send email to `/dev/null` if it starts getting spammy. Thanks!

**Comment by collinss** [comment]
@mscheper Ok, invitation sent.

**Comment by ngaro** [comment]
2 more years have past, and it seems that this issue only contains dead links...
When will some API docs be available ?
If they are bad and incomplete, it would be a petty but i could survive.
Just make sure they exit...

Either put them in this repo or place the location in the README.md

**Comment by JosephMcc** [comment]
There are API docs and have been for a long time. You need to install the cinnamon-doc package and devhelp. Then the docs will be there.

**Comment by hydroperfox** [comment]
I have installed devhelp, but when I browse it there are missing APIs for CJS; for example, there is no `ui.popupMenu.PopupMenuManager` there, even though my Linux Mint version (Linux Mint 22 Cinnamon)'s `menu@cinnamon.org` applet uses it.

Also, there is no consistent documentation for St (GNOME Shell Tookit) API in CJS for example. There is `IconStyle` [here](https://gjs-docs.gnome.org/st15~15/), but not `IconType`, which the applet above uses.

**Comment by theMaskedMushroom** [comment]
Ya, same sentiment here. The best I have found so far is the Devhelp app. It is very raw and sometimes incomplete. Everything on the interwebs is very hard to find (time consuming), often very succinct and not all that helpful. It might be an actual useful entry barrier (limiting the influx of poorly written Spices onto the general population), but who knows?

I do think though that if Cinnamon Spice devs had a clear space defined to interact (a Matrix chat or dedicated Mint forum for instance), a place to meet, a lot of these issues would be mitigated with minimum effort. After all, we are willingly going through all this hardship and hair pulling on our own (practically on our own, with some help here and there). Put us all together in a room and man, I promise we'd get ahead a lot more easily!
