### ISSUE TITLE
Disabling hidpi isn't consistant

### ISSUE THREAD

**Issue by LiraNuna** [linuxmint/cinnamon#3194]
I wasn't pleased about the hidpi resolution my screen got detected as so I disabled it - this is the result.

![Bad scaling when disabling hidpi](http://i.imgur.com/QZm4clh.jpg)

**Comment by marcinsulikowski** [comment]
> This is not something we expect to be done repeatedly

@mtwebster Actually, I do this repeatedly... :disappointed: I'm using a laptop with HiDPI screen and often I attach an external non-HiDPI monitor to it. The monitor has the same screen resolution as my laptop, but it is 27" instead of 14". Every time I attach the monitor, I have to switch to Normal mode and when I detach it -- to HiDPI mode (which, by the way, looks great in Cinnamon! :+1:).

**Comment by mtwebster** [comment]
Actually I recently had issues with this myself testing our some multi-monitor stuff, since plugging/unplugging another monitor will change resolutions on our behalf to the new, existing configuration.  So I think that invalidated my original statement - I'm usually just on a laptop, so it wasn't something I ever had to consider.

**Comment by Vahan86** [comment]
@LiraNuna, is this still an issue for you with Cinnamon 3.0?

**Comment by LiraNuna** [comment]
It's much better with Cinnamon 3.0! The only issue that remains is that the tray applet icons are scaled incorrectly. I'm not sure if this is a Cinnamon issue or the applet's.

![screenshot from 2016-09-14 12-00-26](https://cloud.githubusercontent.com/assets/205628/18525795/d7114b7e-7a72-11e6-84e0-605781b4de44.png)

**Comment by lubo08** [comment]
Hi. I have same problem, after switch from laptop HiDPI to external non HiDPI inside session panel is broken and also window scale is wrong. Cinnamon version 3.2.8. When this will be fixed?

**Comment by Vahan86** [comment]
@LiraNuna, does this issue still relevant to Cinnamon 3.6?

**Comment by Vahan86** [comment]
@LiraNuna, @lubo08, is this still an issue for you with Cinmamon 4.2?

**Comment by lubo08** [comment]
@Vahan86 Its quite better than before. but still not OK. Tray icons are small, also Window icons for minimize, close are very small. Tested on cinnamon 4.2.4

**Comment by Vahan86** [comment]
@lubo08, thanks for the update.

**Comment by LiraNuna** [comment]
Closing as UI scale is pretty amazing now and there are no issues seen.
