### ISSUE TITLE
Window tiling shortcuts don't work across screens

### ISSUE THREAD

**Issue by DiThi** [linuxmint/Cinnamon#3245]
Just as the title says. I can't press win+right several times to move the window to the right screen. Windows 8.1 does, and IIRC when you make a window go to another screen, it's in the regular position instead of tiled (so you have to press one more time the arrow key to tile it).

**Comment by JosephMcc** [comment]
I think this is the same as https://github.com/linuxmint/Cinnamon/issues/4487
If I have a window on my right monitor and use <Super+right_arrow> it will tile to the right half of the screen. If I then press <Super+Shift+right_arrow> the window will move to the same tiled position on the screen to the right.

**Comment by stefan123t** [comment]
Both #4487 and this feature request ask for the Super + Cursor keys to be able to move windows to the next screen and not be constraint by the current screen. Indeed it is a good feature to move to the other screen with Super + Shift + Cursor keys. But to keep the window on the current screen using Super + Cursor is obviously non-intuitive for some users.

**Comment by DiThi** [comment]
I agree. Three reasons:

* More intuitive, discover-able.
* No need to remember 2 shortcuts.
* People coming from windows gets frustrated with the current behavior.

@JosephMcc Please, consider opening this issue or #4487

**Comment by ManIVIctorious** [comment]
I have to admit that this would be a nice feature

**Comment by JosephMcc** [comment]
Ok, I'll reopen this barring a discussion with how the other devs feel about this. There are a couple reasons I disagree. One being that we have other open issues where people complain that these sorts of actions aren't constrained to the current monitor. I personally want a consistent behaviour among these.

@DiThi I admit I don't really buy in on your "three reasons". The first 2 are pretty much the same. I think having the original keybinding constrain within monitor and adding the additional modifier to make it move between monitors makes perfect sense. These keybindings are hardly discoverable in any case. The only way you know about them is if you were somehow informed that they existed at some point or you went looking for them. As far as people coming from windows, I wish people would stop using that reasoning every time they want something. I came from windows and think it works just fine ;)

**Comment by DiThi** [comment]
@JosephMcc I'll phrase it in another way: people that (for any reason) has to use windows sometimes.

Why does it make sense to constrain within a monitor? If one moves the window to another monitor by mistake, it can be undone by pressing the opposite arrow.

Since a long time passed since I opened this, I don't quite remember how I discovered the feature (and why was I so annoyed that I opened an issue). I think it's related to the configuration menu.

**Comment by stefan123t** [comment]
I think the problem here is not that there is a shortcut for moving between screens (Super+Shift+Cursor) which could be reassigned to e.g. Super+Cursor (and vice-versa) by the way.

This Feature Request is only that the tiling (Super+Cursor) is constrained to one screen, when people expect the tiling operation to be able to tile across the complete screen real-estate, i.e. also across screens.

And yes there are probably more important things to fix / implement, but people seem to notice this constraint and obviously do find the Shift key added to the recipe as convenient as Ctrl-Alt-Delete to login *pun intended*.

Kind regards,
Stefan

**Comment by JosephMcc** [comment]
Ok, as an example case. Lets say I have 2 monitors side by side. 
I open a window on my left monitor. 
I use (Super+right_arrow) it will tile to the right half of that monitor. 
If I press it again, it should tile it to  the left half of the right monitor,
A third press would untile it on the right monitor.
A fourth would tile it on the right half of the right monitor.

This would be the behaviour you guys are looking for?

**Comment by stealthybox** [comment]
Bumping this!

I also feel that one shortcut that tiles across all of the screen real-estate would be much more intuitive.
I use 3 monitors as a big square (two on top of each other, and a portrait on the side).
Using a different shortcut when I need to cross monitor boundaries is difficult to think about when the output of the action on the screen (windows moving) is uniform.
This could be an option if we're worried about it being a breaking change?

The thing to be concerned about though is that tiling up twice is mixed with the maximize functionality.
I think this issue is only scoped around crossing monitors sideways.
I don't think there's currently an idea of directional relation or orientation between monitors in the current window moving implementation.

**Comment by DiThi** [comment]
@JosephMcc I missed that comment. Yes, that would work. Another option that may be easier is, when it changes to a different screen, put it in the original position/dimensions (but in the new screen), then having to press again in some direction to tile.

Currently I don't have several monitors so I'm not sure how other OSes and DEs do it.

**Comment by stealthybox** [comment]
@JosephMcc regarding your comment on behavior,

I think @DiThi's original request is to clone the windows functionality:
*(when windows switch to another monitor they are not tiled)*
 - **`tiled right (monitor 1)`
-> `untiled (monitor 2)`
-> `tiled right (monitor 2)`**

This is inconsistent with the current Cinnamon behavior, though:
*(when windows switch to another monitor they match their orientation from the previous monitor)*
 - **`tiled right (monitor 1)`
-> `tiled right (monitor 2)`
-> `tiled right (monitor 3)`**
 - **`untiled (monitor 1)`
-> `tiled right (monitor 1)`
-> `tiled right (monitor 2)`**

The behavior you describe is where the tiles propagate spatially:
 - **`tiled right (monitor 1)`
-> `tiled left (monitor 2)`
-> `untiled (monitor 2)`**
 - **`tiled Q1 (monitor 1)`
-> `tiled Q2 (monitor 2)`
-> `untiled (monitor 2)`**

I prefer the spatial behavior that you described.
Seems like @DiThi likes it too?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
