### ISSUE TITLE
native support for Win7-like windows list

### ISSUE THREAD

**Issue by lollox** [linuxmint/Cinnamon#3252]
Hi

I'd like to see in Cinnamon native support for a rock solid applet able to work as the Win7/8 superbar (icon only, group windows per app, pinned favorites, window preview, etc) 

I know there is yet an applet that try to emulate it, but it's quite bugged, abandoned by its developer, and works quite bad even in style (buttons too small or without the needed padding/margins)

Please consider this request for the next Cinnamon version (you could simply add the missing features to the current window list applet, and let us configure the preferred behavior in options)

thanks in advance

**Comment by jtflynnz** [comment]
I would just like to also request this as an option, understood that some of the devs have stated that it is a design decision and that there are applets that accomplish some of what's been requested, however it is very handy to have when one works with large numbers of windows, and is something that has precedence in the implementations of other desktop environments. 

Additionally, as has been mentioned, the issue with the applets are that, for whatever reason, there is some measure of instability and inconsistency in the occasional basic functions. And even if the individual applets may function wonderfully, there may be times where a feature available in one may be unavailable in another, or vice versa, while integration within the standard window list allows the possibility of mixing and matching said features. 

Believe me when I say that it is not my goal to rag on the work done for Cinnamon; I love Cinnamon, it is my favorite DE for Mint, and I also love that people have taken the initiative to add in some of these features, but on some of these ideas why stop there? When cinnamon is presented as the "Traditional layout [with] advanced features, easy to use [yet] powerful [and] flexible" desktop environment, doesn't it make sense to integrate features that are included in a low-resource DE like XFCE, at least as options? I guess it just rubs me the wrong way that a feature request like this has seemingly been dismissed as handled well enough by 3rd party applets or because it was a design decision. I get that maybe it isn't a priority development topic, but can't this - as Cinnamon is refined these next few iterations - be developed into a proper mechanism?
I would just like to also request this as an option, understood that some of the devs have stated that it is a design decision and that there are applets that accomplish some of what's been requested, however it is very handy to have when one works with large numbers of windows, and is something that has precedence in the implementations of other desktop environments. 

Additionally, as has been mentioned, the issue with the applets are that, for whatever reason, there is some measure of instability and inconsistency in the occasional basic functions. And even if the individual applets may function wonderfully, there may be times where a feature available in one may be unavailable in another, or vice versa, while integration within the standard window list allows the possibility of mixing and matching said features. 

Believe me when I say that it is not my goal to rag on the work done for Cinnamon; I love Cinnamon, it is my favorite DE for Mint, and I also love that people have taken the initiative to add in some of these features, but on some of these ideas why stop there? When cinnamon is presented as the "Traditional layout [with] advanced features, easy to use [yet] powerful [and] flexible" desktop environment, doesn't it make sense to integrate features that are included in a low-resource DE like XFCE, at least as options? I guess it just rubs me the wrong way that a feature request like this has seemingly been dismissed as handled well enough by 3rd party applets or because it was a design decision. I get that maybe it isn't a priority development topic, but can't this - as Cinnamon is refined these next few iterations - be developed into a proper mechanism?

I think all of this may be likewise addressed if applets are more tied to the system, with quicker ways to report bugs, ways for admins beside the authors to make changes given certain criteria, etc. I think it just needs something to finish off the professional polish that has been touted for the rest of the distribution, and then it will be spectacular.

**Comment by anandrkris** [comment]
@jtflynnz - I suppose there is repetition of some text owing to copy paste negligence. :stuck_out_tongue_winking_eye:

**Comment by dalcde** [comment]
#67 closing
