### ISSUE TITLE
organize app icons into folder on desktop

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/Cinnamon#3278]
i have a lot of app icon on my desktop which helps me a with easier access but they occupy a lot space. 
would it be possible to add a feature to drag and drop app icon on other icon creating a folder ?
![iphone_folders1](https://cloud.githubusercontent.com/assets/7669448/3317766/d85d7620-f710-11e3-8191-d0673425075a.png)

**Comment by abdupattoh** [comment]
YES!  I just went to the stardock website to bring this idea to cinnamon.  I suppose this could also be implemented through an Desklet?  But it probably needs more desktop integration.

I especially like the idea of roll-up windows holding icons, so that you can easily reference them.  I guess this could be emuluated with nemo folders... but ... not the same!

http://www.stardock.com/products/fences/

Cairo dock also provides some of this functionality I guess...

**Comment by jerrido** [comment]
Subscribed.  This is exactly what I am looking for.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
