### ISSUE TITLE
Lock screen login box ignores primary monitor

### ISSUE THREAD

**Issue by nirvdrum** [linuxmint/Cinnamon#3282]
I have a 3 monitor setup, running LinuxMint 17 x64.  I have one monitor set to be my primary, as is normal.  And all 3 monitors are of different make, so they wake up at different rates.  I have one that sometimes won't wake up at all (different issue of course).  

The problem is, the lock screen login box doesn't honor my primary monitor settings.  It seems to pick a monitor at random.  This means the login box moves from monitor to monitor every time I wake up my computer, which is jarring.  It also means I often cannot login until the last monitor wakes up.  And moreover, when one monitor never wakes up, I sometimes can't see the login box at all.  It'd be helpful if this box always appeared on the primary monitor.  Barring that, I'd be happy for it to show up on the first monitor to wake up.

**Comment by phord** [comment]
I also find this annoying.  A "primary monitor" setting for the lockscreen could solve this, but I don't know if it's the right thing to do.  I kind of think the right thing to do here is to show the dialog on **all** monitors at the same time, but I expect that's tricky to do for several reasons.  

As a workaround, what I do is just type my password whether I can see the dialog or not.  I *know* it's there; I just can't see it because the monitor it's on is slow to wake.  For the same reason, I can't see my mouse.  And since my monitors are not the same size, it's not always easy to move the mouse blindly to my preferred monitor since I might be unknowingly bumping it into the wall at the bottom of monitor 2.

**Comment by nirvdrum** [comment]
The problem I have with that approach is sometimes the lock screen bugs out and I can type into apps that I shouldn't be able to before the screen fixes itself.  I'm terrified of sending my password out through HexChat.

**Comment by Vahan86** [comment]
@nirvdrum, is this still an issue for you with Cinnamon 3.0?

**Comment by JosephMcc** [comment]
In Cinnamon 3.2 the password dialog shows on whichever screen the mouse is located on.

**Comment by anandrkris** [comment]
@JosephMcc - I feel this should be open as a feature request to a setting for showing in Primary monitor. 
Had a chat with @mtwebster over IRC and he said that it won't be difficult to implement.
