### ISSUE TITLE
[bug] All gnome 3 applications with client-side decoration will not correctly tile to edges or corners

### ISSUE THREAD

**Issue by PlutoniumHeart** [linuxmint/Cinnamon#3306]
Easily reproduced when trying to tile gnome 3 applications with CSD, gedit, disks, disk usage analyzer etc. 
There are always spaces between the window and the edges. 

Also test under gnome 3.12 everything works fine. So it should be related to Cinnamon. 

I am running on Debian Jessie, Cinnamon 2.2.13.

**Comment by Vahan86** [comment]
Tested in Cinnamon 3.0.7. It's working fine for me.

@PlutoniumHeart, is this still an issue for you in Cinnamon 3.0?

**Comment by leigh123linux** [comment]
I can still reproduce this issue in fedora with gedit.

**Comment by Odyseus** [comment]
Hello, everybody.

I just tested this on Cinnamon 3.0.7 stable and nightly (both Mint 18 systems) with mixed results.

- **Disk Usage Analyzer**, **Font Viewer**, **Simple Scan** and **System Log** windows tiled perfectly in every direction.
- **Disks** wouldn't tile into the corners.

Excuse my *newbieness* but, I assume that all this applications that I tested are using what you call *client-side decorations*, right?

**Comment by JosephMcc** [comment]
I can't reproduce this. @leigh123linux Are you running in HiDPI? I wonder if that affects it?

@Odyseus yes those are client side decorated apps. In some cases apps will not tile to certain positions because limitations to sizing that an app will allow. An application may not tile into a corner for example if doing so would make it smaller in one of the dimensions than it can/wants to be. This can be dependent or your particular screen resolution.

**Comment by leigh123linux** [comment]
@JosephMcc  Yes I am using hidpi, changing scaling to normal corrects the issue.
So more hidpi issues :facepunch:

**Comment by Odyseus** [comment]
Thanks for the explanation, @JosephMcc. And now I understand why some applications wont tile under certain situations.

**Comment by ManIVIctorious** [comment]
@JosephMcc Would it be possible to add an option for the window manager to override/ignore these minimum size limits?

**Comment by JosephMcc** [comment]
@ManIVIctorious No. 

Take a window that has a menubar for example. That menubar requires a certain amount of horizontal space depending on the number of items and the length of the text used for those items. We cannot somehow force the window to a smaller horizontal size than what it requires to fit those items. That isn't up to the window manager to decide. That is up to the application or "client window" and toolkit being used to develop its UI. If the client window has no knowledge/capability of how to deal with a partially hidden menubar there is no way it can work.

That's why on one pc where I have a 1080p monitor I might be able to tile an app but on another with a 1366x768 screen I cannot. On the same hardware I might be able to tile a window in English but even changing to a different language might prevent it from being tiled due to longer length of strings being used.

**Comment by leigh123linux** [comment]
Cinnamon 3.0.x is EOL, if you can reproduce with cinnamon 3.8.x feel free to reopen.
