### ISSUE TITLE
Cinnamon Display output freezes after supsend

### ISSUE THREAD

**Issue by FelixHaller** [linuxmint/cinnamon#3311]
#### Environment:
- I'm on Arch Linux x64 with Kernel: 3.15.1-1-ARCH
- Cinnamon: 2.2.13
- HW: Lenovo X220i Tablet, Intel graphics

The following happens in 1 out of 3 cases: 
#### How to (possibly) reproduce:
- work with cinnamon desktop
- suspend your notebook --> screen will lock
- wake up your notebook
- type in your password and press enter
#### What should happen:
- you will be presented with the cinnamon desktop
#### What happens:
- the password prompt disappears, but the screensaver with the time remains
- mouse cursor can be moved
- (seems) you are stuck in cinnamon screensaver
#### What I've tried:
- switch to virtual console (e.g. Ctrl+Alt+F2) and back
  - you will see a snapshot of the desktop
  - you are able to click anything, but there will be no feedback
  - switch to console and back again --> next snapshot with the result of the actions you made
  - means the desktop is still alive, but won't be updated on screen

**Comment by verticalscience** [comment]
Using Linux Mint Cinnamon with 3.13 kernel and NVIDIA GeForce 8200 motherboard graphics.  Tried other PCI-E graphics cards as well.   Desktop doesnt appear after screen lock but can use a terminal window. What's the easy fix?

**Comment by leannecrow** [comment]
Can confirm same issues on my machine. Had it in Linuxmint 17 and now on Linuxmint 17.1. 
      
     Linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I suspend the machine and if I resume it immediately it works normally. But when I resume it after it stayed in suspend state for a long time, it logins but freezes. All the dialogue disappears and I'm left with just the wallpaper. 

Have to reboot by Alt-PrrtScr + RISUB

**Comment by realhu1989** [comment]
Same issue with Linux Mint 17.2, Nvidia GT920M. After wake up from hibernate, only my background and clock appear.

**Comment by nisargshah95** [comment]
The issue persists for me on Linux Mint 17.2 64-bit, Cinnamon 2.6.13, Linux kernel 3.16.0-38-generic. Laptop - HP 15-r022tx.

**Comment by ilhamakbar** [comment]
Thanks @gccpacman 
It worked on my machine.

Linux mint 17.2
Card: Intel Broadwell-U Integrated Graphics

**Comment by Vahan86** [comment]
@FelixHaller, is this still an issue for you with Cinnamon 3.0?

**Comment by m-rossini** [comment]
Same issue with Linux 18 Sarah

**Comment by FelixHaller** [comment]
@Vahan86 Nope. It's fixed.

Arch Linux, Cinnamon 3.0.7, still Lenovo X220 (2nd gen Intel i3).

**Comment by ronator** [comment]
Same here on Linux Mint 17.3 Cinnamon with Kernel 3.19.0-32-generic:
cinnamon-screensaver-dialog: pam_ecryptfs: seteuid error

But I have no issues with login, all works fine. I haven't used suspend for a long time, so I can't tell. I saw this problem with virtualbox, too, and they never fixed it (listed as obsolete), so I guess it is ecryptfs related (as the message already says).

https://www.virtualbox.org/ticket/13147

**Comment by iamgollum** [comment]
I have the same issue as well. Linux Mint 18.1, 4.4.0-53-generic, 512 GB SSD, Zareason Laptop

**Comment by ylmrx** [comment]
Ditto @iamgollum . similar setup too. Dell Latitude 7470

**Comment by tecdec** [comment]
Hi I too seem to have this problem on  mint 18.1. it is very slow to boot and slow to enter into the login screen of cinnamon. I have  Nvidia GeForce 9600M  on a toshiba satellite G50 with 4GB RAM..

**Comment by leigh123linux** [comment]
@tecdec 

There is no chance this will even get looked at till someone provides some error logging!

**Comment by BahodirBoydedayev** [comment]
https://forums.linuxmint.com/viewtopic.php?t=170400

**Comment by AddisonG** [comment]
This is still an issue. It happened with me on a brand new install of Linux Mint 18.1 Cinnamon a week ago, and another brand new install of 18.2 XFCE today.

**Comment by sebalis** [comment]
As @leigh123linux asked for error logs, here is some log output from me. I am running Arch Linux (Antergos to be precise), updated yesterday. Have been getting this problem intermittently ever since I switched to Cinnamon a few weeks ago. The output is from journalctl and as it is too long I will attach it as a file. I get the impression that Cinnamon stops the system before it has completed all suspension activity, and that after wakeup continues to put the system in some kind of semi-suspended state. But I may be completely wrong. The graphical screen is unusable, showing only the time. I can switch to a text console, login, and do things from the command line such as kill processes, restart lightdm, or reboot. In this log I think I tried to suspend a second time from the command line to see if the second wakeup would be better than the first, but it wasn’t. This was at 10:51. I then went away for a while and then came back and rebooted.

[log.txt](https://github.com/linuxmint/Cinnamon/files/1234197/log.txt)

**Comment by TreeKittens** [comment]
# I found a workaround?

I am having an intermittent issue consistent with these symptoms. I can switch to another tty and I attempted the following:

```DISPLAY=:0 cinnamon-screensaver-command -e```

At this point, like the other posters, I found that the cursor changed consistent with what it would be on that screen, but I still couldn't see anything besides the lock screen. I could change workspaces with ctrl+alt+arrows and I would hear the swishing noise, but nothing else changed. I then blindly typed Alt+F2, the letter r, and then hit ENTER, and the cursor didn't change anymore. Confused, I went back to my other terminal and typed:

```DISPLAY=:0 cinnamon --replace```
and hit ^Z and typed bg (to put it in the background) and ... success! *I escaped*! So in short:

```
DISPLAY=:0 cinnamon-screensaver-command -e
Alt+F2 r ENTER on the malfunctioning screen (not sure how necessary this step is, including it for completeness)
DISPLAY=:0 cinnamon --replace
```

appears to be a workaround.

## SYSTEM INFO:
I have no outstanding updates on any level (my update policy is set to install everything, even unstable). The System Info application shows the following information:

Operating System: Linux Mint 18.3 Cinnamon 64-bit
Cinnamon Version: 3.6.7
Linux Kernel: 4.13.0-39-generic
(processor, memory, and hard drives are probably irrelevant)
Graphics Card: NVIDIA Corporation GF108 [GeForce GT 630]
Graphics Card: NVIDIA Corporation GF119 [GeForce GT 520]

I am using nouveau drivers according to lsmod, consistent with the configuration that is known to cause the problem. I have understood that the issue is due to having the screensaver and either monitor idle or suspend settings set to the same time and conflicting; my computer is set to never suspend, but the screensaver starts after 15 minutes and so does turning off the monitor. I will change them to be different, and will come back here if the problem still occurs.

**Comment by icarter09** [comment]
Is anyone still experiencing this issue?

**Comment by BugsyReportsy** [comment]
> Is anyone still experiencing this issue?

I am on Mint 22 and Endeavour Cinnamon.
