### ISSUE TITLE
multiple rows in the workspace switcher

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#3347]
It would be nice if the workspace switcher applet allows to configure the number of rows used, like the old GNOME classic applet did.

That was quite handy to save panel space by having e.g. a 4 x 2 configuration.

**Comment by WildPenquin** [comment]
Hi,

Just pointing out, that at least the behaviour should be consistent. Now, if ticks the option "Show worksapces in a grid" (not sure what it is called since I'm using Finnish) in the Workspace options, it does just that in Éxpo, but not in the applet. At least they should be consistent (i.e. the chooser applet should be a minimap of the Éxpo). IMHO the obvious thing to do, would be to replace the tickbox with an option to choose the number of rows (and columns), and use that setting in the applet, too.

But if this is core feature or not, is a matter of opinion, I think =)

Cheers!

**Comment by Vahan86** [comment]
@JosephMcc, seems to be dublicate of https://github.com/linuxmint/Cinnamon/issues/561

**Comment by JosephMcc** [comment]
#561 does include a request for this and without Cinnamon allowing a 2d layout of the workspaces it doesn't make much sense for the applet to display it that way. Basically, for this to make sense we would probably want #561 and I'm not sure that's a direction we want to go.

**Comment by calestyo** [comment]
> 2d layout of the workspaces it doesn't make much sense for the applet to display it that way. Basically

Why not? It saves precious space in the task bar…

**Comment by JosephMcc** [comment]
Because the workspace switcher represents your workspace layout. If we only allow a 1d layout it makes sense to display a 1d layout in the applet, imho.

**Comment by calestyo** [comment]
I'd guess only few people actually care whether workspace a is right/left/above/below of workspace b unless they use some of the overview displays... I for example only want a number of n workspaces and have each of them assigned a F<n> key for switching and the applet merely serves as a quick display where I am... so the main desire is to keep it small... and given that, having multiple rows in it makes perfectly sense.
