### ISSUE TITLE
Allow themes to be customized

### ISSUE THREAD

**Issue by mintystark** [linuxmint/Cinnamon#3356]
I am wondering if there is any word on allowing themes to be customized in the same since as Applets.  I am thinking that in the Theme Manager where you can see the themes and "Apply theme" that when the theme is selected there is a "Customize Theme".  Nothing fancy, just a simple settings popup like the Applets do. Same settings fields like text, checkbox, select, etc.  With the only difference of having a color picker.  Then an Apply button which would reload the theme.

The easiest thing would then be to have the values in the theme css file.
Something like $setting['setting_name'].

So like:
# main-background {

```
 background-color: $setting['mb_background_color'];
```

}

We would also need to be able to set defaults just like the Applets Settings have.

I am thinking of making an Applet that would do such a thing for specific themes, but don't want to waist my time if you in the works of having this.

Thanks

**Comment by coryhilliard** [comment]
Is there a voting system in place for this feature?  I find this missing feature is THEE number one missing feature since the demise of Gnome 2.  I have built my own theme, but I would love to have just a simple pointy and clicky (as most users of operating systems would too).  Just because I can code CSS, doesn't mean it's fun all the time.

**Comment by yro84** [comment]
well, where can I see a proper tutorial about how to customize the default cinnamon theme? I just want it to have the blue line above the name of the program window on the main panel, I just want this panel to be fully black (real black) and I just want to change the main selection colour to pick orange or something similar to a darker blue. Just simple things like that. Where can I get the how to? Atleast where can I have informations about these things I wanna change on the main theme?

**Comment by cruftytheclown** [comment]
I would like to be able to control the transparency of individual panels.

Then I would use a normal non-transparent panel at the bottom of my screen, and a fully transparent panel at the top of the screen where I would put notifier applets in the top right corner.

**Comment by germanfr** [comment]
@cruftytheclown this may be what you need: [https://cinnamon-spices.linuxmint.com/extensions/view/42](https://cinnamon-spices.linuxmint.com/extensions/view/42). The individual transparency is not a feature yet though.

**Comment by rustedwolf** [comment]
If a color custom prime color selection would be implemented, that would be a very big plus for cinnamon. Then again it there would be no need for large preset list, like it was in Mint-X. Just select style > then select a color from preset or custom color. 
Right now Mint-Y theme (as I look in my settings) has only green color theme, so they won't match up with Mint-X icon other than green color presets...

**Comment by JosephMcc** [comment]
I'm going to close this. This has been discussed internally multiple times and there is no nice and easy way to implement this and make it work nicely and up to the standards users probably expect.

**Comment by Mario-paul** [comment]
_I wasn't sure if I should post here or open a new issue but since it is the same thing I'll just post here. If it is wrong please let me know and I'll post a new one!_

So I am creating/modifying a new set of themes, and it's come to my attention that the values for many elements are hard-coded on the CSS. This is incredibly inefficient and explains why you need separate themes to simply change the accent color of the different Mint-Y themes.

Within the last few years CSS variables have become a thing, and are supported by all major browsers. Cinnamon being a sleek, modern desktop environment, I tried to implement variables in order to easily modify elements on the fly, but it seems to break the rest of the CSS. I'm doing it just like on regular modern CSS, like so:

```
  :root {
     --test123: rgba(243, 0, 0, 0.59);     
  }

.panel-top, .panel-bottom, .panel-left, .panel-right {
  color: #ffffff;
  border: none;
  background-color: var(--test123);
  font-size: 1em;
  padding: 0px; }
```


is this something the Linux Mint devs plan to ever add?

**Comment by JosephMcc** [comment]
There are no intentions to support this currently. For many of our own themes we currently use sass which gives you very similar functionality.
