### ISSUE TITLE
Incorrectly work with panel applet (quick launch). Removing icons. Move icons.

### ISSUE THREAD

**Issue by dimti** [linuxmint/Cinnamon#3474]
Error 1:
A try to delete icon from panel

Actual result:
Deleted left over icon (not that, where im clicked to)

Waiting result:
Deleted that icon, where i clicked to delete

Error 2:
I go to edit mode icon (click to icon and click to edit)
I try to move my icon

Actual result:
My movement icon replaced another icons and double self (sometime icon move is successfull).

Waiting result:
Icon movd to the concrete position between another icons. Another icons not to be replaced and not to be deleted.

My cinnamon have 2.2.16-1 version
My operation system and linux kernel: ArchLinux, 3.16.1-1-ARCH (i686)

Tell me if need additional screenshots or desktop videos or logs - i send that (tell me email or ftp or share services where placed it).

**Comment by bzimmerly** [comment]
This was the nearest I could find to an issue (bug) that I'm experiencing. Here is how to duplicate the bug:

1. Right click Menu / Accessories / Terminal.
2. Click "Add to panel." (Creates -another- terminal launcher in addition to the original.)
3. Try to move the new icon next to the old one. (Cinnamon moves it back. Arg!)

Why would I want to add another terminal icon? *Because* I have scripts like "2hterm" that I want to click. (It generates two horizontal terminal windows tiled next to each other on the current workspace with no menubar.) Adding the Terminal icon to the panel and editing it to use the "2hterm" script is the only way I know to add such a script -WITH- the terminal icon.

**Comment by dalcde** [comment]
No this is not the bug you are experiencing. Open a new issue if it is a different bug.
