### ISSUE TITLE
Make the built-in desktop recording feature of Cinnamon Desktop not be a hidden feature

### ISSUE THREAD

**Issue by Enkouyami** [linuxmint/Cinnamon#3498]
There needs to be some way to unobtrusively inform users that they can record their desktop using Ctrl+Alt+Shift+R. Maybe there should be a built-in menu applet or a application menu entry for it. Also options for it would be nice.

**Comment by jmnx** [comment]
did someone tested this:
https://github.com/rjanja/desktop-capture
??

**Comment by JoshDreamland** [comment]
As a matter of fact, could we not do this at all? I've had two coworkers fill their disks with a recording they didn't know they started. I recently noticed I was in the process of doing so, as well. IDE users press complicated refactor key combos *all the time.* It's not a question of *if,* but *when,* people will accidentally find this feature.

**Comment by germanfr** [comment]
An icon in the system tray would be fine. Also from there would be easy to stop it, etc.

I've recorded with other tools because I didn't know this existed. That would be useful.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by JoshDreamland** [comment]
There are more features to be added here, sure, but I would say that the feature (as implemented right now) is actually a bug.

**Comment by JosephMcc** [comment]
@JoshDreamland If the recording is active there is a giant red dot at the bottom right of the monitor. It isn't that easy to have the recording running without knowing about it. You can also disable the shortcut if you don't want it available.

**Comment by JoshDreamland** [comment]
Yes, the red dot is how I noticed it was on, last time. As to giant, I disagree. My first question was, "why does this workspace have a red dot in the middle?" Then I remembered that Cinnamon has a tendency to start recording desktops without users realizing it. After about 40 seconds of inability to find how to disable it, I deleted the file it was recording to and moved on with my day.

As for disabling the hotkey, that's fine; I don't need to do that much, because 364 days of the year, I run XFCE. Cinnamon came installed on a corporate laptop that I use so infrequently, I haven't managed to replace it.

The point is, this isn't about me: I'm just letting you know that this feature has a potential to fill disks. People who don't know about this feature have no idea why it happens. It might be useful to note that this causes some users (particularly new users, and infrequent users) real grief. What you do with that information is up to you.

**Comment by notnotme** [comment]
Ho... I enabled the feature while trying to force my web browser to force refresh the cache....

Where are stored the saved files by this feature ? So I can delete them. I rebooted the laptop because the FANs was at max speed... while it was still recording (I just figured out what was the strange logo at the bottom right of my screen) ....

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
