### ISSUE TITLE
left-align center region in the panel

### ISSUE THREAD

**Issue by giliteho** [linuxmint/Cinnamon#3597]
Hi,

Is there a way to change the alignment of the panel regions: left, center, and right? 
Specifically, is it possible to make the center panel "left aligned" like the left panel?

**Comment by dalcde** [comment]
@giliteho what are you really trying to do? Applets in the center region are by definition centered. If you want them to be left-aligned, put them in the left region.

**Comment by lestcape** [comment]
@dalcde one thing is a common behavior and another thing is what specific user want to do and not certainly need to be the same. And is not in this case.

As for example if i want to modify the panel behaviors to do what he want now, i need to replace the panel manager, but i can not do that, because i can not disconnect the the global.settings signals... Please can store the handler_id? I want to play with panel and create an extension. Is ok to me that not all things will supported by default, but provide a way to modify the behavior is important, i think. 

https://github.com/linuxmint/Cinnamon/blob/master/js/ui/panel.js#L173
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/panel.js#L174
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/panel.js#L175

Thanks.

**Comment by lestcape** [comment]
@giliteho: request what do you want here:
http://cinnamon-spices.linuxmint.com/extensions/view/33
You also can see this:
https://github.com/linuxmint/Cinnamon/issues/3849#issuecomment-92089385

What i want to do is a little more general and requiere disconnect the signals, but is possible add what you want on the @mohammad-sn new extension...

Regards.

**Comment by lestcape** [comment]
https://github.com/linuxmint/Cinnamon/pull/4045
