### ISSUE TITLE
cinnamon crashes, when importing dconf-data

### ISSUE THREAD

**Issue by friedemann-** [linuxmint/Cinnamon#3607]
Version: nightly

Running 'dconf load' on a file of configuration data crashes cinnamon.
The configuration data is loaded, though.

In my case:

dconf load /org/cinnamon/desktop/keybindings/ < keyconf.file

with a bunch of entries like this

[custom-keybindings/gnome-terminal]
binding=['<Super>grave']
command= ...
name= ...

and in the end

[/]
cumstom-list=['gnome-terminal', ...]

Up to cinnamon 2.2, there where no crashes

**Comment by friedemann-** [comment]
dconf load still crashes cinnamon. dconf executes correctly, all data is imported.

Has someone a clue? This must have happened in the last year or so, before that, it always worked.

Biggest problem: there seems to be a limit for custom keybindings, I'm not able to create new ones, if I have to many. The only possibility is with dconf load.

**Comment by mtwebster** [comment]
Honestly, I'd rather worry about why you can't add keybindings normally, there should be no real limit to these, so I consider it a bug - do you know how many you had before it quit working?  What happens when you attempt to add them?  Can you run cinnamon-settings from a terminal and pastebin any errors or messages you receive while this is failing?

The dconf load, for me it freezes cinnamon sometimes, other times not... it's a huge system shock, to a system that relies on dconf heavily.  I imagine it's triggering every possible callback running on the system at the time, one after the other.  Regardless, it's not a normal thing to be doing, I'm not really going to consider it a bug at this point, regardless of previous behavior.

**Comment by friedemann-** [comment]
I looked a bit into it and I have to admit:
My configuration section /org/cinnamon/desktop/keybindings/custom-keybindings
doesn't name the entries [custom0] etc but with names. So probably system settings relies on that, which would be pretty much my own fault.

For testing, I cleared my custom keybindings and added a lot by hand, the problem doesn't occur, when you do it that way.

For me it works anyway, I just have to restart cinnamon on the console with kill -1 and I don't change my keyboard shortcuts very often.

If you're not supposed to do this (dconf load), this issue can probably be closed.
