### ISSUE TITLE
Cinnamon 2.4 / 17.1RC memory behaviour

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#3690]
The Cinnamon process is growing in memory use over time.  Here are some initial memory observations for this process.  The measurements below are done using a simple readout from the supplied system monitor.  The desktop has been stripped down to a minimum to remove potential causes - a static background, no startup apps at all, no 3rd party applets, but I will admit to a custom theme ;-)  There was no connectivity - no physical connections, no bluetooth applet,  and wifi turned off in the computer by a hardware switch.  I did not touch the keyboard at all in the first set of measurements other than to launch the monitor, so there were no external events that should have been affecting Cinnamon at all.  Memory measurements in MB

startup 73.3 (I launched the monitor by hand as quickly as I could after startup)
rising to 83.5 2 or 3 seconds later
84.6 +53 seconds
84.7 +40 secs more
From this point on I just recorded the running time
84.8 1:30
84.9 2:06
85    2:27
85.1 3:16
85.2 3:50
85.3 4:15
85.4 4:37
86.5 5:15
86.6 5:30

at this point I turned the hardware wireless switch on
memory rose from 86.6 to 94.8 immediately
then I recorded 98.4 and 101.6 in the first 10 secs after turning the switch on
further readings of 101.6, 101.7, 102.4 in the next 10 secs
stabilising at about 105.1

at this point I turned the hardware wireless switch off, memory remained stable at 105.1, so the memory used in the wireless connection setup was not returned

I turned on the update manager. This was the first time I had touched the keyboard after launching the monitor.  Memory rose from 105.6 to 106.7, and fell back again to 105.6 after around 20 seconds.  (No searching for updates etc., just launch of the program.)

At this point I realised that although I had turned off the bluetooth app, I had not actually turned bluetooth off. I turned bluetooth off and rebooted and took another series of measurements:

startup  73.8  quickly rising to 85 after 2-3 secs or so
85.1   1:59
85.2  2:32
85.2  3:07
85.3  3:30
85.4  4:06
85.5  4:48
86.5  4:54
86.6  5:27

So tentatively it would appear that there is something kicking in shortly after the desktop displays that is eating up 11-12 MB, a slow and gradual increase of around 1-200K per minute without any obvious event based cause, something kicking in around 5min or so that uses up about 1MB, and then there is an event based use of around 20MB when initiating a subsequent wireless connection that does not come back when closing the connection. Bluetooth being turned on did not have any obvious effect. Launch of the update manager did not have any obvious effect.

**Comment by NeoGeo64** [comment]
I'm having this memory leak issue too.  I'm on Mint 17.1 and I'm serious about to give up on this distro.

Here is my post about it in the LInux Mint forums (as if it would help) http://forums.linuxmint.com/viewtopic.php?f=47&t=186593

**Comment by lestcape** [comment]
@NeoGeo64 no one force you to use Mint, but any way, Mint not have any memory issue. What occurs it's relate with Cinnamon, not with Mint and on my opinion, what is wrong it's the cjs implemetation of the garbage collector. This is not a memory leak, is a wrong implementation of the garbage collector, as you can see here:
https://github.com/linuxmint/cjs/pull/17

My current stage right now, about 3 hours after of the session init:
![captura de pantalla de 2015-01-05 20 32 37](https://cloud.githubusercontent.com/assets/1389572/5623456/13d11980-951a-11e4-9182-f2df40cb19dc.png)

**Comment by NeoGeo64** [comment]
I use Mint because I love the distro.  I've been dealing with all sorts of issues in the Linux world in the last few months.  Garbage collector, you say?

**Comment by lestcape** [comment]
The problem on my opinion is the garbage collector. Cinnamon can have memory leaks, but not on the commonds procedures. Use this applet:  https://github.com/lestcape/Garbage-Collector and reduce the  maximun value of memory to 10, then restart cinnamon and see if you note after some time a problem with the memory. If you can not note this, is the garbage collector issue, not a memory leak. If you want to know about garbage collector:
http://en.wikipedia.org/wiki/Garbage_collection_%28computer_science%29

**Comment by lestcape** [comment]
@mtwebster I don't know why, but you can read here that delete the profile and then create a new one could solve some memory problems. A configuration problem? The memory will lost when an error occurs and more applets to evaluate could cause more problems, also if there are not loaded?
http://forums.linuxmint.com/viewtopic.php?f=208&t=183250&sid=255f274e0dd621847e777358e2560c46

**Comment by JosephMcc** [comment]
I am with @mtwebster on this. Something specific has to be causing the issue you guys are having. I have at times left my machine running for a week at a time without seeing memory usage like what's being reported. 

Quick case in point, I did a little experiment over the last couple hours. I started by restarting Cinnamon from the panel context menu. Like normal, memory usage started very low and then increased over about the first minute until it steadied at around 125mb. I used the trick of opening and closing the Cinnamon menu over and over to drive the memory usage up to around 170mb. I then closed all open windows except Hexchat and left the machine alone. I have things set so the lock screen kicks on and the monitors shut off after 10 minutes. I came back after after about 2 hours and Cinnamon's memory usage was at 122mb. Even now with Firefox and System Monitor also open I am sitting right around 128mb. 

The only 3rd party applets I have installed are the weather applet, mtwebsters Cinnamon/Gjs monitor applet, and the multi-monitor window list applet. Running dalcde's panel rewok branch and a background slideshow. I don't normally make heavy use of the Cinnamon menu since I almost always use the same few apps. I have them readily available in the panel launchers applet. Also not a big alt-tab or multi-workspace user though I do use them on occasion.

**Comment by lestcape** [comment]
@JosephMcc thanks, thats interesting... But i reproduce the problem some time ago with the default cinnamon configuration... Some thing could create a problem and then we cannot go back, because we not know why this occurs. On my case, i have a big problem, thats is related with gc. If i have a memory leaks, then my applet(https://github.com/lestcape/Garbage-Collector) can not fix the leaks, but when my applet is working, this problem not occurs. So, a gc problem can not be caused by any external code of cinnamon. This means, that if other applets have a memory leak or not, not matter because is a cinnamon problem. And i also downloaded the cjs code and then compare with the gjs code. Cinnamon forks the gjs code before the gnome shell devs apply the path that is added here:
https://github.com/linuxmint/cjs/pull/17

This code is not my code, could you explain why gnome shell devs merge this code if is not needed? I can not explain why. So, need to be something there, that only occurs on some specific configuration...

Any way, on different systems with the same configuration, you can not expected that the same problem occurs, if you add some different configuration to the problem less.

I talking here of a problem that not occurs to all users, only a few, so your experience to the problem, really is not representative if you don' t have the problem. Your help, ofcourse is wellcome, but only say that this problem not occurs to you is not a help.

**Comment by lestcape** [comment]
I lost 1 Gb on 6 hours, please compare with the image above.
![captura de pantalla de 2015-01-06 02 17 25](https://cloud.githubusercontent.com/assets/1389572/5625971/3962e0ea-954a-11e4-9c76-1de7d4a4a144.png)

**Comment by JosephMcc** [comment]
@lestcape I'm not disputing that cjs might be improved by the updates from upstream gjs nor will I pretend like I understand the inner workings of cjs/gjs. It would be nice though to try and get to the bottom of what is causing the issue in the first place since some users experience it and others don't. I posted what I'm seeing to maybe get some sort of comparison to what others are doing and see if we can possibly narrow down the cause. I think that was the point of mtwebsters post. 

What I do know is that people posting a bunch of screenshots of Cinnamon using outrageous amounts of memory or telling us how they're about to leave Mint/Cinnamon because of it doesn't help anything.

**Comment by lestcape** [comment]
@JosephMcc i see now your point... sorry.

**Comment by JosephMcc** [comment]
I stumbled on another thing that could be of interest. Check this: 
https://github.com/GNOME/gnome-shell/commit/9548cd834156447ef8a36a038f0b48eb8992fa8b#diff-09304ba2858e4c3eefca50fd13f45308R564

And a relevant discussion here: 
https://bugzilla.gnome.org/show_bug.cgi?id=685513
It's a long thread but shows how difficult this sort of thing can be to nail down a specific cause to.

**Comment by lestcape** [comment]
@JosephMcc thanks, I never would had thought-out on use the valgrind on cjs, even if i use it on qtCreator.

Now i need to know how no one detected the problem before, if clear there are several. I think that the problem it's still there and we can not discover it because ours normal behavior avoid to test the real cause. Please try to destroy the cairo context on an explicit way. Please, if we don't understand the gjs code, do not expect to merge code that solves memory problems or performance. Do that right now. This is only what i can conclude.

**Comment by mtwebster** [comment]
If you had found that patch a couple weeks sooner I probably would have merged it *before* 2.4, but being so close to a release it wasn't worth the risk in our opinion, when it wasn't really a widespread problem.  Whether we understand it all or not is irrelevant - do you realize how many times gjs (and other gnome-shell stuff) has had things implemented, re-implemented, reverted, etc... it's never been a static thing.  

There's just as much risk in applying the very latest upstream patches applied as there is just leaving it alone sometimes.  Unfortunately that means occasionally some users have problematic experiences.  So we try to work them out and address them.  But if we waited until *every single user had a perfectly bug-free experience* we'd never do a release!

**Comment by lestcape** [comment]
@mtwebster thats it's also a good point but it's a little problematic to me be on your place... Because possible i need to decide the same as you decided, but maybe not. As you see some latest changes create also specific problems. They are made to fix problems, like this change. What could be more important, is really relative to the people. What i don't understand now is, why we need to ask for the cause of the problem? The cause is know. Is interesting see the user report the same thing, one time and another? Of Course that a normal user can not discover the cause of a problem like that. This a time lost for all.

**Comment by mtwebster** [comment]
Yes it's interesting to see the users report the same things, because hopefully one of them provides something useful that can guide us to fixing it.  10 people reporting they have memory issues does *nothing* to help me, particularly if I am not witnessing the same behavior, unless they can provide me with details that will help reproduce it.

I'm not going to blindly add patches without at least attempting to study the ramifications, and the potential for new regressions - I don't care where it comes from - and especially 2 weeks before a release.  What's even more fun, is that the debian maintainers want to run Cinnamon off of upstream gjs.  They'll have the latest language bindings (3.14+ versus 3.10), but they'll also have bugs manifest themselves that we'll have no idea how to handle or where they came from.  We'll have subtly different versions of Cinnamon floating around and behaving differently.  So not only will we have our own self-created bugs and regressions, we'll also have new mystery bugs to deal with, with users pissed off at us for things we have nothing to do with.

**Comment by lestcape** [comment]
Well... if good to know that we don't lost the time then. The debian decision is not a good news... Could not be possible create a wrapper to handle 3.14 as a dependency of 3.10 and then apply the patch just in a separate code without affect the stable cinnamon? This will be a preamble to the new code that can be added later or not and could be development with the help of debian devs... This was my idea of create a wrapper of the St and the different code to start cinnamon over gnome shell and automatically migrate the applets, desklets... I can not continues this project, because the updates come more faster than what i can development the wrapper...

**Comment by NeoGeo64** [comment]
Opening and closing the Menu, you mean the "Start" button ?  I tried 
opening and closing that Menu over and over again and it never decreased 
memory for me.  Also, when I try to restart Cinnamon it just never comes 
back.  So I'm stuck with whatever desktop icons I have and whatever 
windows I have open.  I don't have buttons on top of the windows to 
maximize, close, etc.  Just the window itself. Thank God I had a 
terminal window open so I could reboot gracefully because without it 
there was no other way except holding down the power button.

**Comment by NeoGeo64** [comment]
OK, yeah, my memory leak is nowhere near that bad.  Mine goes up about 
100MB every day.  But, you see, that's still bad because after a couple 
of weeks it's using up all of my RAM.  I can understand the Cinnamon 
process using more and less RAM as it's needed but for it to just 
continue to consume memory.  Cinnamon needs to go on a diet, so to 
speak. haha

**Comment by NeoGeo64** [comment]
You have to understand, though.  A lot of us are Windows converts and 
get frustrated when things break in the OS that the average user can't 
fix with a few clicks (or commands).

**Comment by NeoGeo64** [comment]
Bugs are inevitable in something as complex as a Linux distro.  You guys 
do a fine job of releasing a distro into the world that's easy to pick 
up and use.

**Comment by lestcape** [comment]
I hope that can be understand, that I not try to solve a personal problem, I only try to help other on the same situation than me. I have the knowledge and the necessary resources (launchpad) to solve my own problems, also those of a group of users of cinnamon (the ubuntu 14.04). I understand why the change is not produced, so i not want to create more different branches of cinnamon with the corresponding associate problems that this could be create. My only intention is helping, but i don't had known about the complete scenario, so i need to ask. Any way thank for the explanation.

**Comment by lestcape** [comment]
@NeoGeo64 try to open and closed the menu(start button), not decrease the memory, occurs the opposite in this case, because popup menu have a cairo context, to create a beautiful popup menu(with an arrow). And the cairo context is not currently destroyed on an explicit way.

**Comment by tylery71** [comment]
Cinnamon 2.4.6
Opening & closing windows causing a steady increase in memory usage per #2986 
(slightly modified script)

while true; do timeout 1 xeyes; done

**Comment by rickyzhang82** [comment]
I experienced this in Fedora 21- cinnamon-2.4.6-2.fc21.x86_64. The process cinnamon takes up 2-3GB memory over one week time and slow down desktop. 

I have to manually kill the process and restart it.This seems to be a memory leak.

**Comment by vpal** [comment]
Same issue here on Linux Mint 17.1, got to about 500MB in a few hours.
I'm new to Cinnamon and I really like everything except this leakage so far.
Very sad because if this stays this way I have to say farewell... :(

**Comment by NeoGeo64** [comment]
Well, you can switch to Mint 17.1 KDE, XFCE or MATE.  I'm considering 
doing that.

I like Mint but Cinnamon is just too buggy.  With any other desktop, 
maybe we could enjoy the benefits of Mint without the bugs.

~ Neo

P.S.  And if that don't work we can just find another distro.  I've 
basically given up trying to contact the developers and get things 
fixed.  It's always something we, the users, are doing to make our 
system use too much memory, or become unstable.  Their code is perfect 
and their machines are always humming along fine.  Yeah, right, OK.

**Comment by vpal** [comment]
Yeah, it's really not about that I want to be offensive in any way.
I really appreciate all the work the people working on Cinnamon have 
done and it is really a very good direction and approach after Gnome 2 
and Unity.
And I can really live with some smaller bugs.
But I'm using the computer for work and I need a certain level of 
stability and reliability though.
So a memory leak of this level not fixed on the short term is really 
something that prevents a product from being productionready.

**Comment by mtwebster** [comment]
Can you tell me does this behavior manifest with stock applets/desklets and extensions only? Or are you using 3rd party replacements?  By stock, I mean the ones with the padlock next to them in the settings list.

**Comment by brownsr** [comment]
neogeo64:  can I please refer you to my comment on 6th Jan, and could you please give as much specific information as you can.  People are very motivated to correct memory leaks, but they are not necessarily easy to find, so very specific information is helpful.  I am running the latest development version built from git master, and things do seem considerably improved from my original report.

**Comment by vpal** [comment]
I'm using two that don't have the padlock next them:
http://cinnamon-spices.linuxmint.com/applets/view/17
http://cinnamon-spices.linuxmint.com/applets/view/79
Should I try uninstalling them?

**Comment by JosephMcc** [comment]
@vpal You don't have to uninstall them, just remove them from the panel. I use the weather one and don't have the reported memory issues but I've never tried the other one.

@NeoGeo64 I really don't get the attitude of some of your posts. You say none of the developers are responding to your issue yet mtwebster, one of the main Cinnamon devs, responded IN THIS VERY THREAD trying to get some info from people to help troubleshoot the problem. Since then I haven't seen a single post from you providing any of that. Instead you respond with "they say it's the user's fault and their code is perfect". Really? The reality is that there is something with your systems configuration, the cinnamon features you use, the apps you use, or some combination of those things that leads you to encounter this issue while a lot of people don't. That's not placing blame. Without knowing those things we have no way of trying to reproduce the steps to cause the problem which means we have little chance of being able to fix it.

**Comment by lestcape** [comment]
This has not be resolved never on that way, please focus on doing the things better, and not to write criticals or defenses... We want (all) the best things for cinnamon, we have not divergent criteria of the main contents. I'm a user and also i can develop some applications, so i can understand, this is not the way....

**Comment by collinss** [comment]
@NeoGeo64 I'm not one of the devs for Cinnamon, but I have written and maintained a number of applets, and I can say from experience that it is extremely frustrating when people post a comment saying that they have a bug that they expect me to fix immediately, while giving no additional information to help me track it down, and then get upset when I can't do it because I can't reproduce it and have no idea what's causing it. As @JosephMcc @mtwebster @brownsr and others have pointed out, your comments about the devs and how you think they are treating you are completely unfounded, and don't help anyone. You are never going to find a perfect OS, or a perfect DE (though in my mind Linux Mint Cinnamon comes closer to it than anything else I have ever used), but if you have that much of a problem with it, then maybe you should switch. Either way, your jabs and accusations about the devs are not appreciated, so please stop.

**Comment by rickyzhang82** [comment]
@lestcape I totally agree with you. Can anyone write an instruction how to report the configuration? Is mtwebster's instruction still valid?

**Comment by tylery71** [comment]
@JosephMcc @collinss 
NeoGeo64 is just blowing smoke..
https://github.com/linuxmint/Cinnamon/issues/2986#issuecomment-71335669
https://github.com/NeoGeo64?tab=activity

Unless there is an actual link to anything claimed, I would just ignore it.

**Comment by lestcape** [comment]
@rickyzhang82 thats is a good point, will be important write an appropriate short manual of how report problems. The devs could refer the user about the manual, without lost  time, when is needed. Opposite to this I consider that a normal user can not make an appropriate report of a memory problems. The most reports here don't say anything to the devs (included my own reports).

**Comment by JosephMcc** [comment]
Yes @mtwebsters instruction is still valid. You don't have to be a linux genius to give helpful information. The best place to start is probably to disable any 3rd party applets, desklets, and extensions for a couple days just to rule them out as causes of the issue. Open the built in System Monitor app and click on the Memory column until it's sorted highest to lowest. Cinnamon is probably somewhere near the top even on a fresh startup. Leave the app up on your desktop and go about your normal business. Keep an eye an Cinnamons memory usage. Is it climbing steadily? Is it climbing only when you do certain things? Devs can always ask you more questions to help narrow it down but there has to be a place to at least start. Be aware that the memory usage will grow to some extent but it should pretty much level off.

If you want you can also use this: https://github.com/mtwebster/Cinnamonitor
It's a panel applet that by default will show Cinnamons memory and cpu usage on the panel.

It's also helpful if you let us know what distro and Cinnamon version you are running. You can get the cinnamon version by opening a terminal and running cinnamon --version

**Comment by NeoGeo64** [comment]
Look, I'm sorry for "attacking" the development team for Mint/Cinnamon.  
Perception is reality and that is just how I felt. Sorry for voicing my 
opinion on the matter.

~ Neo

**Comment by gooberfoob** [comment]
I would like to make a comment about this memory leak issue. I will agree with you all that posting aggressive comments will not resolve the problem. I am using Antergos w/ Cinnamon, and I have experienced two bugs. First is the memory leak that has been mentioned. The leak for me seems to happen when I run my computer for a few days. From basic observation it seems to be from opening and closing firefox. My system will run around 400 mb of memory idle, and after a few days it will go up to 800mb idle. I will do more research into it and see what I come up with. The other bug I have come across is, when I do the troubleshooting option to restart just cinnamon, not the whole system I will get a black screen and will cause me to restart the whole computer to fix it. This only happens sometimes. Along with restarting the DE I will loose all the icons on my GUI desktop, but they will be there when I navigate into the GUI file system. Hopefully I was clear and precise with the small amount of information I gave. If anyone has suggestions for what I can do I am 100% on board to help in anyway. Thank you cinnamon devs for all the work you do.

**Comment by vpal** [comment]
I disabled all third party apps and haven't experienced memory consumption above 300MB since then, but I'm really not sure if this is related in any way.
Though there was no extreme memory consumption since disabling apps, Cinnamon's memory consumption is really unstable. It seems to grow all the time I would say the difference is only in the growth rate.
It mostly starts up with around 150MB and also stays on that level for a while and then starts to grow slowly. From what I have seen to about 250MB. I'm not sure about to how much it can go up because I restarted my computer often in the last time.
Question to the developers: What is/would be the amount of memory Cinnamon should consume without third party apps enabled?
It is also really strange to me that third party apps can influence Cinnamon's memory usage. If they are that really risks the stability of Cinnamon.
I also asked all my colleagues who use Cinnamon and they reported memory usage between 250 and 350 MB.

**Comment by dalcde** [comment]
I have around 115 MB. It makes sense that third party extensions affect Cinnamon's memory usage. It's just like running any program, say firefox, will increase the memory consumption of your computer. Since the third party Cinnamon extensions "live inside" Cinnamon, their memory consumption will be counted as Cinnamon's. More importantly, if they are poorly written, there can be lots of memory leaks and will cause huge memory consumption.

**Comment by vpal** [comment]
@dalcde
That is the point: Cinnamon extensions "live inside" Cinnamon
That not only risks Cinnamon's stability by design but is also very likely a security risk as...
Yep FF's memory consumption increases the memory consumption of my system but not my DE's memory consumption.

**Comment by lestcape** [comment]
@vpal:  I'm against the current architecture, but this is on that way because the main support of Gnome Shell and Cinnamon is provided by Firefox and the Firefox design is on that way (i think thats this is ok to firefox, but not for a desktop), because the graphical componentes don't support multitheradings (or at less this the justification). 

Anyway as @dalcde say and about this specific problematic of memory, this is not a big problem. What could be a problem, speaking about memory, is the need of restart the whole desktop, for an specific memory issue of one application, not more than that (the sum of memory, will be the same).

I don't think that is a security risk if the extension, aplets and desklets, will be installed with root permissions (will be a user decision on that case), but currently not occurs on thats way(true). 

Speaking about performance, stability and when a user is disturbed by a problem that is not cinnamon (is an external app), yes, is a problem.

**Comment by dalcde** [comment]
@vpal true, but installing an FF plugin will certainly increase the memory consumption of FF! (well, probably, but you get the idea) What we can do is probably to improve our garbage collection mechanism (which is HARD).

@letscape I think most, if not all, devs are against the current architecture. But that's not an easy thing to fix...

**Comment by vpal** [comment]
@dalcde I think it is a big mistake to compare a DE to a browser. I expect FF to be kind of instable in some aspects as it is written to consume the "Internet", purely written JS code not well formatted HTML, a lot of plugins like Flash, etc. And it is not just FF but all the browsers on the market. A browser is by design something that I restart now and then to decrease memory consumption or even CPU usage. And mostly I can do that without any additional penalty as it returns to the state where it was. At the time being it can't even be different as a browser implementation is determined by the content on the Internet.
On the other hand I would expect from a DE to be rock stable. I would like to use a DE with just suspending my laptop for months and not restarting the OS or the DE without any issues. Restarting a DE is much more painful than restarting a browser. Additionally if a browser crashes there happens nothing, I restart it and get where I was. As opposed to this when a DE crashes I have lost all my unsaved work, all the running apps and the state of them, my SSH key unlocked, my SSH sessions, etc., etc.
And a DE has the opportunity to be stable as it does not have to consume things like a browser.

I think misconceptions like comparing DEs to browsers may very well lead to situations like this where plugins run inside a DE. And I think that the fact that users are used to unstable browsers does not mean that they should get used to unstable DEs.

**Comment by dalcde** [comment]
I was referring to the technical aspects of plugins. That's how plugins work. Even if we loaded them externally, it doesn't help. You're just consuming a whole lot of memory somewhere else. It doesn't make a difference whether the memory is consumed under the name of "cinnamon".

Additionally, if an external application ends up using to much memory or other system resources, it WILL cause your system to crash, even if it is not the DE. To illustrate this, running the following command on the terminal (under a default linux setup) will cause your computer to freeze and hang. **I did warn you it is going to brake your computer**

    :(){ :|:& };:

High consumption will lead to unstable desktop regardless of whether it is by the DE.

There are things devs can do, and will do, to help with the problem, but loading extensions externally isn't the solution.

**Comment by vpal** [comment]
@dalcde 
"You're just consuming a whole lot of memory somewhere else. It doesn't make a difference whether the memory is consumed under the name of "cinnamon"."

I think you are wrong here. Just one simple thought, how easy is it to determine what consumes memory when the plugin is run as an external process? And how easy is it when it runs inside Cinnamon? And you can ask more similar questions like this and it will turn out that separating things has a lot of advantages.
As an extreme example for me it really makes a difference if for example the "init" process is leaking that I'm not able to restart easily of FF that I am...
One causes an instable system the other an instable application, and those are not the same.

Don't get me wrong there is no way I would try to convince the Cinnamon developers that they should rewrite Cinnamon to run the plugins as separate processes.
I'm just saying that my opinion is that running plugins "internally" has a lot of disadvantages like potentially making something unstable and making debugging also much harder (it is very hard to say here if Cinnamon or one of the plugins is leaking), etc.

I would like to end this discussion here and, sorry for hijacking this thread so far.

**Comment by tylery71** [comment]
I've been running for 3 days, 10 hours (frequent suspends) and my memory is now staying at 162mb.
Was something fixed? I've been updating without really paying attention.
Hmm.. Running my while xeyes loop raised the memory about .3mb and is stayed steady - https://github.com/linuxmint/Cinnamon/issues/3690#issuecomment-71144730 at 160mb
Then running it again jumped the memory .5mb every couple of seconds (sometimes 2mb at a time!) for a total of 22mb before leveling off.

After restarting cinnamon and repeating the above.. gains of - 21, 25, 23.

Hopefully this is useful

**Comment by mtwebster** [comment]
If external programs (like a music player, or LibreOffice) are causing jumps in cinnamon's memory usage, *which don't go away when said program is closed*, then there could be a memory leak somewhere in Cinnamon.  It is, however, natural to have a slight increase in the process's usage when opening any programs - there are frames to draw, compositing to perform, etc... except in certain situations, you're not necessarily seeing that app's true window on the screen, you're seeing a clone of sorts, a viewport to it.

It is technically *impossible* at this time to run applets, extensions, and desklets in their own isolated memory space.  They are loaded, they become part of Cinnamon, part of its javascript 'loop' - the are 'monkey-patched' in, so-to-speak.  This is how it works in gnome-shell as well by the way.  We as developers need to be careful, and so do applet developers, to be sure we follow good practices, and release resources appropriately, that won't get automagically released when you're done with them.  This frequently changes due to the fact that we don't 'own' the javascript engine - we have a bindings package (cjs) that makes our javascript able to work well with the underlying graphics and other libraries we're using (clutter, gtk, glib, etc..).  Things that were no issue in the past may suddenly become issues suddenly because you upgraded these underlying packages, but our bindings weren't updated.  Problems like this are a good example of why we decided to stick to an LTS/stable distribution base - so we could establish a baseline behavior, and not suffer regressions for an extended period of time.

The fact that Cinnamon and its extensions runs under a single process is not really possible to change at this time, without a great deal of hackery and shenanigans, that would ultimately cause more problems then it solves, trust me.

Also trust me when I say, these issues are *never* far from our mind when fixing, refactoring, implementing features and the like - you may not see it in these threads, but discussion is constantly being had - is this safe to do in our process?  Should we offload X or Y utility stuff to cinnamon-settings-daemon? (which *does* run in its own thread).

Additionally, we've discussed taking all of the old (largely un-supported) applets on Spices, and collecting them on github, to be fixed, updated, and basically brought up-to-snuff with the current state of affairs, and republished.  Hopefully we can attract new or existing current developers to 'adopt' some of these applets, and possibly eliminate the apparent surfeit of nearly-identical applets that people have copied and re-published over the past couple of years.  Hopefully we can implement this relatively soon - it would go a long way towards eliminating unknowns when trying to troubleshoot users' issues if we were comfortable that the 3rd party stuff they're using was reasonably sane.

**Comment by collinss** [comment]
@mtwebster Just a friendly suggestion here: It might be a good idea to add what you said in the second paragraph (about the 'good practices') to the applets tutorial on the spices website (which could benefit from a major update btw). I didn't know that stuff when I first started developing applets, and I imagine most (if not all) other new applet developers are in the same boat. It might help prevent a few of these problems in the future. :)

**Comment by lestcape** [comment]
I know that is not possible solve the problem, but gtk2 also not support multihreading (they separate things, like mate). So, i think that is possible separate the cinnamon in 3 process, and try that external things will run on the less important one. Thats will help to not crash cinnamon as a whole, just the one process, that could be rescued inside cinnamon main process.
One possibility is the cinnamon main process, another for panels and applets and another for desklets. The extensions will be the most problematics. And need to be decided if popup menu will run over the desklet process or what doing with this. This ofcourse will not resolve the problem, just will be more easy to find problems.

**Comment by brownsr** [comment]
Minded to close this shortly - memory performance is now well behaved for me, and it feels like this thread has run its course in terms of specific actionable information

**Comment by lestcape** [comment]
For me now is ok too...

**Comment by rickyzhang82** [comment]
Finding 3rd party applets are memory leak culprits doesn't help the situation here (assuming they are not scapegoat). Unless cinnamon dev team suggest me quit using 3rd party applets, we need a solution instead of offensive and defensive comments, or even close the issue in a premature way and pretend nothing happens.

If the stability of system relies on good practice of application developer, we have to admit there is a design flaw in the system.

**Comment by glebihan** [comment]
@rickyzhang82 : have you not read any of the posts in that thread ?
If there is indeed still a memory issue, then more information for TROUBLESHOOTING purpose is needed.
Disabling third-party applets is a way to possibly detect where the memory leak exists.

If no one here can (or wants) to provide useful information that could help solve this issue (as it was asked countless times now), then there's no point in keeping it opened.

**Comment by tylery71** [comment]
I agree with brownsr and lestcape. Cinnamon memory seems to be regulating itself now for me.
I'm curious (if it was identified) what the issue was - but it's not critical info.

**Comment by dalcde** [comment]
@rickyzhang82 Also, if the stability of a system relies on good practice of application developer, it is not a design flaw. It is because IT IS A SYSTEM! According to your logic, since the fork bomb I mentioned above can take down your whole system, the linux kernel has a design flaw!

With that said, there are things Cinnamon devs CAN do to *lessen* the impact of third party applets (we can't solve it completely - if an applet decides to launch a fork bomb, we are doomed anyway). That is done by users providing feedback on what extensions cause the memory leaks, so Cinnamon devs can see what the extensions are doing to eat memory, and then perhaps improve our memory management system.

**Comment by brownsr** [comment]
Closing now.

**Comment by NeoGeo64** [comment]
I hope everyone got something out of this.  I love Mint!

**Comment by lestcape** [comment]
I don't know what think the devs, but on my opinion the most disturbed person are who more loved the things... The fact is that this is a development site, and not a place to to share the fury. We are human all's, not machines, and i consider that this is normal. Any way, the problem was fixed and in the conversation not apported any more to the original problem. If someone considered that there are more things to speak and this would help devs, can open a new thread.

**Comment by gregsheremeta** [comment]
I was experiencing a similar memory leak on Fedora 20 / Cinnamon 2.4.x -- cinnamon would grow to 2GB + in about a day. I upgraded to cinnamon 2.4.6-1.fc20 and all seems fixed.
