### ISSUE TITLE
[Bug] Desklets are stealing mouse input when windows are covering them

### ISSUE THREAD

**Issue by DrOptix** [linuxmint/cinnamon#3701]
I'm not sure what version of Cinnamon I'm using at the moment, but I think it is 2.4.

To reproduce try to follow the steps listed below:
1. Open an app, for me it will be Leafpad
2. Move it over notes or weather desklet (i think any desklet will do)
3. Press WinKey + D to hide all windows
4. go and edit a note, click on weather desklet, anything that will give focus to the desklet
5. WinKey + D to rise the windows
6. Try and move the window or click a button or something. If the titlebar or a control from the window is located right above the desklet then the window will ignore the events, but the desklet will process them.

Most comonly I encountered this bug while dragging and dropping files with nemo from one folder to another. Sometimes instead of dragging the selected folders I was dragging a desklet.

I'll try to add an explanatory video/gif when I go home.

**Comment by dalcde** [comment]
Does it still occur with 2.4.8/Cinnamon git?

**Comment by mchladek** [comment]
I'm experiencing the same on Cinnamon 2.6.13 on Arch, although hiding windows and giving the desklet focus first (i.e., steps 3–5 of original commenter's report) doesn't need to be done for this bug to show for me.

It seems related to issue #3306 in that, for me, it only affects Gnome applications or applications using client-side decorations.

To reproduce bug:

1. Drag a window of a Gnome 3 application (e.g., Gedit) or application using client-side decorations (e.g., Corebird) over a desklet (I've tested with both the weather and clock desklets) so that the window buttons are over the desklet.
2. With the application's window still on top and in focus, try any of the following in the area where the window border overlaps with the desklet:
     * Click and drag the window border
     * Click the window border edge to resize the window
     * Click the window close button
3. The window will not register any of those clicks and instead register it as a click (and drag) on the desklet instead.

**Comment by Vahan86** [comment]
Is this still an issue in Cinnamon 3.0?

**Comment by Odyseus** [comment]
Hello, @Vahan86. I can reproduce the behaviour described by @mchladek in Cinnamon 3.0.7 stable and the Cinnamon version installed from this repository. In addition, desklets randomly get stuck to the mouse cursor (as if I clicked and started dragging the desklet) when hovering the cursor over the panel, even when the desktop is covered by a maximized window. I don't know if both issues are related. And I can't trigger the behaviour described by me on demand because is very random and it triggers when the mouse cursor approaches to the bottom panel. I can say that it happened always with the same desklet ([Cinnamon Developer's Tools](https://cinnamon-spices.linuxmint.com/desklets/view/17)) in it's expanded state, covering most of the screen.

**Comment by JosephMcc** [comment]
Have you had it happen at all with any other desklet? Curious if this is an issue with a particular desklet or with Cinnamon itself.

**Comment by Odyseus** [comment]
@JosephMcc: Sorry for not being more specific. Yes, the behaviour described by @mchladekit happens with any desklet in all of my 3 Cinnamon systems. In fact, clicking and dragging a Gnome 3 application it's almost impossible if I try to do it with a desklet directly behind the border window.

I mentioned the other issue with that specific desklet just to give one more possible clue to the one/s that may try to fix this issue.

**Comment by lestcape** [comment]
Same happens for me. This probably is something relate with Chrome https://github.com/linuxmint/Cinnamon/blob/d49dc4d3fe734a26bea1b5119a53770e57e73c76/js/ui/desklet.js#L196

**Comment by Vahan86** [comment]
@DrOptix, is this still an issue in Cinnamon 4.2

**Comment by Vahan86** [comment]
@icarter09, can we close this issue since there is no response from OP?

**Comment by papadakospan** [comment]
It's still an issue for me. Can confirm with notes@schorschii and (at least) Firefox

**Comment by JpegXguy** [comment]
It's still an issue for me. Can confirm with notes@schorschii and (at least) Firefox

**Comment by robbie888** [comment]
I have this issue also Cinnamon 4.8.6 using firefox. It happens with 2 different desklets
