### ISSUE TITLE
Toggle maximise button, in 'High Contrast' window borders, too dark in certain windows on mouseover

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#3705]
So dark, in that, that it is almost just a square of black. I seem to recall this affecting all windows; now - with the nightly version of Cinnamon, it affects only certain windows, including Firefox ('Firefox 33 for Linux Mint mint - 1.0'). Wine windows are affected too. So is Gedit. But, e.g. terminal and settings windows are not.

PS: Why use the high contrast borders at all? Because I find that the 'Mint-X' border icons are insufficiently visible.

My system: Linux Mint 17, 64-bit, Cinnamon 2.4.5, on a Dell Latitude D830 laptop with integrated Intel graphics. System runs well in other respects.

**Comment by dalcde** [comment]
Considering that the High Contrast theme is not maintained by Cinnamon, and doesn't even exist at all in 3.16, closing.

**Comment by ACinnamonUserInUK** [comment]
dalcde: please advise me where I should report this problem, then. Otherwise the situation is this: I've taken the trouble to report the problem (a problem that makes Cinnamon look unpolished); others will find this page via search engines; and the result is . . nothing.

**Comment by CottonEaster** [comment]
Recently I acquired a laptop that, due to its deficiencies (or possibly Mint's, or a combination) has tiny window buttons under most themes. One of the few themes that gets around this problem is . . the high contrast theme - in which, as reported, one of the buttons does not work properly. People with visual impairment will be affected by this more than I am. Do please advise.
