### ISSUE TITLE
Make SUPER+L lock the session, not open the Cinnamon Debugger

### ISSUE THREAD

**Issue by Moonbase59** [linuxmint/Cinnamon#3741]
I was referred here from the [Linux Mint Community »Ideas« page](http://community.linuxmint.com/idea/view/5386), so I re-post my idea here:

Ex-Windows users might be trained to use WINDOWS+E to invoke the »Windows Explorer«, WINDOWS+R to »Run« something (like Alt+F2), and WINDOWS+L to »Lock« the session.

SUPER+E we now got with 17.1—it invokes Nemo.

Why not use SUPER+L to lock the screen instead of invoking the Cinnamon Debugger? Ex Windows users (and I converted several to Linux Mint) tend to get extremely confused when they are used to quick-lock their screen by WINDOWS+L … and Melange pops up.

I'm not proposing to make Linux Mint emulate Windows at all cost—but this one could just make the transition even easier, for some. If you're working (at a client, or in your workplace), you might get called away and/or have to leave your workplace and it's just SO convenient just to be able to hit SUPER+L to lock your screen quickly.

Think this feasible?

**Comment by devcsrj** [comment]
+1 The debugger isn't really something I'd normally need.

**Comment by Nandox7** [comment]
+1 Is there a way to disable Melange at all?
Quitting it doesn't work as it start next time I press Super + L

**Comment by mtwebster** [comment]
Just clear out the keybinding for the debugger - Keyboard shortcuts, General->Troubleshooting - then you can reassign it elsewhere if you want.

**Comment by rrooij** [comment]
I agree with this issue. Most Windows users are used to press Super + L  for locking. The debugger causes confusion.

**Comment by Topperfalkon** [comment]
I think @collinss's idea is a good one, about keyboard "themes" (more properly keybinding themes I think, as keyboard suggests different layouts like Dvorak, etc).

Also agree that the main issue here probably should be to remove the default debugger keybinding from Super + L, optionally setting a different one.

**Comment by fazy** [comment]
I'm currently running the Mint desktop inside VMWare on a Windows host. Locking the Windows host with Windows ("super") + L also brings up the debugger.

As discussed above, super+L to lock would be a good choice for attracting/retaining Windows users. Seeing as most of the look and feel and shortcuts are based on Windows anyway, it wouldn't be an extra big step.

Personally I already know about and don't mind ctrl+alt+L, but for such a common action super+L would be a good (default) addition.

Anyway I'm mostly posting this reply because while my use case (running in VMWare) is probably uncommon, I did find usability issues in trying to remove the unwanted shortcut:

* Super+L brings up a window with no title bar or close button.
* The name is actually on the right "Melange - Cinnamon Debugger" (underlined, but not actually a hyperlink or anything - even outside of a web browser, I wanted to click it to see if it offers anything helpful)
* "Toggle shortcut: <Super>l" is in italics, and at first the `l` looks like a `/`. There is no + sign as is common with describing shortcuts (see almost everyone's post above), and it's not clear how it relates to the Actions dropdown (eventually I concluded it's not, but the apparent / made me think there was a relationship).
* When trying to remove the shortcut, there is no search option in the shortcuts setting, and I could find no mention of "Melange - Cinnamon Debugger".

Thanks to this issue, I was able to learn that "Toggle Looking Glass" is the action that's bringing up the debugger, and from there I can easily change it. So, in its current state it is usable only in the sense that you have to Google it. ;)

**Comment by xiic** [comment]
The best option would IMHO be to change the default Cinnamon Debugger shortcut to something different (e.g. Super+F12, inspired by the Browser debugger tools) and leave Super+L unassigned.

I came here from google, because after locking Windows my Cinnamon-VM always had this "strange" window at the top...

**Comment by jpickwell** [comment]
Like @fazy and @xiic, I also run Mint 17.3 in a VM on a Windows Host (I require Windows for VS). Unassigning the Super+L keybinding is a nice compromise.

**Comment by slurdge** [comment]
@fazy @xiic @jpickwell same here. Had a hard time finding where this popup was coming from.
I think that such a common binding shouldn't invoke a debugger. I think Super+F12 is a nice choice.

**Comment by blackomegax** [comment]
+1

Came from Ubuntu where it's been the default for lock for years. Easier to hit than ctl alt l.

Debugger makes no sense on "L".

**Comment by riseremi** [comment]
+1, it confuses me.

**Comment by mvsoder** [comment]
I also support moving the debugger hot key off of Super-L. I'm in the same position as others having to use multiple operating systems and a consistent key binding, by default, would be helpful. For me, it's a small security issue since locking my screen is a good security practice and it catches me off-guard when I try to lock the screen and I end up with the Cinnamon debugger.

**Comment by metiscus** [comment]
Perhaps a better long term solution would be to present the user with a choice of key bindings on first start that are either the typical Linux solution or closer to those on Windows, that way it helps new users acclimate without alienating existing users.

**Comment by leigh123linux** [comment]
Closed as 'wont fix'.

**Comment by slawomirfurtak** [comment]
In my system (Mint 18.2) there is settings for Melange shortcut but with mysterious name: 
"Toggle Looking Glass". Maybe should we change that name to "Melange - Cinnamon Debbuger"?
![toggle looking glass](https://user-images.githubusercontent.com/28731877/30743159-ca64d616-9f9c-11e7-9fff-e8e41f819899.png)

**Comment by nigels-com** [comment]
Screen locking can be important.  I _need_ the binding to match Unity and Windows, for consistency.
