### ISSUE TITLE
Add "Lock position" option to Cinnamon desklets

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/cinnamon#3767]
I suggest a "Lock position" option to Cinnamon desklets, because occasionallywe trap on them and drag theme around the desktop.

**Comment by Phssthp0k** [comment]
> I suggest a "Lock position" option to Cinnamon desklets, because occasionallywe trap on them and drag theme around the desktop.

2022 and imho we really need a lock...or at least they could be moved only when being edted. Sometimes they god dragged out of screen and it's really a messy job to bring 'em back!

**Comment by SuperJumpBros** [comment]
uh... bump? i'm adding desklets to my desktop and already facing issues with them being dragged, literallly through my maximized windows.. and i don't really care about fixing that bug itself, i'd rather be able to just lock them in place, because i feel it'd be easier to include a feature like the taskbar locking rather then waiting for that to get fixed! please consider adding this feature, it'd be great for all of us!

**Comment by njdf18** [comment]
I really need this feature! My desklets always move to next display when I connect my laptop to any external one.

**Comment by mtwebster** [comment]
I did this a few weeks ago, I'll see if I can get it merged.
