### ISSUE TITLE
An Iface from applets, to control popup menus on a different code of cjs (like mate desktop).

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#3773]
Please take this as a feature request.

I think will be nice to do an Iface from GDBus for "general" applets (better say a basic API from applets) to export some actions that can be used on a non cjs code.

Like an important example will be the mintMenu. We can implement a GDBus client that can consume the API that we export on the applet, like an equivalent to the Mate applet API. So, mintmenu would be displayed inside cinnamon as well. Also will be possible the integration of several different menus that can consume the Mate API with only minimal changes. After read the mintmenu code i know that this will be possible with a few changes. This could be resolved some users requests and also reuse the excellent work on MintMenu.

I try to make a "Configurable Menu" with several features of MintMenu, but of course it not the same, and i don´t know how many time i can maintain the project. But i know that several user want to have a menu with more options, like the mintmenu on cinnamon, so, why not?

Thanks.

**Comment by dalcde** [comment]
This sound technically feasible, but I doubt any developer would actually work on it. One reason is that mate applets will look terribly out of place since they cannot use St and many other cinnamon features.

I think the sensible thing to do is to try to implement this as a third-party applet. If it works well, you can create a pr to include it in Cinnamon. afaik, none of these have to be implemented inside Cinnamon itself but can be done inside an individual applet.

Also, I'm not sure if it's worth all the hassle. If all you want to do is to show the mint menu, it might be possible to simply make an applet that calls an external application with certain parameters (eg. location of applet) and asks the external application to draw at the right place. Using dbus seems like overkill imo.

**Comment by lestcape** [comment]
Yes, you have right on it, what i request is simple (is not merge different GUI). Is just an applet that can call the mintmenu code to be showed on an specific place, without use the cinnamon popup menu api, and again yes, could be simple call a program, but, as mint is also who development the mintmenu, is more factible if the cinnamon part made the same as mate, to not requiere a big change in the mintmenu and make the possibility to reuse this for another different mate applet, without need to modify again the other applet :)

**Comment by lestcape** [comment]
I think we can do more than a simple called.
https://people.gnome.org/~gcampagna/docs/GtkClutter-1.0/GtkClutter.Actor.html

We can have an introspection library, or as a part of gi.Cinnamon a way to loaded mate applet plugins and shared the gtk widget with cinnamon as a clutter actor, some thing similar of what occurs with the current systray api or what occurs with windows actors....
