### ISSUE TITLE
tiny calender reminder for google-calender (or others)

### ISSUE THREAD

**Issue by pneot** [linuxmint/Cinnamon#3799]
Hi,

I'm no programmer, but I hope, that some of you are, and are willing to create my wish.

I'm dreaming of a tiny calender-applet, which runs mostly in the menu-bar (down right ... Linux Mint Rebecca), where the existing calender applets are running.

The specialty about this applet would be, not only to show the actual time and date, but to load the calender from an other application or web-interface (xml, ical, exchange,.....) to be a trustworthy reminder of upcoming events, even if I'm not starting my mailprogram or the webinterface of google-calender.

It's not really necessary to build a completely standalone calender-software - it's enough if it could read other calenders and works as a reminder (pop-up) with a redirection-function to an other calendersoftware or web-interface, depending on the settings chosen.

I hope someone of you likes my dream of this little gadget, and makes my dream come true.

thanks

**Comment by ManIVIctorious** [comment]
An interaction with the evolution calender would be awesome, IMO the calendar applet is quite useless as it is now

**Comment by lestcape** [comment]
I not consider this as a good thing, because Cinnamon need to depend of external programs and there are some alternatives. To, to satisfy the user preference could be complex in this context. 

What i consider that could be a good thing, will be an external applet to do that. Maybe this could be implemented as dependency of if this ability is present on the system or not. In case of not find the characteristics, will be use the current cinnamon calendar.

I thought about doing this long time ago, but really as i say it's difficult satisfy all user request, because they want to use differents calendar types.

Here some people speak about the same things. 
http://forums.linuxmint.com/viewtopic.php?f=47&t=152059

I want to know if there are an standar DBus for calendar, in this case could be try to implemented a Dbus client, without know the default calendar.

**Comment by collinss** [comment]
There was an attempt to do something like that a while ago (see https://github.com/linuxmint/Cinnamon/pull/1850). IIRC, it wasn't quite finished, so it never got merged, but it might be a good place to start if someone wanted to tackle this. I would offer to look into it, but I have a lot going on right now, and the computer I use to program on is basically out of commission until I can resolve some hardware issues.

**Comment by lestcape** [comment]
Yes @collinss good point. There are some request to sticky notes to be more flexible, with the possibility to show alarms, programing message on the calendar. At some point this will enhance the importance of the notes and i will like to do that, but like i say this will be complex at some point where satisfy the user preference, will be difficult.

**Comment by lestcape** [comment]
After read and analize some things of the current stage of art of online calendar, i can discard https://github.com/linuxmint/Cinnamon/pull/1850 as a good implementation of a calendar api, due the fact that depend of the iface of google calendar. The applet also execute a call to spaw commandline in syncronized mode, that is well know as problematic on cinnamon. I don't like how is create the settings, on a separate file of current settings-schema.json and don't see yet and a user-frendly implemetation. 

As an opposite, exist some standard protocols, that can be used to implement a connection for calendars, as can be see here:
http://en.wikipedia.org/wiki/CalDAV

As a good reference, could be this implementation of the calendar client protocols on js:
https://github.com/LordEidi/fennel

**Comment by dalcde** [comment]
#2720
