### ISSUE TITLE
Feature Request: Extention checker.

### ISSUE THREAD

**Issue by ringo32** [linuxmint/Cinnamon#3821]
Im curius if is this possible. especially for upstream,

if Cinnamon get updated..to a newer version, like thunderbird when its upgraded to a new version a compatibility checker if a extention is stil ok.

Extentions are always a weak spot when all get up.

**Comment by anandrkris** [comment]
I suppose, this is already in place? Problematic extensions, if they failed to load, will be disabled automatically.
https://github.com/linuxmint/Cinnamon/commit/c3cc4c652d69c3d214b6ece468fd898a5f6fc550

**Comment by lestcape** [comment]
I think that as a complete solution here, will be allow the users to report when they found a broke extension, then some one can check if this is true(or automatically added to a problematic list), when we have more than 3 report of the same extension on the same cinnamon version. Finally this information could be merged on the index.json that we download from spices and is located on:

~/.cinnamon/spices.cache/ and then the folder of the extension type.

The cinnamon settings could read this and take a decision if report a problem too the final user, if send an email to the author, and also if can be added automatically the current cinnamon version to the "allowed cinnamon version" on the extension list from metadata.json or whatever could be the decision here.

**Comment by lestcape** [comment]
@ringo32 https://github.com/lestcape/Cinnamon-Installer

**Comment by dalcde** [comment]
Extensions automatically won't load if they are not compatible with the current version. Usually you will have to upgrade the extension when a new Cinnamon verion comes out, since extensions cannot claim to support not-yet-released Cinnamon versions! In 2.6 you will be able to force-load an extension even if it does not support your cinnamon version.

We don't have a huge progress bar telling you we are doing version checks, but we are doing it under the hood. I don't think it is would be a good idea to automatically update the extension like thunderbird since the choice of upgrading should always be yours (and the extensions don't necessarily come from cinnamon-spices).
