### ISSUE TITLE
applets crash

### ISSUE THREAD

**Issue by timmie** [linuxmint/Cinnamon#3829]
I use the latest nightly builds.

Adding applets does not work:
"There was a problem loading the selected item, and it has been disabled.

Check your system log and the Cinnamon LookingGlass log for any issues.
Please contact the developer.
"
Which log do you need so solve this issue.

**Comment by pixunil** [comment]
You can find the logs in `~/.xsession-errors` and `~/.cinnamon/glass.log`.

With which applets does it happen? Cinnamon applets or 3rd-party applets?

**Comment by tp0** [comment]
If 3rd party, then isn't just just because the applets have been updated and made compatible with the latest Cinnamon?

I get this for example with the following applets:
http://cinnamon-spices.linuxmint.com/applets/view/12
http://cinnamon-spices.linuxmint.com/applets/view/34
http://cinnamon-spices.linuxmint.com/applets/view/88

Is this solvable by some quick edit, i.e. raising version number in some applet file to fool DE think it is compatible?

**Comment by dalcde** [comment]
Have you installed gir1.2-gtop-2.0?

**Comment by tp0** [comment]
@dalcde: Well, that solved my issue. Did not read those descriptions because I initially did the installation from the applet GUI only.

**Comment by anandrkris** [comment]
@tp0 - On incompatible applets -
http://blog.linuxmint.com/?p=2764#comment-115083 I raised a point on incompatible apps clogging spices and had discussion with development team as well. We discussed about having something a "Report Broken" that would blacklist the apps based on some score. No concrete decisions made but it was discussed.
Ultimately it boils applet / desklet developers maintaining it and usually any arch changes are announced at segfault blog in advance for developers to update their code for upcoming Cinnamon release.
