### ISSUE TITLE
smb:// shortcut

### ISSUE THREAD

**Issue by dburanen** [linuxmint/Cinnamon#3833]
My videos live on a NAS that I access via smb://.  On Windows, we just create a shortcut to \server\foldershare and we're done.  That same ability in Nemo would be fantastic!

I'd love to be able to delete my /home/user/Music and then create a shortcut to an smb://server/Music that nemo understands.  I've created shortcuts to the smb shares in the favorites pane of nemo, but it would be slick to just drop them in the home folder, desktop, etc.

This "shortcut" that you put in your home folder or desktop or wherever could obviously be useful for other locations via other protocols such as ssh:// sftp:// ftp://

**Comment by gritty-gitty** [comment]
Within a file manager, a *folder* differs from files in its default associated application which is the file manager itself. And *remote folders* differ from local ones in that a network connection must be established to them somehow. This is normally done again by the file manager which handles non-web file server protocols by itself like a browser does for web protocols. Basically, it’s the same *action* as the one called “Connect to Server…” in the File menu in *nemo*. Thus it’s an action, therefore it can be assigned to a **launcher** in any folder with a command like this: nemo smb://server/Music.

With that being said, launchers are second-class citizens in almost all graphical interfaces: you cannot drag them around and use them as freely as you would want to. Certainly not as freely as a *local* folder which is *linked* to an existing, *static* destination — which, in turn, would be exactly what you wanted.

In order to achieve this, you should let the system do *nemo*’s job of opening the network connection on boot or login, so the remote folder would appear to be static to *nemo*, so that you could link it in anywhere you want… (This way, even the Windows share itself could be statically linked, which otherwise couldn’t be done within *nemo* for a whole share, only for subfolders of it.) Here is a link about [the procedure to follow](https://wiki.ubuntu.com/MountWindowsSharesPermanently) for this.

**Comment by tylery71** [comment]
This is more of a Nemo issue, not a Cinnamon one.
https://github.com/linuxmint/nemo

You can symlink your directories to the place nemo creates when a connection is made.
After connecting using the connect to server, look in this directory:
/run/user/1000/gvfs/
For my ssh server it looks a little like this:
/run/user/1000/gvfs/sftp\:host=ipaddr/
sym link Music/ like this
ln -s /run/user/1000/gvfs/sftp\:host=ipaddr/home/myusername/Music/ ~/Music 

I haven't tested the above & it will fail once the connection is lost. (It may or may not recreate a new connection)

**Comment by leigh123linux** [comment]
@dburanen 

Please refile the request  against nemo instead.
