### ISSUE TITLE
Everything freezes when unmounting USB storage

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/Cinnamon#3864]
Hello,

I'm running Cinnamon 2.4 on openSUSE 13.2. I'm experiencing a fairly major problem where everything running under Cinnamon freezes when unmounting USB storage devices. I'm not sure exactly which Cinnamon component is responsible, so I'm just filing this bug under Cinnamon.

I've been seeing this bug fairly consistently, although it doesn't occur every time. When unmounting a USB storage device with the Nemo eject icon, the entire interface often stops responding with the exception of the mouse. The Cinnamon panel, start menu, window controls, and the the applications themselves all stop responding, and the system tray icons appear as black squares. This gives the impression that the entire system has locked up and would probably make most users hard-reset the computer. I wait around for about 15 or 20 seconds, and everything comes back to life. The recovery of the system seems to correspond with me physically unplugging the USB device. Again, this doesn't happen every time, but it does happen consistently more than 50% of the time.

I have seen this happen with different USB thumbdrives, my SD card reader, and Android devices mounted as USB mass storage devices, all of which I believe are formatted FAT32.

I would classify this a serious bug, since it gives the appearance that the entire system is irrecoverably frozen.

Thanks for looking into this!

**Comment by Tobi042** [comment]
I can reproduce the issue on Arch Linux with Cinnamon 2.4.6, not only when unmounting USB devices (not always USB 3.0 devices, but the port is 3.0), but also when mounting them. Here too, the issue does not happen 100% of the time but in about 50% of the cases. The solution for me is changing to a virtual console and restarting my display manager.

**Comment by shred** [comment]
The same on Fedora 21 with Cinnamon 2.4.6. As soon as I mount a device (USB, but also network shares), the screen completely freezes except of the mouse pointer. I have to switch to text console and SIGKILL the "cinnamon --replace" process to recover my session (SIGTERM is not sufficient). When I return to the X session, sometimes Nemo is the next thing that crashes.

The issue does not always happen, but quite often.

**Comment by leigh123linux** [comment]
@shred 

I don't see this issue much in fedora, perhaps once every month or two and I mount USB, USB3 and network mounts  (NFS and SSHFS) many times daily.

**Comment by shred** [comment]
@leigh123linux Okay, maybe killing is not necessary, but I am just too impatient to wait a minute. :) However it occurs frequently on two F21 systems I use.

**Comment by Tobi042** [comment]
I recently installed Debian Jessie on the same machine that had the problem with Arch Linux and under Debian Jessie with Cinnamon 2.2.16, the problem doesn't seem to occur.

**Comment by freed00m** [comment]
Cinnamon 2.4.6
I have the same issue.

Not just unnmounting USBs but also unnmounting SSH tunneled servers.

Cinnamon just freezes and I am unnable to restart it via anything. Ctrl+f2 r doesn't work. And neither form tty login cinnamon --replace on exported display. I have to hard reboot :((

---------------------------------System specs--------------------------------------------------------------
Processor : 4x AMD A8-4500M APU with Radeon(tm) HD Graphics
Operating System : Linux Mint 17.1 Rebecca (cinnamon)
OpenGL Renderer : AMD Radeon HD 7640G
X11 Vendor : The X.Org Foundation v1.15.1
Kernel : Linux 3.13.0-46-generic (x86_64)

**Comment by sb56637** [comment]
Any way to get the developers' attention on this? It's a pretty serious bug.

**Comment by collinss** [comment]
I'm pretty sure they already know about. I'm pretty sure they read every issue here, even if they don't always have time to respond.

**Comment by sb56637** [comment]
I just noticed that @freed00m reported this bug with Linux Mint 17.1 Cinnamon, so apparently it's not just limited to non-Mint systems as I originally suspected.

**Comment by freed00m** [comment]
cinnamon-session[2058]: CRITICAL: We failed, but the fail whale is dead. Sorry.... 
Like what the hell this just mean. :D This type of messages leaves me clue less.

**Comment by kugel-** [comment]
I can confirm this bug, it happens since quite while. Please fix, it's really bad

**Comment by sb56637** [comment]
I now think this bug is Nemo related. I even had it happen when opening files from a local folder on my desktop. Should I re-create this bug under the Nemo sub-project?

In any case, the entire Cinnamon interface freezes and the background of the system tray items turns black like this:
![screenshot from 2015-01-30 21 52 59](https://cloud.githubusercontent.com/assets/2692138/6563489/7f7d8a8e-c66f-11e4-9560-9287fbf58888.png)
Additionally, when this bug occurs, it sometimes loses the desktop wallpaper selection, which turns black, and forces me to re-select my wallpaper.

**Comment by shred** [comment]
I am not sure if this is Nemo related. Yesterday the desktop froze again (after inserting a CD). I first killed Nemo, but it didn't help. The desktop recovered after I sigkilled the cinnamon process.

**Comment by sb56637** [comment]
@shred Thanks for mentioning your use case. To me it does sound like Nemo, because it usually launches a "What do I do?" dialog upon inserting removable media. And how did you kill Nemo while your interface was frozen? SSH or virtual console?

**Comment by gmehn** [comment]
Same here, for a couple of months: inserting a USB/SD causes Cinnamon to freeze (mouse responds, nothing else). I can ctrl-alt-f1 to a terminal and reboot/restart the dm, but restarts the entire session.

**Comment by sb56637** [comment]
On openSUSE I downgraded Nemo to 2.2.4, which seems to have fixed both this freezing bug, as well as resolve a *HUGE* memory leak that was making Nemo use 2GB of RAM. 

So this is definitely a Nemo bug. Is there any way to move this bug into the Nemo subproject?

**Comment by sb56637** [comment]
Sorry to report that the Nemo 2.2.4 downgrade doesn't fix anything for me after all.

**Comment by clefebvre** [comment]
Can you give us more info on what fails exactly? Do you see anything in syslog, dmesg? Can you isolate the component responsible for this? (i.e. try to run cinnamon without cinnamon-settings-daemon for instance, and without nemo, to see if it's related to them or to cinnamon itself)..

**Comment by kugel-** [comment]
I'd like to add that the issue title should be updated. It also happens at mounting, and due to automount normally as soon as you insert a USB stick everything is locked up (the kill -9 cinnamon-session trick in a virtual terminal helps for me)

**Comment by mtwebster** [comment]
Could I get anyone experiencing this to try the steps in https://github.com/linuxmint/Cinnamon/wiki/How-to-use-GDB-to-gather-debug-information-on-a-program under 'Debugging Cinnamon'

Be sure to install debug packages first: 
`sudo apt-get install gnome-dbg nemo-dbg cinnamon-dbg muffin-dbg`

You'll only be able to do this if you have another PC (or smartphone/tablet) to log in from via ssh, but I'd love to know what Cinnamon is hanging on when this freeze occurs.  Just be sure to break (ctrl-c) the process during the freeze.

Thanks

**Comment by Falconus** [comment]
I'll look into mtwebster's suggestion in a bit, but for now here is my system log. I basically mounted and then "safely removed" my drive, which contains several partitions of which two are encrypted, about ten times until it had the problem (which I have had before). I had the same experience as sb56637 with the black system tray, and I had to reboot my computer because, while the mouse was working, not much else seemed to have been. I don't know how useful this will be, but this should be from the last time I mounted it until I dropped out of the GUI and sent a reboot command.

Here is an excerpt from my syslog.

Apr  2 12:51:50 christopher-laptop udisksd[2276]: Mounted /dev/sdb3 at /media/christopher/Compatible on behalf of uid 1000
Apr  2 12:51:50 christopher-laptop ntfs-3g[7119]: Version 2013.1.13AR.1 external FUSE 29
Apr  2 12:51:50 christopher-laptop ntfs-3g[7119]: Mounted /dev/sdb2 (Read-Write, label "Windows Backup", NTFS 3.1)
Apr  2 12:51:50 christopher-laptop ntfs-3g[7119]: Cmdline options: rw,nosuid,nodev,uhelper=udisks2,uid=1000,gid=1000,dmask=0077,fmask=0177
Apr  2 12:51:50 christopher-laptop ntfs-3g[7119]: Mount options: rw,nosuid,nodev,uhelper=udisks2,allow_other,nonempty,relatime,default_permissions,fsname=/dev/sdb2,blkdev,blksize=4096
Apr  2 12:51:50 christopher-laptop ntfs-3g[7119]: Global ownership and permissions enforced, configuration type 7
Apr  2 12:51:50 christopher-laptop udisksd[2276]: Mounted /dev/sdb2 at /media/christopher/Windows Backup on behalf of uid 1000
Apr  2 12:51:51 christopher-laptop udisksd[2276]: Unlocked LUKS device /dev/sdb1 as /dev/dm-3
Apr  2 12:51:51 christopher-laptop udisksd[2276]: Unlocked LUKS device /dev/sdb4 as /dev/dm-4
Apr  2 12:51:51 christopher-laptop kernel: [ 1141.010697] EXT4-fs (dm-4): mounted filesystem with ordered data mode. Opts: (null)
Apr  2 12:51:51 christopher-laptop udisksd[2276]: Mounted /dev/dm-4 at /media/christopher/Linux Storage on behalf of uid 1000
Apr  2 12:51:52 christopher-laptop kernel: [ 1141.082579] EXT4-fs (dm-3): mounted filesystem with ordered data mode. Opts: (null)
Apr  2 12:51:52 christopher-laptop udisksd[2276]: Mounted /dev/dm-3 at /media/christopher/Linux Backup on behalf of uid 1000
Apr  2 12:52:00 christopher-laptop kernel: [ 1150.002038] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=21404 DF PROTO=TCP SPT=45680 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:52:00 christopher-laptop kernel: [ 1150.002054] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=21404 DF PROTO=TCP SPT=45680 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:52:20 christopher-laptop kernel: [ 1169.712752] [UFW AUDIT] IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:e8:80:2e:e7:75:06:08:00 SRC=10.59.0.38 DST=10.59.0.255 LEN=78 TOS=0x00 PREC=0x00 TTL=128 ID=4334 PROTO=UDP SPT=137 DPT=137 LEN=58 
Apr  2 12:52:20 christopher-laptop kernel: [ 1169.999797] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=57724 DF PROTO=TCP SPT=45700 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:52:28 christopher-laptop kernel: [ 1177.217524] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=157.55.130.174 LEN=159 TOS=0x00 PREC=0x00 TTL=64 ID=60386 DF PROTO=UDP SPT=8211 DPT=40024 LEN=139 
Apr  2 12:52:33 christopher-laptop kernel: [ 1182.909354] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=10.59.0.1 LEN=63 TOS=0x00 PREC=0x00 TTL=64 ID=31355 DF PROTO=UDP SPT=61642 DPT=53 LEN=43 
Apr  2 12:52:33 christopher-laptop kernel: [ 1182.909389] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=10.59.0.1 LEN=63 TOS=0x00 PREC=0x00 TTL=64 ID=31356 DF PROTO=UDP SPT=44580 DPT=53 LEN=43 
Apr  2 12:52:40 christopher-laptop kernel: [ 1189.997314] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=41779 DF PROTO=TCP SPT=45721 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:52:40 christopher-laptop kernel: [ 1189.997331] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=41779 DF PROTO=TCP SPT=45721 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:53:00 christopher-laptop kernel: [ 1209.994990] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=48833 DF PROTO=TCP SPT=45741 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:53:00 christopher-laptop kernel: [ 1209.995007] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=48833 DF PROTO=TCP SPT=45741 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:53:08 christopher-laptop kernel: [ 1217.077876] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=10.59.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=34850 DF PROTO=UDP SPT=7593 DPT=53 LEN=40 
Apr  2 12:53:08 christopher-laptop kernel: [ 1217.500619] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=10.59.0.1 LEN=70 TOS=0x00 PREC=0x00 TTL=64 ID=34925 DF PROTO=UDP SPT=42256 DPT=53 LEN=50 
Apr  2 12:53:20 christopher-laptop kernel: [ 1229.992566] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=57428 DF PROTO=TCP SPT=45761 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:53:20 christopher-laptop kernel: [ 1229.992583] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=57428 DF PROTO=TCP SPT=45761 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:53:23 christopher-laptop kernel: [ 1233.023928] [UFW AUDIT] IN=eth0 OUT= MAC=33:33:00:00:00:fb:3c:07:54:16:a0:2b:86:dd SRC=fe80:0000:0000:0000:3e07:54ff:fe16:a02b DST=ff02:0000:0000:0000:0000:0000:0000:00fb LEN=136 TC=0 HOPLIMIT=255 FLOWLBL=837987 PROTO=UDP SPT=5353 DPT=5353 LEN=96 
Apr  2 12:53:40 christopher-laptop kernel: [ 1249.990194] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=20116 DF PROTO=TCP SPT=45781 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:53:40 christopher-laptop kernel: [ 1249.990211] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=20116 DF PROTO=TCP SPT=45781 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:54:00 christopher-laptop kernel: [ 1269.987832] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=5551 DF PROTO=TCP SPT=45801 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:54:00 christopher-laptop kernel: [ 1269.987850] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=5551 DF PROTO=TCP SPT=45801 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:54:06 christopher-laptop kernel: [ 1275.164235] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=10.59.0.255 LEN=274 TOS=0x00 PREC=0x00 TTL=64 ID=55804 DF PROTO=UDP SPT=138 DPT=138 LEN=254 
Apr  2 12:54:06 christopher-laptop kernel: [ 1275.164268] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=10.59.0.255 LEN=247 TOS=0x00 PREC=0x00 TTL=64 ID=55805 DF PROTO=UDP SPT=138 DPT=138 LEN=227 
Apr  2 12:54:07 christopher-laptop kernel: [ 1276.194248] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=157.55.56.150 LEN=61 TOS=0x00 PREC=0x00 TTL=64 ID=42897 DF PROTO=UDP SPT=8211 DPT=40007 LEN=41 
Apr  2 12:54:20 christopher-laptop kernel: [ 1289.985502] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=20083 DF PROTO=TCP SPT=45821 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:54:20 christopher-laptop kernel: [ 1289.985517] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=20083 DF PROTO=TCP SPT=45821 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:54:40 christopher-laptop kernel: [ 1309.983219] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=10616 DF PROTO=TCP SPT=45841 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:54:40 christopher-laptop kernel: [ 1309.983235] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=10616 DF PROTO=TCP SPT=45841 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:54:47 christopher-laptop udisksd[2276]: Cleaning up mount point /media/christopher/Compatible (device 8:19 is not mounted)
Apr  2 12:54:47 christopher-laptop udisksd[2276]: Unmounted /dev/sdb3 on behalf of uid 1000
Apr  2 12:54:48 christopher-laptop kernel: [ 1317.923146] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=10.59.0.1 LEN=70 TOS=0x00 PREC=0x00 TTL=64 ID=50621 DF PROTO=UDP SPT=39068 DPT=53 LEN=50 
Apr  2 12:54:51 christopher-laptop kernel: [ 1320.235370] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=111.221.74.29 LEN=61 TOS=0x00 PREC=0x00 TTL=64 ID=5217 DF PROTO=UDP SPT=8211 DPT=40006 LEN=41 
Apr  2 12:54:57 christopher-laptop kernel: [ 1326.086941] VFS: busy inodes on changed media or resized disk sr0
Apr  2 12:55:00 christopher-laptop kernel: [ 1329.981026] [UFW AUDIT] IN= OUT=lo SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=50410 DF PROTO=TCP SPT=45861 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:55:00 christopher-laptop kernel: [ 1329.981042] [UFW AUDIT] IN=lo OUT= MAC=00:00:00:00:00:00:00:00:00:00:00:00:08:00 SRC=127.0.0.1 DST=127.0.0.1 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=50410 DF PROTO=TCP SPT=45861 DPT=10025 WINDOW=43690 RES=0x00 SYN URGP=0 
Apr  2 12:55:06 christopher-laptop kernel: [ 1335.115792] [UFW ALLOW] IN= OUT=eth0 SRC=10.59.0.59 DST=10.59.0.255 LEN=274 TOS=0x00 PREC=0x00 TTL=64 ID=63368 DF PROTO=UDP SPT=138 DPT=138 LEN=254 
Apr  2 12:55:06 christopher-laptop rsyslogd: [origin software="rsyslogd" swVersion="7.4.4" x-pid="938" x-info="http://www.rsyslog.com"] exiting on signal 15.
Apr  2 12:55:26 christopher-laptop rsyslogd: [origin software="rsyslogd" swVersion="7.4.4" x-pid="968" x-info="http://www.rsyslog.com"] start
Apr  2 12:55:26 christopher-laptop rsyslogd: rsyslogd's groupid changed to 104
Apr  2 12:55:26 christopher-laptop rsyslogd: rsyslogd's userid changed to 101
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] Initializing cgroup subsys cpuset
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] Initializing cgroup subsys cpu
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] Initializing cgroup subsys cpuacct
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] Linux version 3.13.0-37-generic (buildd@kapok) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 (Ubuntu 3.13.0-37.64-generic 3.13.11.7)
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] Command line: BOOT_IMAGE=/vmlinuz-3.13.0-37-generic root=/dev/mapper/mint--vg-root ro quiet splash
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] KERNEL supported cpus:
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000]   Intel GenuineIntel
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000]   AMD AuthenticAMD
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000]   Centaur CentaurHauls
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] e820: BIOS-provided physical RAM map:
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009e7ff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x000000000009e800-0x000000000009ffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000001fffffff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x0000000020000000-0x00000000201fffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x0000000020200000-0x000000003fffffff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x0000000040000000-0x00000000401fffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x0000000040200000-0x00000000aac0cfff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aac0d000-0x00000000aad8dfff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aad8e000-0x00000000aad94fff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aad95000-0x00000000aadb7fff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aadb8000-0x00000000aadc5fff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aadc6000-0x00000000aade7fff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aade8000-0x00000000aaf22fff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aaf23000-0x00000000aafe7fff] ACPI NVS
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aafe8000-0x00000000aaffcfff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000aaffd000-0x00000000aaffffff] ACPI data
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000ab000000-0x00000000afffffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000e0000000-0x00000000e3ffffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000fed10000-0x00000000fed13fff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000fed18000-0x00000000fed19fff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000fed1c000-0x00000000fed1ffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000fee00000-0x00000000fee00fff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000ff980000-0x00000000ffbfffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x00000000ffd80000-0x00000000ffffffff] reserved
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000044f7fffff] usable
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] NX (Execute Disable) protection: active
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] SMBIOS 2.6 present.
Apr  2 12:55:26 christopher-laptop kernel: [    0.000000] DMI: ASUSTeK Computer Inc. N53SV/N53SV, BIOS N53SV.215 01/09/2012

**Comment by Falconus** [comment]
Note: this was a USB 3.0 port.

**Comment by anandrkris** [comment]
@Falconus - Would recommend copying logs into sites like pastebin...

**Comment by Falconus** [comment]
@anandrkris why is that better than here?

**Comment by mtwebster** [comment]
@Falconus there's nothing really wrong with here, but using pastebin or dpaste for long blocks of logging/code keeps this discussion cleaner, and those sites generally present large blocks of text in an easier-to-read format.

**Comment by anandrkris** [comment]
@Falconus Apologies, if I confused you. I just suggested for future instances as logs usually run into pages :smile: and makes the issue discussion bit unwieldy to read...

**Comment by gritty-gitty** [comment]
For me, this is just one of the possible manifestations of [issue #2946](https://github.com/linuxmint/Cinnamon/issues/2946) which may happen on mounting or unmounting USB drives or ISO images. And then, it is not only nemo that can freeze the GUI, but also the “Removable Drives” applet.

**Comment by shred** [comment]
After upgrading to Fedora 22 beta, this bug did not occur any more here.

**Comment by HTL2001** [comment]
just had this happen to me, archlinux nemo 2.4.5-1

from a VT I terminated "nemo -n" which brought back control

**Comment by rkingsbury** [comment]
This affects me on Mint 17.1 x64 Cinnamon, 3.16 kernel

**Comment by snownpines** [comment]
I'm also affected. Same setup as rkingsbury.

**Comment by gritty-gitty** [comment]
Since the update of *gvfs* to v1.20.3-ubuntu1.1 (on LM 17.1 Rebecca) which had stated the fixing of some freezing behavior in its changelog, this kind of freezing never happened again.

**Comment by donlencho** [comment]
Unfortunately, after having put a lot of hope in Mint 17.2, I must say it is still happening to me with an up to date version (from a clean install, not an upgrade), when mounting or unmounting USB devices, USB 2 and USB 3 if it matters...
Did anyone find where it comes from?
How can we trace it for a potential solution?
This is the most annoying bug I've experienced and it is present on all four computers I use with Mint.
Thank you,

**Comment by jsalatiel** [comment]
Same problem here when mounting USB devices.
The only way to workaround is control + alt + backspace to restart X.

**Comment by dandv** [comment]
Mint 18 Cinnamon 64-bit: I've unplugged a USB drive several times and had no problem.

**Comment by Vahan86** [comment]
I also had no problem with unplugging a USB drive. Cinnamon version: 3.0.7

**Comment by JosephMcc** [comment]
It would be nice if some of the posters who had the issue could confirm weather or not they are still having problems under 3.0

**Comment by donlencho** [comment]
I intend to update to Mint 18 soon, haven't had the time yet. I will report here afterwards.

**Comment by JosephMcc** [comment]
Thanks the feedback would be appreciated.

**Comment by Falconus** [comment]
I am now running Linux Mint 18, and I have not had a problem with my USB 
storage devices. I will let you know if that changes, but I don't expect 
it to. Please note that I am using a different computer now than when I 
reported the problem in April, 2015, since that computer apparently 
developed serious motherboard issues.

**Comment by geckolinux** [comment]
I'm now on Cinnamon 3 with openSUSE (Leap and Tumbleweed), and so far so good. I guess I'll mark this as closed.

**Comment by JosephMcc** [comment]
Cool, thanks
