### ISSUE TITLE
[IMPROVEMENT] Add gnome-look.org

### ISSUE THREAD

**Issue by mikey12345** [linuxmint/Cinnamon#3872]
In the "Themes" window, where you can change system appearence, it would be nice to add a button that can install stuff from gnome-look.org.
It should be easy, gnome-look has a public API that could be integrated with Cinnamon, this means we could have random wallpapers, a huge theme/cursor/icon/font/screensaver repository, and there is also some desklets there too.

**Comment by glebihan** [comment]
I looked into this a while back.
Unfortunately, it's not as simple as you might think (or as I first thought too).

gnome-look does indeed have a public API for searching, but the problem is that the content is not hosted on gnome-look (not all of it at least), and most of the download links are outside links to various websites. The API does not offer a way to get the actual download link.

Moreover, there is no standardization whatsoever regarding the contents of the downloads (directory structure, single / multiple themes per download, ...), which would make installation nearly impossible to handle.

So, although the idea is good, I don't see a way this could be implemented.
