### ISSUE TITLE
Mouse cursor cannot move past left or right edge of panel to 2nd monitor

### ISSUE THREAD

**Issue by phord** [linuxmint/Cinnamon#3934]
I have two monitors side-by-side.  I can freely move the mouse cursor from one monitor to the other without any "resistance" at the screen edge except when the mouse is on the panel.  If the mouse cursor is on the panel, I cannot move the mouse cursor across the left or right edge of the panel onto a different monitor.  This trapping occurs when I am simply moving the mouse; it does not matter whether I am dragging anything or not.

This problem manifests in annoying ways.  I usually notice it when the mouse is on the 2nd monitor and I am carefully reaching for something in the top-left corner of the 2nd monitor (typically the left-aligned close button).  As I reach for this spot, if the mouse strays one pixel too far so the hotspot is on the 1st monitor (and therefore on the top-placed panel on that monitor) I am suddenly unable to move the cursor back to the 2nd monitor so I can hit the target I was aiming for.  So the cursor gets "grabbed" by the panel and is unable to move away again unless I first move down 30 pixels or so to get off the panel.

I determined experimentally that the problem occurs on top-placed panels and bottom-placed panels; it occurs on the left edge and the right edge of the panel, but not on the top or bottom edge of the panel.  If two panels are visible, it afflicts both of them.

**Comment by collinss** [comment]
This is intentional so as to make it easier to access elements on the edge of the panel. However, there was a recent change made to the panel system to support multiple monitors, and one of the updates is the ability to disable that feature in settings. You can see http://segfault.linuxmint.com/2015/02/recent-cinnamon-development/ for more details.

Note: This change will not be available in Cinnamon 2.4. You will either have to wait until the next release or, if you are feeling adventurous, you can try building it yourself or using the nightlies - but expect lots of bugs if you do, as there is a lot of development happening.
