### ISSUE TITLE
Resize tiled window bug 2.4.6-1 on ArchLinux

### ISSUE THREAD

**Issue by shanemikel** [linuxmint/Cinnamon#3984]
When using the mouse to resize a window that's been attatched to fill half of the screen on the right side, the window will immediately jump almost all the way off-screen on the left side, when the mouse is released, it will grow huge to more-than fill the screen.  This doesn't seem to happen on the left side, or when tiling into the corners.
![screenshot from 2015-03-21 19 46 50](https://cloud.githubusercontent.com/assets/6720672/6767774/3621b912-d003-11e4-82ed-cb4795f45cdd.png)
![screenshot from 2015-03-21 19 47 03](https://cloud.githubusercontent.com/assets/6720672/6767775/38eef826-d003-11e4-9b67-5ab8dc4b247a.png)
![screenshot from 2015-03-21 19 47 23](https://cloud.githubusercontent.com/assets/6720672/6767776/3b53387a-d003-11e4-9939-3130de59bf84.png)
One thing that didn't come out right in the second screenshot:
my cursor was held down, so the graphic shouldn't be a regular pointer.

**Comment by JosephMcc** [comment]
I remember having issues like this in the past and it was down to the window border theme. Maybe try a couple other ones and see if the problem still exists.

**Comment by shanemikel** [comment]
Changed to another window border theme as suggested, and that stopped happening.  Even if it only happens with certain themes, this is a strange phenomenon that needs somebody's attention.  FYI, I was using Zukitwo if the reader wants to reproduce.

**Comment by simonwiles** [comment]
I can confirm the same issue with Zukitwo, but only with horizontal resizing.  I can snap or tile a window to the top or bottom half of the screen and resize it vertically without difficulties.  This remains true if I snap or tile into a corner position -- vertical resizing works as expected, horizontal resizing results in the behaviour so well described by @shanemikel.

I like Zukitwo very much, and will probably continue to put up with this rather than change theme, but I would be interested in trying to fix it, if anyone is able to provide some hints or insight into what might be causing the problem (never worked on gtk+ themes before!).

**Comment by JosephMcc** [comment]
This has always been an issue with tiling and the Zukitwo themes. The original author should probably fix this since other themes work fine.
