### ISSUE TITLE
Windows with long titles make Cinnamon glitch

### ISSUE THREAD

**Issue by laudc** [linuxmint/Cinnamon#3985]
Hi!
Try opening, for example, this tab in Firefox: http://www.wonder-wand.co.uk/WonderWand/Testimonials.html
As you can see, the page has a malformed title tag with very long text. The result is that the Cinnamon menu bar glitches, making all the items disappear.
Closing the tab fixes this.
![screenshot from 2015-03-22 05 58 23](https://cloud.githubusercontent.com/assets/9155575/6768111/948fe76c-d058-11e4-8200-02db270eddde.png)
Screenshot attached.
Thanks.

**Comment by lestcape** [comment]
Confirmed

**Comment by dalcde** [comment]
It's not caused by a long title. It is caused by this new line character: http://www.fileformat.info/info/unicode/char/2028/index.htm

For reference, this website contains four of those characters, and everything else is pushed down: http://dec41test.soc.srcf.net/test.html
This website has a very long long title, and Cinnamon has no issues with it: http://dec41test.soc.srcf.net/test2.html

pixunil's fix seems to work because the evil character appears after the 500th character in the title, but won't work for my website above
