### ISSUE TITLE
Sound applet on system tray not refreshing after Bluetooth connection

### ISSUE THREAD

**Issue by DiegoPomares** [linuxmint/Cinnamon#4025]
Hey guys,

Well the title says pretty much how it is. You can reproduce it with this steps:

1) Laptop is using integrated speakers.
2) Turn on Bluetooth speakers, laptop starts using said speakers cause they were paired previously.
3) Volume control in sound applet doesn't seem to work, it's actually changing the volume of the integrated speakers (the ones that are not in use right now) instead of the Bluetooth speakers (the ones you'd expect to change).
4) The fix is to enter to Sound Settings and clicking on the Bluetooth device, which you'd guess its quite an annoying thing to do everytime =(

Cheers!

**Comment by anandrkris** [comment]
https://github.com/linuxmint/Cinnamon/issues/464 > Yes, an annoyance. Good news is this is fixed now, I suppose.

**Comment by dalcde** [comment]
Fixed https://github.com/linuxmint/Cinnamon/issues/2888#issuecomment-90080727

**Comment by drewrobson** [comment]
I still have this issue with Cinnamon 2.6.7. The "Output device" list updates automatically (thanks to #2888), but the *selected* output device does not update.

Steps to reproduce, same as above:

1) Desktop is using built-in output ("Output device" shows "Analog Output" as selected device)
2) Turn on Bluetooth headset. Desktop starts using said headset because it was paired previously. The "Output device" now adds "Headset" to the list, which is great. However, "Analog Output" *still shows as the selected device*.
3) Volume control doesn't seem to work, it's actually changing the volume of the built-in output (that is not in use right now) instead of the Bluetooth headset (the one you'd expect to change).

**Comment by drewrobson** [comment]
@dalcde, would it be possible to reopen this issue please? I suppose I could open a new issue, but this really seems the same as the OP's issue. Thanks!

**Comment by ManIVIctorious** [comment]
The sound applet as well as the sound settings have seen a lot of work since cinnamon 2.6, is this still an issue for you in cinnamon 3.0?
