### ISSUE TITLE
No Suspend option in the shutdown menu

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/Cinnamon#4060]
Since I upgraded to Ubuntu 15.04, the Suspend option has disappeared from the shutdown menu. I tried a couple of weeks ago upgrading to the nightly version but there was no change.

From the Unity desktop, the Suspend option appears in the shutdown menu and works correctly.

**Comment by leigh123linux** [comment]
I don't know why you post this issue here, it's down to whoever packages it for Ubuntu to fix (eg build it against the proper systemd libs).

**Comment by jmgomezpoveda** [comment]
As it was working in other desktop environments (Unity) I thought it was an incompatibility in Cinnamon.

Could you point me to the missing library? I.e. what triggers the suspend menu option to appear or not? With that info I can then try to fix it myself or open a bug in Ubuntu's Launchpad.

**Comment by leigh123linux** [comment]
It tests for systemd-logind or old upower

https://github.com/linuxmint/cinnamon-session/blob/master/cinnamon-session/csm-logout-dialog.c#L190

**Comment by jmgomezpoveda** [comment]
I have created a bug report in Launchpad for this issue: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1446276

**Comment by jmgomezpoveda** [comment]
If anyone has tried Cinnamon under Ubuntu 15.04 and the Suspend option is not appearing, please indicate so in the launchpad bug. This will help confirm and debug the issue.

**Comment by jmgomezpoveda** [comment]
As indicated in https://bugs.launchpad.net/ubuntu/+source/cinnamon-session/+bug/1446276/comments/3:

    suspend happens through logind since Ubuntu 13.10. The package depends on libsystemd-login-dev, and according to the build log (https://launchpadlibrarian.net/188689398/buildlog_ubuntu-vivid-amd64.cinnamon-session_2.2.2-5build1_UPLOADING.txt.gz) it uses systemd for session tracking. Our systemd package ships all libraries, we didn't disable any.

**Comment by lestcape** [comment]
@jmgomezpoveda  Ok, do you find how mint (cinnamon) check and deside if will be used systemd or old upower, as @leigh123linux say, now try to find how this is resolved on ubuntu and you will see they are not check the same condition. They used another way, then what will be the correct way, i don't know, but i think will be the way that is in freedesktop.org, because thats need to be general... On mate occurs some similar things, i also check that...

Regards...

**Comment by jmgomezpoveda** [comment]
Updating to Cinnamon 2.6 (using the PPA ppa:moorkai/cinnamon), and executing the commands below, has solved the issue for me (after a restart).

gsettings set org.cinnamon.desktop.session settings-daemon-uses-logind true
gsettings set org.cinnamon.desktop.session session-manager-uses-logind true
gsettings set org.cinnamon.desktop.session screensaver-uses-logind false

Any reason why these settings are not set by default?

**Comment by kjfergu** [comment]
@jmgomezpoveda I'm not positive, but I beileve it's because LM uses sysvinit (I think), not systemd, as its init system. Thus it makes sense that the default settings would work for the distribution whose maintainers also make Cinnamon.

I can confirm that the above changes fix this problem. See also http://segfault.linuxmint.com/2015/06/cinnamon-2-6/

**Comment by lestcape** [comment]
@jmgomezpoveda is not set by default, because by default you can has different configuration to start your system. Is set by default with the Mint way (using MDM). If when you reported this, you will change to use MDM you will avoid this problem. This problem is not new and also is present on ubuntu 14.04 see the description of my repository on launchpad. https://launchpad.net/~lestcape/+archive/ubuntu/cinnamon In ubuntu 14.04 the priority is not for systemd, so, the problem is detected on other part of cinnamon (usb device are not mounted automatically). What now is provided, is a way to be configured, to be compatible with the way to start your computer. 

There is also possible detect this while running, but is requiered a different code in cinnamon that is not compatible with MDM. Is also possible change the MDM code to be compatible with this change, but then MDM will not understand the Mate desktop. The Mate desktop is another important desktop for Mint (but is not developed by Mint). This breaks the possibility of the change occurs (detect the session at runtime). Then the only possible solution currently is provide a way to set this manually, if you want to be compatyible with all distros and mode of start you PC...
