### ISSUE TITLE
Native / Official clipboard applet

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/Cinnamon#4092]
Hi, I am aware that there are applets like [GPaste](http://cinnamon-spices.linuxmint.com/applets/view/214) that do a good job*\* but I would like to see a native and official clipboard applet for Cinnamon. As Cinnamon adds new features and matures as a DE, I believe, having nifty and functional applets would offer a great user experience.

Wishlist:
1. Maintain History for n entries / Clear History
2. Edit the clipboard content
3. File support
4. Send to pastebin
5. Invoke actions (e.g. open link in browser) on clipboard content
6. QC bar code support (not a priority)

Others who have used / using KDE would that [Klipper](https://userbase.kde.org/Klipper) it offers similar features.

*\* It was unsupported for a while till someone one forked it.

**Comment by martinrotter** [comment]
+1 Using clipit so far.

**Comment by harogaston** [comment]
Why not talk to the developer of GPaste about implementing those features and later issue a pull request? That's one way it could work.

**Comment by calestyo** [comment]
There are ports of the GPaste applet to cinnamon... e.g.:
http://cinnamon-spices.linuxmint.com/applets/view/214
https://cinnamon-spices.linuxmint.com/applets/view/237

Things were once even close to get such port merged into upstream gpaste (https://github.com/Keruspe/GPaste/issues/126), but unfortunately cooperation between GPaste and cinnamon upstreams turned out not to work (https://github.com/linuxmint/Cinnamon/issues/4656).

cinnamon should really get this as a "official" plugin... if clipboard management isn't one of the core functionalities of windowing systems then what?

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
