### ISSUE TITLE
Broken/unstable cinnamon applets/extensions should be removed, fixed, or have a visible warnings.

### ISSUE THREAD

**Issue by Trucido** [linuxmint/Cinnamon#4149]
Quite a few cinnamon applets and extensions on http://cinnamon-spices.linuxmint.com/applets/ and http://cinnamon-spices.linuxmint.com/extensions/ should be reviewed. I ran into a few that can crash cinnamon or have other ill effects such as spamming dbus and getting denied by polkit (like Multi-Core System Monitor 1.5)

I understand this involves quite a bit of work auditing them, but a lot were designed for older cinnamon versions and/or older mint systems which no longer work properly. This could potentially be extremely confusing for new users.

Other info:
lsb-release: Linux Mint 17.1 Rebecca

**Comment by mtwebster** [comment]
We've discussed this, and I think we're going to create a github  repo to collect all old applets (say, ones that haven't been updated since version X.X) and remove them from spices... sort of an Island of lost toys.

We could then work on updating/fixing them (perhaps also giving active applet devs commit permissions) and releasing them back to the wild as they're fixed.

Hoping to start on this after the upcoming release (in a few weeks or so).

**Comment by lestcape** [comment]
I can help if is needed, just i want to know the criteria, because an applet could have  problematic options, than also can crash cinnamon. All can help if can be possible create a github project to be used only to report issues of external applets. The most problematic thing will be an applet that working for and active cinnamon version, but not for other version, but i see you are working on this (applet versioning) Thanks.

**Comment by NikoKrause** [comment]
This can be closed now since spices are having a GitHub repository now.

@joseph
