### ISSUE TITLE
Windows snap : Option to not maximize on top

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#4183]
I think it can be useful to add an option to not maximize the window when you put it at the top side of the desktop for the windows snap feature. I often like to put my windows at the top but they are often maximized whereas I just want to put them at the top. I don't want to disable windows snap because I use it on the left and right side.

**Comment by JosephMcc** [comment]
You can put them at the top without maximizing them. The tiling only kicks in if the actual cursor touches the screen edge. In the settings you can also choose to tile to the top half instead of maximize.

**Comment by Paviluf** [comment]
I know that I can put them at the top without maximizing them but when you do it relatively quickly you touch the screen edge and the window is maximized :(

**Comment by mtwebster** [comment]
You can make it so it only tiles half-top when it touches the top edge, or use alt-drag to drag the window, which will allow you to place the window closer or even partially off-screen.

**Comment by Paviluf** [comment]
I know but, tiles half-top when it touches the top edge is not what I want to do and use alt-drag is not really practical. A little option will be appreciated :)

**Comment by tripleee** [comment]
I agree.  I find the edge tiling to be a royal pain in the neck.  I basically never want the window manager to resize my windows, whereas edge snapping is a very useful feature indeed.  Currently, you can disable both, but not one or the other (in spite of [issue #816](https://github.com/linuxmint/Cinnamon/issues/816) where apparently it once was individually configurable). The top edge is particularly annoying because when you drag windows from the title bar, it is easy to trigger by mistake. (The others I can live with simply because they don't easily trigger by mistake; but turning off a feature I really never want to use would be at least equally useful.)

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed. Your job is done and we'll take it from here :)

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
