### ISSUE TITLE
Issues with graphic (LMDE2)

### ISSUE THREAD

**Issue by SamBurgos** [linuxmint/Cinnamon#4246]
Greetings, I'm having some troubles with the graphic part inside Cinnamon, as far as I know this didn't happen on version 2.4.x, also I don't know if I someone else posted this so I'm sending this, the issue consist in some graphics troubles when I'm working after that the windows, tooltips, programs, dialog boxes and related start appearing with a weird form, I tried to take some screenshots but once the problem starts the windows take this behavior and don't let me do anything else

![screenshot from 2015-06-03 09 15 04](https://cloud.githubusercontent.com/assets/1509924/7964029/ef6842ca-09d2-11e5-9bd5-8ab3277839d5.png)

As you can see in the above screenshot, the terminal window should show but only shows up as a blank shadow with nothing else, once it starts and if I try to open more programs they all started to look like this (because of this I can't take more screenshots)

Hardware specifications:
![screenshot from 2015-06-03 09 34 37](https://cloud.githubusercontent.com/assets/1509924/7964085/3eebb55c-09d3-11e5-8b4b-77a3834e40bf.png)

inxi -Gx output:
![screenshot from 2015-06-03 09 24 06](https://cloud.githubusercontent.com/assets/1509924/7964093/479eeed0-09d3-11e5-9137-ebc0f22fd357.png)

OS specifications:
LMDE 2 fresh installed with Cinnamon 2.6.7

Steps to reproduce the problem:
Is hard for me to figure it out the exact way, but as long as I detected it happens after I close some open windows (no matter the program, dialog box and related) and then the system start having this behavior, I installed the va-driver-all (https://github.com/linuxmint/Roadmap) in LMDE which in turns pulls out some dependencies of my graphic card but it didn't solve the problem for now

Like I said, is hard for me to test exactly how and when this happen but if you need some help I'll be glad to give more info. Thanks

**Comment by clefebvre** [comment]
Can you paste the result of "apt version gnome-terminal"?

**Comment by SamBurgos** [comment]
Greetings, the result gave me "3.6.2.1+betsy", however, the gnome-terminal is not the only one affected by this; applications like nemo, firefox, synaptic, virtualbox, and all others have this problem once it starts

I can try to take more screenshots if you wish but it's going to be hard once it starts

**Comment by mtwebster** [comment]
Do you have any extensions installed?

**Comment by SamBurgos** [comment]
![screenshot from 2015-06-03 10 00 28](https://cloud.githubusercontent.com/assets/1509924/7964774/d9841f66-09d6-11e5-8b4c-e1e394e4205d.png)

This extension doesn't add any support for 2.6 version, I added the last line in the metadata.json to make it "compatible"; I'll remove it for now and I'll let you know if something happens

**Comment by mtwebster** [comment]
Okay... by the way, you don't need to edit metadata anymore - you can add the extension, and it will warn that it's out of date, prompting if you *really* want to try to load it or not.

**Comment by pixunil** [comment]
Also I would like to see your effects settings, as they changed in 2.6 and often produced issues like that.

**Comment by SamBurgos** [comment]
![screenshot from 2015-06-03 10 34 30](https://cloud.githubusercontent.com/assets/1509924/7965565/98b1fd8c-09db-11e5-9659-d953fc628c1f.png)

![screenshot from 2015-06-03 10 34 28](https://cloud.githubusercontent.com/assets/1509924/7965566/98b31f64-09db-11e5-9809-0b3a4aec6908.png)

Is this good enough? To be honest I haven't changed that much, except by setting all effects "ON", otherwise I left them as default since I don't understand many of those options yet

**Comment by SamBurgos** [comment]
Up until now, I haven't had that problem again so I assume the extension was the guilty on this, for me I can consider the issue as closed since it happens every hour or so and I didn't have much choice than restart completely and for now I haven't had troubles again

As an semi off-topic: too bad I can't install the extension, I like the behavior of having transparent windows so I can check what's behind, guess that I have to wait until developer update it

**Comment by VolMi** [comment]
> I like the behavior of having transparent windows so I can check what's behind, guess that I have to wait until developer update it

Are you aware of this setting?
![window_opacity](https://cloud.githubusercontent.com/assets/1189207/7968300/34eb825a-0a30-11e5-9178-01be05f78497.png)
I also like it, just scrolling on the title bar, no extension needed.

**Comment by SamBurgos** [comment]
More screenshot on the case: 
![screenshot from 2015-06-04 14 23 44](https://cloud.githubusercontent.com/assets/1509924/7994366/1d394e5e-0aca-11e5-8ea8-335d5d172259.png)

![selection_001](https://cloud.githubusercontent.com/assets/1509924/7994372/2ca81bfe-0aca-11e5-9771-0fa61d60b351.png)

In one of the screenshots I manage to open Glass Log to see if I can check something as well as a terminal but it's the same as the others, once it starts I can't do anything. 

*Added info*: the restart Cinnamon keybinding works but if I try to do that a message that says _"Cinnamon has crashed and is running in fallback mode, do you wish to restart?"_ appears and my session ends up running with gnome-panel (I owe you the screenshot on that one), however when the session fallback into that, the problem with the blank shadows is fixed by itself. Another (nasty) possibility is that session fall down into one without window manager (no close, minimize or maximize buttons) in any program or any panel

Also I would like to ask if there is any log I can check when this happens? Although I can't use any graphical tools at least I can do tty and check any possible log to try to paste it later if possible

**Comment by tatave2000** [comment]
I exactly have the same problem on my computer. I tried to setup LMDE2 Cinnamon 32bits on two different Hard disks but the result is the same ("invisible windows" appearing on the screen) just after. If I minimize, maximize and restore several times the window, it works again ...  few minutes.
Mate environnment works correctly but I prefer Cinnamon. If someone have any solution ...

**Comment by breezenunya** [comment]
I have the same issue. At times I will have a few hours before my all new gui's go ghost and turn invisible except for the shadow box outline. It is happening at this moment. took scene shots but am not sure how to post them here in terminal. guess i have to ctrl alt backspace before i can see the file manager to drag and drop. I'm running an asus eee pc 1015px with an n450 atom processor intel gma graphics 2g ddr2 800 and fully updated LMDE 17.2. I have had this same issue since Cinnamon was implemented as the desktop of choice, updating from 17.1 to 17.2 made absolutely no difference. This wasn't apparent with the Xfce desktop, but I have seen other post related to this issue, LDME forum, Mint Cinnamon forum, etc. None resolved. Which, perhaps mistakenly, leads me to believe it is a problem with the Cinnamon desktop. I will post my screenshots after restarting. Dang it! I accidentally maximized my terminal window. It Disappeared. Went to start panel, right clicked, picked unmaximize. Now my terminal window is just an empty shadowbox like the rest.

**Comment by breezenunya** [comment]
Notations on the below screen shots.

1: right clicking on a tab in firefox. Not even the shadow outline.

2:The preferences display menu

3:The preferences desktop menu

4:The menu is visible,notice the highlighted pictures tab, as opposed to anything you select from it, which is invisible.

5:This is the file manager showing the contents of my picture directory after clicking the here to for mentioned pictures tab in the menu.

  As a side note I noticed, after more than a little blind clicking, that the window closing x in the top right corner of these ghost windows is entirely contained in the shadowbox outline, ie if it was visible it would be totally obscured by the shadowbox.

  I truly believe way more people are affected by this problem, but like myself...until now, are just resigned to restarting over, and over,until some seemingly random change, by some unknown, but not unloved, Linux Guru miraculously fixes the problem. Because they, like myself, love Mint to much to even think of switching distro's until a fix is found.. or stumbled over. I will supply any info I can to those smarter than my special "short bus special" self to facilitate finding a fix for this bug.  

![screenshot from 2015-11-05 05 40 08](https://cloud.githubusercontent.com/assets/15669142/10978737/8404da0c-83c6-11e5-9f47-a5612ae806a2.jpg)
![screenshot from 2015-11-05 05 40 36](https://cloud.githubusercontent.com/assets/15669142/10978750/947fc216-83c6-11e5-932c-53e1a348137a.jpg)
![screenshot from 2015-11-05 05 43 15](https://cloud.githubusercontent.com/assets/15669142/10978760/9e8df05c-83c6-11e5-9cf0-90ca85d7a14b.jpg)
![screenshot from 2015-11-05 05 52 41](https://cloud.githubusercontent.com/assets/15669142/10978766/a4612008-83c6-11e5-8a67-4976b68c9f45.jpg)
![screenshot from 2015-11-05 06 14 28](https://cloud.githubusercontent.com/assets/15669142/10978775/add01aa4-83c6-11e5-90e5-1f4e6eb42c25.jpg)

**Comment by breezenunya** [comment]
How can I best help in solving this?

**Comment by joseguerrero** [comment]
Hi, I can confirm all of what @SamBurgos and other people have reported.

This happens in a clean LMDE system with Cinnamon 2.8.4+betsy, you just have to start working (open the browser, nemo, etc) and within an hour or less it occurs, at least in two different machines with the following specifications: 


![captura de pantalla de 2015-12-02 04_14_06](https://cloud.githubusercontent.com/assets/3450341/11533618/cd51ac28-98dc-11e5-9406-89155eb27aed.png)

![captura de pantalla de 2015-12-02 09_08_07](https://cloud.githubusercontent.com/assets/3450341/11533624/d98f81f4-98dc-11e5-8e14-bee22e85cff9.png)

I can also confirm this happens since cinnamon 2.4.7+betsy, here is a screenshot of a fresh installation of LMDE with the bug:

![captura de pantalla de 2015-12-02 08_59_18](https://cloud.githubusercontent.com/assets/3450341/11533630/e4905998-98dc-11e5-954c-d1f6d05de50f.png)

I am also interested in helping solve this bug, I have no deep knowledge of cinnamon internals but I can help with testing.

Regards!

**Comment by ManIVIctorious** [comment]
Is this still an issue for you in cinnamon 3.0.x?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?
