### ISSUE TITLE
Power Manager applet shows battery percentage on non-battery powered machine

### ISSUE THREAD

**Issue by brianjmurrell** [linuxmint/Cinnamon#4289]
On my desktop machine running Cinnamon 2.6, which most definitely does not have a battery in it, the Power Manager applet is showing "Laptop battery 34%".

**Comment by pixunil** [comment]
Can we have a look at your power section of cinnamon settings?

**Comment by brianjmurrell** [comment]
@pixunil Sure.  Are you looking for a portion of my gsettings tree and if so which portion, or are you looking for a screenshot of something?  If so, what in particular?

**Comment by brianjmurrell** [comment]
Happy to provide the requested information.  I just need clarification on what it is that you want.

Cheers.

**Comment by brianjmurrell** [comment]
"Laptop battery" (which doesn't actually exist) has gone down from 34% to 0% now steadily over the last few days.  Could this battery that is being read be the battery in my Bluetooth mouse by any chance?

**Comment by sfilipov** [comment]
I believe I am experiencing the same bug since I upgraded from 17.1 to 17.2 (Cinnamon 2.4 to 2.6 if I am correct). My machine is a laptop and has a battery but before the upgrade that was the only battery that was visible. Since the upgrade, Power Manager also recognizes the battery in my Logitech mouse.

For some reason the mouse battery has a higher priority than the laptop battery. The applet icon is the one for discharging even though my laptop is plugged in. That's because the mouse battery is the one discharging.

The information about the mouse is of no use - I already know it is constantly discharging. I would like to have the previous behaviour of the applet.

![power_applet](https://cloud.githubusercontent.com/assets/2607726/8507957/19190a2a-2263-11e5-8ab0-cd4004d03e0c.png)

**Comment by pixunil** [comment]
@sfillpov, I think this is another reported bug, see #4329.
@brianjmurrell, are you absolutely sure that you don't have a device that is some kind of battery (mouse, keyboard, SPU, …)?
It could also be a label issue, so that the wrong word is used.
And for that screenshot I requested, I was only curious whether `cinnamon-settings power` has got the same behaviour.

**Comment by brianjmurrell** [comment]
@pixunil: Yes, this is probably it.  I do have a Logitech Bluetooth mouse.  So the applet is misidentifying that as a laptop battery then.  How can we fix that?

Requested screenshot:

![image](https://cloud.githubusercontent.com/assets/559317/8620687/343d5dde-26ef-11e5-9e25-b08bfc116107.png)

**Comment by pixunil** [comment]
Can I have the outputs of these two commands, please:

```
$ dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetPrimaryDevice
$ dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetDevices
```

It would help to determinate whether it is a Cinnamon issue or a cinnamon-settings-daemon issue.
Also one question, in the applet menu (like on [the screenshot](https://github.com/linuxmint/Cinnamon/issues/4289#issuecomment-118509287)) is it also "Laptop battery" or "Mouse"?

(I assume that you expect that it names it "Mouse" instead of "Laptop battery")

**Comment by brianjmurrell** [comment]
Sorry for the delay.  I somehow missed the request 12 days ago.  As you requested:

```
$ dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetPrimaryDevice
Error org.cinnamon.SettingsDaemon.Power.Failed: There is no primary device.
$ dbus-send --session --dest=org.cinnamon.SettingsDaemon --type=method_call --print-reply /org/cinnamon/SettingsDaemon/Power org.cinnamon.SettingsDaemon.Power.GetDevices
method return sender=:1.22 -> dest=:1.745 reply_serial=2
   array [
      struct {
         string "/org/freedesktop/UPower/devices/mouse_hid_00o1fo20oe5o51o03_battery"
         uint32 5
         string ". GThemedIcon battery-good-symbolic gpm-mouse-060 battery-good "
         double 54
         uint32 2
         uint64 0
      }
   ]
```

Ahhh.  In Fedora 22 now, the applet does correctly say "Mouse" for the battery.

The applet icon in the tray shows a "full" battery where the same icon in the applet menu shows a less than full battery and a reading of 55%.  I suppose that's a different issue though.

**Comment by pixunil** [comment]
Yes, can confirm, it's taking your mouse battery, nothing else.

I think the icon issue sounds like #4329.

When I'm taking you right, there isn't anything bad now, would you close this please?
