### ISSUE TITLE
cannot set F6 or F8 as shortcut in the control centre

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#4311]
Hey.

Cinnamon 2.6.7, Debian sid.

When I try to set F6 or F8 as shortcut for actions (e.g. switch to workspace 6, or 8) then nothing happens and the old value remains.

When I set it manually in dconf-editor at org.cinnamon.desktop.keybindings.wm.switch-to-workspace-6
(e.g. to "['F6']") then it didn't work at first either.
What I did then was:
- set to default (i.e. empty) all the deprecated values org.cinnamon.muffin.keybindings.*
- restarted cinnamon
then it worked (but of course I still couldn't set it via the control centre.

Cheers,
Chris.

**Comment by denisleroy** [comment]
Looking in this. It's likely a xkeyboard-config problem, i.e. not really the fault of the cs_keyboard.py code.

**Comment by denisleroy** [comment]
Not a xkeyboard-config problem after all, but rather the CellRendererKeybindind() class in cs_keyboard.py is somewhat broken. Not sure what is wrong with the keyboard.grab(), but simply replacing the custom CellRenderer with the vanilla Gtk3 CellRendererAccel() fixes the problem for me. I can do a PR for that, but one does lose the ability to edit the accelerator key "by hand" (i.e. typing in the key name instead of just grabbing it).

**Comment by denisleroy** [comment]
I can no longer reproduce this bug from the master branch. Looks like this got fixed by b4e3a3ba65887f17aa69a5d4ae05113870955b83.

**Comment by calestyo** [comment]
yeah, I think it works :)

**Comment by JosephMcc** [comment]
If your original problem is solved would you please close the issue?

**Comment by calestyo** [comment]
sure... sorry, I haven't noticed it was still open
