### ISSUE TITLE
Switching workspaces flickers a tiled window

### ISSUE THREAD

**Issue by gauravjuvekar** [linuxmint/Cinnamon#4347]
Ok, this bug is kinda hard to describe so I'll try to make a screencast later.

To repro

Make 6 workspaces
Go to the 5th workspace
Open two terminals and tile them to the left and right side with super + leftarrow and super + rightarrow
Switches workspaces using ctrl + alt + arrow keys. 

Observed when switching from workspace with no windows (eg 4 to 3), one of the tiled windows flashes as if you are moving it (ctrl + alt + shift + arrow)

$ cinnamon --version
Cinnamon 2.6.7
$ nemo --version
nemo 2.6.5
$ lsb_release -r
Release:	17.1

**Comment by shred** [comment]
This also happens when switching workspaces by keyboard shortcut. I use Super-1 to Super-5 to quickly switch between my 5 workspaces. When this bug occurs (mostly for the first app after logging in), the window flickers and keeps appearing and disappearing during workspace switch animation. The effect disappears after restarting cinnamon (alt-f2 r).

**Comment by tp0** [comment]
Did you ctrl+alt+shift+arrow move the tiled window that ends up flashing/flickering? In that case this should be same as: #4291

**Comment by shred** [comment]
@tp0 Yes, for me it's exactly the #4291 bug. However I cannot speak for @gauravjuvekar who opened this bug here.

**Comment by gauravjuvekar** [comment]
@tp0  @shred  Confirmed exact duplicate of #4291 , closing

**Comment by tp0** [comment]
No longer experiencing this on 17.2.
