### ISSUE TITLE
Showing obsolete/incompatible: themes, applets, desklets, etc is pointless.

### ISSUE THREAD

**Issue by ledufff** [linuxmint/Cinnamon#4384]

**Comment by JosephMcc** [comment]
That's great but there is no system in place to say "Hey, this is cinnamon 2.6, only show me xlets compatible with me." Or 2.4, 2.2, whatever. Plus it's a community content site. We have no control over if and when devs decide to update their work.

There has been some talk now and again of going through and pulling the old incompatible stuff and putting it in a git repo so devs looking for something to work on can pick them up and update them. At this point nothing has been done though.

**Comment by lestcape** [comment]
Spices is a platform where user can interact and decide if an applet is or not compatible with some cinnamon version. Then using this information, if the number of reports will be more than a max value, cinnamon setting, can alert the user about a possible incompatibility. This is what currently happen with extensions... You can have an invalid report in spices, but spices can be moderate by voluntary user as occurs in mint forums, to correct any information and also provide a more specific error. Also the devs can interact on an explicit way and modify what user think.

**Comment by ledufff** [comment]
Fortunately Cinnamon 2.2 and 2.4 is still being used on Stable distros such as LMDE or Debian. Maybe I didn't explained myself, I don't want to see any Spices content disappear or something, I'm asking: Why not just show the known compatible ones with Cinnamon 2.x in Cinnamon 2.x?  I see that there's voluntaries moderating spices and false positives, but most users don't know about this hidden work, they only see that 60%-70% of the content is incompatible. If somebody want to test or try some "incompatible" content, will have to go to spices website, which stills making pointless showing  that content on control center, except, if showing it is a way to incentive testing in the common user.

**Comment by JosephMcc** [comment]
I understand what you're getting at. Currently there isn't anything in place to support this. Doesn't mean something couldn't be done at some point.

**Comment by lestcape** [comment]
@ledufff I also understand what you say. You are reporting a problem, and i give an idea about how can be "resolved". Detect a broken extensions, only will be possible if user reported the fail in some way.
Ask (your self) how you can know if some extension is or not compatible with some cinnamon version. There are not way to make a deep test, so, some one need to test the extensions and add a mark for compatibles or not compatibles. The Cinnamon devs are Cinnamon devs, not testers of the development of any third-party extension. So, the only solution here are the users, so... What i say is, that is needed a way to report automatically (by users) a broken extensions in the spices web site. This means, add the report to a database, this means when user want to install something, the cinnamon settings will be checked the database value (online) for the compatibility state and will be reported this state to the user that want to install this extension.

If you have a better idea to solve it, that not involved a report, please i want to listen it. I say spice, because is in my opinion the only accessible place from users, the extensions, the cinnamon devs and the dev of the extension.

**Comment by NikoKrause** [comment]
Same as https://github.com/linuxmint/Cinnamon/issues/4149
