### ISSUE TITLE
Quickly find apps from different keyboard layouts as well

### ISSUE THREAD

**Issue by rexmadgere** [linuxmint/cinnamon#4390]
Sometimes I look up an app and I start typing in a wrong keyboard layout. It'd save a lot of time if it were to work anyway, like it does in the major web search engines (Google, Yandex).
Here's the table for the common Russian keyboard.
![image](https://cloud.githubusercontent.com/assets/9503811/8472556/e44e26ae-20aa-11e5-9382-c340b64872f1.png)

**Comment by Kaens** [comment]
Now that sounds like a good idea, seconded... Also, I'll go ahead and fix the table so it's not a picture omgwtf

US|RU|Key Scan Codes
---|----|-----
` |ё|29
q|й|10
w|ц|11
e|у|12
r|к|13
t|е|14
y|н|15
u|г|16
i|ш|17
o|щ|18
p|з|19
[|х|1A
]|ъ|1B
a|ф|1E
s|ы|1F
d|в|20
f|а|21
g|п|22
h|р|23
j|о|24
k|л|25
l|д|26
;|ж|27
'|э|28
z|я|2C
x|ч|2D
c|с|2E
v|м|2F
b|и|30
n|т|31
m|ь|32
,|б|33
.|ю|34

**Comment by lestcape** [comment]
I think this is not a good way, because there are a lot of keyboards layouts... But i think this is important and useful. And i propose a thing like that and was rejected here:
https://github.com/linuxmint/Cinnamon/issues/630#issuecomment-51620618

Maybe will be accepted now, but i consider immature the way of how cinnamon handled the keyboard shortcut right now:
https://github.com/linuxmint/Cinnamon/issues/4379

So, this will be now another problem to take on account where not all think are working as we want. Anyway, this is not my decision.

**Comment by Kaens** [comment]
Well... somebody once had to implement all those keyboard layouts, too, despite there being a real lot of them (some pretty much unused). This is a somewhat tedious, but by no means daunting task. Look, we even have a table ready for Russian now :)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
