### ISSUE TITLE
Dropbox Tray Icon Missing

### ISSUE THREAD

**Issue by tarres** [linuxmint/Cinnamon#4396]
After upgrading to Mint 17.2 the Dropbox Icon isn't showing up in the tray area anymore.

**Comment by tp0** [comment]
#481, #2846

**Comment by tp0** [comment]
#481, #2846 and I think you mean not showing up after boot when Dropbox is autostarted.

Workaround: set a delay in the Startup Applications settings (was unreliable to me) or put this in a bash script that is loaded on boot:

    sleep 10
    dropbox start -i

**Comment by LukMercury** [comment]
As an alternative, you can:
1. Launch Startup Applications from the Menu:
![launch](https://cloud.githubusercontent.com/assets/12476514/10411041/511896e8-6f61-11e5-910e-e0de9ddc6c18.png)

2. Delete the Dropbox entry and add your own command "dropbox star" with a 5 second delay:
![settings](https://cloud.githubusercontent.com/assets/12476514/10411047/a154b57e-6f61-11e5-8967-812478cefd00.png)

**Comment by tp0** [comment]
For me that wasn't working reliably: the delay was always reset to 0 (not sure if that's a related issue). No problems ever with the bash script.

**Comment by Bob-El** [comment]
I have the same problem and like tp0, the delay is always reset to zero. Here's what I to fix it.
First, I had to get the icon up. So, in a terminal session, after the $ prompt, I typed;
*      ps -A | grep dropbox*
to verify whether Dropbox is running or not. To stop Dropbox, I typed;
     dropbox stop
After I got the message that the daemon had stopped, I typed:
     dropbox start -i
and that got me the icon in the Panel. 
So, I right-clicked on the icon and selected "Preferences...".
Then I unclicked the selection box "Start Dropbox on system startup" since it doesn't work anyway. 

After that, I tried different options in Startup Applications and played with different delays up to 15 seconds. My final solution was to write a script to, first, run Dropbox (in case it isn't running), wait 10 seconds, stop Dropbox, wait 10 seconds and start it again. This is not elegant. You might come up with a better way but if works. Here's my script.
      #!/bin/bash
      # DropStart.sh
      # Dropbox custom startup script to show the icon in the Panel
      dropbox start -i
      sleep 10;
      dropbox stop
      sleep 10;
      dropbox start -i

Copy and past that in a text file and save it to a folder somewhere in your Home folder. I called mine "DropStart.sh". Call it what you want but you must append ".sh" to it. I have a few scripts so I have a folder called "Scripts" to put them in. 
Open a terminal session in the folder where the script is and type the following command to make the script executable;
      chmod +x DropStart.sh
Finally, go to Startup Applications, open the Dropbox startup and replace the startup command with the script by clicking on "Browse..." and locating and selecting the script. I also put a 3 second start delay.

Experiment with it if you want but I find the delays are imperceptible. The icon appears and I'm happy again...until the next time something screws up.

**Comment by RohanSJ** [comment]
I had no problems initially on Linux Mint 17.3, but a recent update or upgrade of some software (I'm not sure what) caused me to get this problem. Perhaps there's now a race condition that I didn't have earlier.

I tried LukMercury's approach, but these days if you get rid of the Dropbox entry in Startup Applications (whether by deleting it, turning it OFF, or command-line "dropbox autostart n"), at next boot Dropbox will just put it back! Or if you set a delay on it, at next boot Dropbox will change the delay to 0 (as tp0 mentioned).

So I ended up using Bob-El's approach, adding the new script to Startup Applications as a new entry called DropboxRestart (which is in addition to the standard Dropbox entry that I haven't been able to get rid of permanently). This is working fine for me.

**Comment by Bob-El** [comment]
Thanks, Rohan. It's still working for me also.


On 13 January 2016 at 00:59, Rohan Jayasekera <notifications@github.com>
wrote:

> I had no problems initially on Linux Mint 17.3, but a recent update or
> upgrade of some software (I'm not sure what) caused me to get this problem.
> Perhaps there's now a race condition that I didn't have earlier.
>
> I tried LukMercury's approach, but these days if you get rid of the
> Dropbox entry in Startup Applications (whether by deleting it, turning it
> OFF, or command-line "dropbox autostart n"), at next boot Dropbox will just
> put it back! Or if you set a delay on it, at next boot Dropbox will change
> the delay to 0 (as tp0 mentioned).
>
> So I ended up using Bob-El's approach, adding the new script to Startup
> Applications as a new entry called DropboxRestart (which is in addition to
> the standard Dropbox entry that I haven't been able to get rid of
> permanently). This is working fine for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linuxmint/Cinnamon/issues/4396#issuecomment-171178985>
> .
>



-- 
Bob Lanctot
Ottawa, ON, Canada
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"There is no better defense for absurdity than
obscurity." - John Locke

**Comment by Joe5391** [comment]
@Bob-El 
I signed up just to tell you that your script worked.  Thank you for taking the time to post this solution.

**Comment by jbourne27** [comment]
The following alternative http://forums.linuxmint.com/viewtopic.php?f=47&t=184839&start=80#p1114691 worked for me.

**Comment by f3l1x** [comment]
Confirmed: Linux Mint 17.3 x64 Cinnamon

```
dropbox stop && dbus-launch dropbox start
```

Works.

**Comment by WhiteAce** [comment]
Hello I Have the same problem. Dropbox and also MegaSync applets doesn't show up on the panel. I have tried solutions mentioned above, but neither seems to work for me. I am using Mint 17.3 with Cinnamon Desktop. If some one knows the solution for this problem please share it :)

**Comment by LukMercury** [comment]
Hi WhiteAce,

Are you sure the applet "System Tray" is still on the panel? I once accidentally removed it.
If you right click on the panel and then select + Add Applets to Panel , System Tray should be marked by a green dot. There is also a Restore Settings to Default option under Troubleshoot in the same menu.

**Comment by WhiteAce** [comment]
Thanks @LukMercury  your solution did the trick :)

**Comment by OlsonB** [comment]
Same here.. the icon on the panel will appear, but it's not useful other than perhaps indicating green or yellow if synced or uploading

Left click does nothing and right click just brings up the menu for the tray applet or whatever.

Cinnamon 17.3, Kernel 3.19.0-32-generic.. nvidia drivers 352.63 (recommended) AMD 1090t, GTX970, 16GB RAM

**Comment by ap-Codkelden** [comment]
Confirmed for Arch Linux, kernel 4.6.2, Cinnamon 3.0.5.

The Dropbox icon present in system tray, but no more. Menu "About" by Dropbox icon  right-click shows info about system tray.

**Comment by supergeante** [comment]
Dear all, 
thanks @LukMercury i actually did remove the system tray. I put it back on linux cinnamon sarah and all went back in order.

**Comment by zquestz** [comment]
Simplest solution that works.

* Disable the systemd dropbox service.
* Setup dropbox to auto start
* Open Startup Applications and enable Dropbox with a 3 second delay.
* Open your terminal and run `sudo chattr +i ~/.config/autostart/dropbox.desktop`

This will make the autostart file read only and dropbox can't overwrite it to remove the delay. To disable auto start you will need to `chattr -i` the file, and then you can delete it or uncheck the startup checkbox in Dropbox.

**Comment by alexanderdd** [comment]
I still have this problem (dropbox starting normally and running in background, but no tray-icon visible) in Linux Mint 18.1, all packages up to date. 

Should I open a new bug? Cause this one is closed...

**Comment by OlsonB** [comment]
Bug is bug. Yes?

**Comment by alexanderdd** [comment]
Sorry I don't understand what you are saying with that. Should I open a new
bug report?

2017-08-15 22:49 GMT+02:00 OlsonB <notifications@github.com>:

> Bug is bug. Yes?
>

**Comment by richardpratt** [comment]
there are two problems:

the first is that  dropbox is attempting to use the DBUS based appindicators, but does not supply the correct interfaces for them, so we need to use dbus-launch first;
so we create a new Startup Applications command “DropBoxStart” with comment “dropbox tray icon workaround” and command: dbus-launch dropbox start
and we untick the existing dropbox startup applications command to allow our new one to do its work;

however, and this is the second problem, dropbox overwrites the startup applications command from two places :
~/.config/autostart/dropbox.desktop 
and
usr/share/applications/Dropbox  (need to edit this one as root)

(I think usr/share/applications overwrites ~/.config/autostart but I haven’t tested this)

anyway: edit the Exec line by commenting out “dropbox start -i” thus:  

[Desktop Entry]
Name=Dropbox
GenericName=File Synchronizer
Comment=Sync your files across computers and to the web
Exec=#dropbox start -i
Terminal=false
Type=Application
Icon=dropbox
Categories=Network;FileTransfer;
StartupNotify=false

so when Dropbox does its overwriting, it is with a commented-out command, which therefore causes no problems

**Comment by AstralTim67** [comment]
Is it possible to relay this information to whoever is in charge of the Dropbox servers?  Also, I am constantly having to move the dropbox folder to another drive containing my original dropbox content but the "Move" command doesn't allow you to do it because the folder already exists.  There must be a way for the software to recognize the pre-existing folder and use that one instead of having to rename and juggle folders.  It's a real pain.

**Comment by ebeton-ro** [comment]
@AstralTim67 I recommend to use a simlink to solve your problem.
In order to do that stop Dropbox first. Delete the folder used by the Dropbox as default. Make a simlink that points to you folder instead and voila. This is what I use.
