### ISSUE TITLE
 Exclusive fullscreen applications shouldn't use window decorations or animations when alt-tabbing

### ISSUE THREAD

**Issue by Anti-Ultimate** [linuxmint/Cinnamon#4415]
Would make switching between them much faster.

**Comment by JosephMcc** [comment]
Could you explain this a little more. Not really sure what you are after.

**Comment by Anti-Ultimate** [comment]
On Windows, if you start e.g. a game that uses exclusive fullscreen mode, Windows disables the overlays (e.g. if you change your volume etc.). Also, no animations are drawn on alt-tabbing and no window decorations are present.

On Cinnamon (and actually almost every other DE), exclusive fullscreen windows get treaded exactly like every other window except the lack of compositing. 
It shouldn't draw any overlays (volume switching etc.) , window decorations or animations (when you ALT - TAB out of a game, for example), as those can temporary cause micro stutter and lag (If Cinnamon follows Gnome's logic, it would mean having to redetect the exclusive fullscreen window and disabling composition again.)
This would also fix the windows being offset for a short time after alt-tabbing.(Right where the decorations would be)

I'm not sure if this is even possible under X11, but it should be possible under Wayland.

**Comment by JosephMcc** [comment]
Thanks for responding. At one point the volume OSD didn't show above fullscreen windows. This was changed because people complained about it. If you search the current open issues you will also find complaints about the fact that notifications don't show above fullscreen windows. It seems that a lot of users don't want these to be hidden.

I'm a little confused  by the issue of window decorations coming up when using alt-tab with a fullscreen window open. I'm not a gamer and don't have any installed but with recent changes to Cinnamon fullscreen handling I don't get window decorations showing on fullscreen applications when using alt-tab.
