### ISSUE TITLE
Keyboard navigation in Cinnamon settings unusable

### ISSUE THREAD

**Issue by tobami** [linuxmint/Cinnamon#4447]
Keyboard navigation was implemented in #794. But specially with the new version 2.6, it is unusable.

The main reason for not being usable is ther not being any visual feedback whatsoever as to the position of the cursor. You can only find out by hitting tab and then space and see which switches are being toggled

A more minor usability hindrance is that the text labels are tab "objectives", which means that to move from one switch to the next, you have to hit tab twice instead of once.

**Comment by JosephMcc** [comment]
Visual feedback is dependent on the gtk theme you are currently using. Some, like Mint-X, don't show the focus borders as a design decision while themes like Adwaita do. 

Currently when a row contains a switch it can be toggled with the focus either on the switch or the row that contains it. Maybe that could be improved for keyboard navigation.

The other spot I find a bit strange is the main icon view. Tabbing around causes the focus to land in some strange places. Wondering if that's caused by the way we now alphabetize them. Once focus is in the icon view navigation with the arrow keys seems to work fine though.

**Comment by tobami** [comment]
As far as non-technical users are concerned, Mint-X *is* Cinnamon.

I am sure the theme can be made usable for keyboard navigation without altering the normal look otherwise.

**Comment by JosephMcc** [comment]
@tobami Mint-X is the theme for Linux Mint. Cinnamon is developed mostly by Mint devs for Mint but it's used by and gets improvements from users/maintainers of a number of other distros. Regardless, an issue with the Mint-X theme is not a Cinnamon issue.

**Comment by ManIVIctorious** [comment]
Well this is obviously a theming issue, just checked with breeze-gtk and no problems detected. @JosephMcc can this be closed?

**Comment by Watilin** [comment]
Hello,

I know that this issue is 1 year old but I just landed here while searching for the exact same problem as @tobami 's, that is, no visual feedback for the tab key.

Let me courteously disagree with this assertion from @JosephMcc:
> Regardless, an issue with the Mint-X theme is not a Cinnamon issue.

I’d argue it is, because Mint-X is Cinnamon's default theme and there are two solutions that come easily in mind to fix the problem:
* Encourage an update on the Mint-X theme to properly handle tab navigation, or
* Change the default theme.

I'm genuinely suprised that keyboard navigation isn't taken more seriously into account by the Cinnamon community. Isn't this kind of stuff – this and accessibility in general – one of the principles of the Linux/Unix philosophy?

**Comment by JosephMcc** [comment]
> I’d argue it is, because Mint-X is Cinnamon's default theme and there are two solutions that come easily in mind to fix the problem

Again, Mint-X is not the default theme for Cinnamon. Cinnamon has no included Gtk theme. So no matter how much you argue this issue doesn't belong here and that's why it was closed.
