### ISSUE TITLE
Calender and system tray applets colliding due to window list applet stretching

### ISSUE THREAD

**Issue by alberthdev** [linuxmint/Cinnamon#4458]
Recently, when upgrading to Cinnamon 2.6, I encountered an issue with my panel/taskbar.

In the past (Cinnamon 2.2), having a lot of windows open resulted in a normal taskbar. The windows list applet was constrained to its size, and just shrinked the window list as more and more windows opened:
![paneltaskbarclutteredexpected](https://cloud.githubusercontent.com/assets/1274384/8766798/51ea0928-2e14-11e5-8fd1-76ab4487b4bb.png)

This is the "expected" behavior. With my upgrade to the latest release of Cinnamon 2.6, it seems that this behavior is no longer the case. As more windows are opened, my tray icons are pushed to the right side of my screen, under other applets as well:
![paneltaskbarcluttered](https://cloud.githubusercontent.com/assets/1274384/8766803/810a15ae-2e14-11e5-8dc4-b5e41f83ae50.png)

With fewer windows open, the pushing/colliding does not occur. 
![paneltaskbarnotcluttered](https://cloud.githubusercontent.com/assets/1274384/8766805/99772316-2e14-11e5-9072-2c1f31ddf3cb.png)

Interestingly, with the colliding icons under the applets, the tray icons are still accessible. In fact, they likely take higher precedence for clicking - the calendar applet is not clickable unless I click the far right, since the tray icons are capturing my clicks.

On a resolution of 1600x900, with the panel applets show above, this behavior does not occur until at least 6 windows are present. 5 windows and fewer does NOT push the tray icons to the side.

**Comment by dalcde** [comment]
What theme are you using?

**Comment by alberthdev** [comment]
Minty. Interesting... it looks like the regular Mint theme is fine, while the Minty theme has some issues. I'm not too familiar with Cinnamon internals, but I'm guessing this would be a bug for them, then...

**Comment by dalcde** [comment]
The problem lies in line 1869 of `cinnamon.css` in the theme:
```
.applet-box {
    padding-left: 5px;
    padding-right: 5px;
    min-width: 1em;
    transition-duration: 100;
}
```
By declaring `min-width: 1em;`, the theme is telling Cinnamon "all of my applets can do with `1em` of space". When you have too many window list items, what happens is that Cinnamon realizes that there is insufficient space to show all applets in full. Then Cinnamon asks each applet if they can shrink (ie. if their current width is greater than the min-width). Usually the window-list item is the only applet that replies that it can shrink, so the window list applet shrinks and the items appear smaller, while other applets are left unaffected.

However, in the Minty theme, all applets say that their `min-width` is `1em`. Hence Cinnamon thinks all applets can shrink, and distributes the shrinking among all applets evenly. This causes the space allocated to the right area to be smaller and the applets collide.

So I would say this is a bug in the Minty theme, since they are incorrectly declaring the `min-width` to be `1em`. There might be something that can be done in Cinnamon to prevent this issue, but this would involve changing how sizes are allocated deep down.

**Comment by alberthdev** [comment]
Gotcha... interesting. I guess Cinnamon wasn't correctly parsing the CSS before, so the "normal" behavior persisted until this update. (I guess that beckons the question - was CSS parsing in Cinnamon broken before?)

Also, what would be the proper fix for this theme? It seems that the theme developer doesn't really have a means of contacting them, so I'd like to fix this myself if possible!

**Comment by dalcde** [comment]
It wasn't a change in CSS parsing. It is a change in how the panel allocates space. It theoretically makes much more sense but practically breaks some things if things are initially broken.

To fix the issue, you can just remove the `min-width: 1em` line and you'll be fine.

**Comment by alberthdev** [comment]
Sounds good - I just made the change and the overflow issues are gone. Thanks again!
