### ISSUE TITLE
Wrong window position.

### ISSUE THREAD

**Issue by ledufff** [linuxmint/Cinnamon#4492]
If you're using two monitors and try the Windows / Positioning / Center window in screen shortcut you'll  get something like pic related. 
[Thanks for the clarification tp0, I don't speak English] 
![2015-08-05-150636_3286x1848_scrot](https://cloud.githubusercontent.com/assets/10855368/9096584/999a2e98-3b83-11e5-8cd8-94354c5b0548.png)

**Comment by tp0** [comment]
If you mean Windows > Positioning > `Center window in screen shortcut`, then I have noticed this too.

I think this is something more inherited because of X11...

![screenshot from 2015-08-06 23 24 56](https://cloud.githubusercontent.com/assets/5863551/9122594/b35d48a0-3c92-11e5-8eed-9c1335a0c7d0.png)
