### ISSUE TITLE
LibreOffice icon problems in taskbar

### ISSUE THREAD

**Issue by joshas** [linuxmint/Cinnamon#46]
When I launch LibreOffice Calc, no icon is displayed besides text. Lanching LibreOffice Writer afterwards displays Writer icon for it in taskbar. Launching any other application from LibreOffice suite displays correct icon in taskbar. Just two first launched applications from LibreOffice suite have problems with icons display in taskbar.

**Comment by Ronconi** [comment]
I have problems with LibreOffice 5.1 extensions specially Zotero. It's work but look bad. I think it's a GTK library problem. I use Linux MInt 17.3 Cinnmaon

**Comment by efernbach** [comment]
LO 5.1.4.2, Linux Min 18, Cinnamon Desktop, Windowlist with app grouping applet
Problems with LO applications in Taskbar persist. Presentations and Writer documents are mixed up on panel, in some cases, I can't exactly reproduce it, you minimize a document and it is no longer accessible since there is no icon on the panel.
