### ISSUE TITLE
GNOME applications with client side decorations do not tile properly

### ISSUE THREAD

**Issue by immindich** [linuxmint/cinnamon#4621]
When I use a newer GNOME app (gedit, for example) and I try to tile it to a corner or edge, the header bar goes outside the screen.

Here's what the top right corner of my screen looks like when I try to tile gedit:

![gedit](https://cloud.githubusercontent.com/assets/14264467/9882989/aa2f6cfe-5ba5-11e5-8a3d-984b93683e19.png)

It also takes up too much space.  Here's what it looks like with System Settings, which tiles correctly, in the other corner:

![gedit_tiling](https://cloud.githubusercontent.com/assets/14264467/9882990/aa328524-5ba5-11e5-8eb6-cf7e550b375c.png)

I've tested this with evince and eog and the same thing happens.  It doesn't happen when just maximizing the windows normally.  I am running Cinnamon 2.6.13 on Arch Linux.

**Comment by JosephMcc** [comment]
Can you test this again with Cinnamon 2.8. They seem to work ok here.

**Comment by leigh123linux** [comment]
The issue is still present here with 2.8

**Comment by immindich** [comment]
I'll be able to test this again once 2.8 gets to Arch.

**Comment by immindich** [comment]
This is definitely still happening in 2.8.

**Comment by MalcolmMielle** [comment]
I'm reporting the same problem with fedora 23.

**Comment by Vahan86** [comment]
@immindich, is this still an issue for you with Cinnamon 3.2?

**Comment by immindich** [comment]
@Vahan86 I actually stopped using Cinnamon a while ago for unrelated reasons, but I just installed 3.2 to check.  When I tile gedit, part of the title bar goes past the edge of the screen.

**Comment by fish-face** [comment]
I have this problem on 3.2.8, but it seems to be related to multi-monitor, and perhaps even also HiDPI. My standard setup involves a laptop (at 1920x1080) and an external monitor (2048x1152.) Under circumstances I don't yet know precisely, sometimes I start having exactly this problem, with window borders of newer GNOME applications overlapping the screen edge in all directions (occurs on either monitor.) I can then make the problem go away by going to the Displays settings and insignificantly tweaking the monitor layout, applying the change and then untiling and re-tiling the affected windows.

I mention the HiDPI aspect because when I unplug the external monitor I have the laptop set to go to its native resolution of 3200x1800, which triggers Cinnamon's DPI scaling and could potentially cause the bug when reconnected to the monitor. I haven't experimented with that though.

**Comment by Vahan86** [comment]
Is this still an issue in Cinnamon 4.2?

**Comment by Vahan86** [comment]
@icarter09, can we close the issue since there is no response from OP?
