### ISSUE TITLE
Can't add app launcher to panel

### ISSUE THREAD

**Issue by raph82** [linuxmint/Cinnamon#4651]
In Cinnamon 2.6.13 / Linux Mint 17.2 Rafaela (fresh installation), trying to add a launcher fails without any message. Always reproducible by either way:
1. right-click on any icon of the panel-launcher applet > Add. Fill the name and command fields and click Confirm. Nothing happens.
2. Open the Menu, browse a category then right-click an icon of the right-hand pane > Add to panel. Nothing happens.

 [Multiple users have confirmed it](http://forums.linuxmint.com/viewtopic.php?f=90&t=200170).

**Comment by Vahan86** [comment]
I have the same issue. Please fix it. Thanks.

**Comment by eGit** [comment]
Same here. Cinnamon 17.2.

Please FIX!

**Comment by eGit** [comment]
When will this fix be delivered via the official Mint Update process?

**Comment by mtwebster** [comment]
We're fairly close to a new release anyhow, and this has an easy workaround, that we may just wait.

The workaround:

Easy version:

Remove the applet, re-add it.  You should now be able to add new launchers via any method (the menu or right-click->add).  Just be certain that if you make a custom one, **be sure to explicitly pick an icon for it by clicking the picture in the dialog, and using the file chooser**.

Hard version (but can preserve your existing configuration):

1) Navigate to ~/.cinnamon/configs/panel-launchers@cinnamon.org
2) There will be one or more files called `*number*.json`
3) Open the file up - if you had more than one file, find the right one by checking the names that are in the `value` field of `launcherList`.
4) Look for entries called `cinnamon-custom-launcher-1.desktop` and remove those lines.  The panel launcher applet should reload automatically and display the remaining entries correctly. *Be careful with JSON syntax - if you end up removing the last item in that list, make sure to also remove the comma (,) on the preceding line*

The problem was that failing to select a custom icon when creating a custom launcher was breaking the load routine in the applet, so any launchers defined *after* that bad one would never get loaded either.

**Comment by eGit** [comment]
And without the workaround...if we just wait for the new release...will it all work again without any workarounds?

**Comment by mtwebster** [comment]
Yes

**Comment by Florimel** [comment]
Did you already put this fix in the official update distributed to Cinnamon installs out there?
When will you do it?

I run Linux Mint 17.2 with all updates and still the bug is there for me :(

**Comment by JosephMcc** [comment]
The fix is in Cinnamon 2.8+ and will be in Mint 17.3

**Comment by terentz** [comment]
In Mint 17.3 I can't modify the 'type' of application when creating an application launcher, nor when I modify it's properties. The drop-down, familiar in previous versions, has disappeared... Annoying

**Comment by Alkaris** [comment]
This seems to be issue still on Linux Mint 19.2, except when I go to add icons to the panels, it duplicates the panel and adds new panel to my taskbar. What is even going on with this?

I can't add new icons at all when I select them from the menu and do `Add to Panel` because it creates a new panel group of icons. This is very broken, and when I hit the Remove button it says there are too many of the same panels, and asks if you want to remove them all, so so I do that. But when I go to the Add button it gets a orange circle with an exclamation mark saying


> Something went wrong while loading panel-launchers@cinnamon.org. Please make sure you are using the latest version, and then report the issue to the developer.

**Comment by mtwebster** [comment]
Right click anywhere on the panel launcher applet (even over some other icons) and click '+ Add'

That should bring up a small dialog where you can create a custom launcher.

If you instead wish to add a launcher for something in the menu, you can right-click the item in the menu, and click '+ Add to panel'

It sounds like you're attempting to add whole new instances of the panel launcher applet, rather than add individual items to an existing one.

![Screenshot from 2019-08-21 19-12-02](https://user-images.githubusercontent.com/262776/63474591-b468cd00-c447-11e9-8dcf-2bc6132f6b43.png)
![Screenshot from 2019-08-21 19-13-24](https://user-images.githubusercontent.com/262776/63474621-d2cec880-c447-11e9-910e-7c90b63d6e09.png)

**Comment by Alkaris** [comment]
> It sounds like you're attempting to add whole new instances of the panel launcher applet, rather than add individual items to an existing one.

@mtwebster No? When I go the application I want from the menu and right-click and select Add to panel, the panel gets duplicated, it adds a second panel, instead of adding to the current existing panel.

**Comment by mtwebster** [comment]
I can't reproduce this, is it the stock menu you're using? (menu@cinnamon.org)

**Comment by smurphos** [comment]
https://github.com/linuxmint/cinnamon/issues/8390

**Comment by Alkaris** [comment]
This is with stock menu yes. No idea why it just suddenly decides to break all of a sudden,

**Comment by mtwebster** [comment]
All I can really suggest to try is wiping your applet-related settings - 

This will reset your currently enabled applets (back to stock configuration):
```
gsettings reset org.cinnamon enabled-applets
```
and this will clear out your existing applet settings:
```
rm -rf .cinnamon/configs
```
then restart cinnamon (Alt-F2, r), and see if this is still a problem.

**Comment by smurphos** [comment]
@mtwebster - this issue I linked above outlines how to easily reproduce @Alkaris 's symptoms.

Basically, if you have an empty panel and either add a GWL or a panel launcher applet or just use add to panel from the menu, add to panel from the menu is buggy until after a Cinnamon restart.
