### ISSUE TITLE
Feature Request:  Jump Lists for Panel Icons

### ISSUE THREAD

**Issue by ourichermath** [linuxmint/Cinnamon#4676]
The one thing I miss from Windows are the jump lists on the program icons in the panel (Windows Taskbar).  Please add this capability to Linux Mint Cinnamon.

https://superuser.com/questions/496059/what-is-a-jump-list-in-windows

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Tyco72** [comment]
Thank for have added this request. The jump lists are essential for productivity. I was opening the same request.
The jump lists give a huge boost in productivity when you work on many files and open/close them frequently in the applications. You have an instant access to the last opened files for each application, without to navigate every time in the menu and sub menus of each application to reach their list of recent files (if they have a such list).
In the jump lists in Windows you can also pin up your most frequently used files in the lists. 

I wonder why almost 4 years after opening this request, the jump lists haven't been yet implemented.  
The missing of jump lists and a preview pane in the file manager are the 2 main issues which don't allow me to effectively switch to Linux. (For the preview pane in Nemo, I have already opened a request)

**Comment by smurphos** [comment]
I've got jump lists. It's a feature provided by the grouped window list applet since Cinnamon 4.0.x

**Comment by Tyco72** [comment]
@smurphos 
Which applet did you use? I use the classic Cinnamon desktop. I don't use grouped icons. 
Anyway I tried the "Icing task manager" applet, but it added further unwanted icons on the taskbar and in context menu I didn't see any link to recent opened files (I tried also using grouped icons).
Jump list should work independently from using grouped icons or modern/classic desktop.

**Comment by Tyco72** [comment]
It is not a true jump list, as I mean. It looks to be a list of all recent opened files. It is not specific for a certain application running in the taskbar. But which applet is this? For the moment if would be anyway helpful, if it works also with the classic Cinnamon desktop.
Here a sample of what I mean for jump list (application specific) in the taskbar:
(Please reopen the issue, if your mentioned applet doesn't do the same job.)

![jump list 2](https://user-images.githubusercontent.com/47554612/56463067-96be2500-63cd-11e9-963d-33a23339081d.jpg)

![jump list windows explorer](https://user-images.githubusercontent.com/47554612/56463066-96258e80-63cd-11e9-99e7-a2aba25ad0cd.jpg)

**Comment by smurphos** [comment]
It is a true jump list - it was in the right click context menu for geany (a text editor) so showed a selection of recent files for which I've got geany as the default application. If I have libreoffice calc pinned I get recent calc filytpes in the list etc for that icon right-click menu.  Right click on a pinned nemo shows Bookmarks and recent places etc. etc. 

Cinnamon's infrastructure is as such that all panel functions are provided by one applet or another. In this case the the jump-list function is provided by the grouped-window-list. If you want it you need to use  the applet. Doesn't matter whether you prefer the rest of the modern or the traditional  layout, just remove the panel-launcher applet and and window-list and replace with the grouped-window-list. Explore it's options (there are lots) if you want labels etc rather than just icons for the window list functionality, or want to turn off the grouping functionality.

**Comment by Tyco72** [comment]
Hi, finally I have found the right applet "grouped window list" and I could configure it. I thought It was to be downloaded. 

I see now the recent files in the context menu, but it doesn't work for all programs. It works for LibreOffice, but it doesn't work for VLC player. The "Recent>" section in the context menu is not present. Please try if it works for you and let me know whether I have to add a bug.

The list is anyway a fixed item list. Single items can't be pinned as favorites on the top of the list, and items can't be deleted from the list. I would propose these as improvements. 
It would be better also if the jump lists could be added through a dedicated applet, so that you have not to reconfigure all the taskbar.

**Comment by smurphos** [comment]
For VLC you need to ensure it is set as the default application for the media type - right click on your media, open with > other applications > select VLC > click set as default. That will enable it's recents jump list for that mimetype

The Xplayer / Mediaplayer list is better - you also get playback controls. These additional controls are dependent on the application developers implementing actions in the applications desktop file, which VLC have not seen fit to do (and I don't think VLC provides the command line functions that would facilitate this being  

Dedicated applet? - you can add the stock Recents applet to the panel to get access to  a drop down list of all recents irrespective of applications. There is also the spices applet Places Centre that has an option (default off) to list recent documents in it's panel menu. 

Yes there is no GUI support as it stands for manipulating the recents list (short of clearing it altogethor).The ability to 'Pin' recents would be good.

**Comment by Tyco72** [comment]
Now it works also for VLC. But I see that the implementation is still very rough. I would propose the following improvements, to make the the jump lists usable more effectively. I think all are very important:

- The jump lists should track the recent opened files independently by the default program associated to the files. If I open the same photo with different photo editors, I should see it in the jump lists of all the photo editors, not only in the default one. It is a crucial aspect.
- The jump lists should allow to delete single items in the list.
- It should be possible to pin favourites entries on the top of the list.
- It would be nice if you could set to expand the list of recent files in the context menu by default. So that you can quick open files with only 2 clicks. (There are users which use the jump lists very intensively:) )
- It should be possible to enable/disable the jump lists directly in the standard panel, without to have to rebuild/ reconfigure the whole panel using the grouped window applet. It is not nice to switch off the "panel launchers", because only on it you can directly edit the launch commands of the applications.

Do I have to open an issue for each feature request, or only one containing all?

**Comment by smurphos** [comment]
Given that this issue is closed maybe you should open a fresh issue with your Feature requests. I think a single issue would suffice as they are all related. Re the last request personally I think it would be better to add the ability to edit pinned apps commands in the grouped-window-list, which would make the grouped-window-list a full replacement for panel-launchers.

**Comment by Tyco72** [comment]
Ok, thank you. I have opened a new entry here:
https://github.com/linuxmint/cinnamon/issues/8537 

I hope it can help also other users. I have added your proposal to the point 5)
