### ISSUE TITLE
Remove from favorites with right click option 'remove' or drag it out of a menu

### ISSUE THREAD

**Issue by hrvoojex** [linuxmint/Cinnamon#4701]
When you want to remove an item from favorites, you have to find it in a menu and then right click and select 'remove from favorites'. Yes, you can drag it from favorites to menu. If you drag it out of the menu borders on the desktop, nothing happens and this can be confusing for a new user.

Would it be possible to remove it right from the favorites menu with a right click or a mouse drag and drop on a desktop (out of the menu)?

*I apoligize for my bad english.

**Comment by tp0** [comment]
+1. Not huge issue once you know how, but very unintuitive for new users.

**Comment by lestcape** [comment]
If you want to drag and drop a menu item to the launcher in the panel, this mean you want to remove the item from the menu? I think this will not be helpful. What i think be helpful, is a way to add things, is not convenient normally an easy way to remove the things. More if introduced some inconvenience like this. The Right click is also not convenient because the same thing, is easy and you can remove items accidentally.

**Comment by NikoKrause** [comment]
Almost the same as https://github.com/linuxmint/Cinnamon/issues/4000

**Comment by JosephMcc** [comment]
Close enough to be a duplicate and https://github.com/linuxmint/Cinnamon/issues/4000 has more discussion.
