### ISSUE TITLE
no way to launch panel if it crashes

### ISSUE THREAD

**Issue by paolobenve** [linuxmint/Cinnamon#4714]
I'm using Cinnamon 2.6.13, I installed it on an ubuntu gnome 15.04

Sometimes cinnamon panel crashes, and I haven't found a way to (re)start it: issuing ctl-alt-esc restarts cinnamon but doesn't launch the panel.

I have to restart the session, and after that I have my panel on the screen.

I think the panel should be launched when cinnamon is restarted.

**Comment by glebihan** [comment]
There is no such thing as launching the panel, as Cinnamon is a single process and the panel is part of it.
So what's happening to you is not the panel not starting.

Could you describe more precisely what happens and, if possible, when it happens so that it's possible to try and reproduce your issue ?

**Comment by paolobenve** [comment]
I noted that the panel disappears all the ways I connect to the desktop with a vnc client (I'm using vcnviewer) from another pc

**Comment by paolobenve** [comment]
But why doesn't I the panel appair again restarting cinnamon with ctl-alt-esc?

**Comment by paolobenve** [comment]
anyway, how do I get the panel running if it crashes?

**Comment by ManIVIctorious** [comment]
you can switch to another tty and hit `DISPLAY=:0 cinnamon --replace`
This should restart the cinnamon-session
