### ISSUE TITLE
Make systray-applet icon size themable

### ISSUE THREAD

**Issue by A-Shahbazi** [linuxmint/Cinnamon#4723]
I added systray applet to my panel but the icons seemed a little small. I did a little investigation and realized that systray applet icons do not obey theme icon-size. I have a cinnamon theme which defines several panel properties including panel height and icon-size:

```
...
.system-status-icon {
    icon-size: 16px;
    icon-shadow: black 1px 1px 2px 0px;
}
...
```

The systray icons, however, do not follow the assigned icon-size. Following are 2 screenshots. I have changed icon-size to 21px in one of them so that the issue become more clear.
icon-size: 16px
![screenshot from 2015-10-19 18 04 42](https://cloud.githubusercontent.com/assets/7456141/10580998/49c14bf0-768d-11e5-9351-b0eef22a6146.png)
icon-size: 21px
![screenshot from 2015-10-19 18 06 59](https://cloud.githubusercontent.com/assets/7456141/10581009/5962541e-768d-11e5-8ef8-6cca363dde25.png)

**Comment by ManIVIctorious** [comment]
If I change the panel height all applets, including the system tray icons, rescale properly. Is this still an issue for you in cinnamon 3.0?

**Comment by JosephMcc** [comment]
I would have to double check by I'm pretty sure you still can't set the size of the icons from the theme. I'll mark this as a feature request but wouldn't hold my breath because the hard coded icon sizing helps work around some systray issues. Just do a search for systray issues here to get a hint at how problematic it is to keep the systray working.

**Comment by lestcape** [comment]
Thank to @mtwebster that remove the icon cache for Gio I can use gicon in the indicators, but i can not use system-status-icon in combination with panel-button. I need to use instead applet-box and applet-icon, because indicators can not used the same styles as status icons. I think, because icons are not directly inside the panel-button actor. Also this styles are not working for the status icons. Also indicator icons are not thinking to be integrated with the size property of the theme, In some cases the icons are an array of bytes and they are loaded form a clutter colg texture, with a predefine size in the cinnamon implementation. Now i'm loaded the icon for a gicon, but also with a predefine size, using a GdkPixbuf.Pixbuf that lucky implements gicon and allow me make indicators theme-ables.

The indicators are not homogeneous and will not be loaded into a vertical panel if will not be estimated the size of the icons, base on the panel layout (the orientation of the applet). I changed all size estimation to be possible estimate correctly the height and width of the indicator actors, base on the with and height of the panel and his Layout.

There are more problems, but here i implement an external applet, to be possible test it and use the advantage without wait for be merged (I way to much really): https://github.com/lestcape/Systray-Indicator

**Comment by lestcape** [comment]
This was added to indicators, they have not his own style class, so it's not complete added yet...

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
