### ISSUE TITLE
systray-applet: behaviour of icon click was changed

### ISSUE THREAD

**Issue by rinaldus** [linuxmint/Cinnamon#4741]
I updated to Cinnamon 2.8 and noticed, that left mouse click on icons now opens program context menu, right mouse click opens applet context menu. But how can I open main window of program? For example, Skype doesn't have option to open main window from its context menu.

**Comment by alium** [comment]
same problem with qt4/5 programs

**Comment by volnes** [comment]
Same here

**Comment by ManIVIctorious** [comment]
With cinnamon 2.8 the default switched to use the new app-indicator api instead of the deprecated system-tray icons. You can switch indicators off in the settings of the applet.

The Missing of some functionality in the indicators is a bug/decision in the respective applications, so you should file issues to them

**Comment by JosephMcc** [comment]
If you want the old behaviour you should be able to go to Cinnamon Settings->General and disable the indicator support.

**Comment by alium** [comment]
Thank you @JosephMcc, works, this is not a bug.

**Comment by lestcape** [comment]
I want to know what will be the most common behavior for open the main windows when click inside the appindicator icon.

Will be move the menu to use the left click or will be implemented something like double click?

Regards...

**Comment by lestcape** [comment]
@clefebvre ????? 
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L410
