### ISSUE TITLE
No matter what Theme I set, some programs do not respect it (e.g. nemo)

### ISSUE THREAD

**Issue by rbieb** [linuxmint/Cinnamon#4754]
I'm trying to change the icon the icon theme via the settings menu, and it seems to work, but only partially. 

Example: Some icons in the menu change (Firefox & system settings), but some other settings are stuck with adwaita (Logout & quit). The icons in nemo or nautilus do not change either.

Cinnamon version: 2.6
Kernel Version: 4.2

**Comment by JosephMcc** [comment]
That's because icon themes can inherit icons from other themes. What's happening is the theme you're trying to use only supports some things, like application icons. If however it doesn't supply its own version of other icons, like the action icons in nemo/nautilus, it will fallback to the ones provided by another theme. That is typically the gnome/adwaita icon theme since all installs have those.
