### ISSUE TITLE
Unexpected "Push tile up" behaviour

### ISSUE THREAD

**Issue by septhijssen** [linuxmint/Cinnamon#4766]
In short:
Window tiling yields a slightly different maximization when done by mouse dragging compared to keyboard shortcuts. 

In more detail:

This is in Mint 17.2 with Cinnamon 2.6.13. Furthermore in settings 'Window Tiling' is enabled and 'Maximize, instead of tile, when dragging to the top edge' is on.

When you drag a window to the top it will maximize properly (same result as maximizing by Alt-F10 or a double click on the title bar).

Alternatively, you can maximize by using the 'Push tile up' shortcut (Super-Up) twice. First it will cover the top half, second it will maximize. However, this maximize state is not truly maxed. Note that this might be hard to see; the differences with a proper Alt-F10 max are subtle. The Push-tile-up almost max state still has visible window borders on the sides, and furthermore the top corners are rounded (in Mint-X window border theme).

**Comment by mtwebster** [comment]
This is intentional - no matter what that setting, keyboard manipulation will tile half first, then maximize if you tap up again.  You can undo each step by tapping down.

We originally removed dragging to the top edge to maximize (it would only tile) - after some feedback we made mouse-dragging configurable but left the keyboard alone, as we assumed the only folks who wanted that older behavior (dragging to maximize) weren't likely to be the keyboard shortcut type.

Regardless of the state of that setting, dragging away a maximized window, then dragging back again to tile, will *always* re-maximize the window - again, a behavior most mouse-users have come to expect.

**Comment by septhijssen** [comment]
I am afraid you misunderstand. I am of the keyboard shortcut type, and totally used to the first-top-half, then maximize after a double up. However, the maximization state that you get after this double up is not a true maximization. There is a subtle difference with proper-maximization that you might not notice at first.

You can see this by pressing going in almost max state via tile-push-up (twice), and then pressing Alt-F10 (toggle maximization). After pressing Alt-F10 once you see that the edge gets pushed ever so slightly further outward. Hitting Alt-F10 again will revert to unmaximized state. Hitting Alt-F10 once again will give a proper maximization. The subtle difference in this last max-state is for example that the top left and right corners are not cut (rounded) of.

**Comment by mtwebster** [comment]
Found the issue with this - unfortunately the fix is relatively complicated so it's going to wait until after the 2.8 release.

**Comment by ManIVIctorious** [comment]
Is this still an issue in cinnamon 3.0?

**Comment by septhijssen** [comment]
It appears to be solved in 3.0 for me.

**Comment by ManIVIctorious** [comment]
So could you please close the issue then?
