### ISSUE TITLE
Few persistant bugs

### ISSUE THREAD

**Issue by grenzor** [linuxmint/Cinnamon#4802]
From 2.8:

Windows previews are nice but they are too small (not sure if this is only on HiDPI) – is there a way to make them bigger?

Also some things from 2.6 as well

3) Top of mint menu is cut off in HiDPI (res. 1928x1080)

4) When HiDPI is off, logging in for the first time after comp startup happens within 1-3 seconds. With HiDPI it takes a clear 5-10 seconds. Is there a way to speed this up?

**Comment by JosephMcc** [comment]
Open a single issue for each bug. Having multiple bugs in each issue makes these hard to maintain.

3) If you mean running 1920x1080 monitor in HiDPI, effectively cutting it to 960x540, I don't see this as a bug since I'm not really sure Cinnamon is designed to run at such a tiny resolution.

4) Likely this is due to the larger size of images for everything, such as icons, that need to be loaded.
