### ISSUE TITLE
Mint-X theme on window borders produces unacceptable text when antialiasing is turned on

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#4836]
The text in question is the text in windows' titlebars; and this happens with every font I have tried and is worse when using bold. The visual defect is that antialiasing (on any settings save 'off', I think) produces a strong white outline at the bottom of the letters.

Mint 17.2 x64 Cinnamon 2.8.2 on a Dell D830 laptop.

**Comment by JosephMcc** [comment]
Can you post a screenshot? Mine is set to what I think is the default for the titlebars. Font: Noto Sans Bold 10 and anti-aliasing is set to Rgba. I don't see an issue.

**Comment by TheNotary** [comment]
I can see it in a very pronounced way when I tilt my laptop monitor more upwards.  Tilting your monitor downwards and increasing the brightness might help with it.  

More to the point, I'm currently investigating how font effects are applied.  I have a feeling that this is happening because of more than just anti-aliasing.  Is the font for titles given an 'inset' styling, to make it seem slightly as though it's been chiseled into a surface?

**Comment by JosephMcc** [comment]
Is it only a problem with Mint-X or with other themes as well?

**Comment by TheNotary** [comment]
Looks like it's just Mint-X.  I can get you a photo if you can't replicate the appearance.

**Comment by JosephMcc** [comment]
Ok. Mint-X isn't Cinnamon. If it's just an issue with the theme or simply styled in a way that you don't like, it has it's own repo: https://github.com/linuxmint/mint-themes
