### ISSUE TITLE
Cinnamon applet changed in 2.8.4

### ISSUE THREAD

**Issue by mellobob** [linuxmint/Cinnamon#4850]
I just upgraded to cinnamon 2.8.4 and am disappointed to find that my beloved clementine's panel icon has reverted to the same behaviour that rhythmbox thinks is correct.

Previously:
    Left click brought the application to the front or hid it
    Middle click was stop/play
    Right click brought up a context menu
    Scroll adjusted app volume

Now:
    Left click brings up a menu
    Middle click does nothing
    Right click brings up yet another menu
    Scroll does nothing

I don't much like the change.

**Comment by collinss** [comment]
Try disabling indicators (Settings > General > Enable support for indicators)

**Comment by mellobob** [comment]
PERFECT! Just like I it.

Not an important question ... but why did it work with the previous
cinnamon?

On Fri, Nov 20, 2015 at 7:30 PM, Stephen Collins <notifications@github.com>
wrote:

> Try disabling indicators (Settings > General > Enable support for
> indicators)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linuxmint/Cinnamon/issues/4850#issuecomment-158578027>
> .
>



-- 
**** Listen to my FREE CD at http://www.mellowood.ca/music/cedars ****
Bob van der Poel ** Wynndel, British Columbia, CANADA **
EMAIL: bob@mellowood.ca
WWW:   http://www.mellowood.ca

**Comment by collinss** [comment]
Cinnamon 2.8 introduced support for Unity indicators. Most applications check to see if there is support and only uses the old statusicons as a fallback if there isn't. Previous to this, Cinnamon did not support indicators, so you would see the status icon, but in 2.8 you were seeing the indicator rather than the status icon.

**Comment by mellobob** [comment]
On Fri, Nov 20, 2015 at 8:21 PM, Stephen Collins <notifications@github.com>
wrote:

> Cinnamon 2.8 introduced support for Unity indicators. Most applications
> check to see if there is support and only uses the old statusicons as a
> fallback if there isn't. Previous to this, Cinnamon did not support
> indicators, so you would see the status icon, but in 2.8 you were seeing
> the indicator rather than the status icon.


​So, I assume this is an all or nothing thing. Will I be missing status for
other applications which only support indicators? Guess I'll have to deal
with that if/when it happens.​



-- 
**** Listen to my FREE CD at http://www.mellowood.ca/music/cedars ****
Bob van der Poel ** Wynndel, British Columbia, CANADA **
EMAIL: bob@mellowood.ca
WWW:   http://www.mellowood.ca

**Comment by lestcape** [comment]
@mellobob the indicators are not supported for all apps, but it`s a relative new charasteristic and was invented by kde and popularized in unity (who also invented new features that are not accepted by kde). Recently was also include in freedestop.org (the kde version only). In general, can be integrate better with a D.E. is more flexible to be displayed as you want, but it's more new in cinnamon, so i hope this will be integrate better on new release. Anyway, you have an option to return to the old one implementation. What this option do is not enable indicators, so if you note something different (with indicator support in off), will not be because of indicators.

**Comment by JosephMcc** [comment]
Closing this since it seems to be solved.
