### ISSUE TITLE
[Cinnamon 2.8] Missing Windowlist for Spotify 1.0.x 

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/Cinnamon#4858]
There no windowlist for Spotify 1.0.x on Cinnamon 2.8

http://repository.spotify.com/pool/non-free/s/spotify-client

https://i.imgur.com/Ea2ugUU.png

Any problem with Spotify 0.9.17 on Cinnamon 2.8 or with Spotify 1.0.x on Mate 1.12

**Comment by romainreignier** [comment]
:+1: 
The same here, Cinnamon 2.8, Spotify 1.0
I have also noticed that Spotify is no longer handled by the sound applet. I think it is also a Spotify 1.0 issue.

**Comment by Lodorand** [comment]
I'm having the same issue, Spotify is neither in task manager or system tray. DurandA found [a workaround](https://github.com/linuxmint/Cinnamon/issues/4783#issuecomment-154832951) by moving the window to another workspace and then moving it back.

Problem was not there before v2.8.

**Comment by DurandA** [comment]
You can add a launcher with `wmctrl -xa spotify.Spotify || spotify` in the meantime. It will focus your window manager on Spotify if it is already running or start it otherwise.

**Comment by rwpreece** [comment]
Here's my post from #4783 in case it helps...

Hi Clem,
That screenshot shows enough of the Spotify client that I noticed it's the **1.0.x beta/pre-release** that many are moving to due to the **0.9.x version causing Cinnamon crashes/hangs** (which I'll bet is related to proxy issues and error handling in the chromium plugin that Spotify uses).

The **1.0.x version of Spotify** (http://repository.spotify.com/pool/non-free/s/spotify-client) installs to **/usr/share instead of /opt/share** like the 0.9.x versions.  Also, it looks like the executable is **"Spotify" instead of "spotify"** now.

The /usr/share/cinnamon/applets/sound@cinnamon.org/applet.js probably needs a little tweaking to accommodate the changes.  

At first glance it looks like it's just missing references for:
1) player name and status, and the open and close buttons.
2) Album art, artist and track.

I wonder if **Spotify 1.0.x** is now using **mpris to pass dbus information** now.  It sounds like it was significantly re-written.

**Comment by m1lhaus** [comment]
Any progress on fixing the bug? I know that it affects only Spotify beta client, but this beta client matches Windows version stack and it works just fine. So there are still at least two bugs:

- no cover, album or track info in Sound applet
- no Spotify record no Windows list applet as mentioned above

Workaround to second issue is to disable option "Show window thumbnails on hover" in Windows list applet settings. I don't know any workaround to fixing the first issue.

**Comment by kelebek333** [comment]
My problem solved with disable option "Show window thumbnails on hover" in Windows list applet settings. 

Thanks @m1lhaus.

But if enable "Show window thumbnails on hover" after refesh Cinnamon, Spotify window list shown on panel.

**Comment by JosephMcc** [comment]
This should be fixed in git master by https://github.com/linuxmint/Cinnamon/commit/ded116d53631a2e8cd249cad7583328424ef8609
