### ISSUE TITLE
Position of tooltip of item from window list is not fixed.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#4866]
Position of tooltip of item from window list is not fixed. It depends on position of mouse pointer. Depending on the side from where you hover over the item, from that side the tooltip appears (please see the screenshots).
It would be good if position of tooltip will fixed (on center of item).

![screenshot from 2015-11-23 20 28 56](https://cloud.githubusercontent.com/assets/12819058/11343936/91275568-921f-11e5-889b-00168d61ecbe.png)

![screenshot from 2015-11-23 21 18 19](https://cloud.githubusercontent.com/assets/12819058/11343946/a3726f5a-921f-11e5-9baa-5f97c1f611af.png)

![screenshot from 2015-11-23 21 19 00](https://cloud.githubusercontent.com/assets/12819058/11343951/adbc8fae-921f-11e5-9252-9b2e6ec79666.png)

**Comment by dalcde** [comment]
This is by design

**Comment by Vahan86** [comment]
I understood, just it seems a little bit unpolished to me.

**Comment by NikoKrause** [comment]
Since this is by design, it isn't an issue, is it?

**Comment by Vahan86** [comment]
@NikoKrause, for me it's issue related to the design which imho needs improvement.

**Comment by NikoKrause** [comment]
If it's the design decision of the cinnamon developers, as dalcde says above, it's unlikely to change. You can't implement two different design concepts. There may be people, who like it as it is. 

An issue for me is something, what is broken or what can be improved. But when the developers say, that it is made on purpose or that it is by design, it's no more an issue, it's a matter of taste. That's only my opinion.

I hope this doesn't sound rude. It isn't supposed to be. I think it's important to have the opportunity to discuss about such things as design decisions. But it's also impossible to make everybody happy and it's also important to accept the decisions of others, when they don't agree with you.

P.S.: Cinnamon itself is a consequence of a disagreement. The developers weren't happy with the design decisions of GNOME, if I remember right.

**Comment by Vahan86** [comment]
@NikoKrause, I see your point and partially agree with you. Why partially, because I would like to understand the purpose of such design decision, I would be thankful to get an brief explanation of that, for me "it is by design" is not a strong argument, but ok, it's no matter anymore. I am closing this issue due to lack of interest to this topic.

**Comment by NikoKrause** [comment]
I can not speak for the developers, just can say what I think. Most of the time you have the focus on your mouse, when it moves. So the tooltip isn't very far away from the mouse, when it appears, where the mouse enters. I never paid attention to this before though. And I'm not sure how other OS are handling this. Anyway I use the window preview of the window-list applet. 

I also don't know the code for it, but I would assume that it would be more complicated to calculate the center of each item. Also now that vertical panels are coming. And there's an Option to extend the width of the window button, when there is enough place for it, i.e. the width is not fixed. So you would have to take care of all these options, instead of just showing the tooltip, where the mouse appears. And I'm not sure if the effort would be justified for something small linke that.
That's just a guess. Not sure about it.

So far my point of view.

Why do you think it would be better to fix the Position of the tooltip?

**Comment by JosephMcc** [comment]
I didn't design this so I don't know for sure but I can think of cases where the design could make sense. The window list applet has a setting that allows it's buttons to extend and fill more of the available space. You can end up with some quite wide buttons when using that setting. It probably makes more sense for the tooltip to appear near the mouse in rather than centered on the button.
