### ISSUE TITLE
question on applet development: how can I keep popup menu open when removing item?

### ISSUE THREAD

**Issue by hyOzd** [linuxmint/Cinnamon#4869]
Hi, I'm developing a cinnamon [applet](https://bitbucket.org/hyOzd/mailnagapplet). By default when you click a popup menu item, menu closes. I can change this behaviour by re-implementing `PopupMenu.PopupBaseMenuItem.activate()` method to:

	activate: function(event, keepMenu)
	{
		this.emit('activate', event, true); // last parameter `true` is for `keepMenu`
	}

The thing is; in my code, I also remove the clicked menu item. In this case menu closes. I believe the reason is that; since the item that has the focus is removed, menu also loses the focus and as a result of this, menu closes.

How can I trick the popup menu to stay open? I want user to be able to continue interacting with the menu after removing some items. Any ideas?

**Comment by mtwebster** [comment]
Can you grab focus with something else before you emit activate?

Why emit at all?  You could intercept at 'button-press-event' (a ClutterActor signal) and not propagate the signal (return true), and just handle removing the item.

I'd lean toward the second suggestion - the menu API and 'activate' are for typical usage (click an item, menu closes, etc..) - if I recall, we added the keepMenu parameter so switch widgets could be toggled without the menu closing.  There's still a lot of accounting going on behind the scenes with an 'activate' event, that you don't need here.

**Comment by hyOzd** [comment]
> Can you grab focus with something else before you emit activate?

I think I should do this. But how? Is there an API i can use?

**Comment by hyOzd** [comment]
This worked for me, what do you think? Do you think it's a good idea?

    this.menu.actor.grab_key_focus(); // this.menu is of type Applet.AppletPopupMenu

**Comment by lestcape** [comment]
In general: If the focus is not inside the PopupMenu actor or in the same case, inside of a child of this actor the menu will closed.

If you want implement a general behaviour, where yo don't need to have a control of the focus (moving it manually to other actors), you need to override the menuManager class, and not use the cinnamon standar. There are of course several context where override this class is really not necessary and also there context where is not possible, because you want to keep compatibility with the cinnamon API.

There are not a general solution to do what you want, I proposed here:
https://github.com/linuxmint/Cinnamon/issues/4406

a function in main.js (or other accessible place) to allow disable the "autoexecute" of the menumanager on focus changed.

**Comment by hyOzd** [comment]
@lestcape thanks a lot for clarification and the idea. At the moment, manually calling `grab_key_focus()` seems to be good enough for my simple applet.
