### ISSUE TITLE
Moving Notification pop-up on Cinnamon desktop

### ISSUE THREAD

**Issue by dirent1** [linuxmint/Cinnamon#4892]
Hello,
Greetings from Turkey.
As I know, users can change notifications pop-up position in MATE but we can't in Cinnamon.
It always shows at the top-right corner but I would like to see at right-bottom area, over on clock, sound applets for example. Many of users want to change the place too.
In previously versions of Cinnamon's, users can change this situation via to modify Cinnamon.css but in 17.2 we can't even modify.
If you give some permissions to modify Cinnamon.css it would be great for us.
If you add an option to user interface of Notification Settings can change it like in MATE, it would be greater than.

Thanks in advance.
Best Regards,
dirent

**Comment by kelebek333** [comment]
+1

**Comment by geckolinux** [comment]
+1

**Comment by Vahan86** [comment]
+1

**Comment by JosephMcc** [comment]
You guys do realize that people who follow github get an email for every reply? Please stop with all the +1's if you have nothing useful to add.

**Comment by ademcal** [comment]
I agree with you greating idea :)

**Comment by dirent1** [comment]
@JosephMcc 
Hi, 
The guys who've wrote "+1" as a comment, just want to support this request and also want to call somebody's attention. 
Helping to the guys to describe this issue, it should be better if you add two buttons with counters (such as "Like" and "Dislike" or "Me too" or "No need" buttons) on top of or bottom of Feature Requests. 
Because I think the users want to be attend and manifest themselves when they see a needed request. 

Thanks and regards,
dirent

**Comment by ManIVIctorious** [comment]
@dirent1 the missing of like buttons is obviously a github issue.

@josephmcc i know it is quite annoying, but i personally use the plus ones to keep track of the issues i am interested in in cases everything has already been said

**Comment by JosephMcc** [comment]
My comment was mostly made because someone was jumping around adding +1's to feature requests. This is something users obviously like the idea of so I'm not sure anyone needs to get multiple emails a day to let them know ;)

**Comment by dirent1** [comment]
@JosephMcc 
I see the Unsubscribe button right side on the page. If the user doesn't want to inform about the topic anymore, can click that button easily. 
Anyway
Again, we want can change the notification pop-up's area :+1:

**Comment by crobarcro** [comment]
I just want to add I would like to see this too. By default popups cover window controls and other important parts of the screen. An option to choose a window corner would be nice. Personally I just wish they were bottom left or right corner.

**Comment by piotrekkr** [comment]
If you want to move notification pop-up vertically, temporary solution would be changing /usr/share/cinnamon/js/ui/messageTray.js like in my comment #5130 . It will work until next cinnamon update.

**Comment by geckolinux** [comment]
Thanks very much @piotrekkr  for the useful workaround. The notification covering my window controls and Firefox tabs was driving me crazy.

**Comment by two-dogs** [comment]
Thanks very much @piotrekkr, worked for me too, kudos

**Comment by argamanza** [comment]
It's a must have feature i think, hope it will be implemented ASAP.

**Comment by geckolinux** [comment]
@piotrekkr  Hmm, the hack doesn't seem to work anymore on Cinnamon 3.0.

**Comment by piotrekkr** [comment]
@geckolinux I'm waiting for Linux Mint 18, there should be cinnamon 3.0 included, I think. Meanwhile I'll  find some live cd with cinnamon 3.0 and try to move notification there. I'll let you know if I succeed.

**Comment by geckolinux** [comment]
@piotrekkr  Thanks, much appreciated! I'll have a live CD of openSUSE with Cinnamon 3.0 out in the next few days. I'll give you the link ASAP.

**Comment by piotrekkr** [comment]
@geckolinux I tried installing cinnamon 3.0 in when using `Ubuntu 16.04` live cd but failed due to unresolved dependencies. Now I'm trying arch linux variant named `Antergos`. I read somewhere that there is cinnamon installed already. Maybe it will work. 

I just viewed cinnamon code on github and it seems that `messageTray.js` file hasn't changed since January 9. Can you change line 1829 to this:

    let newY = monitor.y + height + 50; // additional 50 px from top

restart cinnamon and check if it is working? Basically do same thing like in https://github.com/linuxmint/Cinnamon/issues/5130#issuecomment-195567060

**Comment by geckolinux** [comment]
On 05/09/2016 03:17 PM, piotrekkr wrote:
> change line 1829 to this:
>
> |let newY = monitor.y + height + 50; // additional 50 px from top |

Thanks very much! That did the trick.

**Comment by goetzc** [comment]
As I don't have a top panel, only on the bottom, this trick doesn't work for me, but with a small tweak it does. In the same file `messageTray.js` and same function `_onNotificationExpanded`, change:

`        let newY = monitor.y + height;`
to
`        let newY = monitor.y + 768 - 60 - height;`

replacing 768 with you vertical resolution.<sup>[1]</sup> You may have to adjust the 60 value, it work great for me.

<sup>[1]</sup> You can find it under `Settings -> Display` or `xrandr | grep '*' | awk '{print $1}'`

----
The downside of editing those files, is that the will be overwritten on the next update. I don't know if an extension could be made to solve this, maybe the Cinnamon JS API already enables this.

Having the possibility to move the notification bubble in an more user-friendly way would be very useful in those cases where it hides some window elements or if the panel is on the bottom, as it seems to be better down there.

**Comment by piotrekkr** [comment]
@goetzc I don't quite get why you did calculate like that. I have also only bottom panel and adding 50 to `newY` works just fine. Notification popup does not cover my window controlls. 
![notifications](https://cloud.githubusercontent.com/assets/503782/17223393/a17a7350-54fc-11e6-97b9-515832f7efcd.png)

**Comment by goetzc** [comment]
Because I want the notification on the bottom :)
<img src="https://cloud.githubusercontent.com/assets/2220440/17223895/2ee8e908-54c4-11e6-80fb-353790a3a191.png" width="250">
Now I realize that I forgot to mention that I also changed `false` to `true` in:
`let panel = Main.panelManager.getPanel(0, false)`
So the panel size is also included in the new notification position calculation.

**Comment by piotrekkr** [comment]
Yeah but there can be a problem when there is multi line notification since it will probably be over bottom panel. 

Try this in console:

```
notify-send "test" "test\ntest\ntest\ntest\ntest\ntest\ntest\ntest\ntest\ntest\ntest\ntest\ntest\ntest"
```

To overcome this you can do something simplier. You need to get screen height, notification height and substract them. Also substract some more pixels to make some margin between bottom panel and notification:

```
let newY = monitor.height - this._notificationBin.height - 50; 
```
Try it, it worked for me:

![notification](https://cloud.githubusercontent.com/assets/503782/17226878/f6886d02-550b-11e6-9c5f-fcce0c39ec5f.png)

**Comment by goetzc** [comment]
@piotrekkr oh you are right, and this is much better now!

**Comment by Odyseus** [comment]
Hello, everybody.

I already added my thumbs up to this feature request with the hope to see the notifications popup position be allowed to be changed from Cinnamon settings.

In the meantime, and thanks to the exchange between @goetzc and @piotrekkr on this issue, I managed to position the notifications popup at the bottom right of the screen. Next I will describe the exact changes that I made.

I opened as **root** the file **/usr/share/cinnamon/js/ui/messageTray.js**, located the **_onNotificationExpanded** method and edited it as follows:

**Disclaimer!!!**
**Do the maths. The messageTray.js file is a system file that has to be edited as root. If you are not aware of the risks, stay away from this file.**
**These changes will be overwritten every time Cinnamon updates.**

#### Cinnamon 3.0.7 stable specific
Change this line...
```javascript
let panel = Main.panelManager.getPanel(0, false);
```
...like this...
```javascript
let panel = Main.panelManager.getPanel(0, true);
```

#### Cinnamon 3.0.7 nightly specific (installed from this repository)
Change this line...
```javascript
let panel = Main.panelManager.getPanel(0, 0);
```
...like this...
```javascript
let panel = Main.panelManager.getPanel(0, 1);
```

#### Cinnamon stable and nightly alike
Change this line...
```javascript
let newY = monitor.y + height;Change this:
```
...like this...
```javascript
let newY = monitor.height - this._notificationBin.height - height - 10;
```

At this point, if the file is saved and Cinnamon is restarted, notifications will start to show up at the bottom right of the screen but with a little *drawback*. The notification will still be animated from the top of the screen to its final position at the bottom. And will travel all the way back from the bottom of the screen to the top when the notification is hidden.

The only way that I found to avoid all this dancing around of the notification popup is as follows:
Change this line (for Cinnamon stable and nightly alike), near the beginning of the file...
```javascript
const ANIMATION_TIME = .2;
```
...like this...
```javascript
const ANIMATION_TIME = .001;
```

This change will make the notification popup to show up without animation. Do not try to set it to 0 (zero) because it will break the notifications.

**Comment by kelebek333** [comment]
You can easily change Cinnamon's notification position with following Cinnamon Tweaks extention.

https://cinnamon-spices.linuxmint.com/extensions/view/41

**Comment by geckolinux** [comment]
@kelebek333  Hey, nice find! Thanks very much, works great.

**Comment by two-dogs** [comment]
i would suggest the instructions indicate positioning described relative to location on display regardless of panel location, i keep the panel (any desktop) on top, so distance from panel may not be distance from display 'top' or 'botton'  :)

**Comment by piotrekkr** [comment]
@kelebek333 Is this extension available in System Settings => Applets? I have Mint 18 and just refreshed applet list but can't find it there.

**Comment by piotrekkr** [comment]
Ok at last I found how to install it manually. Download it and decompress it in ~/.local/share/cinnamon/applets.

**Comment by JosephMcc** [comment]
> Was this really tested because I have big red ! beside this applet and after clicking "Add to panel" I get errors from glass.log:

@piotrekkr You need to read more carefully. This is your fault and not the fault of the developer. It isn't an applet. It's an extension. You can download it and install it from Cinnamon Settings->Extensions. And remove the one you copied to the applets folder.

**Comment by piotrekkr** [comment]
@JosephMcc Ok, I thought that extension is same as applet just different name, my fault.

**Comment by JosephMcc** [comment]
There are 3 different types of xlets in Cinnamon (4 if you count themes). Applets, desklets, and extensions. Each has their own page in Cinnamon settings. Of the 3, extensions are the most likely to break when a new version of Cinnamon is released. Unlike an applet or desklet, an extension actually patches new code into Cinnamon's javascript code. Because of that extensions are capable of doing more than an applet or desklet but are much more dependent on the code around what they are patching into not changing.

**Comment by MegaV0lt** [comment]
Thanks for the hint with cinnamon tweaks. Finally was easy to move the notification to the bottom. 

Would be nice to have that as an option without having install extra software.

**Comment by Slater91** [comment]
The tweaks presented here seem to no longer be effective. Cinnamon Tweaks has also been removed for unknown reasons, so there currently seems no way to move notifications - a fact that, together with the lack of a "close" button and a few other quirks, is making me think of moving away from this desktop environment which is rapidly falling behind in usability.

**Comment by 88fneSwku4Qt8xh2DE8i** [comment]
@JosephMcc this feature seems like something to be added into cinnamon's core to prevent such issues. The settings for this feature can be easily added to the Notifications section in cinnamon settings, and a simple algorithm to take into consideration the total size of each notification, on the fly to prevent multiline ones cutting through panels or screen edges, could be implemented without too much resource usage. Right now, firefox is unusable if I'm in a lively chat because the constant notifications block the tabs on the right side, with my panel at the top of the screen

**Comment by panaak** [comment]
i tried to move the notification down a bit in `messageTray.js`, but it didn't work until i removed this condion:

```javascript
        // let newY = monitor.y + height;
        let newY = monitor.y + height + 50;


        // if (this._notificationBin.y < expandedY)
        //     this._notificationBin.y = expandedY;
        // else if (this._notification.actor.y != expandedY)
        //     this._tween(this._notificationBin, '_notificationState', State.SHOWN,
        //                 { y: newY,
        //                   time: ANIMATION_TIME,
        //                   transition: 'easeOutQuad'
        //                 });


        this._tween(this._notificationBin, '_notificationState', State.SHOWN,
                    { y: newY,
                      time: ANIMATION_TIME,
                      transition: 'easeOutQuad'
                    });

```

https://github.com/panaak/Cinnamon/blob/ce234ad226669af3fb66e10ef5b4e794ca95a493/js/ui/messageTray.js#L1861

i don't quite understand why.. i didn't dig into the code that much..

**Comment by MegaV0lt** [comment]
After two yerarsa still no feature in cinnamon. even the cinnamon tweaks is deletet. what a shame

**Comment by nikhilw** [comment]
Still nothing?
And what happened to CinnamonTweaks @Odyseus ? After upgrade to 18.3 it just stopped working, so I checked and seems it is gone!

**Comment by MegaV0lt** [comment]
Same here. After upgarde to 18.3 cinnmon tweaks does not work anymore

**Comment by Slater91** [comment]
@nikhilw it's only been two years for such a basic feature. Don't be so hasty!
Meanwhile I switched over to KDE and I finally find myself at home. I think Cinnamon will lose users if it does fix some of its most basic and/or serious issues.

**Comment by chrispoket99** [comment]
Hi, for version 18.3:

sudo vim /usr/share/cinnamon/js/ui/messageTray.js

function: _showNotification, forward of the line:1674

change: let topGap = 5;
to: let topGap = 300;

and tweak topGap value to your preferences

reset cinnamon with alt+F2 and enter r

**Comment by panaak** [comment]
@chrispoket99 solution works for me.

**Comment by Z-42PO** [comment]
@chrispoket99 I recommand to start from the bottom, like this : 
line:1698
change: this._notificationBin.y = monitor.y + topGap * 2;
to: this._notificationBin.y = monitor.height - this._notification._table.height - topGap * 2;

in one command : 
`sudo sed -i 's/this\._notificationBin\.y = monitor\.y + topGap \* 2;/this\._notificationBin\.y = monitor\.height - this\._notification\._table\.height - topGap \* 2;/g' /usr/share/cinnamon/js/ui/messageTray.js`

**Comment by chilliger** [comment]
@Z-42PO cuts the notifications for me

**Comment by MegaV0lt** [comment]
How can i activate cinnamion 3.8 branch? It the commit working? 
https://github.com/linuxmint/Cinnamon/pull/7111

**Comment by Qqwy** [comment]
While the PR is not live yet, you can already use it by following [the instructions outlined by @jaszhix here](https://github.com/linuxmint/Cinnamon/pull/7111#issuecomment-351682239).
