### ISSUE TITLE
How to use alternative window manager

### ISSUE THREAD

**Issue by thkoch2001** [linuxmint/Cinnamon#4895]
Hi,

I'd very much like to use xmonad as an alternative window manager together with the cinnamon. I adapted and followed 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=772179#15

It works, as long as I don't run ```cinnamon``` or ```cinnamon-launcher```. Because either of those will start the default cinnamon window manager. But I still want to have the cinnamon panels and start menu.

Is there a way to just replace the window manager?

**Comment by leigh123linux** [comment]
This isn't possible as you can only have one window manager ( cinnamon is a WM).

**Comment by thkoch2001** [comment]
As I understand, Kwin is the WM for KDE, Mutter is the WM for Gnome3, Gnome2 had another Window Manager. And Muffin is the Window Manager for Cinnamon:
https://en.wikipedia.org/wiki/Mutter_(software)#Muffin

Otherwise please be so kind and update the Wikipedia site.

In former times, it was a non-issue to replace the standard window manager of a desktop environment. Gnome3 broke this possibility with its shell.

**Comment by dalcde** [comment]
Wikipedia is correct. Cinnamon is technically a plugin of muffin, but
muffin is rarely used outside Cinnamon, so for most purposes, we treat
them as part of the same thing. You cannot use Cinnamon without muffin
just as you cannot use a Cinnamon applet outside Cinnamon, or a GNOME
extension outside GNOME.

**Comment by ava-dylang** [comment]
I am rather frustrated that the cinnamon menu is directly coupled to the cinnamon panel is directly coupled to the muffin WM. The cinnamon menu is possibly the most valuable desktop component to me and not being able to use it on other window managers is frustrating to say the least (and the whole cinnamon panel for that matter)

**Comment by llucax** [comment]
Same here, I hate how new desktop environments are really breaking modularity and crippling users choices in terms of WM, specially when they are so limited at tiling...

**Comment by LeoTindall** [comment]
Here to agree with previous posters. I love Cinnamon but find it difficult to be productive without a tiling window manager. I desire to use elements of the Cinnamon DE (e.g. notification handling, media key handling) without the Cinnamon notions of panels or window management.

This is possible with, e.g., XFCE (I've done it on Xubuntu), GNOME (on Ubuntu 18.04), and KDE (on Arch).

**Comment by Bushmills** [comment]
I'm missing the window manager "tabs", such as fluxbox offers them (and muffin doesn't). Because of the requirement of running cinnamon together with muffin, I'm now moving away from muffin. Most reason of using it was the corner actions reminiscent of compiz readily built in, but as I can have those with other environments with a bit of configuration effort - while I can't have window manager tabs with cinnamon - cinnamon leaves me no other option (apart from hacking muffin). I therefore consider a choice for cinnamon now as a choice towards giving up choice.

**Comment by invsblduck** [comment]
After trying Cinnamon and realizing Muffin has no support for configuring (disabling) "Click to raise," I landed here because I need a more powerful X11 wm (as I'm accustomed to for over 20 years). Seeing how no one mentioned actually *trying* a different wm in this ~6 year old thread, I just ran `openbox --replace` as a test, and now I'm writing this in OpenBox... and Cinnamon is completely gone. :joy: Entire DE is gone. Indeed the tales of said monolith are true.

I think this must be written by Windows programmers and not old Unix programmers. :)

**Comment by jelabarre59** [comment]
Yeah, same thing here.  I tried swapping muffin for Marco (from Mate Desktop), and while it ran, the Cinnamon panel and such are gone.   Now I need to find how far to revert back in Cinnamon to get Window Manager theming back, and then pin the desktop to never move beyond that version.
