### ISSUE TITLE
Qt Creator scaling problems on hidpi screens

### ISSUE THREAD

**Issue by PhilJd** [linuxmint/Cinnamon#4902]
Qt Creator doesn't scale some UI elements correctly on hidpi screens (tested on 2560x1600 Macbook retina + 3840x2160 Dell 4K screen). 
Scaling is set to "double" in the cinnamon settings and $QT_DEVICE_PIXEL_RATIO is 2.
I'm not sure if this issue is related to cinnamon or qt, but with Gnome (3.18) the scaling works correctly.
I'm running Cinnamon 2.8.5-2 on arch linux, qtcreator is 3.5.1-1.
Cheers,
Phil
![2015-12-01-144821_2560x1600_scrot](https://cloud.githubusercontent.com/assets/16101605/11502934/132ba8d8-983e-11e5-896f-6e4cd4961b55.png)
![2015-12-01-151541_2560x1600_scrot](https://cloud.githubusercontent.com/assets/16101605/11502993/6c43b532-983e-11e5-92d3-d188a539ffe5.png)

**Comment by kamilsaigol** [comment]
Confirmed 2560 x 1440
QtCreator 3.5.1
Cinnamon 2.8.5
Arch

**Comment by JosephMcc** [comment]
Is this still an issue under Cinnamon3?

**Comment by PhilJd** [comment]
Yes, this still is an issue. I'm on Cinnamon 3.0.7, using Qt 5.7.0.
QT_AUTO_SCREEN_SCALE_FACTOR variable is set to 1.
By the way, this is not connected to Qt creator, this affects all apps using qt, for example albert (settings) and  texmaker. Gnome and Openbox display the fonts correctly. 
As under Gnome the gtk theme is also correctly set, it might be worth trying to fix QT_STYLE_OVERRIDE first (#5440)  and see if this also affects the scaling behaviour?

**Comment by PhilJd** [comment]
Issue persists in Cinnamon 3.2.1, Qt 5.7.0.

**Comment by alialparslan** [comment]
my screen is 3200x1600
this setting works perfectly for me:
```
#!/bin/bash
export QT_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCREEN_SCALE_FACTORS=2
/home/username/Qt/Tools/QtCreator/bin/qtcreator "$@"

```

**Comment by leigh123linux** [comment]
QT5 scaling sucks, the issue should be reported to them so they can fix it.

**Comment by soshiant1992** [comment]
thank you @alialparslan 
i was waiting for this about two years

**Comment by Goddard** [comment]
Works great now @alialparslan thanks.

**Comment by timxx** [comment]
Thanks @alialparslan, add **QT_AUTO_SCREEN_SCALE_FACTOR=1** (no need other env) works perfectly for me.

**Comment by sloth1** [comment]
me also, QT_AUTO_SCREEN_SCALE_FACTOR=1 works on openSUSE Leap 15

**Comment by johannestophoj** [comment]
On my 3840x2160 display I had a problem that whenever I select an item the rightmost panel would resize (shrink) to a default size where I could only see part of the content. The above script solved this issue (and made the fonts readable). KDE Neon 5.14.3

**Comment by leigh123linux** [comment]
QT5 should auto scale if it doesn't file the issue against qt5.

**Comment by KhazAkar** [comment]
I know, It's a topic to enable scaling, but how to disable it entirely?

**Comment by sindhusweety** [comment]
where to mention 
QT_AUTO_SCREEN_SCALE_FACTOR=1

**Comment by haoyun** [comment]
I this this issue may be related to the following bug
<https://bugreports.qt.io/browse/QTBUG-64738>
in `gnome-settings-daemon`. (Probably only when one uses `GDM`)

https://github.com/GNOME/gnome-settings-daemon/blob/7f26c2ac06712cc8834d23826eb153b07c222a12/plugins/xsettings/gsd-xsettings-manager.c#L817-L818
```
        update_property (add_string, "Xft.dpi",
                                g_ascii_dtostr (dpibuf, sizeof (dpibuf), (double) settings->scaled_dpi / 1024.0));
```
--------------------------------------------

In cinnamon, the value `settings -> font selection -> text scaling factor` has to be a multiple of `0.1`, If one set it via `settings -> font selection`.
https://github.com/linuxmint/cinnamon/blob/564152582dce8746953d9c15b0ad5291d9da6e6b/files/usr/share/cinnamon/cinnamon-settings/modules/cs_fonts.py#L53

On the other hand, on a HiDPI screen, when `settings -> accessibility -> Large Text`  is enabled, it will set text scaling factor to '1.25`
https://github.com/linuxmint/cinnamon/blob/2499b0920ddbc86692f89cb54777486005add497/files/usr/share/cinnamon/applets/a11y%40cinnamon.org/applet.js#L16
https://github.com/linuxmint/cinnamon/blob/2499b0920ddbc86692f89cb54777486005add497/files/usr/share/cinnamon/cinnamon-settings/modules/cs_accessibility.py#L10
https://github.com/linuxmint/cinnamon/blob/2499b0920ddbc86692f89cb54777486005add497/files/usr/share/cinnamon/applets/a11y%40cinnamon.org/applet.js#L207-L208

--------------------------------------------------------------------

Now the problem is, if the text scaling factor is set to be `1.2` by any change, the `Xft.dpi` will be set to a floating number, by `gnome-settings-daemon`, e.g., in my case,
```
$  xrdb -query -all
----------------------------------------------
(cut)
Xft.dpi:        230.3994140625
(cut)
```

This will cause `QT_AUTO_SCREEN_SCALE_FACTOR=1` having no effect.
To fix it, one can set `Xft.dpi` manually to an integer number.
