### ISSUE TITLE
Start menu offset to left screen boundary too large

### ISSUE THREAD

**Issue by utack** [linuxmint/Cinnamon#4918]
Since cinnamon 2.8 the distance from the left screen boundary to the left boundary of the start menu seems too large.
It appears to be a High DPI bug.
Also notice the different shape of the start menu.
Normal 1x scaling
![norm](https://cloud.githubusercontent.com/assets/8551234/11611631/d9bc2170-9bd7-11e5-97c6-814a376bb7e2.png)

High Dpi 2x scaling
![hi](https://cloud.githubusercontent.com/assets/8551234/11611628/d724dc18-9bd7-11e5-8176-d0e7f7638670.png)

**Comment by JosephMcc** [comment]
I don't currently have a HiDPI setup to test on but I can take a guess as to what's happening by looking at your screenshots. 

Look at the 1x image and note the size of the icon and "Menu" label in comparison to the panel. Then look at the 2x image. The applet height is much smaller in comparison to the panel. That means the width likely is as well. You get the arrow style in the 2x image when the menu is too close to the monitor edge to draw the the additional rounded corner next to it. My bet is that if the icon and label in the 2x version were the same relative size as in the 1x version the issue would disappear.

If there are no other differences in settings between the two images like using a custom panel size or allowing the panel to scale text and icons, then it seems we aren't scale something properly.

**Comment by lestcape** [comment]
I need to say this. I really don't want to have the space between a the monitor border and the applet popup menu. If is there an special reason to make the separation i want to know if could be considered make a new non standard variable type, in the css style, to be possible decide on themes the gap between the monitor border and the popup menu.

I know, this is a feature implemented to work in this way in conscience, but was implemented by the gnome devs. The cinnamon devs only use this feature and i think without take care about the difference of the desktop.

The gnome desktop have a different conception of what they want to have, so i think this is ok for appearance, but is not ok for the perception of the space in the desktop, is not ok for the fact that the items more closed to the border of the desktop, minimized the mouse movement for the user and is also not ok for the perception of the novice user that come from windows, they at less will see this as a bug. I'm not agree with this perception, but see this images posted in mint forum (http://forums.linuxmint.com/viewtopic.php?f=47&t=209599):

http://postimg.org/image/gn3iabeu1/
http://postimg.org/image/7p489pq2f/

**Comment by JosephMcc** [comment]
Ok, first things first. The "what windows users expect" or "better for novice windows users" arguments I don't really care about. This seems to be an reasoning that pops up a lot. This is mostly a visual issue and this is Cinnamon on Linux, not Windows. I also don't really buy the "minimize mouse movement argument". This a very small distance your talking about and has very little effect on the amount of movement involved.

That being said, making it themable probably isn't a bad idea. For themes that don't show the boxpointer like in the images you posted it might look better directly against the monitor edge. I don't think it would be too hard to add a "-distance-from-monitor-edge" property for this.

**Comment by lestcape** [comment]
@JosephMcc I don' t know what is important to you or not, i only translate the perception of a user with some special characteristic (a windows user) here and i also think he is wrong on what he say. So, we are agree on this (for different reasons, but we are agree). 

If you considerer a very small distance as non distance, this is an interesting consideration, because exist and for years of works a little portion could be really big. Anyway I think your personal appreciation of a distance is not a good argument, but well maybe my simple arithmetic distance*year*uasage also not.

**Comment by JosephMcc** [comment]
So a bit of follow up on this. This wasn't changed in for Cinnamon 3.0. We did however have some discussion about and I think moving forward we might ditch the boxpointer altogether and opt for doing this a bit differently. Menu would be centered on the applet they belong to and the ones close to the screen edge would center as much as possible and set flush against the screen edge when they cannot. Here is a quick teaser of an idea being considered: https://www.dropbox.com/s/pq1ypow8dkyx5p9/menus1.mkv?dl=0

**Comment by lestcape** [comment]
@JosephMcc I agree with you. The menu would be centered on the applet they belong always, but the menu pointer (not the menu itself). So, this only will be possible if we change the distance in red (see the picture). With the change of the api that you introduced, this is not possible in the border, because there are not a distance now. You introduced this change to fix a problem with the box pointer inside the corner. Instead of reduce the distance between the corner and the center, the solution in my opinion  could be increase that distance, to allow display the menu properly while the box pointer will still centered. 

But this is only my idea and this will involve deny your idea, a thing that i don't want, but i don't see any other solution, there are another?

![menu](https://cloud.githubusercontent.com/assets/1389572/14803781/525ac596-0b22-11e6-8fda-721564c886c7.png)

**Comment by utack** [comment]
It is not a priority in any way, but good to hear there is some progress and that it will be fixed longterm

**Comment by JosephMcc** [comment]
@lestcape Not sure if you've had a chance to try the new menu implementation. I'm closing this since the boxpointers no longer exist.

**Comment by lestcape** [comment]
Yes i have this thanks, i like it for several reasons and also i like the effect when a menu is opening. I also fix the references for the box-pointer in the indicator implementation, because cause a problem when this was merged...
