### ISSUE TITLE
Plugging in usb headphones needs to switch volume control too

### ISSUE THREAD

**Issue by LiamDawe** [linuxmint/cinnamon#5031]
When you plug in USB headphones, the sound auto transfers to the USB headset, but the volume control stays on the main speakers, this forces you to go and manually move it over in the Sound settings.

I feel like this is a really annoying papercut that could do with being fixed.

**Comment by Piiit** [comment]
I have the same problem. When I plugin the USB headphone, I must go to the right-click-menu of the sound applet and choose the usb headphones manually. 
A similar problem occurs when I unplug the same headphones, then it does not switch back to the internal sound output of the laptop. This is even more annoying since I cannot switch to that option manually, because there is no output source option left if I have only a single output source. Even when I open the configuration manager > sound > output dialog it shows only "internal audio" which is selected from GUI, but not for the backend I suppose. Doubleclicking it doesn't work either. 
Workaround for the moment: plugin usb headphones, choose internal audio, unplug usb headphones.... 

Do you need some additional information? Log files?

**Comment by ledufff** [comment]
I also have to change the main source manually when using an external monitor with speakers through HDMI cable.

**Comment by christophra** [comment]
Associated with this is that the USB output often ends up with non-centered balance at the start. Exactly how much seems to be random, so it's possible that trying to adjust the volume before selecting the output device sets the balance.

**Comment by shvfn** [comment]
I also have this problem with an USB-Audio-Interface. Volume control only works after manually selecting it in sound settings. Would be great to not have to do this every day! :)

**Comment by Nightbr** [comment]
Hey same problem here with a G930 headset with volume control. The volume control only control the default selected sound output... It could be great we can change volume for each sound output with set it as default.

**Comment by kb53** [comment]
Unplugging the USB resolves that it keeps jumping the volume. My PLA is what I use someone had thrown out with their PlayStation unwanted junk. They work fine in PC in windows or Linux.
Linux Also mixer GUI gives me the default, but when you restart it does not revert back to the Default setting that you checkmark the box for. To further complicate, certain apps, Clementine and Google Chrome have additional separate audio devices. The result is also having to switch back via Mixer Panel all the time to get it back to normal. It would be cool for me to learn some kind of script that would set all the playback and output devices, that I could put either on the desktop of in a launcher on XFCE panel, to just switch all audio to one device or the other. I keep the PLA headphones at Max volume since they have a rotary control knob which I just use to control the volume. My speakers, I just adjust those from the keyboard. 
Does anyone have a script I can click on from desktop or in a launcher. Or a panel item for XFCE that will just do that. 
Or even a keyboard shortcut I can invoke using like ALT-P and ALT-S for PLA and SPKR.

**Comment by Vahan86** [comment]
@LiamDawe, is this still an issue in Cinnamon 4.2?

**Comment by LiamDawe** [comment]
Sorry haven't used for a long time with no plan to. Might as well close.

**Comment by bes1002t** [comment]
Still have this issue in Cinnamon 4.4 in Fedora 32.

I plug in the USB headset:
- sound still from laptop speakers until I switch manually to headset via sound settings
- voice is still recorded via laptop microphone until I switch manually to headset microphone via sound settings

This is annoying because if I forget to switch the microphone manually, everyone in meeting could hear me even if I mute my headset microphone.

**Comment by Nightbr** [comment]
Hey guys, you can set your headset as the default sound device and it should work:

Comment out (##) the line `"load-module module-switch-on-port-available"` in `/etc/pulse/default.pa` 

Also in `/etc/pulse/default.pa` make your device the default one:

```
set-default-sink alsa_output.pci-0000_00_1b.0.hdmi-stereo
#set-default-source input
```

Save the file, then run` pulseaudio -k` in the terminal.

Other thread about this issue:
- https://forums.linuxmint.com/viewtopic.php?t=264566
- https://forums.linuxmint.com/viewtopic.php?t=288517

Hope this can help.

**Comment by eperulli** [comment]
Same problem here.
When I plug my cable earphones, Cinnamon switches correctly from speakers to earphones.
When I unplug the eraphones, Cinnamon doesn't switch from earphones to speakers until I switch manually from the sound applet. If I don't switch manually from the applet, spekaers remain muted.  Never happened with other DE, so I guess it's not a driver or a kernel-related bug.

**Comment by tedbarth** [comment]
I have the same problem, but can say that on Ubuntu I had that, too.

**Comment by ledufff** [comment]
This has to do with either pulseaudio/pipeware/alsa-mixer, because it's been years now of using Xfce and it has this issue as well.
