### ISSUE TITLE
Window list : window preview on mouse over don't show the correct title

### ISSUE THREAD

**Issue by coucout** [linuxmint/Cinnamon#5072]
It's very pity because, like in the attached screenshot, you cannot see the whole name of the file that is opened in LibreOffice. Instead of this, you've only "LibreOffice 5.0". Not very useful.... :-1:
![screenshot_window_preview](https://cloud.githubusercontent.com/assets/3479885/12882261/a84c1360-ce50-11e5-8906-994303564802.png)
With Google Chrome, it seems very strange. It always show "Sans titre - Google Chrome", regardless it's a new tab or a loaded tab.
![screenshot_window_preview2](https://cloud.githubusercontent.com/assets/3479885/12882467/1f6ad890-ce52-11e5-84ef-2dd95df57db0.png)

**Comment by JosephMcc** [comment]
This should already be fixed in git master. Not sure if/when a fix is going out for 2.8. The length of the title is still limited to some extent to prevent overly wide popups but the title shown now matches what you see in the actual window list itself.

https://github.com/linuxmint/Cinnamon/issues/4879
