### ISSUE TITLE
Sound applet (Cinnamon 2.8.7) doesn't have Spotify (1.0.25) artist/title/art yet desktop notifications does?

### ISSUE THREAD

**Issue by paulcaheny** [linuxmint/Cinnamon#5180]
![screenshot from 2016-04-02 16 18 21](https://cloud.githubusercontent.com/assets/18231690/14226857/e8f1f98e-f8ee-11e5-8a5c-7b3c4f12d300.png)

See attached screentshot, desktop notification can access Spotify information perfectly (top of image), while the sound applet in the tray has nothing. If the desktop notifications can get this info from spotify, why not the sound applet?

**Comment by collinss** [comment]
That's because Spotify sends the notification information as a one time thing. The sound applet doesn't (and probably can't reliably) use this information. The real issue is that recent versions of Spotify broke their MPRIS support, so that information isn't available to the sound applet using the appropriate method. To sum up, this is not a Cinnamon issue, it is a Spotify one.

**Comment by lestcape** [comment]
@collinss You know why the sound setting take some time to display the components? There are a way to load just the main tab and then then display the other on idle? I think is the most delayed of all and i know probably is the most complex, of course. Anyway good job on this and thanks.

**Comment by hmcezar** [comment]
It's fixed now in the current testing version (1.0.27).

**Comment by volkovmqx** [comment]
somehow the image is not that good quality

![screenshot from 2016-04-16 23 13 15](https://cloud.githubusercontent.com/assets/6787334/14583921/e8082d64-0428-11e6-95fa-24e590ce89e9.png)

**Comment by JosephMcc** [comment]
This should be fixed in git master for Cinnamon 3.0. At least until spotify does something that breaks it again :)
