### ISSUE TITLE
White line in the right side of the screen

### ISSUE THREAD

**Issue by telmotrooper** [linuxmint/Cinnamon#5228]
Hello, friends. I'm under Cinnamon 2.8.8 on Antergos (an Arch Linux distro) and I'm having a weird issue. Since my last installation I'm getting a weird white line in the right side of the screen, but only on the desktop, it doesn't show up above any window and I can put the mouse above it just fine. Also, I believe it's related to the problem, everytime I try to shutdown the system I get a message telling me Certificate and Key Storage is still running.

That's how it looks:

http://i.imgur.com/EbNknTa.png
http://i.imgur.com/VWpd18b.png
http://i.imgur.com/ILb1RZR.png

**Comment by telmotrooper** [comment]
Update: if I do "xkill" and click over the white line it disappears.

**Comment by telmotrooper** [comment]
Update: I found out the process creating the white line is "nemo", the file manager. If I kill it the bar disappears and if I open any folder through it, the bar shows up again and doesn't go out untill I kill nemo again.
That's a pretty awkward issue.

**Comment by JosephMcc** [comment]
From talking to one of the Mate devs working with gtk3.20, I believe what you are seeing is actually a scrollbar for the nemo desktop window. The new version of gtk brought significant changes to how themes are handled and some new style classes have been added to nemo in git master to help with this. I'll double check with someone more familiar with 3.20 and be sure it works properly now.

It reappears when you reopen nemo because nemo is once again taking control of the desktop window. You might be able to work around this temporarily by disable desktop icons in Cinnamon Settings->Desktop

**Comment by telmotrooper** [comment]
@JosephMcc Just tried your suggestion and disabling "Show desktop icons" does hide the bar, which leads me to believe your assumption is true. Thank you for the clarification and I hope the issue is fixed soon.

**Comment by leigh123linux** [comment]
@telmotrooper Your issue looks more like a theme issue, does adwaita also do it?

I don't see this issue using stable or git, screenshot is F24 running gtk-3.20 and cinnamon-3.0 (cinnamon, nemo & muffin are the latest git versions).

![screenshot from 2016-04-24 09-38-14](https://cloud.githubusercontent.com/assets/1299302/14766406/4c1c44d4-0a00-11e6-87af-8cbfa7a9f278.png)

**Comment by telmotrooper** [comment]
@leigh123linux I just tried changing themes to check, I have the issue in both themes I tried, default Cinnamon and Numix-Frost. Maybe it has been fixed on the latest update? I'm still on Cinnamon 2.8.8 because that's the latest version available in the arch repository. Also, I just noticed I'm getting some GTK related warnings when I try to check my `nemo --version`:

> [telmo@Telmo-PC ~]$ nemo --version
>
> (nemo:4372): Gtk-WARNING **: Theme parsing error: gtk.css:158:192: '_text_shadow_color' is not a valid color name
> 
> (nemo:4372): Gtk-WARNING **: Theme parsing error: gtk.css:1609:39: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
> 
> (nemo:4372): Gtk-WARNING **: Theme parsing error: gtk.css:1609:77: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
> 
> (nemo:4372): Gtk-WARNING **: Theme parsing error: gtk.css:3232:39: 'linear-gradient' is not a valid color name
> 
> (nemo:4372): Gtk-WARNING **: Theme parsing error: gtk.css:3237:41: The :insensitive pseudo-class is deprecated. Use :disabled instead.
> 
> (nemo:4372): Gtk-WARNING **: Theme parsing error: gtk.css:3237:53: The :insensitive pseudo-class is deprecated. Use :disabled instead.
> 
> (nemo:4372): Gtk-WARNING **: Theme parsing error: gtk.css:3244:35: 'border_disabled' is not a valid color name
> nemo 2.8.7

**Comment by raveit65** [comment]
@JosephMcc 
Such a issue can happen if the theme define a border on notebook or scrolledwindow, because those selectors are above .nemo-desktop selector in widget hierarchy.
But with new selector .nemo-window-desktop this can be eliminate.
That a selector like notebook, scrolledwindow or frame can match everywhere is a side effect of using nodes with 3.20 and it is a hard work to kill unwanted borders.
@telmotrooper 
All those deprecated stuff needs to remove from theme css.

To sumary: this is a theme issue ;)

**Comment by raveit65** [comment]
Btw, such a selector can be added to nemo.css

```
/* remove unwanted border from desktop window */
.nemo-desktop-window box.nemo-window-pane scrolledwindow {
    border-width: 0px;
    border-style: none;
}
```
and something for notebook.
This gtk+-3.20 syntax and should be harmless for other version.

**Comment by raveit65** [comment]
and for notebook:
```
/* remove unwanted border from desktop window */
.nemo-desktop-window box.nemo-window-pane notebook {
    border-width: 0px;
    border-style: none;
}
```

**Comment by telmotrooper** [comment]
@raveit65 Thank you for your help, today the arch package numix-frost-themes has been updated to 3.5.r679-1 and with that the white bar has disappeared for good. The warnings on `nemo --version` are also gone. I'm guessing they've implemented the solution mentioned.

I'd like to thank you three, @JosephMcc, @leigh123linux and @raveit65 for bringing new information into the discussion. I'll be closing the issue now that the package has been updated.
