### ISSUE TITLE
GLib-CRITICAL: g_key_file_free: assertion 'key_file! = NULL' failed

### ISSUE THREAD

**Issue by Ovrclockd** [linuxmint/Cinnamon#5233]
So I destroyed my computer by trying to set up an OpenRA server with Docker 

https://github.com/rmoriz/openra-dockerfile

and I restart my computer and now I get a prompt that reads

"Your session only lasted less than 10 seconds. If you have not logged yourself, this could mean that there is some installation problem or that you may be out of diskspace. TRY logging in with one of the failsafe sessions to see I you ccan fix this problem."

Then a checkbox that says "View details (~/.xsession-errors file)"

GLib-CRITICAL: g_key_file_free: assertion 'key_file! = NULL' failed

https://forums.linuxmint.com/viewtopic.php?f=208&t=220963

**Comment by leigh123linux** [comment]
You would be better off re-installing as the little info you provided isn't enough to know where you fucked up!

**Comment by JosephMcc** [comment]
I'm closing this since I don't really see how this is a Cinnamon issue.

**Comment by Generalf69** [comment]
Well, to sad that this topic was closed because INSM having 100% the same issue except that I have installed docker on my raspi via ssh.
Anyway after pushing some keys on the keyboard by accident the laptop did reboot and came back with small prints Ubuntu 18.1 instead of the mint logo and ended up with a simple GUI which doesn't accept my user/password. When running the login on a terminal, user and password is accepted
