### ISSUE TITLE
add a setting to disable overlay scrollbar "feature" throughout the cinnamon session

### ISSUE THREAD

**Issue by calestyo** [linuxmint/Cinnamon#5306]
Hey.

Since some GTK version they've added that overlay scrollbar "feature".

IMHO that's just yet another mobile-platform centric and desktop-hostile feature, with only one real "advantage": saving display space, which is however not really that big issue on desktop systems.
I'd say even for things like graphics editing, where one wants do use as much display space as possible, one rather invests that few pixels spent for the scrollbar than not having it.

The big disadvantages are:
- one only sees the scrollbars for a short while after the mouse have been moved over the respective control element => that means that there is no real way to quickly spot all scroll bars on the whole screen, without moving over everything (every time again, the UI changes)

IMHO even worse one of the two main features of scrollbars is completely lost, with the other one being the ability to actually scroll (which is however often simply done by the scroll wheel or via some gesture on the touchpad):
- one can no longer see "where" one currently is within the scrollable content, unless one moves the pointer over it (and makes it visible for a short while)
I think that's really a big drawback when navigating through the UI of some program

There's an environment variable that allows to disable that crap:
GTK_OVERLAY_SCROLLING=0

It would be great if cinnamon could export some configuration option in the system settings that allow setting that session wide at session startup.

Cheers,
Chris.

**Comment by geckolinux** [comment]
Hello @mtwebster , for some reason on openSUSE the new `org.cinnamon.desktop.interface` `gtk-overlay-scrollbars` setting doesn't actually disable overlay scrollbars, in fact in actually complicates the issue:

I have had `export GTK_OVERLAY_SCROLLING=0` in my `~/.profile` for a long time now. But since Cinnamon added the new `gtk-overlay-scrollbars` key with default to `TRUE`, it has been overriding my `~/.profile`. 

On another system with no modifications to `~/.profile`, even after I set `gtk-overlay-scrollbars` to `FALSE` and logged out / logged in again, the overlay scrollbars remained. So again I had to resort to the  `export GTK_OVERLAY_SCROLLING=0` in ~/.profile .

**Comment by calestyo** [comment]
hmm works at least fine here on Debian

**Comment by mtwebster** [comment]
@geckolinux Have you checked what your environment actually contained when you had gtk-overlay-scrollbars set to false?  Any terminal should show you that with `env` - could something at the distro-level be overriding the variable?  It's pretty straightforward, I'm not sure why it wouldn't just work.
