### ISSUE TITLE
Large windows have glitches around

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#5379]
Windows with a large size have like a piece of screenshot of the background at the right, and the window shadow is like moved to the top left. Here is a picture:
![screenshot from 2016-06-15 17-12-45](https://cloud.githubusercontent.com/assets/10391266/16085600/d4b098a0-331c-11e6-86c4-d656b44aaa83.png)

Normally you won't resize windows larger than your screen size, but the problem is that it happens with windows smaller than the size of the screen (in my case 1366x768).

I am running Cinnamon 3.0.5.

**Comment by f2404** [comment]
Yep, I've experienced the same.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/muffin/commit/3ec71cb49328578f5848fa95bf672056ad420fc1 (awaiting update)

**Comment by germanfr** [comment]
Wow, what a great fix. At least it will only happen with windows twice the size of the screen.

**Comment by mtwebster** [comment]
Thanks for the edit...

A little background on this,

The reason this 'check' is there is because at some point half a year ago the chrome/chromium dev window started requesting ridiculous-sized windows (something like millions of pixels wide x 40 tall) when you drag and drop (https://github.com/linuxmint/Cinnamon/issues/4789) - nvidia cards could handle it, but intel graphics would just die.

Btw screen size means the total size of all monitors - so with 2 monitors the maximum shadow width will be 2x the total with of both monitors.

**Comment by germanfr** [comment]
Nice, as long as it works.  What I meant is that that fix looks more like a patch than a fix. But I don't know how it really works.

_PS: I edited my reply because I read it twice and seemed so rude (and that wasn't my intention). Sorry if I bothered you._
