### ISSUE TITLE
Cinnamon is making my Qt apps look ugly by overriding QT_STYLE_OVERRIDE

### ISSUE THREAD

**Issue by pmts** [linuxmint/Cinnamon#5440]
I'm using Cinnamon on Gentoo Linux. I have set QT_STYLE_OVERRIDE=adwaita in my global environment. Unfortunately, when I start Cinnamon, it gets overridden to QT_STYLE_OVERRIDE=gtk, which makes all Qt apps look hideous. 

I tried putting my version of this variable in .bashrc and .profile, but that only helps with Qt apps started from command line. I could not figure out how to make Cinnamon launch Qt apps with the adwaita theme.

**Comment by ManuelSchneid3r** [comment]
This should be an issue of [cinnamon-session](https://github.com/linuxmint/cinnamon-session/blob/96f25057cac202e13c338886d00bc0383394ad26/cinnamon-session/main.c#L387)

This is due to Qt [5.7](https://github.com/qt/qtbase/commit/899a815414e95da8d9429a4a4f4d7094e49cfc55)

New style override variable seems to be ["gtk2"](https://github.com/qt/qtstyleplugins/blob/master/src/plugins/styles/gtk2/gtk2.json)

**Comment by two-dogs** [comment]
rather than try to make the qt app conform to gtk install qt5ct (qt5 configuration manager) and  allow the app to render in qt as it was suppose to

**Comment by ManuelSchneid3r** [comment]
Everyone in the internet spreads this shit. Im sick of it. A random app that themes your toolkit. I want a proper solution. Why not just use the gtkstyle Qt provides in its qt5stylesplugin?

**Comment by leigh123linux** [comment]
I am using this patch for fedora

http://pkgs.fedoraproject.org/cgit/rpms/cinnamon-session.git/tree/fix_qt_override.patch

**Comment by ManuelSchneid3r** [comment]
@leigh123linux Well this patch depends on qt5ct.

Please do not add  qt dependencies. Just drop the line. The whole point of an env var is to be the environment not an integral part of the executable. Set it in /etc/environment or somewhere else.

I opened an [issue](https://github.com/linuxmint/cinnamon-session/issues/76) in the correct repo. This issue can be closed.

**Comment by leigh123linux** [comment]
@ManuelSchneid3r 

If qt5ct isn't installed it defaults to whatever theme qt sets as default.
As for your gtk2 idea, that requires qtstyleplugins to function! (don't try to be a smart arse because your crap at it).

**Comment by ManuelSchneid3r** [comment]
Kind words thank you. As opposed to you I bring constructive ideas to the discussion. I just factually criticized your patch. No try to be smart-arse.
However this is a plain gtk project. qt5ct is a Qt application. Let the decision be up to the devs.
Of course qtstylesplugin is necessary, since qt moved the whole gtk stuff away from base into this plugin. From the changelog I linked:
> [ChangeLog][QtWidgets] Remove QGtkStyle, it is now provided in qtstyleplugins repository.

(don't try to be a smart arse because your crap at it).

**Comment by leigh123linux** [comment]
My patch offers choice for the user to set theme in /etc/environment if not set it sets qt5ct  which enables the user the choice of theme using qt5ct to set it.

P.S I don't see an ideal solution to this issue, theming qt sucks

**Comment by ManuelSchneid3r** [comment]
Almost three months for a single line. Has cinnamon been abandoned?

**Comment by two-dogs** [comment]
@ManuelSchneid3r ,  i googled it, not abandoned.

**Comment by ManuelSchneid3r** [comment]
@two-dogs this was rather jokingly since nothing happened with this issue, althought it does (will for mint users) affect everybody.

**Comment by leigh123linux** [comment]
@ManuelSchneid3r It's fixed

https://github.com/linuxmint/cinnamon-session/commit/7c34ec9028c5f7b01e5393aeff78cc7e9a0cc8b5

If your distro package maintainer is to lazy to patch your using the wrong distro

**Comment by clefebvre** [comment]
No need for the harsh words. Relax guys :)

I think the commit shown above fixes the issue indeed. The problem in 3.0 is that it tackled QT styling before 5.7  issues emerged and also that it didn't check if the variable was already set.

This fix will be part of 3.2. You can also apply the commit as a patch if you need it in 3.0.

If it's alright with everybody I'll close the issue.

@ManuelSchneid3r is right, the issue should be on cinnamon-session. But the discussion is here and they're duplicates, so I'll close the cinnamon-session issue right now.

**Comment by JosephMcc** [comment]
It might really belong to cinnamon-session but I don't think a typical user understands all the different parts that make up Cinnamon. That's why I don't usually ask for these to be moved unless they belong to Nemo.

Part of me wonders if it wouldn't almost be easier to consolidate all Cinnamon issues/feature requests here and have them in one place (minus Nemo).

**Comment by leigh123linux** [comment]
Fixed by https://github.com/linuxmint/cinnamon-session/pull/75

**Comment by ManuelSchneid3r** [comment]
As I said qt5ct will fuck up everything. Qt now ships with 5.7.1 and qt5ct is still compiled against 5.7.0. Every Qt application now fails starting, printing "FATAL: Cannot mix incompatible Qt library (version 0x50700) with this library (version 0x50701)".

**Comment by leigh123linux** [comment]
QT5 is a total fuck up, it has lame HIDPI and piss poor theme support for gtk.

@ManuelSchneid3r 
I thought fusion was the default set by qt5ct?

**Comment by ManuelSchneid3r** [comment]
Yes somehow qt is a pain, but indispensable though :smile:. The single problem is that they dont support gtk styles  anymore. I dont know which default qt5ct sets. I hope gtk since this is the single reason qt5ct is needed. Fusion is shipped as one of the standard styles with qt.
Actually i find HIDPI support is not that bad, it handles HiDPI like Gtk by [scaling things](http://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt). Just out of interest, why do you think it is bad?
Shortly after I wrote that above I realized that this will not be much of a problem for linux mint, since you hold back the packages and  hopefully dont run into this incompatibilities.
