### ISSUE TITLE
Click on the title bar to raise a window

### ISSUE THREAD

**Issue by jyboisiaud** [linuxmint/cinnamon#5450]
cinnamon version: 3.0.6

clicking in a background window raises it into foreground, even if windows focus mode is sloppy

feature request:
- clicking in a background window title bar (or any part of the window manager of the background window) raises it into foreground
- clicking in the application part of a background window do not raise it to foreground

**Comment by HenrikStevn** [comment]
+1 this feature was removed in Gnome for silly reasons a long time ago ("removed" as in moved to regedit.exe/gconf).

Please reinstate it into Cinnamon, it is an essential feature for many users. KWin can do it just fine, why not Cinnamon?

**Comment by defnull** [comment]
Yes please. This is very helpful for example if you have an IDE in full-screen (because it needs the space) and a console window open at the same time. I want to keep the console window in foreground most of the time, even if I'm interacting with the IDE, but not always.

Currently I have to lock the console window in foreground and have to minimize it to get rid of it. Minimizing is annoying, because it's hard to find the correct console again if I have several open at the same time. Disabling foreground-lock takes several clicks and is annoying, too.

With the old behavior that could be enabled in gnome2 (Raise window only on click in title-bar, not on focus or click into the window. Move to background with Ctrl+click in title-bar) this is more fluent. I have a lot more control over the window ordering, because it never changes on its own or as a side-effect of focus-change.

I would just click the IDE title-bar to remove the console and also give back focus to the IDE, and use Ctrl+tab to find the console again. The last part would work even better if the Alt+Tab overview would indicate the original size and position of the selected window. The current solution (show icons only, and window thumbnail after a delay) does not work well for console windows. It's to small to read the content, and sometimes there are a lot of consoles open. I personally like to identify the console I'm looking for based on size/position.

**Comment by JosephMcc** [comment]
For alt-tab, in Cinnamon Settings->Windows on the Alt-Tab page try changing the style to "Window preview"

**Comment by dg1727** [comment]
Maybe this should be considered a bug report instead of a feature request.  

Currently [LMDE 2, Jan. 2017 beta - /usr/bin/cinnamon is at version 3.2.7], the "Windows" settings window, Behavior tab, starts with the following 2 options:  
- Window focus mode [Click/Sloppy/Mouse] 
- Automatically raise focused windows [ON/OFF] 

If "Window focus mode" is set to Click and "Automatically raise focused windows" is set to OFF, then the user's choice for "Automatically raise..." doesn't take effect, which I think qualifies this as a bug.  That is, focused windows are automatically raised even though the user asked for them not to be.  

User "defnull" outlines a very similar situation as to what I use on a daily basis.  In fact, it was a problem in referring to the "Windows" settings window while I was writing this comment with my Web browser maximized.  

The requested operation mode has been a fixture in Linux/Unix window managers including XFWM 4.10 and dating back a couple of decades.  An implementation of it in Cinnamon would be very helpful.  :-)

If there's something I'm missing in the Cinnamon UI, please let me know.

**Comment by zakwilson** [comment]
I just switched to Cinnamon and ran into the same issue. The raise-to-click setting is ignored if the window focus mode is click. I want to click inside a window to focus, but only raise when clicking the frame, using alt+tab, the panel task switcher, etc.... This is a significant productivity enhancement for me.

I suppose I can use kwin, but it doesn't seem like this should be hard to implement.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
