### ISSUE TITLE
Problem creating shortcuts with super-key (win-key/mod4)

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#549]
I have set up the shortcut to launch "Home folder" as Mod4+E (corresponds to super+e (or winkey+e)), but to actually open my home folder I need to press super+e+e . When pressing super+e (or most other letters) I get a small gray input box in the buttom left corner, which is almost complety covered by the buttom panel. Super+d works fine for showing the desktop.

**Comment by szarnyasg** [comment]
This did not work for me in Linux Mint 17, however, it does work with a fresh install of Linux Mint 17.1 (Cinnamon 2.4.5).
Note: It did **not** work after updating from 17 to 17.1 with this method -- <http://linuxg.net/how-to-properly-upgrade-from-linux-mint-17-qiana-to-linux-mint-17-1-rebecca-via-command-line/>.

**Comment by RaphaelBrugier** [comment]
Hi, 
In Mint 17, I used to remove the overlay key binding with this command :
`gsettings set org.cinnamon.desktop.keybindings.wm overlay-key ''`

But this option does not exist anymore in mint 17.1

Thanks to @mtwebster comment that link to its commit I have now understand the option has moved to the applet configuration itself.

Problem solved !

**Comment by Kolyunya** [comment]
Still not solved in 2.2.16. The shortcut `Super-Y` triggers only after `Super-X-Y`.
Should the issue be reopened maybe?

**Comment by mtwebster** [comment]
Cinnamon is at 2.6 now, you need to upgrade, we don't backport fixes like this generally.  What distro are you on?

**Comment by Kolyunya** [comment]
@mtwebster thanks for a quick reply. I'm on a fresh Debian 8 and we still only have 2.2.16 here.
By the way I've managed to kinda fix the issue by enabling the `Hyper is mapped to Win keys` option but I'm not quite sure why and how this fixes the problem and won't it break something else.
Do `Super-X` shortcuts work as expected out of box in 2.6?

**Comment by mtwebster** [comment]
Yes-  this issue is definitely fixed in 2.6.

testing and unstable both have 2.6 - I'm not sure if that's an option for you.  Unfortunately the timing was bad pre-8 for getting a newer version into Jessie (stable).

**Comment by margamanterola** [comment]
As part of the team maintaining cinnamon in Debian, we do intend to provide a Jessie backport of 2.6, but we've been busy with other stuff until now and haven't been able to.  Hopefully not much longer now.

**Comment by gsobczyk** [comment]
Hi. I have the same problem:

1. I've already installed mint 17.3 with cinnamon-2.8.6+rosa.
1. I've installed guake 
1. assign Win+grave (` key)


**Result:**

1. pressing Win+grave key doesn't trigger guake (I must press Win+grave+grave)
1. when focus is in guake I must press Win+grave+grave to hide it (but it print ` in terminal)

**Question:**

How can I solve this?

**Comment by mtwebster** [comment]
Disable the binding in guake,

Open Cinnamon settings->Keyboard, go to the shortcuts tab.

Add a new custom shortcut:

Call it: `guake toggle`
Command: `guake -t`

Assign it super-` there.  It should work.

**Comment by gsobczyk** [comment]
thx, it works!

**Comment by eric-tucker** [comment]
Ubuntu, Cinnamon 2.8.6.  I just want to rebind Super + Up/Down to switching workspaces up/down.  I've tried editing using the default shortcut editor and dconf-editor but I can't seem to get it to work.  Thoughts?

**Comment by hanzo2001** [comment]
### Mint 18 Sara
I don't know if this is solved but my shortcuts with `Super` aren't working. When I use the **Keyboard-Shortcuts** tool to set them up, `Super` is actually named `mod4`

**Comment by userid** [comment]
try this:
Menu -> Preferences -> Keyboard -> Layout Settings

click on "Options" on the right,
"Alt/Win key behaviour"
Change it from Default to "Hyper is mapped to Win-keys"

**Comment by c02y** [comment]
@userid 

I use sxhkd for launching programs, and I got several keybindings of `Super` + other keys like `super + k` for kitty, `super + a` for fsearch, but since `cinnamon menu` is using `Supper` key by default or my habit, all the keybindings with `super` key in my sxhkd are only  triggered when I hit `super + x` the second or the third time, they are never triggered for the first time I hit the key. Other keybindings without using `super` such as `F12` is OK, or other keybindings using `super` configured without sxhkd(such as set in System Setting Manager) such as `Super + t` for terminal are OK too.

1. sxhkd is working fine with XFCE
2. if I change the key for cinnamon menu to other key like `super + q`, the `super` keybindings in my sxhkds are working fine.

After seaching for a while, I found this post,

And I tried 
> try this:
Menu -> Preferences -> Keyboard -> Layout Settings
click on "Options" on the right,
"Alt/Win key behavior"
Change it from Default to "Hyper is mapped to Win-keys"

after that it works for sxhkd keybindings, but `Super` key is not working for Cinnamon menu, then I tried other options in that list, Single `Super` seems to conflict with keybindings like `Super + k` in my sxhkd after all.

**Comment by jexxadox** [comment]
I was trying cinnamon out on another distro. cannot get it to register the super key, much less bind it to anything. this is kind of a deal breaker. when i try to set it as a shortcut key it shows "oxf8" and won't let me hold it to bind another key to it. I was under the impression that the super key was heavily used for shortcuts.
