### ISSUE TITLE
The API applets can make such a bubble popup

### ISSUE THREAD

**Issue by lukaszpolowczyk** [linuxmint/Cinnamon#5490]
The API applets can make such a bubble popup. How to make your own, so that its contents could fill any complex layout elements GTK UI XML or HTML and CSS?

It's about something more complicated than a simple vertical menu.

Example
http://i.stack.imgur.com/9zSbJ.jpg

In the documentation I can't find a solution.

**Comment by xenopeek** [comment]
You could look at the code of any other applet, like the menu (it's also an applet), that does something similar to what you want.

**Comment by JosephMcc** [comment]
The best place to get feedback for this type of thing is #linuxmint-dev on IRC. There you can speak to a developer that might be able to ask you the right questions and maybe point you in the right direction. Just be patient since the devs don't always have an eye on the IRC window and can some times take a while to respond.
