### ISSUE TITLE
Cinnamon not correctly responding on clicks 

### ISSUE THREAD

**Issue by msambg** [linuxmint/Cinnamon#5509]
We have a set of 16 DELL T5810 Precision Workstations.

In a fresh Linux Mint 18 Sarah installation (Cinnamon, every pc has the same image ) it happens from time to time on different machines that the mouse doesn't react on clicks anymore, and also keyboard commands are not interpreted right. 

So it seems as the desktop  is frozen, but that's not really frozen. You can move the mouse, click on some menus. which may expand or not, but you are not able to select anything, press buttons or move Windows . 

Also keyboard seems not to react correctly in keypresses concerning the GUI. e.g. Alt-Tab is not working. 

But you can do an Ctrl-Alt-F1, login in as new user and startx where everything is working correctly. You can switch between the two Desktops with Ctrl-Alt-F8 and  Ctrl-Alt-F1 where one is working correctly, the other still not responding. 

System:    Kernel: 4.4.0-28-generic x86_64 (64 bit gcc: 5.3.1) Console: tty 0
           Distro: Linux Mint 18 Sarah

Machine:   System: Dell product: Precision Tower 5810
           Mobo: Dell model: 0HHV7N v: A00 Bios: Dell v: A13 date: 05/20/2016

CPU:       Quad core Intel Xeon E5-1620 v3 (-HT-MCP-) cache: 10240 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 27933
           clock speeds: max: 3600 MHz 1: 1927 MHz 2: 1646 MHz 3: 1201 MHz 4: 1468 MHz 5: 1721 MHz 6: 1529 MHz
           7: 1543 MHz 8: 1204 MHz

Graphics:  Card: Advanced Micro Devices [AMD/ATI] Oland GL [FirePro W2100] bus-ID: 02:00.0
           Display Server: X.org 1.18.3 drivers: ati,radeon (unloaded: fbdev,vesa)
           tty size: 238x66 Advanced Data: N/A out of X

**Comment by mainmachine** [comment]
Same behavior on Ubuntu 16.04, Cinnamon 3.0.6 from the Kranich Stable PPA

Running on an AMD APU and Nvidia GPU, so it looks like this is not hardware specific

There are several other bug reports that I think are the same as this, but @msambg has done the best job of describing the error

It's like a freeze of the UI, except for the mouse cursor...

**Comment by mainmachine** [comment]
So for me it looks like after about an hour after a fresh boot (or restart of cinnamon) the phenomena occurs.

Looking at htop, "cinnamon --replace" has six threads, or one main thread with five children...? Not exactly sure how to interpret htop, other than if you hit the "t" key it arranges all processes heirarchically.

On a fresh start, each process is using 0.0% CPU and 193M RAM "reserved". After ~1 hour has passed, I am seeing CPU occasionally spike, but a steady avg of 2-3% for the "main" process, and RAM usage goes up as well - I'll post a sample next time it reaches this state.

Interestingly, when I run a game full screen, I do not see any indication of this issue, which makes sense since I have "Disable compositing for full-screen windows enabled" - this points to an issue with cinnamon itself.

Happy to post any logs, or gather any information that will help. I leave this machine running pretty much 24/7, so I can leave something running to gather data...

**Comment by mainmachine** [comment]
FYI, my issues were completely resolved (over a week of non-stop runtime, several days at a time, more than long enough to draw out the bug) after I upgraded to Cinnamon 3.0.7, and Nvidia drivers 370.23 (from 367.35) - I'm sorry but I don't know which one fixed the issue, or if it was an interaction of the two. Perhaps my bug was unrelated, although I was running on the 367.35 driver prior to 3.0.6 with no issues, so I suspect it is the Cinnamon upgrade that did it in my case.

**Comment by JosephMcc** [comment]
@msambg are you still encountering this issue?
