### ISSUE TITLE
Idea: Global Menu

### ISSUE THREAD

**Issue by seaweedchan** [linuxmint/Cinnamon#551]
No idea how hard this would be to implement, but shouldn't most applications already have support for it because of Unity?

A native global menu as an applet would be amazing, especially for those users who aren't on Ubuntu like myself.

**Comment by lestcape** [comment]
https://github.com/linuxmint/Cinnamon/issues/3032#issuecomment-76527610

**Comment by Wamnseln** [comment]
Any news?

**Comment by lestcape** [comment]
As i know, the only news will be here: https://github.com/lestcape/Global-AppMenu
 
As resume:
   - I can not find a way to prevent firefox for drop the appmenu.
   - Gtk application depend of some enviroment variables that i can set in the applet, but is to late for nemo to see this variables (nemo started before the applet). So, need to be set as a cinnamon enviroment when the session init or otherwise i can try to execute nemo -q and nemo -n to restat nemo if the applet will start with the cinnamon session, but for some reason this not work as need to be...
  - Gtk application are now exported the menu on dbus but i currently can not parse well the dbus response, so the menus are not constructed propertly (this is not a big problem and is only for gtk application, will be fixed).
 -Right now I don't ask any thing to the Dbus iface for the gtk action, so i don't know if i can handled properly the gtk action when i finish the gtk parse for the appmenu.
 - I can not find a way to hide the menubar for gtk application, possible solution could be re-exported the gtk iface to the unity equivalent and let the unity code do that for me. I this case i'm working for nothing to display the gtk menu, but is possible that i can use a similar code of maximum extension to only undecorate the menubar, without re-exported the menu. I don't know right now.
- I need to implement a new popup menu structure that allow multiples open menus at same time.
- The rest of things will be try to fix specific bugs of some applications, general little bugs, memory problems, signals that not removed and remap the popup menu structure to use the new one.

**Comment by lestcape** [comment]
How i can set  "gtk-shell-shows-menubar" to be effective for gtk widgets?

I set this without effect in :
```
     ~/.config/gtk-3.0/settings.ini
     ~/.config/gtk-2.0/settings.ini
      /etc/gtk-3.0/settings.ini
```

also without effect over the js code:
```
        let gtk_settings = Gtk.Settings.get_default();
        gtk_settings.set_property('gtk-shell-shows-menubar', true);
```
The last code create problems when i try to restart cinnamon... Nemo and gedit crash... suggestion?

Thanks

**Comment by mtwebster** [comment]
Perhaps you need to something like this: https://git.gnome.org/browse/gnome-settings-daemon/commit/plugins/xsettings?h=gnome-3-10&id=4c8902a8f10a78ad67b1443ef9039dda526238e8

to cinnamon-settings-daemon..but for ShellShowsMenubar?  Right now it appears that we always set it to false: https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/xsettings/csd-xsettings-manager.c#L985 but I had always understood our c-s-d settings were overridden by settings.ini, and, like you tried, GtkSettings.

Still, maybe this will help a bit figuring it out.

**Comment by mtwebster** [comment]
Was this an ubuntu invention?  I see nothing in gnome git referring to it.  Have you taken a look at mutter/gnome-shell/gnome-s-d *ubuntu* sources?  Probably as quilt patches.

**Comment by lestcape** [comment]
Thanks, what i read is that ubuntu patch the gnome-settings-daemon to allow this... But also that could be enable as global (thats is not possible on cinnamon, maybe because is set to false). Is a big hint... I will looking into it. Thanks.

**Comment by lestcape** [comment]
If this was a ubuntu invention, right now its not. https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-shell-shows-menubar

**Comment by lestcape** [comment]
Yes exactly because cinnamon put to false this is not working(i remove this lines, reinstalled the packages and is working). Is not ok to me change this, if is not a cinnamon intention, but i will be happy if will exist a way to change the values(appmenu and menu bar), as a user decision, otherwise the global menu could not have senses (duplicate the menu is not useful). I let this to the cinnamon devs decision and will be ok to me any of decision, but i appreciate to know. I can stop working for nothing in this case.
Thanks.

**Comment by mtwebster** [comment]
I have no issue making it usable.  We just never thought anyone would want it (we didn't) - Why not do something similar to the ShowAppMenu commit I linked above, only we can add a "AppMenuProvider" dbus interface that an applet would need to implement, instead of detecting shell/cinnamon - maybe such an interface has already been done elsewhere?  This would need to be of utmost reliability.

**Comment by lestcape** [comment]
I don't know if there are an interface. I think that there are several different implementations only.

I think, that this is the problem. Not all application can export the menu well. Ubuntu have a individual patch for several application to fix this problem. I don't know if Mint used the same ubuntu source or other in this applications. Also on ubuntu, the patch is private to unity session. On kde for Arch they using the ubuntu module, but recently was dropped when ubuntu changed the name to unity-gtk-module and now they use another different solution. The unity-gtk-module has not problem (only the name) and could be installed on Mint and it's working. Also on Arch for xfce @rilian-la-te patch the unity-gtk-module in another way. Finally there are several implementations for an specific distro and desktop. I don't want to provide another more (is to much) but i can not prevent what the others distros would want to do, so i think that i cannot give any warranty. Maybe find a solution for Mint only.

Is possible that the dbus communication not work, because the applet only could access to the service after the nemo start, so this could be too late and not useful then, but maybe thats could be changed dynamically without crash cinnamon or gtk applications, need to be tested. My current experience is that change this values when the application are running could cause problems.

Use these values directly from the gtk settings files also is not an option, could create collisions to other desktop enviroments.

I think could be a possibility add this values to gsettings as a cinnamon property and enable or disable when cinnamon setting daemon start is the most secure way i think...

**Comment by rilian-la-te** [comment]
My patch can be used on Cinnamon also. It is only move from GtkSettings to
GSettings.

**Comment by lestcape** [comment]
@mtwebster this is the server class to test the efect of this commit :
https://github.com/linuxmint/cinnamon-settings-daemon/pull/84

```
const Gio = imports.gi.Gio;
const GLib = imports.gi.GLib;

const WATCHER_INTERFACE_SHELL = 'org.Cinnamon.MenuShell';
const WATCHER_OBJECT_SHELL = '/org/Cinnamon/MenuShell';

const DBusMenuShellIface = 
    '<node> \
        <interface name="org.Cinnamon.MenuShell"> \
            <!-- Functions --> \
            <!-- Signals --> \
            <signal name="ShellShowAppMenu"> \
                 <arg type="(b)" name="show" /> \
            </signal> \
            <signal name="ShellShowMenuBar"> \
                 <arg type="(b)" name="show" /> \
            </signal> \
        </interface> \
    </node>';


function DBusMenushell() {
    this._init.apply(this, arguments);
}

DBusMenushell.prototype = {

    _init: function() {
        this._dbusImpl = Gio.DBusExportedObject.wrapJSObject(DBusMenuShellIface, this);
        this._dbusImpl.export(Gio.DBus.session, WATCHER_OBJECT_SHELL);
        this._everAcquiredName = false;
        this._ownName = Gio.DBus.session.own_name(WATCHER_INTERFACE_SHELL,
                                  Gio.BusNameOwnerFlags.NONE,
                                  Lang.bind(this, this._acquiredName),
                                  Lang.bind(this, this._lostName));
    },

    EmitShellShowAppMenu: function(show) {
        this._dbusImpl.emit_signal('ShellShowAppMenu', GLib.Variant.new('(b)', [show]));
    },

    EmitShellShowMenuBar: function(show) {
        this._dbusImpl.emit_signal('ShellShowMenuBar', GLib.Variant.new('(b)', [show]));
    },

    _acquiredName: function() {
        this._everAcquiredName = true;
        global.log('Acquired name ' + WATCHER_INTERFACE_SHELL);
        this.EmitShellShowAppMenu(true);
        this.EmitShellShowMenuBar(true);
    },

    _lostName: function() {
        if (this._everAcquiredName)
            global.log('Lost name ' + WATCHER_INTERFACE_SHELL);
        else
            global.logWarning('Failed to acquire ' + WATCHER_INTERFACE);
    }
};
```

Recommendations? where will be the server class? Will be a part of org.Cinnamon services as a new iface inside the main service iface? On the client services and iface are now the same, but this can be changed as a recommendation.

Thanks.

**Comment by lestcape** [comment]
@rilian-la-te my idea is used the unity-gtk-module directly without need a patch, to can be installed on mint by default and not create problems on ubuntu at the same time. Your patch is what currently we are doing here, but directly over cinnamon-settings-daemon, as unity an gnome shell do...

**Comment by lestcape** [comment]
A reference to the Unity patch:  https://github.com/linuxmint/cinnamon-settings-daemon/blob/7ae74fe755e4dc0de30f74f1e9aa3a78e94ee1e5/debian/patches/90_set_gmenus_xsettings.patch

**Comment by lestcape** [comment]
This is currently directly possible https://github.com/linuxmint/cinnamon-settings-daemon/blob/7ae74fe755e4dc0de30f74f1e9aa3a78e94ee1e5/data/org.cinnamon.settings-daemon.plugins.xsettings.gschema.xml.in.in#L38

cjs code:
```
        let value = GLib.Variant.new('a{sv}', { 'Gtk/ShellShowsAppMenu': GLib.Variant.new('i', shellShow) });
        let xsetting = new Gio.Settings({ schema: 'org.cinnamon.settings-daemon.plugins.xsettings' });
        xsetting.set_value('overrides', value);

        let value = GLib.Variant.new('a{sv}', { 'Gtk/ShellShowsMenubar': GLib.Variant.new('i', shellShow) });
        let xsetting = new Gio.Settings({ schema: 'org.cinnamon.settings-daemon.plugins.xsettings' });
        xsetting.set_value('overrides', value);
```

where  shellShow will be 1 to enable and 0 to disable, i will remove my pull request, is redundant...

**Comment by lestcape** [comment]
Published what i have here: http://cinnamon-spices.linuxmint.com/applets/view/229
Please note, that the global menu took a long time to work on ubuntu properly, and is normally that several application do not export the menu or will export just some part of it. I will appreciate feedback by the people who are interested on this, because this is not interesting for me and I will not use it, so i can not detect what is wrong. Wherever i will try to fix will be then, for an specific request of a user. 

If someone is interested on continue the development of this applet properly, I also will be happy to help in it.

Regards.
