### ISSUE TITLE
[Archlinux, Cinnamon 3.0.7] Startup tray issues.

### ISSUE THREAD

**Issue by kolorafa** [linuxmint/Cinnamon#5525]
**When booting up Cinnamon a lot of tray icons doesn't appear.
Looks like the icon applet start to late and other apps fail to add icons.**

For example:
Skype randomly show up (if it doesn't it sill running but without icon, i need to restart skype to fix it)
Synergy always die with message "System tray unavailable. Quitting." so i need to run Synergy one more time to show and run.

Is there a way to fix this other than making huge delay on startup apps?

I have spinning disk on that notebook so it slows down loading and probably make the difference that apps starts before tray applet, but that's my educated quess.

**Comment by two-dogs** [comment]
@kolorafa , i would look at the output of 'looking glass' log

**Comment by kolorafa** [comment]
Sorry for the delay.

I have this problem every boot. On both of my linux arch machines.

http://kolorafa.firehost.pl/test/snapshot-2016-08-19-19-21-23.png

![](http://kolorafa.firehost.pl/test/snapshot-2016-08-19-19-21-23.png)


attaching glass.log (don't see any errors)

like you see on screenshot, the skype is running but not showing
the syncthing-gtk is running but the icon is blank
i will install synergy on this machine too later

[glass.log.txt](https://github.com/linuxmint/Cinnamon/files/427538/glass.log.txt)

**Comment by kolorafa** [comment]
Just to mention, the cinnamon was installed as a second Desktop Enviroment on those machines.

Also kadu, running but no icon like skype.

**Comment by mainmachine** [comment]
The apps that don't show up - are they apps that require authentication or superuser creds to run?

I had a similar problem with Owncloud client - it would run but no icon in the system tray. I had to install libgnome-keyring for it to show up, IIRC. This is on Ubuntu, not sure what the package name would be on arch.

Do you have "system tray" listed in Settings > Applets?

**Comment by kolorafa** [comment]
The problem is only about the timing

If i add delay in apps startup settings, so they start later, then the icons appear without any problem.
So it looks like cinnamon traybar starts to load, other apps starts to load, and the other apps try to "access" the tray  and got "not found" because they tray isn't loaded at that time.

The apps doesn't require any additional stuff, because skype and kadu don't use keyring, and Synergy clearly say in 'Window Message' that "No tray found, exiting" because it requires the tray, it will not work in background without tray icon.

But like i said - after adding  5(seconds?) delay in the control panel to those apps, they appear normally.

**Comment by mainmachine** [comment]
OK, so it is indeed a race condition. Maybe the devs. haven't tested on an HDD...?

Still, I would think that the tray would load up first, as all applications would be starting at the same relative times...

If you're really looking to up the loading speed, I think your only option is to either implement a delay, get an SSD, or dig into the code...

The only thing you could change in the code would be to delay applets form loading until the tray is loaded, so it's not much better than just manually adding a delay as you are doing...

**Comment by kolorafa** [comment]
The fun part is that the problem is the same on my new Laptop (i7 + HDD) and my old workstation (old xeon cpu and SSD).

Both of them run Arch (antergos), both of them was installed with gnome and after that installed cinnamon.

Maybe because the cinnamon was installed second is the problem occurs?

**Comment by mainmachine** [comment]
Hmmm... now that you mention it I do remember a conflict between Cinnamon and Gnome, probably because they are so closely related - I used to run Lubuntu with Cinnamon, then when Ubuntu-Mate was oiffical I've tried that with Cinnamon and liked it much more. Lubuntu's setting did weird things to Cinnamon sometimes, and I think the Mate/Cinnamon shared Mint relationship has kept those two in a state where they "play nice" with each other.

I did have Gnome and Cinnamon installed together, and it did cause problems - I can't remember what, but they both use gsettings in different ways, general GTK settings don't always have a desired effect on the other desktop, etc.

You could purge Gnome and then reinstall Cinnamon... or just look for gnome-system-tray (or whatever it might be called) as, maybe that's conflicting...?

**Comment by lestcape** [comment]
cinnamon-settings-damemon and gnome-settings-daemon have some restriction to no run on unity some things, but i don't see a restriction like: only run in cinnamon or only run in gnome shell desktop. Thats probably because other desktop use the gnome settings daemon, like it's more less generic. Both daemons at the same time, could be a problem.

Anyway, @kolorafa this is with indicators or status icons?
 
Status:
![alt tag](https://cloud.githubusercontent.com/assets/1121642/16687875/5f868ae2-451b-11e6-9bf9-4a82047447b1.png)

Indicators:
![alt tag](https://cloud.githubusercontent.com/assets/1121642/16687876/5f9eb766-451b-11e6-8ebd-b44957b677dd.png)

**Comment by kolorafa** [comment]
Different looks depending on icon (using dark mode, and most of them show higher than clicked - probably because my left (secondary) display have smaller resolution):

Audacious:

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-21-07-41-19.png)

HotShots:

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-21-07-46-00.png)

Kadu:

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-21-07-42-19.png)

Syncthing:

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-21-07-43-32.png)

Volume control:

![](http://kolorafa.firehost.pl/test/snapshot-2016-10-21-07-50-45.png)






But the problem with not showing icons is only on applications icon (skype, syncthing, ....) i needed to delay those app to show correctly, never got this problem with cinnamon icons (sound, network, ...)

**Comment by lestcape** [comment]
Ok, it's with status icons...

**Comment by two-dogs** [comment]
https://github.com/linuxmint/Cinnamon/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3ABUG%20systray

a tag to keyword/s 'systray' and 'bug'

**Comment by kolorafa** [comment]
My friend on Linux Mint 18 Cinnamon have the same problem.

The problem occur on older hardware with ssd so the CPU is the bottleneck and only occure when you have to much apps starting at once at boot (0s delay).

**Comment by filbar** [comment]
I have this problem too on Fedora 25

**Comment by leigh123linux** [comment]
Anyone want to test the pull request?

**Comment by leigh123linux** [comment]
I'm closing the issue here as the autostart code is in cinnamon-session, please file the issue there instead.
