### ISSUE TITLE
Cinnamon "burps" every about 30 seconds

### ISSUE THREAD

**Issue by tomwix** [linuxmint/Cinnamon#5532]
I'm running Linux Mint 18
I'm experiencing an annoying behavior in which every 30 seconds (I measured), anything displayed on the screen at the moment freezes for a half a second. This is particularly annoying while watching a film or playing a game. This issue does not affect sound and appears to not affect any other processes.
The exact same issue has happened to me on my old laptop running 17.1. (Both are Dell laptops, old one is an i5 processor, current is i7)

So far I couldn't find any relevant log that may point towards the issue. I will supply any log or extra data needed on demand.

Can anyone think of a process that runs constantly and does something heavy every 30 seconds?

**Comment by JosephMcc** [comment]
Are you running any 3rd party applets, like system monitor applets?

**Comment by mainmachine** [comment]
I've noticed something similar on 3.0.6 - just switched from 2.8.6, been running since before 2.0.

Everything is great at boot (or restart of Cinnamon), but after some period of time, a UI freeze occurs. Mouse cursor still moves, but keyboard response is "delayed", so for instance if I type a command in a terminal, it doesn't update as I'm typing, but then once the freeze is over the output types in really fast, if you follow...

If I'm SSH'd in, or on a different VT, there's no indication of any kind of problem, so it looks to be Cinnamon specific. I use the Multicore monitor applet, but I've tried disabling that and restarting cinnamon with no change in result.

Sorry if I'm hijacking, but the timing of @tomwix's report seems to coincide with my experience - this just started happening very recently.

I'm on Ubuntu 16.04 using the Kranich PPA, which currently has 3.0.6 stable build.

**Comment by mainmachine** [comment]
@tomwix - I think my symtpoms look to be exactly this: 

https://github.com/linuxmint/Cinnamon/issues/5509

Are you seeing this as well, or is your situation different?

**Comment by tomwix** [comment]
No, this is not the same issue. Though I did had it from time to time on my previous laptop

**Comment by JosephMcc** [comment]
@tomwix You never did answer the question about any third party xlets you might have running on Cinnamon.

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by SjoerdV** [comment]
@Vahan86 @JosephMcc Wow 7.5 years later and... I have exactly the same issue as reported here: a short hang (including input devices and screens) every 30 seconds. It goes away if I logout and login again. First I thought it was something intel/nvidia did with their modules/drivers, but it seems cinnamon does something unique here.

It is also intermittent: when I fiddle around with xrandr and when coming out of S3 sleep mode (maybe both are needed to trigger this issue, not sure)

Nothing in the journal though.

I'm on LMDE 6 fully updated (Kernel: 6.1.0-18-amd64), dell xps15 laptop with nvidia optimus
But I experienced this behavior on earlier kernels as well.

I only have a single third party 'Scripts Menu' spice installed.

Would be nice to work with you to troubleshoot this!

**Comment by leigh123linux** [comment]
@SjoerdV  Start a new issue as this one has no useful info
