### ISSUE TITLE
"Chat room" fails to connect from the Welcome screen, out of the box

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5558]
I'm already online, but Hexchat (launched when I click on "Chat room" in the Welcome screen) fails to connect:

![image](https://cloud.githubusercontent.com/assets/33569/17687425/acbc9794-6329-11e6-86f8-bfff1f46811c.png)

**Comment by JosephMcc** [comment]
Ok, so I know you brought up the idea of some sort of README to help direct people to the proper place for reporting issues. But for now we don't have that. 

When you are talking about a mint tool that is shared across all Mint flavors then it is not a Cinnamon issue. In this case you should probably post this under Mint Welcome which you can find here: https://github.com/linuxmint/mintwelcome

In many cases it isn't that hard to decide where an issue belongs. You can see the full list of repos here: https://github.com/linuxmint

For Cinnamon we really don't expect people to know which Cinnamon repo to post under so just using the main Cinnamon one is fine. Really the only time you will be asked to move those is if they are nemo specific as we do try to keep the issues for those two separated since some users use nemo outside of Cinnamon.

Worse case, you'll be asked to move them to the appropriate place. Usually by me and I nearly always give a link.
