### ISSUE TITLE
Downloadable 'desktop themes' can be more than that

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/Cinnamon#5559]
Cinnamon gives users the ability to download what it calls 'desktop themes'. However, such themes - for instance, [this nice one](https://cinnamon-spices.linuxmint.com/themes/view/567) - can in fact contain 'control' themes too. Should this be made clearer to users? Or are those who created 'desktop' themes not meant to be branching out into 'controls'?

**Comment by JosephMcc** [comment]
> Should this be made clearer to users?

There is link to the spices page for the theme in the settings. We can't really control what a user provided xlet supplies as a description.

> Or are those who created 'desktop' themes not meant to be branching out into 'controls'?

That is really up to the theme dev. It's nice if they do and supply a full uniform theme. That is their decision to make though.

I'm going to close this since it isn't really a bug/feature request and we already have similar open issues that you could contribute ideas to if that's what you want to do. Like this one: https://github.com/linuxmint/Cinnamon/issues/3809
