### ISSUE TITLE
Poor UI for choosing time zone

### ISSUE THREAD

**Issue by jbergknoff** [linuxmint/cinnamon#5588]
Hi, I'm a big fan of Cinnamon. Please point me in the right direction if this is the wrong repository for this issue.

In the Cinnamon date/time settings (`cinnamon-settings calendar`), you choose a time zone by clicking your location on a world map or by selecting from an enormous dropdown list of cities. Both of these need work.

World map: this is unusable. The map is small. Trying to click on Texas gives me either Mexico City (wrong country -- chose this once by accident and wondered why daylight saving time wasn't being tracked), Matamoros (never heard of it), Indiana/Vincennes, Indiana/Tell City, or sometimes Chicago. Yes, the map could be made bigger, but this is a terrible way of selecting a time zone anyway. This could probably be made usable if you clicked the map to zoom in on a region, then it highlighted all of the time zones in that region in different colors, there was a visible hover state for each time zone, and you click the appropriate one.

Dropdown: this list (1) is huge, (2) is sorted inconsistently, but mostly alphabetically instead of by region, (3) cannot be navigated by keyboard, and (4) doesn't include all or even most major cities, at least in the US. No keyboard navigation is particularly painful. Instead of the list, the settings page could, for instance, accept a city name or a postal code.

While on the subject of date/time settings, the lock/unlock feature is a headache and doesn't seem to add any value (?).

Thanks for your consideration. I'd be happy to contribute some work towards these changes if there is interest in them.

**Comment by JosephMcc** [comment]
I have to admit this is one of those things I've never really messed with. I set it at install time and forget it.

Keyboard navigation seems to work fine for me if in the drop downs. I click the button with the mouse and can then scroll through with the arrow buttons. It even wraps back to the top when you hit the bottom.

I don't know how this works internally, maybe it's limited to only certain cities and doesn't allow using just anything. I live in Northern California but set it to Los Angeles because that is in the timezone that I want.

The lock feature is intentional so changes can only be made by an administrator. I doubt it's going anywhere.

**Comment by dandv** [comment]
Living in Californai, this has never bothered me, but I suppose it might be a problem for specific geographies.

However, GNOME's dialog (or wherever it comes from) has been highlighted as the best UX for picking a time zone (!):

http://ux.stackexchange.com/questions/5740/which-way-should-i-display-time-zone-names-to-make-them-easily-pickable/5742#5742

**Comment by leigh123linux** [comment]
Please report the issue against libtimezone as we no longer provide it within cinnamon code.
