### ISSUE TITLE
Shutdown menu - make Suspend the default on laptops

### ISSUE THREAD

**Issue by dandv** [linuxmint/Cinnamon#5589]
When I press the power button on my laptop, the vast majority of the time, I don't want to turn the machine off, but to suspend it. However, the default option in the list (Suspend, Restart, Cancel, Shut Down) is to Shut Down.

As a keyboard user, if I want to suspend the machine, you have to press the power button, then Left Arrow three times, then Enter. (That's because right arrow doesn't wrap around.)

Anyway, It would be great to make the default option Suspend, at least for laptops, if not regardless of the machine. Resuming from standby is far faster than booting up, and preserves the user's state - great reasons to encourage that, vs. rebooting. If the user does have the time to reboot, then one extra second to select Shut Down won't be a problem.

**Comment by leigh123linux** [comment]
> As a keyboard user, if I want to suspend the machine, you have to press the power button, then Left  Arrow three times, then Enter. (That's because right arrow doesn't wrap around.)


You could setup a keybinding to do that.

**Comment by JosephMcc** [comment]
Can't you just set the behavior you want in Cinnamon-setting->Power management->When the power button is pressed?

I certainly wouldn't want it to default to suspend over shut down. Mainly because many setups and combinations of hardware seem to have issues with suspend. Or at least resuming from it.

**Comment by dandv** [comment]
> I certainly wouldn't want it to default to suspend over shut down. Mainly because many setups and combinations of hardware seem to have issues with suspend. Or at least resuming from it.

What do people do, given those issues? Do they choose to Power off, restart, then resume all their applications and restore state in each (or start blank), or do they just not use suspend?

In the former case, pressing one extra key is trivial compared to the amount of work to restore your session. In the latter case, if suspend doesn't work for them, they won't use it.

My overall point that if the goal of the Power menu is speed, then Suspend should be accessible with the least keystrokes. If the goal isn't speed, then it doesn't matter which option is the default.

**Comment by Cos-mo** [comment]
You might want to add this applet: https://cinnamon-spices.linuxmint.com/applets/view/236

**Comment by Vahan86** [comment]
If I am not mistaken the default option is "Ask", when you press the power button the list appears where you can choose the action you want.

If you want "Suspend" as a default option you can just set to "Suspend" in Cinnamon-setting->Power management->Power->Extra options->When the power button is pressed.

**Comment by dandv** [comment]
> If I am not mistaken the default option is "Ask", when you press the power button the list appears where you can choose the action you want.

I mean the default from the Ask dialog, of which for some reason you can't take a screenshot because it hijacks the keyboard input or something:

![image](https://cloud.githubusercontent.com/assets/33569/18030968/797d2d20-6c80-11e6-993a-c97dab0e16c5.png)

(this screenshot was taken with a timer)

**Comment by JosephMcc** [comment]
@dandv I understood what you were asking for. Was just pointing out a way to get an end result closer to what you want.

**Comment by anandrkris** [comment]
If I may suggest something, a middle ground perhaps, can we make these options enabled with keyboard shortcuts (Alt + key?) for easy navigation (where a letter is underlined for each action) 
Alt + S - Shutdown
Alt + E  - Suspend
Alt + C - Cancel ( Esc already works)
Alt + R - Restart

**Comment by JosephMcc** [comment]
@anandrkris not sure that adds much benefit. You can already navigate them with the arrows keys so you aren't saving a lot of work.

**Comment by Cos-mo** [comment]
> You can already navigate them with the arrows keys so you aren't saving a lot of work.

That is, what the first poster already described and appears rather cumbersome. Up to 4 times (for hibernate) right arrow and then Enter.

The suggestion by anandrkris can even get enhanced:
Simply the first letter of the buttons for hibernate, suspend and reboot. As there is no input field the alt key should not be needed; it is obvious, that nothing than the buttons are addressed by the shortcuts.
Difficulty might be, that the starting letters are different in different languages.
Cancel (ESC) and Shutdown (Enter) do not need an additional shortcut. One is enough. Redundant shortcuts could get confusing.

**Comment by JosephMcc** [comment]
> That is, what the first poster already described and appears rather cumbersome. Up to 4 times (for hibernate) right arrow and then Enter.

Ok, but as I noted there is a super easy way to do this. Simply set the action for pressing the power button to "Suspend" instead of the default "Ask".

> You could setup a keybinding to do that.

Yet another easy way to do what the OP wants.

The point being that you can already do what you want in multiple ways without needing to change anything.

**Comment by Cos-mo** [comment]
> Ok, but as I noted there is a super easy way to do this. Simply set the action for pressing the power button to "Suspend" instead of the default "Ask".

Wanting mostly to do anything different than shutting down does not mean, that the user will never shut down.

The benefit of using the dialog is, that you can use any of the available commands. The benefit making a different command as default (the suggestion by the OP) or to call the commands from the dialog with a single key press (my alternative) is, that you can call the mostly used command (OP suggestion) or any command (my suggestion) with  single key press.

I admit, far from being one of the really important enhancements, but a nice refinement.

**Comment by mainmachine** [comment]
How often are you guys suspending that several key presses are such a big source of pain?

I'm seriously asking, as I don't ever suspend, and want to understand the use case.

Also, why is this (from @leigh123linux):

> You could setup a keybinding to do that.

...not a viable solution? 

Referring to keyboard shortcuts, this can be done for just one, or all possible shutdown/suspend operations...

**Comment by dandv** [comment]
I suspend when leaving my place, when leaving work, when leaving the commuting vehicle, when leaving coffee shops; about 5-10 times per day? There are better keyboard shortcuts to improve, I agree (e.g. #3883).

**Comment by Odyseus** [comment]
Hello, everybody.

I thing that @Cos-mo's suggestion would be the best approach. In fact, I thing that *access keys* should be an accessibility option that enables them in **all** dialogs, not just Cinnamon's. Although, I don't thing that this would be possible.

**Comment by JosephMcc** [comment]
> How often are you guys suspending that several key presses are such a big source of pain?

I never do. The default in this dialog has also been the same forever and is what people expect. I think you would need really good reasons for changing the default, which was the original request.

It's not that the other ideas here are bad ones. It's that there are already multiple ways to accomplish the end result the OP wants. Not sure how much of a priority there would be for something like this.

**Comment by dandv** [comment]
Agree this shouldn't be a priority.

Also, the default isn't impacted by adding shortcuts, right? Would there be a problem if someone submitted a PR with shortcuts for the buttons in that dialog?

**Comment by JosephMcc** [comment]
PR's are always welcome.

**Comment by synthakai** [comment]
I agree with OP dandv that the dialogue default value should be configurable. I also use it every day and I mostly use suspend button in it, which is very inconvenient to choose using the keyboard.
I like to use this dialogue because it has a countdown timer. Please, don't suggest solutions for me and OP that perform suspend immediately. If we wanted an immediate action like suspend, or hibernate, or shutdown performed, we wouldn't have started the topic in the first place.
So, I suggest a full democracy here - the user should be able to choose the action and whether it happens immediately or in a dialogue with a countdown timer:
1. when the user pushes the suspend button: either the system performs the **configurable action** (suspend, for example) immediately **OR** the system shows the dialogue with the countdown timer, with the configurable action/button (suspend) chosen;
2. when the user pushes the hibernate button: either the system performs the **configurable action** (hibernate, for example) immediately **OR** the system shows the dialogue with the countdown timer, with the configurable action/button (hibernate) chosen;
3. when the user pushes the power button: either the system performs the **configurable action** (shutdown, for example) immediately **OR** the system shows the dialogue with the countdown timer, with the configurable action/button (shutdown) chosen;
4. when the user closes the lid/pushes the lid button: either the system performs the **configurable action** (suspend, for example) immediately **OR** the system shows the dialogue with the countdown timer, with the configurable action/button (suspend) chosen;
5. when the user uses Ctrl-Alt-Del to invoke the dialog: either the system performs the **configurable action** (shutdown, for example, or maybe lock screen) immediately **OR** the system shows the dialogue with the countdown timer, with the configurable action/button (shutdown or lock screen) chosen.

**Comment by leigh123linux** [comment]
The logout dialog isn't part of the cinnamon package. please re-file the issue against cinnamon-session instead.

https://github.com/linuxmint/cinnamon-session/blob/master/cinnamon-session/csm-logout-dialog.c

https://github.com/linuxmint/cinnamon-session/issues
