### ISSUE TITLE
Switching workspaces when dragging a window

### ISSUE THREAD

**Issue by Splarv** [linuxmint/Cinnamon#5618]
This is a feature request.
I like how the tiling and the snapping works now (Version: 3.0.7+sarah). But I think the feature to use arrow keys when dragging a window is unnecessary complication. Instead need to permit switching workspaces by standard (already existed in the keyboard preferences) shortcuts while dragging a windows. I, for instance, like to use configured by myself Super-F1-F4 to switch workspaces by the left hand while the right hand puted on mouse.

**Comment by JosephMcc** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by contribucious** [comment]
Hello @Splarv and the Cinnamon community!

_(after a long time "away" from computers; and still the case, even if I recently wanted to try Linux Mint 19 in a virtual machine to see what's new and... very nice I have to say! Kudos to the team!)_

### Two (related) things in your suggestions in fact. _Hopefully, @JosephMcc noted both._

- [X] Regarding **switching workspace to N+1 (at right) / N-1 (at left)** with any user-defined keyboard shortcut when dragging a window, it's now implemented in the nightly version, thanks to this @mtwebster's [recent commit in muffin repository](https://github.com/linuxmint/muffin/commit/59647a3de95f241e675ce89b19c10b869dfb6533) following the @germanfr's [issue](https://github.com/linuxmint/Cinnamon/issues/7637).

- [ ] Regarding **switching workspace to N** when dragging a window, as keyboard shortcuts section related to workspaces stuff allow this type of switching, it's logical to allow that too while dragging a window, _I would say_.

Maybe more easy to add nowadays, as @mtwebster prepared the ground for this type of things in this recent commit if I understand correctly this sentence in his commit message:
> This adds some utility in keybindings.c to allow implementing this 
> simply, and _maybe allowing for its use elsewhere in the future_.

**Comment by contribucious** [comment]
### INFO

The second checkbox of my previous message can now be checked, since **Cinnamon 4.0.0**. Yay!

Thanks to [this recent commit](https://github.com/linuxmint/muffin/commit/956dcc392f15d015629b197e6d7f539441ad0eec) of @mtwebster (reworked from a solution _window.c + keybindings.c_ to a solution _keybindings.c exclusively_ by the way) as well as [this related commit](https://github.com/linuxmint/Cinnamon/commit/7f6ea126c57f5580edeb0e97e3c6cbf270a69589) for the update of the OSD message (allowing the user to be aware of this new feature).

# Mini-tutorial + Known issue(s)

## **User-defined keyboard shorcuts:**

### - Dragging a window to workspace N+1 (at right) / N-1 (at left):
set the desired keyboard shortcuts in the Cinnamon settings and use them.

### - Dragging a window to workspace N:
same.

## **Built-in keyboard shortcuts:**

### - Dragging a window to workspace N+1 (at right) / N-1 (at left):
**Main solution:** use the left/right arrow keys
**Alternative solution:** use the left/right arrow keys in the numeric keypad when Num Lock is OFF

### - Dragging a window to workspace N:
**Main solution:** use the 1-0 keys of the numeric keypad when Num Lock is ON
**Alternative solution:** use the 1-0 keys above the A-Z keys (i.e. the "numeric row") — useful if no numpad.

**==> The alternative solution doesn't works properly currently: not working at all in my case at least.**
