### ISSUE TITLE
Josephm and Raventofx should be fired!!!

### ISSUE THREAD

**Issue by LinuxHax00r** [linuxmint/Cinnamon#5674]
they are censoring all of my ideas! and they are against freedom of speech and betterment for the whole linux community

**Comment by LinuxHax00r** [comment]
AND FEREN IS RUDE ABOUT MY MORE ENLIGHTENMENT GRAMMER

**Comment by ManIVIctorious** [comment]
God, I can't believe how annoying a single person can be...
All closed issues from you were closed because of good reasons, please stop pissing people only because you don't realize which sort of issues belongs here and which not.

I also don't think that this demanding voice does you well in real live, maybe you should work on it, just a thought...

**Comment by matcheydj** [comment]
Keep in mind the server side load. There is always GNU/Parabola Arch Linux
if you want to join the dark side. Goog keeps their fountain of derp shiny,
and frown upon our hijinks also. Peace

**Comment by LinuxHax00r** [comment]
THOU ARE THE ANNOYING @ManIVIctorious and you and making 0% sense you dumb @matcheydj
