### ISSUE TITLE
Why Global Menu is good for Mint (as optional feature)

### ISSUE THREAD

**Issue by alxgvr** [linuxmint/Cinnamon#5769]
Hi. I`ve been asking for adding global menu applet to Cinnamon for a long time.
Clem recently said that he will add this question to roadmap and will think about it.

I just wat to show why it is important for me and many other users.

Global Menu is the only thing I like about Unity. Advantage: more rational usage of screen space. When window is maximized header bar and menu bar disappears. It is very handy for laptops with small displays, and for working with fullscreen applications like Gimp, Inscape, Libre Office.

Here some screenshots. First: Global-AppMenu applet for Cinnamon is active, window undecorated (I edited matacity theme file). Window buttons with tile applet also present. Second: regular cinnamon settings. Third: comparison.

![screenshot from 2016-10-08 00-45-41](https://cloud.githubusercontent.com/assets/19569543/19206980/86ad0e6c-8cf5-11e6-9dcf-cb0b114f09a7.png)

![screenshot from 2016-10-08 00-46-26](https://cloud.githubusercontent.com/assets/19569543/19206981/8ad57b78-8cf5-11e6-8778-432a0309f029.png)

![globalmenu](https://cloud.githubusercontent.com/assets/19569543/19206988/8f718e06-8cf5-11e6-96d1-7766c03209e5.png)

Just look how clean desktop looks with GM...

Would be great if not only GM will be added, but also undecoration of maximized windows feature (some DEs like MATE and XFCE already have it). Now, unfortunately, only way to do this is to manually edit metacity theme you using (maximus is not working anymore). All together: GM applet, "window buttons with tile" applet, and undecoration feature will bring this Unity-like desktop mode for many people who like it. Mint is most tweakable GTK3 DE now. Adding this features will make it ultimate DE ever :)

**Comment by leigh123linux** [comment]
Adding this would make cinnamon as shitty as gnomes-hell IMO

**Comment by lestcape** [comment]
@leigh123linux sorry but why? 
I think if you want to be taken seriously some real argument will be a good start.

Is an applet right now, not more than that. Could be a default applet? I think not. The problem will be that the Mint team will need to fork unity-gtk-module if they want to really support it as a cross desktop.

Don't worried, will run in Fedora :)

The true is that i don't like it, but yes there are a lot of people that like it as also gnome-shell....

**Comment by leigh123linux** [comment]
@lestcape

1. It doesn't make much sense if you have the panel on the bottom (standard layout for mint and fedora).
2. It would also look shit with vertical panels.
3. It takes up a lot of space on the panel (with 'window list' applet to switch between apps).

P.S Is that good enough arguments for you?

**Comment by alxgvr** [comment]
No, it is not goog enough arguments. It is beautiful and cean with vertical
panels. There is a lot of space for window list applet (just move it to the
right side on pannel) I use it ALWAYS with window list buttons. Yes, it
doesnt make sence wen pannel at the bottom. But who force you to use it? It
is just applet. No one sugesting to activate it by default. Standart Mint
layout wont change. People who need this feature will go to applets list
and activate it. People who don't need - will not even know that it is
there.

сб, 8 окт. 2016 г., 19:02 leigh123linux <notifications@github.com>:

**Comment by lestcape** [comment]
@leigh123linux thanks, there are arguments now. One it's more than enough.

**Comment by mtwebster** [comment]
This is not going to happen.  This behavior is contrary to what Cinnamon is built around.  All our efforts try to focus on presenting windows and the desktop in a reasonably consistent manner, and a vast majority of users have come to expect that.  Whether it were to just be an option or not, it would dilute our efforts, drag development time from things we're interested in improving or implementing already (and that *do* fit with our broad use model).  It also doesn't work in all environments, as mentioned, because of a needed dependency (that we would need to pick up also, and maintain it as well).

When we implement things like vertical panels, etc.. understand that this is most definitely *not* an effort to emulate Unity in any way - we see it as a viable configuration option in our desktop, and we will work hard to make it consistent with our desktop.   It changes nothing about the fact that I want my menus to appear with the program they're for.

We've stated numerous times before, we will do whatever we can to accommodate applet development - if there's something missing, we'll try to address it.  It's cool as hell to see what people come up with for applets, but just because it's cool or useful doesn't mean we should enlist it into our default installation.  It needs to fit, otherwise it's a burden, or at least a potential one.

This is where it belongs already, in my opinion.

**Comment by lestcape** [comment]
@mtwebster as you mention "We've stated numerous times before, we will do whatever we can to accommodate applet development - if there's something missing, we'll try to address it.". Think there are not missing options in the applet right now, and thats is because you also help in this, but user associate the global menu functionalities with the maximum functionalities, thats is also a way for undecorate-decorate a windows.

There a in muffin a read only property for windows decoration. Can be this property for read and write without a lot of enforces?

**Comment by lestcape** [comment]
@leigh123linux Do you know how i can fix the licenses of the global-menu to be clear for fedora? I can use GPL-2 or GPL-3 without a problem. 
And also see this: https://github.com/lestcape/Global-AppMenu/issues/38#issuecomment-255558003

**Comment by leigh123linux** [comment]
@lestcape Did the fedora packager complain about the licenses?, I looked a the package review and didn't notice any concerns.

as for the other issue, I'm not sure vut patches are normally gratefully received.

**Comment by lestcape** [comment]
@leigh123linux 
https://bugzilla.redhat.com/show_bug.cgi?id=1382810:
[x]: License field in the package spec file matches the actual license.
     Note: Checking patched sources after %prep for licenses. Licenses
     found: "*No copyright* GPL (v3 or later)", "GPL (v2 or later)",
     "Unknown or generated". 1 files have unknown license. Detailed output
     of licensecheck in /home/review/1382810-cinnamon-applet-
     globalappmenu/licensecheck.txt

===> It is clearly GPLv3+, upstream should just update some license headers...

**Comment by leigh123linux** [comment]
@lestcape It's the readme file causes the issue


```
AppMenu-master]$ licensecheck -r *
globalAppMenu@lestcape/interfaces-xml: *No copyright* UNKNOWN
globalAppMenu@lestcape/indicatorAppMenuWatcher.js: GPL (v2 or later)
globalAppMenu@lestcape/configurableMenus.js: GPL (v2 or later)
globalAppMenu@lestcape/po: *No copyright* UNKNOWN
globalAppMenu@lestcape/WindowProperties.js: GPL (v2 or later)
globalAppMenu@lestcape/dbusMenu.js: GPL (v2 or later)
globalAppMenu@lestcape/applet.js: GPL (v2 or later)
globalAppMenu@lestcape/po/mo: *No copyright* UNKNOWN
LICENSE.md: UNKNOWN
README.md: *No copyright* GPL (v3 or later)
```

Try this commit

https://github.com/lestcape/Global-AppMenu/pull/40

**Comment by lestcape** [comment]
Thanks @leigh123linux

**Comment by lestcape** [comment]
I will try to create a pull request on cinnamon windows manager to change the value of this property and the be possible implement the maximum functionalities in a property way:

https://github.com/jsparber/mutter-hide-legacy-decorations/blob/master/hideTitlebar.patch

As we can see it's not a big deal, added this functionality, just a thing of preferences.

**Comment by akash-258** [comment]
Any update 2021?
Global Menu saves space and replaces windows title which no one needs.

**Comment by JosephMcc** [comment]
Just to save you the time of posting in closed issues. No there is no update. There are no plans to implement a global menu. It's just becoming less and less useful as more apps move to the newer style of gtk.

**Comment by akash-258** [comment]
@JosephMcc Thank you, you have a valid point
