### ISSUE TITLE
menu-applet: places/recent files shown in AllApplicationsCategory bug

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5872]
This is a similar issue as https://github.com/linuxmint/Cinnamon/issues/5820 (which was solved), but I can't figure out, what causes this bug.

(1) Restart Cinnamon (Ctrl+Alt+Esc)
(2) Open the menu.
(2.1) If you use Cinnamon nightly, then press right and go to the very bottom of the AllApplications box. 
(2.2) If you use Cinnamon 3.0.7 or lower, then press down and go to the very bottom of the AllApplications box.
(3) The places and recent files are shown in the AllApplicationsCategory.

It happens only when the menu is opened for the first time after Cinnamon restarts. I can't figure out, how to prevent that. (The solutions I had come up with, caused new bugs.)

**Comment by NikoKrause** [comment]
Okay, I tested it on another machine. In contrast to the issue https://github.com/linuxmint/Cinnamon/issues/5820 this issue here doesn't appear in Linux Mint 17.3. So it's a new bug. Can anybody test this on Linux Mint 18 stable, so I can locate, when this issue appeared for the first time.

**Comment by itzexor** [comment]
I think what's happening is the "All Applications" category is becoming unselected and thus the list is becoming unfiltered. It only happens for me immediately after a restart, and when it happens you can see that becomes unselected and then the list grows as evidenced by the scrollbar change. Wait 5 seconds or so before opening the menu and it doesn't happen.

I'm not sure what's happening but it might be something external influencing it.

**Comment by NikoKrause** [comment]
@itzexor 
You are a genius. Thanks!

**Comment by itzexor** [comment]
I think the best way to solve this particular issue would be to prevent any menu updates while the menu is open. It could possibly happen while the user is on some other category and it would be disruptive, even if it is set back to all applications after the refresh. Can probably put a check in refresh all if the menu is open and if so, start a timeout to call refresh all again in 10 seconds or something.

**Comment by NikoKrause** [comment]
@itzexor 
Could you try your suggested solution and create a pull request for that?

**Comment by itzexor** [comment]
I believe this issue is solved, so this should be closed.

**Comment by NikoKrause** [comment]
Oh yes. I didn't noticed. I wonder, which PR fixed this issue.

**Comment by Atrosha** [comment]
Bug doesn't fixed or I founded similar. I'd described it in alpha-testing, sorry.
https://github.com/linuxmint/alpha-testing/issues/12

Linux Mint 19.1 Cinnamon
Linux kernel: 4.15.0-48-generic
Cinnamon version 4.0.10
current daily build
x64

After update from alpha-testing repository, reboot, watch movie and start menu opened, I found this list of elements (moviefilename + clearlist) added to current list in "Internet" section. The very first section I'd selected.

It's non-critical because all back to normal by selecting differ menu section after that.

It seems what start menu + recent files initialization goes wrong.
