### ISSUE TITLE
Desktop image changed when usb memory device plugged (ubuntu)

### ISSUE THREAD

**Issue by locolauty97** [linuxmint/Cinnamon#5905]
When I plug an usb memory, the image of the background changes, for the background that's configured in the unity desktop.

**Comment by mainmachine** [comment]
I had this happen at one point, because Preferred Applications > Removable Media was pointing to Caja (IIRC) instead of Nemo - this is Cinnamon installed on Ubuntu Mate. I suspect it's due to some variable pointing to the distro default rather than Nemo specifically, and the devs don't want to change the setting globally (i.e. for all installed desktop environments).

It sounds like you're running cinnamon on Ubuntu proper?

May be related to https://github.com/linuxmint/Cinnamon/issues/3695 and some of the reports in https://github.com/linuxmint/Cinnamon/issues/3953

**Comment by locolauty97** [comment]
Thanks, I fixed, the  #3695 was helpfull!
