### ISSUE TITLE
Systray icons size issues in Cinnamon 3.2.1

### ISSUE THREAD

**Issue by guzzard** [linuxmint/Cinnamon#5932]
Arch Linux with Cinnamon 3.2.1. No issues in version 3.0.7.

![image](https://cloud.githubusercontent.com/assets/9007314/20194097/44e0e4de-a791-11e6-98c7-6fd6b279befd.png)

Bluetooth, KeePass, and Redshift icons are four times too big causing alignment issues etc with the whole panel.

Can be worked around by setting a customized panel size in the panel settings. When moving the panel height slider the systray icons size are adjusted and corrected. Icon size remain correct even after reboot.

![image](https://cloud.githubusercontent.com/assets/9007314/20194295/0bcdf5a0-a792-11e6-95fd-f7bd3985f150.png)

**Comment by lestcape** [comment]
This is because, they use the applet style class, while this is not correct. Please, see the last point:
https://github.com/linuxmint/Cinnamon/pull/5790
    Indicators are now complete theme-ables, but this need a fix (applet-box and applet-icon are not the correct style class).

https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L946
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L1207
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L1250

**Comment by lestcape** [comment]
Another possibility could be that some types of icons don't follow the theme rules... If the last it's true, the best it's try to fix this on the origin, to support this types of images, but could be resolved if will capture the allocation or map signals inside get the theme icons size and set it to the icon when will know.

If all of this fail, just simple revert this commit (that what is doing it's give the control of the size to the theme):
https://github.com/linuxmint/Cinnamon/pull/5790/commits/85777b31dd3104b216cc9909b8d2f1f755c0f18d

**Comment by guzzard** [comment]
Thanks for the quick feedback @lestcape! For me the workaround is ok since it solves the problem. But I think it would be good to determine if the issue is in Cinnamon or in the other applications. If it's the other applications I fully agree that the best solution would be to fix it there.

**Comment by lestcape** [comment]
Not matter, I was waiting for a thing like that... Only that I had not found any case before. This is why i separate this stupid commit of one line from the rest of things...

**Comment by lestcape** [comment]
@guzzard what theme you use? We need to ensure that the icon-size of the applet-icon it's set in the theme otherwise that's the problem.
```
.applet-icon {
    icon-size: 16px;
}
```

**Comment by JosephMcc** [comment]
@lestcape Sorry I missed you on IRC. Work is really busy at the moment.

If the problem comes from the applications themselves or from Cinnamon probably doesn't matter too much. We can't really depend on a bunch of other applications fixing this for us.

@lestcape I haven't actually looked at the code involved but I wonder if you could try getting the icon-size value from the theme and if it doesn't return you anything then just set the icon size yourself. That way you would have a fallback. If not, just reverting that specific part could be the best bet. The systray is a troublesome applet as you can see just from looking at the github issues and we might not want to be trying to get too fancy with things in there.

**Comment by lestcape** [comment]
Thanks @JosephMcc, your suggestion was done... Tested with redshift-gtk. This actually fix the bug when not icon-size it's set in the theme icon class.
