### ISSUE TITLE
Sound window has different names in Menu, System Settings and Sound applet.

### ISSUE THREAD

**Issue by Vahan86** [linuxmint/Cinnamon#6001]
As you can see the "Sound" window has different names in Menu, System Settings and Sound applet.

![4](https://cloud.githubusercontent.com/assets/12819058/20535734/7c012dbc-b0ff-11e6-834e-e82673d93ecd.png)

"Sound Settings" in Sound applet:

![1](https://cloud.githubusercontent.com/assets/12819058/20535747/903d5d0a-b0ff-11e6-9138-463445ffcd9e.png)

"Sound" in Menu and System Settings:

![3](https://cloud.githubusercontent.com/assets/12819058/20535773/ab6e639e-b0ff-11e6-9ec0-728b33f1f5f4.png)

![2](https://cloud.githubusercontent.com/assets/12819058/20535781/b3d3d64a-b0ff-11e6-9e22-3f91799361f5.png)

**Comment by JosephMcc** [comment]
I don't want to sound rude, but I don't see this as being an issue. It makes sense for it to be called "Sound settings" in the applet menu. Just calling it sound would seem a little strange in that particular case.

**Comment by NikoKrause** [comment]
I think the same as JosephMcc.
When you look at the menu description it says:
Manage sound settings
Manage date and time settings
Manage power settings

Removing "settings" in the applets contextMenu would be confusing.
Adding "settings" in the System Settings would make no sense, because every button would have "settings" in it (Effect settings, System Info settings,...)

The 2 previous things you mentioned (All settings and Networking) weren't consistent, thanks for pointing them out. That's why I changed them. The 3 things you mention now are consistent and shouldn't be changed.

**Comment by Vahan86** [comment]
Ok, I am closing these issues.
