### ISSUE TITLE
Icon Size Is Too Small In Taskbar

### ISSUE THREAD

**Issue by opticyclic** [linuxmint/Cinnamon#6072]
The default icon size appears to be 16px rather than 32px.

You can "All Cinnamon to scale panel text and icons according to the panel height" but that then makes the text look wrong.

This would be easier if there was an option to scale text and icons separately.
The panel height can only be set with a slider that doesn't tell you what the actual height is so you can't be precise.

Being able to set the icon size specifically (maybe common increments?) would be useful.

In the meantime I have switched to https://github.com/jaszhix/icingtaskmanager

**Comment by dg1727** [comment]
> The panel height can only be set with a slider that doesn't tell you what the actual height is so you can't be precise.

> Being able to set the icon size specifically (maybe common increments?) would be useful.

I agree strongly, including about making the slider have detents @ icon sizes that are (or are likely to be) in the OS icons/ folder.  I'd prefer if both the panel size & the icon size were shown in the same settings window.  

A.  An advantage of showing the pixel height (width for panels @ left & right of screen) of the panel itself is that this determines how much screen space is available to regular applications; the user may care how close (s)he can come to fitting certain standard window sizes (e.g. 1152x864 vs. 1280x1024 on a 1920x1080 display).  

I realize that technically the border width of regular application windows would need to be known too, but I think what I describe here is a good balance between code complexity & the amount of trial-and-error that a user will have to do to get their screen layout the way they want.  

B.  I'd like the height (width) of the icons to be shown also, because I prefer that bitmap icons be put directly onto the screen without fractional scaling.  :-)  

---
Maybe the title of this issue should be changed, such as to "More granularity in height/width scaling of panel, icons, text".

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
