### ISSUE TITLE
[FEATURE REQUEST] Provide refresh rate chooser in the Display settings

### ISSUE THREAD

**Issue by vladipus** [linuxmint/Cinnamon#6091]
It would be cool to have Display settings having a refresh rate dropdown chooser next to screen resolution. This way it could change the `<rate>` parameter in the `monitors.xml` file, without the need to edit this file in a text editor.

Thank your for what you're doing.

**Comment by mainmachine** [comment]
I like this idea quite a bit, would be great for Intel and AMD OS driver users.

Can someone point me to the "display" module in the code? 

I know how to xrandr and xorg, I'm going to take a stab at implementing this, but I can't get farther than cinnamon-settings.py

**Comment by leigh123linux** [comment]
@mainmachine 

Try

https://github.com/linuxmint/cinnamon-control-center/tree/master/panels/display

**Comment by mainmachine** [comment]
@leigh123linux - thanks for the direction! :)

Looks like this is a planned, but postponed feature: https://github.com/linuxmint/cinnamon-control-center/issues/55

@vladipus - as this is a function of cinnamon-control-center, I suggest you close this request or otherwise redirect it to the issue I linked above
