### ISSUE TITLE
Vertical Panel with date and time cause icon to be off the panel

### ISSUE THREAD

**Issue by immortel32** [linuxmint/Cinnamon#6109]
Hi,

If I put the panel in vertical with the time and date applet displayed, All the notification icons are off the bar.

Please see the image. If I remove the date and time, everything is ok.

![selection_021](https://cloud.githubusercontent.com/assets/7100598/21296092/36ebf4c8-c531-11e6-9fd4-97d513e84cb0.png)

**Comment by brownsr** [comment]
I would imagine this is because custom date format is turned on in the calendar applet configuration.  Normally a vertical panel shows a simple HH (newline) MM as that fits comfortably.  However where a custom date format is turned on we honour whatever is set up there, and if it is too long for the panel width then the result will be something like above. The contents of the section of panel will centre align, and the vertical centre will be halfway along the widest applet.
Please let us know if setting a custom date format is the reason for this, to confirm our understanding of what may be underlying your issue.

**Comment by immortel32** [comment]
You are 100% right. so I have 2 questions:
How to make a new line with the custom date?
Is there a way to make the panel large to fit the text like "September"?

**Comment by brownsr** [comment]
%n   makes a new line.  The default format in a vertical panel is %H%n%M

The panel cannot be scaled that wide.

**Comment by immortel32** [comment]
Thanks for the info.

I will modify my custom date.
