### ISSUE TITLE
skype indicator freezes screen

### ISSUE THREAD

**Issue by hackoon** [linuxmint/Cinnamon#6163]
When skype is disconnected (grey icon) cinnamon freezes  the screen - returns to normal when connection comes back (green icon)

It seems to be connected with skype indicator icon update because without indicator support the grey icon flashes continuously but the screen doesn't freeze. 

Makes skype unusable with indicator support activated.

**Comment by lestcape** [comment]
Sorry i tested this with Skype 4.3 and with Skype Alpha (without indicator support) and i can not reproduced the freezes.

**Comment by lestcape** [comment]
Also i don't see a continuously flashes without indicator support. You probably have another problem...

**Comment by hackoon** [comment]
mind you it only happens if internet connection is lost or very slow. it could also be that my gpu (gma x3100) is much slower than yours so my system (thinkpad) freezes but yours not - because of slow OGL + skype updating too fast. 
this problem may affect more people only they will not know its because of skype. System just freezes when internet connection is slow or lost.
maybe there is some way to limit the maximum updates of icons/second or optimize the update code in other ways. The flashing indicates some slow path in the update code. 
If you need it I can make some small mp4 file of the flashing

**Comment by lestcape** [comment]
This will be out of what i considered that i can do. As i say,  this could have side effects, i.e. a bad animation for icons and probably more things and if i can not see the problem and also i can not see how it's better i can not be sure of what i do it's ok and is helping a little.

My test was with a core 2 and with an intel onboard video (this is of course, a bad video acceleration to this time). How much i will need to downgrade the hardware to see something? Also i can only try for indicator... I don't know anything about how work the status icons.

i have a netbook, i will see if there i can see something, but it's out date so, i don't know when i can see this.

**Comment by hackoon** [comment]
It depends on the gpu - the x3100 has *very* slow shaders. I will try to reproduce the bug myself on another old intel atom. I will be back with the results later.

**Comment by hackoon** [comment]
Finally I can reproduce the bug on another system!!!

it depends on sni-qt:i386 being installed (indicator support for qt4 apps). Its a recommended install for skype. Installing it and have skype internet disconnected freezes the screen. Please try it.
I couldn't reproduce the flashing grey icon, which seems not be directly related.

Removing the sni-qt:i386 package is as a workaround and allows to have indicator support and running skype without it.

**Comment by lestcape** [comment]
@hackoon sni-qt it's installed in my system and i can not see a freeze. Thats good for you.

**Comment by hackoon** [comment]
@lestcape sni-qt is installed by default on mint18 but not the 32bit deb which skype use. make sure you install it by "apt install sni-qt:i386"

**Comment by lestcape** [comment]
@hackoon Not, i have not the i386 version installed and i have skype 4.3... I don't known why you install this...

**Comment by hackoon** [comment]
@lestcape because skype is 32bit so it needs sni-qt:i386 for indicator support. Its recommended to install it but I have no idea why it was installed on my system. In any case it should work - but I don't mind for myself as I can live without skype indicator support for sure. I only worry that others may have more problems to solve or even recognise this issue and just judge cinnamon as to unstable to use.
It seems to me while skype certainly is a very badly maintained app it could point to some bug in the indicator code.

**Comment by lestcape** [comment]
I'm in my home now. I have here an AMD machine and an ATI card... The test that i do was in my work and there i have sni-qt:i386 installed. I installed sni-qt:i386, and here i can notice some little freezes... Just for a moment.

**Comment by lestcape** [comment]
@hackoon can you help me to test this code. 
https://raw.githubusercontent.com/lestcape/Systray-Indicator/master/systray-indicator%40cinnamon.org/indicatorManager.js

1- Download the file.
2- Make a backup of your file: /usr/share/cinnamon/js/ui/indicatorManager.js
3- Replace the download file with your local copy as root (just execute nemo as root to replace the file)
4- Restart cinnamon.
5- Test it.

You can revert the change if you want, and when you want... If you replace the file again with your backup.

What this do, it's decrease the number of update icon request if the hardware it's slow, but not if it's fast. In that way the animation only will be broken when really it's necessary....

**Comment by hackoon** [comment]
Well it does stop the freeze, but then cinnamon is at 100% cpu and 38% mem raising. Seems cinnamon has a memory leak and it did rise fast. It seems cinnamon didn't release the memory after I closed skype.
II just removed sni-qt:i386 again, without qt indicator support it works fine, only the grey icon is still flashing.

**Comment by lestcape** [comment]
The patch not avoid the call, just avoid the update of the icon... The code before the icon update in the cinnamon side it's minimal (just recive the signal check the signal type and then send another specific signal to update the icon). This mean that i can not do anything to avoid this... The solution could be inside the sni-qt:i386 package. And this is not a memory leak, it's keep cinnamon in an infinite loop, so as cinnamon never enter in a idle state. As a result the garbage collector will not be activate and then the memory will not be cleaned.

**Comment by hackoon** [comment]
I am not so much into gui programming, I guess somehow skype is saturating the dbus and cinnamon is hooked into it and can't do anything but dance. Is there any possibility to disable only skype indicator request so it just uses the normal tray icon and the rest can use indicator? It wasn't a problem before but now cinnamon has indicator support by default and that may freeze quite a amount of those who use skype on 32bit cinnamon or have sni-qt:i386 installed.

**Comment by hackoon** [comment]
I posted a bug report on skype forums but I have little hope that any help will ever come from that end.

**Comment by lestcape** [comment]
It's is possible disable specific indicators, but the question will be. Some one need to evaluate if this is a commons problem, or just for a little portion of user... The fact it's that: Cinnamon it's not a desktop to be installed in a notebook or equivalent machine. This violate the prerequisites of cinnamon: a low resolution display, a not good cpu and graphics...

I also have a notebook with cinnamon and the main reason to create configurable menu, was for show the menu in a low resolution display. https://github.com/lestcape/Configurable-Menu Also, I disagree with the minimum requirements. I think we can reduce the image resolution, create an scroll for categories inside the cinnamon menu and do more things to reduced the minimal requirements, but well... Non of this was done and if we have situation like this, really you think why try to reduced the minimal requirements if this things can happen...

**Comment by lestcape** [comment]
The indicator support it's not any more the default option... You can active it if you want. I recommend you not active the indicator support in an slow machine. I now need to ask you what version of cinnamon you have, because the code that i share with you it's for cinnamon 3.2, where the indicator support it's not he default option...

**Comment by hackoon** [comment]
cinnamon 3.2.7 - could be I was wrong that indicator support was enabled by default. I am fine with using the workaround if you decide not to patch it. I must contradict you cinnamon runs quite well on older machines if you upgrade the memory. I am a bit sensible to that throw away and buy new mentality that destroys our planet but that is a bit of topic.
Anyway thanks a lot for your effort.

**Comment by lestcape** [comment]
@hackoon : 
1- Your proposition it's remove the skype support for indicators, not matter if we have a new machine or not... What  you say, It's not fix the problem (because can not be do in the cinnamon side). It's take a decision in favor of some users and against of others. I'm a cinnamon contributor, not a cinnamon owner. So, please understand that this decision it's not in my side and then i can not do anything.

2- There are a workaround for slow machines, that can be apply without affect other users, so why affect other users then?

3- I never say, cinnamon will not run in oldest machines... In fact i say:
- I disagree with the minimum requirements
- There are minimum requirements
- I disagree with the low resolution requirements (and also create a menu, because of this)
- I also have a notebook with cinnamon (so i known cinnamon runs quite well on older machines, because a notebook it's like an older machine in several things).
- I'm more sensitive than you about throw away and buy new mentality, not because this can destroys our planet. It's because i was born in Cuba, where the average salary is $ 20 dollars for month and I was able to buy my first computer at age of 28. So, of course has an old computer was a dream for me and for a long time. Also a lot of my friends and family are living in Cuba and they have oldest computers or also nothing.

The problem here it's not about our personal inclinations or what we think it's ok... It's about what will be better for more people. But thats also it's my opinion and also i'm not a cinnamon dev to take a decision about this.

**Comment by hackoon** [comment]
I don't see any problem in disabling skype indicator support - skype is a buggy program and its usual practice to do so. If you can do this only for slower machines - all the better. Or at least show a warning that indicator support may crash cinnamon on slower hardware.

**Comment by lestcape** [comment]
@hackoon there are not way to know if a machine it's slow or not... Just you can know, if in some specific context you have a lot of slopes signals to process. This could be because some program are working at the same time, because some program freezes your computer, and for a long list of causes, not just because of an slow machine. So, there are not an easy or general way to decide if a computer it's slow or not...

This mean yes, this also can occurs in the most faster computer in some specific conditions... As i say: "i can notice some little freezes... Just for a moment."
https://github.com/linuxmint/Cinnamon/issues/6163#issuecomment-271165925

And also see:
https://github.com/linuxmint/Cinnamon/issues/5458

Like i say, enable or disable things it's not in my side....

**Comment by hackoon** [comment]
skypeforlinux is now complete different from the old skype. 64bit and everything so at least with skype there is no further problem
