### ISSUE TITLE
Cinnamon 3.2.7 - LM 18.1 : High CPU usage until I restart Cinnamon

### ISSUE THREAD

**Issue by Booteille** [linuxmint/Cinnamon#6201]
High.

As said in the title, Cinnamon is using a lot of CPU usage until I restart it through Cinnamon Debugger ([Window] + [L] => Restart Cinnamon).

The CPU is getting used a lot since the beginning of the session.

Here are two screens of htop:

![high_cpu_cinnamon](https://cloud.githubusercontent.com/assets/2203721/21926823/b3c47e32-d983-11e6-97a0-f1834dd092fa.png)

After I restarted Cinnamon:

![capture du 2017-01-13 11-25-27](https://cloud.githubusercontent.com/assets/2203721/21926832/c08f0998-d983-11e6-9892-fefe2c1b8780.png)

**Comment by JosephMcc** [comment]
Try disabling applets like the system monitor applet and see if that has any effect.

**Comment by Booteille** [comment]
Oh, sorry. i fogot to tell you I already did it by the past.

Here is another screen with system monitor applet removed.

![capture du 2017-01-18 09-01-33](https://cloud.githubusercontent.com/assets/2203721/22055744/f06cc984-dd5c-11e6-8797-c286d3306584.png)

I would like to notice I just started the session and did NOTHING except open the terminal and run htop.

**Comment by leigh123linux** [comment]
@Booteille Why do you have several cinnamon processes running?

**Comment by Booteille** [comment]
I don't know. That's what happens when I start the session.

**Comment by Booteille** [comment]
I am stupid. I didn't think about that simple thing, sorry.

I created another user and he has not the issue.

![capture du 2017-01-18 10-05-52](https://cloud.githubusercontent.com/assets/2203721/22057718/3d2c1c3a-dd66-11e6-985c-ea5dee5f6480.png)

I am trying to change settings of this new user to copy those I actually have.

**Comment by Booteille** [comment]
Okay. I just noticed Cinnamon was set to start on Software Rendered mode on the login screen.
The high cpu usage was related to this fact. Once I selected "Default Session" or "Cinnamon" instead of "Cinnamon Software Rendered" on the login screen, everything got better.

I am sorry for the waste of time. I should've think about those things before posting.

**Comment by ECipolatti** [comment]
@Booteille how do u change it? i mean i want to do the same as you, but i dont know how.

**Comment by JMIsham** [comment]
click the round icon next to the username

**Comment by ECipolatti** [comment]
i already do that, even i have it on default, but keeps getting 15% of my CPU :(

**Comment by diveyez** [comment]
Same, still high cpu usage by cinnamon --replace
Tried all my normal fixes, nothing works. I might move to gnome due to this. Dont like it.

**Comment by gatopeich** [comment]
I am in the same situation, Cinnamon taking ~5% CPU continuously on a 8-core system.
- strace shows many calls to recvmsg on socket `@/tmp/.X11-unix/X0`
- perf top shows cinnamon mostly busy on `g_source_iter_next`
However the problem seems to be pulseaudio's CPU hunger apparently due to busy polling on output devices.
After some tinkering I decided to remove pulseaudio and cinnamon CPU use went down to 1~3%.

**Comment by educatedwarrior** [comment]
Why does Linux audio suck so bad.

**Comment by gitlui** [comment]
For me this was exactly the Problem. My kid must have changed it by spamming the keyboard on the login screen. Thank you very much!

**Comment by sebaplaza** [comment]
Thanks @Booteille ! It's works !
I've been searching for months the origin of this problem. 

> Okay. I just noticed Cinnamon was set to start on Software Rendered mode on the login screen.
> The high cpu usage was related to this fact. Once I selected "Default Session" or "Cinnamon" instead of "Cinnamon Software Rendered" on the login screen, everything got better.
> 
> I am sorry for the waste of time. I should've think about those things before posting.

Thanks @Booteille ! It's works !
I've been searching for months the origin of this problem.

**Comment by Technologicat** [comment]
For the record, in LM 20, I noticed Cinnamon constantly using 15-100% of one CPU core. Turned out it was the **CPU and GPU temperature applets** in the panel! Removed those from the panel, rebooted, and the problem is gone.

This was difficult to track down, so:

- To see whether it's a recurring problem, restart Cinnamon (*Window key + L ⊳ Actions ⊳ Restart Cinnamon*).
- To see where that CPU time is going, use the `perf-top` utility from the `linux-tools-generic` package. For example, `sudo perf top -g -s overhead,comm,dso,sym`. If you're new to `perf`, see e.g. [this article](https://www.fosslinux.com/7069/installing-and-using-perf-in-ubuntu-and-centos.htm). You can hit `?` to view a list of keyboard commands. Pressing `q` exits the tool.
- If you suspect the problem could actually be caused by disk traffic, open `gnome-system-monitor`, and look at *Open Files* for the `cinnamon` process. (You could also `htop` or `pgrep cinnamon` to find the PID, and then `lsof -p XXX`). If that list reveals anything potentially interesting, use `strace -f -p XXX` to see what it's doing.

In my case, expanding the `perf-top` entry for the `cinnamon` process (arrow keys, then Enter), [`execve`](https://en.wikipedia.org/wiki/Exec_(system_call)) appeared in the list quite often. That was a hint `cinnamon` was often executing one or more external utilities. Temperature monitor applets are often implemented that way, using `lm-sensors`.

So the culprit wasn't Cinnamon itself, but a panel applet! It seems the reason it's difficult to track down "high CPU usage in Cinnamon" is that there are a variety of possible causes, and not all of those come from Cinnamon itself - even though `htop` reports it's the `cinnamon` process that's seemingly causing the CPU usage.

**P.S.** Tangentially related: if Cinnamon sits (at most) at a couple percent of CPU usage, but your laptop fan is still running suspiciously fast/loud, then it could be GPU usage:

- Check your graphics drivers. Especially, if you have an Optimus laptop (integrated Intel, plus a discrete NVIDIA GPU), and you're using the proprietary NVIDIA drivers, it may help to select the *NVIDIA On-Demand* mode in the *NVIDIA Settings* applet so that the discrete GPU (which produces more heat than the integrated one) stays off except when needed. For Cinnamon, the integrated Intel GPU is just fine.
  - See [Ask Ubuntu](https://askubuntu.com/questions/1201072/how-nvidia-on-demand-option-works-in-nvidia-x-server-settings) for what exactly that option does. The X server included in LM 20 is 1.20.8, which is [recent enough](https://www.reddit.com/r/archlinux/comments/e0igw2/psa_xorg_server_1206_supports_prime_offloading/) to support PRIME offloading. Version 455 of the NVIDIA driver, available in the *Driver Manager*, [is also recent enough](https://wiki.archlinux.org/index.php/PRIME#PRIME_render_offload).
    - To start a process using the NVIDIA GPU, prefix its command line with `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia`.
    - So, to confirm the on-demand mode is working, compare the output of `glxinfo | grep vendor` (should say Intel) with that of `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia glxinfo | grep vendor` (should say NVIDIA). Instead of `glxinfo | grep vendor`, also one of `glxgears -info` or `glxheads :0` is fine.
  - While at it, you might also want to create a file `/etc/modprobe.d/nvidia-options.conf`, with the content `options nvidia-drm modeset=1`, and then `sudo update-initramfs -u` and reboot. This gets rid of screen tearing.
    - To confirm it's working, `sudo cat /sys/module/nvidia_drm/parameters/modeset`. It should say `Y`.

Now I have Cinnamon using only a couple percent of CPU at most, and using the integrated Intel GPU, while NVIDIA can be activated on the fly where needed. It runs very nicely and quietly. Thanks to the Linux Mint Cinnamon team for the great product!

**Comment by Templayer** [comment]
> > Okay. I just noticed Cinnamon was set to start on Software Rendered mode on the login screen.
> > The high cpu usage was related to this fact. Once I selected "Default Session" or "Cinnamon" instead of "Cinnamon Software Rendered" on the login screen, everything got better.
> > I am sorry for the waste of time. I should've think about those things before posting.
> 
> Thanks @Booteille ! It's works ! I've been searching for months the origin of this problem.

Years later and these comments still help.

I have been restarting Cinnamon at each login via a hotkey for over three years now, and yet the solution was so simple.

But the high CPU usage with "Cinnamon Software Rendered" that persists until Cinnamon is restarted is still an issue that should've been solved a long time ago...
