### ISSUE TITLE
Mintmenu should not disappear after launching just one application

### ISSUE THREAD

**Issue by freemangilgamesh** [linuxmint/Cinnamon#6207]
sometimes I want to launch many apps at one time but this mintmenu keeps disappearing and so i have to reclick on it again.

**Comment by JosephMcc** [comment]
In most cases the way it behaves now is exactly how I would want it to behave and how pretty much every other menu I can think of behaves.

**Comment by freemangilgamesh** [comment]
should we always lag behind other OSes?

**Comment by JosephMcc** [comment]
It has nothing to do with other OSes. It has to do with the basic behavior of menus used everywhere. I would actually find it annoying if the menu didn't close once I chose the application I wanted to launch.

**Comment by freemangilgamesh** [comment]
Middle ground: it should be optional then and everyone is happy!

**Comment by lestcape** [comment]
@freemangilgamesh most of application gain the focus when they are launched. This mean the menu and his launcher (the actor in the panel) will lost the focus in favour of the application windows. In cinnamon, like in any other desktop environment, all opened menu required to has the focus or at less his launcher need to has the focus, because the menus are not individual applications and then they are not running isolate.

Your request will change how the focus are manager in cinnamon as a whole, not just the menu... In other words to do that, you will need to have a complete new desktop conception and this of course it's an invention that you can do as an experiment, to see the cost when you learn programming. If you don't want to learn programming, just accept that this is an invention and close this thread please.

**Comment by freemangilgamesh** [comment]
@lestcape I get it now bro. You're right.
