### ISSUE TITLE
Pidgin icon disappears after a while

### ISSUE THREAD

**Issue by talonx** [linuxmint/Cinnamon#6216]
Cinnamon 2.2.16 on Debian 8 Jessie, kernel 3.16.0-4-amd64

The Pidgin icon on the system tray disappears after a while, especially after a notification has come and the machine was locked (not suspended) for a while. I don't have the exact steps to replicate this but it happens at least once a day.

The icon remains active, clicking on it brings up the app and any unseen chat windows, but it's not usable since new notifications are invisible as well. 

Restarting pidgin solves the problem until the next occurrence.

**Comment by leigh123linux** [comment]
2.2.x is no longer maintained.

**Comment by gitman0** [comment]
I am experiencing this in Fedora 27 with Cinnamon 3.6.7 and pidgin 2.12.0

As mentioned by the original reporter, restarting pidgin addresses the problem.

It seems to be after the display has gone to sleep.

**Comment by leigh123linux** [comment]
@gitman0 Maybe it would be worth filing the issue against pidgin

**Comment by gitman0** [comment]
I'm coming from Cinnamon 1.6.7 with pidgin 2.10.11 where it was not an issue. Understandably, much has changed in Cinnamon since then, but pidgin has not really changed all that much since the 2.10.11 release, at least not in terms of systray handling (based on their [changelog](https://bitbucket.org/pidgin/main/src/v2.12.0/ChangeLog?fileviewer=file-view-default)).

What changed in pidgin and/or cinnamon that requires so many [work-arounds](https://github.com/linuxmint/Cinnamon/search?q=pidgin&type=Commits&utf8=%E2%9C%93)?

I would like to avoid the loop where I report to pidgin, and they refer me back to you. How can I convince them its not a Cinnamon problem?
