### ISSUE TITLE
In Settings UI, explain the window focus modes

### ISSUE THREAD

**Issue by dg1727** [linuxmint/cinnamon#6265]
In the System Settings "Windows" applet, Behavior tab, there is an option "Window focus mode" [Click/Sloppy/Mouse].  

Suggestion:  Next to the drop-down choices box, put a question-mark button which pops up a message box explaining the 3 modes.  

There is already text in Muffin's po/en_GB.po file which has this explanation (search for "are focused").  I don't know of a way to bring up this text in the existing Cinnamon UI, which means to me that if there is such a way, it isn't obvious enough.  

Muffin's source code also contains a file called doc/how-to-get-focus-right.txt which says:  
> Sloppy focus suffers from a bit of a discoverability problem (for example, I have seen a scientist sit down to a computer for which sloppy focus was in use and take a few minutes before figuring out how window activation worked; granted the layout of the windows in that situation was a bit unusual but it still illustrates that sloppy focus is hard [...] to figure out)

So apparently I'm not alone in finding that the names Sloppy & Mouse, plus a few seconds of trying out those 2 modes, aren't enough to tell me what those names mean.  

I don't think the user should have to go to the global apps menu's Help application to find out about this one setting; besides, the closest that the Help application gets to this explanation is a screenshot of the System Settings app, never mind the Windows window or any detailed text.

**Comment by NikoKrause** [comment]
#~ msgid ""
#~ "The window focus mode indicates how windows are activated. It has three "
#~ "possible values; \"click\" means windows must be clicked in order to "
#~ "focus them, \"sloppy\" means windows are focused when the mouse enters "
#~ "the window, and \"mouse\" means windows are focused when the mouse enters "
#~ "the window and unfocused when the mouse leaves the window."

Those are comments, i.e. probably sentences from previous versions, which were deleted.

**Comment by JosephMcc** [comment]
The info could simply be put in a tooltip.

**Comment by NicoWeio** [comment]
My PR #8247 has been merged, so I suggest we close this issue.

**Comment by NicoWeio** [comment]
A kind reminder that this issue can be closed :)
@dg1727  @clefebvre
