### ISSUE TITLE
Minor UI glitches in apps-menu configuration dialog

### ISSUE THREAD

**Issue by dg1727** [linuxmint/cinnamon#6283]
1.  In the apps menu's **Configure...** dialog, **Panel** tab, if **Menu hover delay** is set to 0, then a blank is shown (instead of 0) when the dialog is opened.  
2.  The default keyboard shortcuts to open and close the menu are shown as "Super L" and "Super R."  Many users will think these are Super+L and Super+R, which are not what's meant.  So I suggest changing the default labels to "Left Super" and "Right Super."  This may affect UIs elsewhere that mention the superkeys.  
3.  The text says "Keyboard shortcut" (singular) even though there are 2 of them.  I suggest "Keyboard shortcuts" instead.  

Cinnamon 3.2.7

**Comment by icarter09** [comment]
For points 1 and 3:
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2).
If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".

For point 2:
Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
