### ISSUE TITLE
Hot corrner settings - problem with writing (Polish translation)

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/Cinnamon#6323]
Hello
In cinammon, hot corner setting is problem with sentence "Wyświetl wszystkie okna.".
I check in file transations ( https://github.com/linuxmint/cinnamon-translations/blob/master/po-export/cinnamon/cinnamon-pl.po ) - line 178 looks good.

What can be reason of this problem?
I attach screenshot. Linux Mint 18.1
http://imgur.com/a/5ysqu

**Comment by NikoKrause** [comment]
Which Cinnamon version do you use?

In the screenshot it looks exactly like in a previous translation version, i.e. it's a mistake in the translation
https://github.com/linuxmint/cinnamon-translations/blob/1e54b2ae072bd727e4fd9b9e4a5117b927bae8d1/po-export/cinnamon/cinnamon-pl.po

**Comment by NikoKrause** [comment]
Do you see this on Cinnamon 3.2.7?

**Comment by pyroxar** [comment]
I don't see Cinnamon 3.2.7. It is in Linux Mint 18.1?

**Comment by NikoKrause** [comment]
Linux Mint 18.1 ships with Cinnamon 3.2.x

You can check your Cinnamon version on different ways:
1. You can open a Terminal and type `cinnamon --version`
2. Or you can open `Systeminformation` (`Informacje o systemie`) in the menu. It looks like this for me:
![screenshot-area-2017-02-28-182330](https://cloud.githubusercontent.com/assets/8415124/23416603/c724ee9c-fde3-11e6-8758-6227dd47e011.png)

I changed my PC to Polish translation. As expected it looks like this for the hotcorner:
![screenshot-area-2017-02-28-182219](https://cloud.githubusercontent.com/assets/8415124/23416630/e4f6f33e-fde3-11e6-9906-2de8b11176ae.png)

As I said above. It's a translation error in Linux Mint versions minor 18.1. 
It's fixed in Linux Mint 18.1. (At least in Cinnamon 3.2.7, i.e. Linux Mint 18.1 with all updates installed.)
If you see the error, I think you don't use Linux Mint 18.1.

**Comment by pyroxar** [comment]
I installed fresh Linux Mint 18.1 with cinnamon **3.2.6**. I will update system in Saturday. I hope that update be resolve.

**Comment by pyroxar** [comment]
All work good.
