### ISSUE TITLE
Workspace switcher applet too slow when using mouse wheel

### ISSUE THREAD

**Issue by agoode** [linuxmint/Cinnamon#6376]
Pull #6021 changes the workspace switcher applet to make it more usable with touchpads. Unfortunately, it now makes it much less usable with discrete mouse wheels.

The delay should not apply if the event scroll source is `CLUTTER_SCROLL_SOURCE_WHEEL`.

See https://developer.gnome.org/clutter/stable/clutter-Events.html#ClutterScrollSource

**Comment by germanfr** [comment]
Hi, that's a great idea. Unfortunately for some reason the `ClutterEvent` object received has no such function and it throws this error.
```
(cinnamon:2935): Cjs-WARNING **: JS ERROR: GLib.Error g-invoke-error-quark: Could not locate clutter_event_get_scroll_source: 'clutter_event_get_scroll_source': /usr/lib/libclutter-1.0.so.0: undefined symbol: clutter_event_get_scroll_source
```

It breaks even when I try to test if it exist like this.
```js
if(event.get_scroll_source) { // <-- Breaks here
    is_mouse = event.get_scroll_source() === Clutter.ScrollSource.WHEEL;
}
```

I have the latest version of Clutter installed on my system (1.26, which is where this function was added).

Also, I'd like to mention that this feature was added in order to make it **usable** for touchpads, because when a mouse wheel throws one scroll event a touchpad throws 6, and it was impossible to switch one workspace at a time. Unless you are jumping 4 workspaces I don't notice any difference with my mouse. It would be great if this could be solved with that, but unfortunately I'm not able to solve the issue I explained above.

Something as simple as this would do the trick if it worked.

```patch
+        let is_mouse = event.get_scroll_source() === Clutter.ScrollSource.WHEEL;
+       
         // Do the switch only after a ellapsed time to avoid fast
         // consecutive switches on sensible hardware, like touchpads
-        if ((now - this._last_switch) > MIN_SWITCH_INTERVAL_MS ||
+        if (is_mouse || (now - this._last_switch) > MIN_SWITCH_INTERVAL_MS ||
```

**Comment by JosephMcc** [comment]
Even if you got this to work, it wouldn't work in Ubuntu Xenial or Debian Jessie based distros which don't support clutter 1.26 (aka Mint). Beside that I don't see how this is "unusable". I tested the original work when it was done and use it regularly now and it works fine with a scroll wheel.

**Comment by olejorgenb** [comment]
https://gitlab.gnome.org/GNOME/mutter/merge_requests/181 (note that the methods didn't actually return useful values on my system)
