### ISSUE TITLE
Desktop Icons are messed up each time after login (Cinnamon 3.4.0)

### ISSUE THREAD

**Issue by ThanosApostolou** [linuxmint/Cinnamon#6541]
After every login Desktop Icons are like this (it's like the 2nd line has been "merged" with the 1st one):
![screenshot from 2017-05-17 14-17-25](https://cloud.githubusercontent.com/assets/21288843/26151565/13a8f136-3b0c-11e7-8b25-c0c982bb8def.png)
After I refresh the Desktop (with <kbd>F5</kbd>) then they are shown properly:
![screenshot from 2017-05-17 14-17-43](https://cloud.githubusercontent.com/assets/21288843/26151598/333d7774-3b0c-11e7-8142-22de967e0a9a.png)

I'm using Fedora 26, Cinnamon 3.4.0. I have enabled the option **Allign to Grid** and I have dissabled the option **Auto-arrange**.

Please tell me if you can reproduce it with other distributions too and if you need any additional info.

**Comment by mtwebster** [comment]
Well aware of this particular issue :)  and working on it.  Thanks

**Comment by xonxor** [comment]
Hi @mtwebster I'm not sure whether you are also aware of a similar issue that is present in multi-monitor setups. On first login icons completely disappear, and if for some reason any icons show up they are jumbled up as @ThanosApostolou rightly pointed out. The issue seems to be related to primary monitor setup. I don't know if it's appropriate to post a [link ](https://bugs.launchpad.net/linuxmint/+bug/1650977) to the launchpad bug tracking page for Linux Mint on Github, but here it goes anyway because it's no use duplicating threads especially given the fact its been there for a while now. Thanks in advance, and thankyou for your contributions :)

**Comment by mtwebster** [comment]
That launchpad issue is fixed in 3.4 and not related. This particular issue here is new as a result of a huge amount of desktop changes for 3.4.

**Comment by xonxor** [comment]
Good to know :) Thankyou for you swift response!

**Comment by JosephMcc** [comment]
This is a Nemo issue and it should be fixed in git master.
