### ISSUE TITLE
Built in Blue light filter functionality

### ISSUE THREAD

**Issue by KylePiira** [linuxmint/Cinnamon#6582]
At this point, Android, iOS, Windows, and GNOME 3 all have a built in blue light filter. It would be really nice to see something similar in Cinnamon

**Comment by JosephMcc** [comment]
Currently there is no reason to do this. Redshift does this quite well already and should work on most desktop environments. It's a better solution than spending time working on something that would be specific to only Cinnamon. GNOME3 did this because of Wayland. As far as I know, Redshift, like many other things doesn't work.
