### ISSUE TITLE
3.4 - launching on screen keyboard via accessibility applet or accessibility settings launches caribou and onboard at once

### ISSUE THREAD

**Issue by brownsr** [linuxmint/Cinnamon#6595]
![screenshot from 2017-06-09 18-55-16](https://user-images.githubusercontent.com/6322481/26988062-cf211bfa-4d45-11e7-997a-b5e89731b820.png)

**Comment by Cos-mo** [comment]
The old keyboard appears superfluous as I described in https://github.com/linuxmint/Cinnamon/issues/6619. See there also for more suggestions I made.

**Comment by JosephMcc** [comment]
> The old keyboard appears superfluous

No it isn't. Cinnamon can be used without slick-greeter and is in other distros.

**Comment by Cos-mo** [comment]
> Cinnamon can be used without slick-greeter and is in other distros.

I intentionally wrote "appears".
Besides that I wonder if you mean "distros" or editions (of Mint). I don't know, if another edition of Mint uses still the old keyboard (the missing note in the Cinnamon change-log doesn't allow conclusions); but if also the other editions(!) use now onboard, why must caribou be still pre-installed in Mint(!) ?

Yes, the user can switch from lightdm to mdm (I assume you mean this), but he must in this case install mdm at first in his system. So you could - as mdm is to my knowledge a product solely of the Mint team - be possible to set caribou as a recommended package for mdm, instead of pre-installing it, because possibly the one or other user might switch to mdm.

Hopefully we agree at least in the point, that 2 on-screen keyboards launching simultaneously does really not make any sense and gives the trouble, which I described.

**Comment by Cos-mo** [comment]
I just noticed, that in Mint 18.2 / Cinnamon 3.4.4 onboard can still be launched via gksudo (but not as a user).

Is this (= usable elevated) intended / necessary / an oversight?

**Comment by mtwebster** [comment]
undefined.

I can run anything as root whether it's intended to be run that way in a particular situation, or not.  It doesn't mean I should - for a lot of it you'll get a lot of weird, undefined behavior, in addition to something still possibly working.

I'm fairly certain for onboard this needs to be allowable for it to work in the greeter, but there's no way for my user processes to block this from happening any other time, as the connections onboard establishes are on a completely separate dbus session (it's a different user), one that isn't running Cinnamon - which is what blocks it in the user session per this patch.

We'd need to establish some resident helper process that runs as root in the background (or coopt an existing one) to override this capability - it's not something I think is necessary for this case.

Also, I've always felt when I run something as sudo, it had better listen.  I'm the king here.  Whether this is correct use or not.

I imagine this is leading to someone activating the OSK, getting Cinnamon's native one, then trying sudo onboard to force the issue.
