### ISSUE TITLE
Fadeout instead of ellipsis(...) on text-overflow

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/Cinnamon#6602]
for panel/taskbar and also alt-tab, when it is cramped and isn't enough room ... is used but takes-up space & is cluttered
fade-out is an improvement

similar to ffox 53's
[CSS3 mask: ](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image)[Fade out ](https://bugzilla.mozilla.org/show_bug.cgi?id=1251161)[ tab label on overflow instead of ellipsis](https://bugzilla.mozilla.org/show_bug.cgi?id=658467)
![wikifadecomparison](https://www.soeren-hentzschel.at/wp-content/uploads/2016/12/tab-darstellung-firefox-53.png)
![wikifadecomparison](https://bug658467.bmoattachments.org/attachment.cgi?id=8865076)

**Comment by JosephMcc** [comment]
This is problematic in Clutter. Mixing different effects doesn't work well. These break down when using the accessibility setting.

**Comment by cmrdt** [comment]
note that something similar already happens for the start-menu

![fade](https://user-images.githubusercontent.com/24411108/27664020-4e82046c-5c33-11e7-8b91-3efab1dae272.png)

**Comment by mtwebster** [comment]
I'd love to see this as an alternative to ... ellipses, unfortunately I feel strongly it would be best implemented/handled in cairo and pango (the low level drawing/text libs) rather than in cinnamon itself.  The fade you see in our menu is extremely heavy, and buggy, and is best used sparingly.  Any additional burden we put on our theme system would be felt as well, with increased memory and CPU use, particularly with how widespread this might be applied.  As Cinnamon is a single-threaded UI, we have to be careful and choosy about what and how much work we give it.
