### ISSUE TITLE
Lock screen doesn't work

### ISSUE THREAD

**Issue by awnumar** [linuxmint/Cinnamon#6641]
My system information:

```
Linux blackbox 4.11.6-1-ARCH #1 SMP PREEMPT Sat Jun 17 08:19:42 CEST 2017 x86_64 GNU/Linux
```

I have the following versions installed:

```
local/cinnamon 3.4.2-1 (cinnamon)
local/cinnamon-control-center 3.4.0-1 (cinnamon)
local/cinnamon-desktop 3.4.2-1 (cinnamon)
local/cinnamon-menus 3.4.0-1 (cinnamon)
local/cinnamon-screensaver 3.4.1-1 (cinnamon)
local/cinnamon-session 3.4.1-1 (cinnamon)
local/cinnamon-settings-daemon 3.4.2-1 (cinnamon)
local/cinnamon-translations 3.4.2-1 (cinnamon)
```

When attempting to lock the screen, nothing happens. Is there a command I could run to get some more debugging information?

A side note: this issue only appeared with the last update.

**Comment by yami-kage** [comment]
same problem, since latest release on up to date Antergos w/ Cinnamon
`Linux Machine 4.11.6-3-zen #1 ZEN SMP PREEMPT Thu Jun 22 13:47:45 UTC 2017 x86_64 GNU/Linux`
here is terminal output when trying to lock screen / start screensaver in different ways:
`[yami@Machine ~]$ cinnamon-screensaver-lock-dialog 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Can't connect to screensaver!`

`[yami@Machine ~]$ cinnamon-screensaver-command -l
Can't connect to screensaver!`

`[yami@Machine ~]$ cinnamon-screensaver
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 17, in <module>
    from util import utils
  File "/usr/share/cinnamon-screensaver/util/utils.py", line 7, in <module>
    import xapp.os
ModuleNotFoundError: No module named 'xapp'`

is this another python dependency error?
[similar past bug](https://bugs.archlinux.org/task/52316)

**Comment by leigh123linux** [comment]
Get arch to fix their issue

https://bugs.archlinux.org/

You have a missing dep

https://github.com/linuxmint/python-xapp

**Comment by awnumar** [comment]
@leigh123linux I noticed that and installed `python-xapp`. Didn't fix the issue.

It worked fine before the update, so unless the update uninstalled that dependency then I don't see how that could be the cause.

**Comment by leigh123linux** [comment]
@awnumar 

post

cinnamon-screensaver-command -l

**Comment by awnumar** [comment]
@leigh123linux 

Never mind, think it just needed a restart. Thanks!

**Comment by Routhinator** [comment]
Guess this issue affects Ubuntu as well as Arch.
