### ISSUE TITLE
Cinnamon 3.4 On Mint 18.2: White Background after upgrade

### ISSUE THREAD

**Issue by mrsuyyagh** [linuxmint/Cinnamon#6672]
I have just smoothly upgraded Mint from 18.1 to 18.2. After reboot, the desktop background image was replaced by an off white colour. Attempting to select a new background has no effect. I am using the Linux Mint theme, and for Window borders and Controls, the Ambianace theme.

Fiddling around, I noticed that the desktop background image reappears only when I select the desktop layout as 'no desktop icon' -which of course is not a workable solution. Perhaps this has to with how the new cinammon deals with icons.

**Comment by mtwebster** [comment]
It’s a theme issue. Try a different “control” (gtk) theme for now.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/nemo/commit/e5ae40f19db4e449403a27b6c8cb04f0df9a32a0

While testing this, I tried: http://www.omgubuntu.co.uk/2017/05/install-improved-ambiance-gnome-theme - which appears to be fixed already (though I'm not sure how it may differ otherwise from the one supplied in Mint's current 'light-themes' package.)  Not, this new package does *not* address a small border/shadow that gets applied whenever the focus window is *not* on the desktop itself.  This nemo patch will take care of that, and it's minor for now.
