### ISSUE TITLE
Window List improvments

### ISSUE THREAD

**Issue by MajorGrubert** [linuxmint/Cinnamon#67]
In Xfce Panel we have those options :
#1 : Show application name (or not) (I love this)
#2 : Options for ordering button
#3 : Options for grouping behaviour  (allways / never / depend of free space)
#4 : Options for restauring windows (in current workspace / in original workspace)
#5 : Options for showing windows (all workspace / all monitor)

In GS window list extension (not MGSE), here, https://extensions.gnome.org/extension/25/window-list/ 
mouseover shows an overview with a small window picture AND small pictures of other window from the same app, and it's very gorgeous (take a look : https://extensions.gnome.org/static/extension-data/screenshots/screenshot_25.png ) and usefull so :
#6 : Options for mouseover :

. only title app : "Chromium"
. statut app : "New Issue - linuxmint /Cinnamon - GitHub - Chromium"
. simple overview (only window)
. total overview (all app window)

Happy new year.

**Comment by edwinksl** [comment]
What is the current status on the implementation of grouping behavior (#3 feature)? I was going to create an issue when I realized there were already many duplicates, which clearly demonstrate some significant demand for this feature.

**Comment by AdmiralAnimE** [comment]
Can we have a merge of launchers and open windows?
![panel](https://cloud.githubusercontent.com/assets/6396538/10537019/fe0d31f2-73f7-11e5-8a6e-cdb6c58ba7f9.jpg)

**Comment by mbutz** [comment]
Hi,
I am looking for the option for showing all windows from all workspaces in the window list (by default via Alt-Tab). I do not mean: Show one window on all workspaces. Rather I mean to have the option to reach every open application window regardless of whether it is on the current or some other workspace via the window list and therefore by using a keybinding such as Alt-Tab.

This issue seems to be the only one I could referring to this. Does anybody know if this is possible by default or whether there is an applet for this?

Thanks
Martin

**Comment by mcarans** [comment]
Now that the applet "Windows List with App Grouping" breaks with Mint 18.1, app grouping should be added to the default window list so that an applet is not needed.

**Comment by Piiit** [comment]
Just use Icing Task Manager applet

**Comment by mcarans** [comment]
@Piiit Thank you. This works, but I am concerned that it too will end up unmaintained. The Github page for it says: "This is a fork of the unfinished development branch of Window List With App Grouping applet, originally by jake-phy who forked the code from GNOME Shell Window List."

In the case of "Window List With App Grouping", it causes the panel to become unresponsive if installed in Cinnamon 3.2. Given Mint is generally such a friendly Linux OS, this is confusing behaviour particularly for newbie users (who may well have come from other OSes where app grouping works out of the box). 

In my view, app grouping is basic functionality that ought to be included in the default window list.

**Comment by mdchaves** [comment]
Regarding the "App Grouping", it appears to be a very popular request indeed; I personally consider it an essential feature. Similarly, the possibility of having windows list items without titles (on icons) is very nice as well. In my opinion, leaving their implementation to applets is not the best solution. As somebody already said here, most Cinnamon applets tend to get abandoned and buggy over time. Consequently people wrongly blame Cinnamon for crashes and instability caused actually by those applets. Unfortunately Cinnamon gets a bad reputation undeservedly. So in order to resolve that problem, I think that those features should be integrated into the Cinnamon code itself. As a native stock feature, they would get a continuous maintenance, without harming Cinnamon stability.

**Comment by mbutz** [comment]
Concerning my question - see above - I found an answer here: https://forums.linuxmint.com/viewtopic.php?f=208&t=151864. It involves using the gconf-editor and especially a keybinding for the entry "switch-panels". No applets, just plain Cinnamon.

**Comment by mcarans** [comment]
I have had to disable Icing Task Manager as it does not show the correct windows in its preview when multiple windows are open so the only way to get to the correct window is by alt-tab. Therefore, as of now, there is no way to have functioning app grouping.

**Comment by dg1727** [comment]
A "merge of launchers and open windows" didn't show up in this thread until the 11th comment https://github.com/linuxmint/Cinnamon/issues/67#issuecomment-148649748

The similar feature that was being proposed earlier in this thread was (in my words) an option for all window-list buttons for a given app to be combined into one button, with a pop-up menu to select which window to switch to.  

I just want it to be clear what possibilities are being discussed.

**Comment by mcarans** [comment]
We have Icing Task Manager now for app grouping, but as recent issues around libcjs and crashing with Mint 18.2 illustrate, this functionality should be part of the core Cinnamon to ensure that it works out of the box.

**Comment by JosephMcc** [comment]
Thank you for your suggestion. See https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html for information on how we handle feature requests.
