### ISSUE TITLE
[Feature Request] Create a GUI program to change the color/transparency of the panel, menu, and window titles

### ISSUE THREAD

**Issue by ylevental** [linuxmint/Cinnamon#6722]
```
 * Cinnamon version 3.4.4
 * Distribution - Mint 18.2
 * 64 bit
 ```

**Issue**

My idea is that someone will add a GUI program to change the color/transparency of panel, menu, and window titles. Windows 10 can do it, as seen here: http://www.intowindows.com/how-to-change-taskbar-color-in-windows-10/.  You don't see it in the screenshot, but now they include window titles.

**This would help make Cinnamon appeal to a wider range of users.**

**Expected behavior**

The person would be able to pick the color from a palette, and this would instantly change the color of the panel, menu, and window titles.  There would also be a slider to change the transparency.  They could pick all three features simultaneously, or do one at a time.

**Comment by feren** [comment]
@ylevental I'm working on something related to this in the form of a Accent Colour Changer in feren OS, but that's only for the blue colour replacement on the Win10 Cinnamon Theme...
Though, Panel-wise, you could maybe try 'Transparent Panels' for now...

TBH, I don't think they'd do something like this in this current time, especially since an issue of mine over having a Chameleon Colour hasn't really seen any comments so far...

**Comment by mtwebster** [comment]
https://github.com/linuxmint/Cinnamon/issues/3356
