### ISSUE TITLE
onboard is not working any more

### ISSUE THREAD

**Issue by Links2004** [linuxmint/Cinnamon#6816]
```
 * Cinnamon 3.4.6
 * Mint 18.2
 * Intel
 * 64 bit
 ```

**Issue**
i have upgraded my mint setup, with this upgrade i have get a new cinnamon version (3.4.6)
but `onboard` has stopped working.

```
$  onboard
Traceback (most recent call last):
  File "/usr/bin/onboard", line 36, in <module>
    ob = Onboard()
  File "/usr/lib/python3/dist-packages/Onboard/OnboardGtk.py", line 139, in __init__
    remote.Show(dbus_interface=ServiceOnboardKeyboard.IFACE)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.onboard.Onboard.Keyboard' on object at path /org/onboard/Onboard/Keyboard
```
found 
https://forums.linuxmint.com/viewtopic.php?t=249041
and a link to
https://github.com/linuxmint/Cinnamon/commit/48bd81b975e38181171198c94e116aa7160c6c13

**Steps to reproduce**
try to start `onboard` with mint 18.2 cinnamon

```
sudo apt-get install onboard
onboard
```

**Expected behaviour**
`onboard` is starting and working.

**Other information**
if there is a compatibility problem with the integrated onscreen keyboard, how do I remove / disable it, 
and get `onboard` to work?
the integrated on is fare way from what I need.

**Comment by leigh123linux** [comment]
Its by design 

https://github.com/linuxmint/Cinnamon/commit/48bd81b975e38181171198c94e116aa7160c6c13

**Comment by Links2004** [comment]
so no change to get onboard working?
the integrated virtual keyboard is bad compared to onboard's options and flexibility.

**Comment by mtwebster** [comment]
There are a number of technical reasons why onboard doesn't work, which is why it's been blocked.  The only reason it just happened recently is that it was never relevant for us, but upon switching to lightdm as our login manager, it was added as a default app, and began causing problems in Cinnamon (just like Caribou's normal osk does.)

Some interesting, relevant discussion taking place right now with Ubuntu: https://lists.ubuntu.com/archives/ubuntu-desktop/2017-August/005138.html

I'll be keeping an eye on developments there, and If/when anything changes with onboard, we can definitely revisit this.  I'd also like to address issues with our current osk.  As it is not something a majority of users need, things like this tend to lag behind a bit in responsing to new issues, such as those caused by ultra-high resolution monitors.  Not to mention I'm not sure any of the devs own such a monitor at this point.

Feel free to list additional issues with the current keyboard - what keys is it missing, etc..?  We can maybe check for updates to it upstream as well.

**Comment by Links2004** [comment]
I think some pictures and Screenshots says more then some words.

key and size comparison:

![image](https://user-images.githubusercontent.com/974709/29495346-de99540c-85bd-11e7-8654-c06164763846.png)

- key wise there are many keys missing number keys, arrow, pos1, end, ins, page up/down, del, alt gr, menu, right ctrl, right shift, ^, "windows key", may language specific keys like ß, €,   ....
 - the keys move if you switch in the "number mode"
 - not very handy is the fact that the key not on the same places then on a standard keyboard like in onboard
 - on other practical feature that i miss the area left and right of the key can still be used.
 - the keyboard overlaps the panel on the bottom 
 - writing chars like { [ ] } requires 3 detected clicks compared to a key Kombination  

 - not a deal breaker but I think the keyboard theme is to light (If it only where this Issue where never here)

![img_20170820_152923](https://user-images.githubusercontent.com/974709/29495393-aadb5b8c-85be-11e7-9c2d-d6543ca7c6df.jpg)

I get onboard to start wenn its run as root and its working fine then, 
but I clearly don´t want to run is as root on daily based.

not sure what the problems are you mentioned above in mint 18 and 18.1 onboard where working fine for me there.

**Comment by sphh** [comment]
I run into the same problem. May I suggest that at least the user daring to run onboard gets an explanation why onboard does not start. Just to see an exception does not help very much ...

@mtwebster  could you please explain what are the technical issues why onboard does not work. Starting from Cinnamon 17.0 up to 18.2 I had no problems with onboard on any Linux Mint release. Thanks.

Some more thoughts (in no particular order):
* It would be nice to be able to start and stop caribou from the command line.
* Onboard detects if a physical keyboard is attached in which case it does not activate itself.
* Despite the setting "Show the keyboard anytime something expects an input", the caribou keyboard is displayed all the time.
* When activating the setting "Show the keywoard only when the user activates it", I cannot find how to activate/deactivate caribou.
* onboard can be activated/deactivate anytime I want - even if the autohide option is enabled.
* caribou wastes a lot of space with the wide boarders.

Is it somehow possible to reenable onboard again? Pleeeaaze!

**Comment by mtwebster** [comment]
Attempt to use onboard to enter text in the cinnamon menu search box.  Essentially, onboard has no conception of Cinnamon elements on the desktop.  It works fine with normal applications, but we either receive these bug reports or you get them from people complaining it doesn't work for cinnamon itself.

I realize for some this is a regression - I explained the reason for blocking it above.  The same reason caribou was blocked (we actually use caribou's 'library' for the built-in osk).  But having something that only half works, depending on the user in question, wasn't a good option to us.  We'd rather have a good built-in keyboard, however we rely on users to tell us when and how to improve it for the most part, as it's not a commonly used feature.

Now that we have some feedback, we'll definitely work to improve it in the next release, or, if the timing is right, look at making sure this new version of onboard (see mailing list link I mentioned) works with Cinnamon.

**Comment by Links2004** [comment]
may an Environment variable is a option until onboard has full support for cinnamon.

```c
if(getenv("CINNAMON_NOT_ACQUIRE_ONBOARD") == null) {
 cinnamon_dbus_acquire_name (bus,
                           DBUS_NAME_FLAG_REPLACE_EXISTING,
                           &request_name_result,
                           "org.onboard.Onboard", FALSE);
}
```

if a user is able to set the env via `/etc/profile` or `~/.profile` he should know what he is doing,
and know to that onboard will not work perfectly with for example the Cinnamon menu.

for a avg user it will still be blocked and no bug reports from them will come in, 
and if someone really want to use it in the mean time,
you can say deal with it you have activated your self with a hidden switch ;)

will surly help the devs too since they need to test with Cinnamon to get it working.

Note:
I never noticed the the menu search is not working with onboard until now, and its totally something i can life with.

**Comment by sphh** [comment]
Thanks @mtwebster for the explanation.

I noticed the behaviour regarding the menu search box myself. While it was rather annoying, I could live with it, because I could select the program from the menu itself. BTW the corresponding bug report is here: https://bugs.launchpad.net/onboard/+bug/1556250

It looks like you cannot please everybody: Either you get a bug report that onboard is not working in the cinnamon menu (and possibly other cinnamon menu items) or people complain about a mysterious Python exception...

I support @Links2004 suggestion to give the user the power to enable onboard despite its drawbacks. Maybe an initial dialog box telling the user to confirm these drawbacks would be a more user friendly solution. But this dialog box should have a "Don't show again" checkbox (which perhaps becomes enabled again, if a new version of onboard is installed).

**Comment by mtwebster** [comment]
Are you guys all 64-bit mint 18.2? I'll spin a couple cinnamon packages without the block for now if you'd like.

I'd prefer to defer making a permanent change for now until I discuss some more internally, and possibly buy myself some time for the onboard changes (who knows, we may drop our osk if that's good enough - I'd love to have less to maintain) - but we'll have some way to enable onboard in the long run, though it'd be simple enough to tie it to a dconf setting (you could use dconf-editor to enable it) instead of an environment variable.

**Comment by sphh** [comment]
@mtwebster thank you for your generous offer!

Yes, I use 64-bit Mint 18.2.

**Comment by Links2004** [comment]
@mtwebster I am at 64bit too,
for a deb packages without the block I would be very grateful.

a dconf switch for the long run sounds great too (if the onboard changes does not fix the problems).

**Comment by mtwebster** [comment]
Sorry for the delay.. 

First of all, this assumes you're otherwise up-to-date in mint-update thru level 3, including cinnamon updates.

These 2 you definitely need:
https://dl.dropboxusercontent.com/u/8201170/cinnamon/cinnamon_3.4.6_amd64.deb
https://dl.dropboxusercontent.com/u/8201170/cinnamon/cinnamon-common_3.4.6_all.deb

These 2 you should install only if they're already on your system (check if you want with `dpkg --list | grep cinnamon` and look for cinnamon-dbg and cinnamon-doc.  They won't be in a default install.
https://dl.dropboxusercontent.com/u/8201170/cinnamon/cinnamon-dbg_3.4.6_amd64.deb
https://dl.dropboxusercontent.com/u/8201170/cinnamon/cinnamon-doc_3.4.6_all.deb

Download the packages first, then install from a terminal - `dpkg -i *.deb`

After you install, log out and back in.  You'll want to blacklist 'cinnamon' in mintupdate (it'll show up after you install these packages here) - just right-click it and 'ignore updates'.  If you do accidentally update (onboard quits working ;)) just repeat this install.

**Comment by Links2004** [comment]
yay, thanks.
working fine for me.

**Comment by steven-varga** [comment]
Thank you for taking time and providing a fix. However for some reasons I am unable to download the linked files from dropbox, instead I see: "File not Found" error message. 

Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya

**Comment by mtwebster** [comment]
Ah sorry apparently Dropbox just did away with 'public' folders... I've updated the links in the original post, let me know if they cause any trouble.

**Comment by clefebvre** [comment]
Quick follow up on this.

With the following changes in Onboard, we no longer need to inhibit it:

https://github.com/linuxmint/onboard/commit/d03e767431225530b6b889aad9eb5a56a98e74f3
https://bugs.launchpad.net/onboard/+bug/1722511

This will be fixed in Cinnamon 3.6.

**Comment by hoshi411** [comment]
Please fix onboard in cinnamon. Please! This almost killed me to spend so much time getting cinnamon on my system and setup and then realize that such an important app was blocked. More and more of us hybrid , tablet users are switching to cinnamon because it is not laggy and is minimal for our devices and Onboard support is crucial. 
Please do not snub it.

**Comment by juanda3111** [comment]
Hello everyone, can anyone please tell me if this solution works for Ubuntu too? I'm new in linux and at the time I'm using ubuntu 17.10 and cinnamon 3.4.6.
Is kind of urgent, since I need to use onboard because I have a keyboard with the english config and I need to write in russian, for my work.
