### ISSUE TITLE
High CPU load of cinnamon after running for multiple hours

### ISSUE THREAD

**Issue by SethosII** [linuxmint/Cinnamon#6875]
```
 * Cinnamon version (cinnamon --version): Cinnamon 3.4.6
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 18.2
 * Graphics hardware *and* driver used:
lshw -class video
  *-display               
       description: VGA compatible controller
       product: Sky Lake Integrated Graphics
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:280 memory:f0000000-f0ffffff memory:e0000000-efffffff ioport:e000(size=64) memory:c0000-dffff
 * 32 or 64 bit: 64 bit
 ```

**Issue**

Running the computer for a longer period of time leads to high CPU load by the cinnamon process. Restarting cinnamon brings the CPU usage back to normal.

**Steps to reproduce**

1. use the computer for some time
2. eventually hear the fans spin up
3. look at the output of top, CPU usage by cinnamon is high, at least 20 %, but fluctuating mostly between 40 % and 60 %, sometimes even up to 80 %
4. restart cinnamon
5. look again at the output of top, CPU usage by cinnamon is again very low (< 10 %)

**Expected behaviour**

The CPU load of cinnamon should stay low even after longer period of running.

**Other information**

I don't know what would be meaningful, just let me know what you need and I can provide the information.

**Comment by SerafDosSantos** [comment]
I've had this problem lately. I removed all applets with system calls and it fixed most of the problem. Although I can live without applets, Cinnamon is more appealing with them.

I'm hoping there is a fix soon...

**Comment by itzexor** [comment]
If removing third party applets fixes the issue, then the third party applet needs to be fixed. @SethosII are you using third party applets as well?

**Comment by SerafDosSantos** [comment]
@itzexor Yes, mostly third party.

I haven't identified it/them yet, but it needs to be done. What I was mostly thinking at the time was that there shouldn't be third party applets but only applets developed by the Cinnamon team. Else this problem will always exist in some way. Got the word by some 2nd generation third party applet developer that some are like hell to maintain.

**Comment by jaszhix** [comment]
@SerafDosSantos Have you looked at the Cinnamon source? The extension code is completely disorganized. It is part a problem with the applets, but also part the APIs they are consuming. I'm starting to not trust GObject APIs simply because breathing on them the wrong way breaks them. Normal javascript projects do not entail this much trouble with C bindings (e.g. most node projects I've worked on). I think you should be a little more considerate of people who may have spent considerable effort trying to make it work.

The Cinnamon applets are distributed everywhere, and tested and developed by a relatively greater number of people. If you'd like to see the situation improve you could open a PR, but blaming third parties in every issue is not productive.

**Comment by SerafDosSantos** [comment]
@jaszhix I'm sorry to offend you if I am, and I'm wishing not to.

I'm no dev eventho I used to do some before, which is why I keep my info up through GitHub.

I'm simply a long time Mint/Cinnamon user which I think is a great Distro/DE and I'm seeing problems lately which I wasn't seeing before.

Is it the third party applets? I removed them and I have no problems since.

@jaszhix and I were discussing about multicore-sys-monitor@ccadeptic23 in another issue post; applet which I removed and added some replacement; and kept having a high CPU usage. I am from time-to-time trying to find the problem but relatively as a simple user. If it's Cinnamon the problem, well I'm participating into solving the problem. If it is the third party applets, well then, lets fix the problems.

I only hope we can fix the problems. But yet, I'm not a great help into solving them. I'm only a user voice into the Cinnamon project.

Like I said: when I remove the third party applets using system calls, I have no high CPU usage.

**Comment by SethosII** [comment]
The applets I'm using are [Icing Task Manger](https://cinnamon-spices.linuxmint.com/applets/view/269) and [Weather](https://cinnamon-spices.linuxmint.com/applets/view/17). I will disable them and see if it helps. Also, should I try what happens if I remove them when the issue occurs?

**Comment by jaszhix** [comment]
@SerafDosSantos Thanks, its no problem, I was just put off by the suggestion of removing third party applets entirely from Cinnamon. I think extensions are one of Cinnamon's greatest features, and I agree they can use more work in general, but they're also all running in the same context and should be isolated a bit more. I am going to attempt to refactor some of the extension code soon.

@SethosII At least in ITM, there are things that might alleviate the issue, like turning off hover peek, ensuring you're only using app grouping, etc. There's currently an [open issue](https://github.com/linuxmint/cinnamon-spices-applets/issues/1173) on the Spices repo for it. From what I could tell, no functions are getting invoked while its idling, which leads me to think its signal management or a mainloop issue.

**Comment by SethosII** [comment]
I ran without any applets for some time and the issue didn't occur so it seems to be related to an applet.

@jaszhix I will try the debug version of your applet linked in https://github.com/linuxmint/cinnamon-spices-applets/issues/1173#issuecomment-326450374 and report back but I won't be able to do so in the next days, so bare with me.

**Comment by SethosII** [comment]
The issue didn't occur anymore, so closing it.
