### ISSUE TITLE
Problems with 

### ISSUE THREAD

**Issue by cdgoldin** [linuxmint/Cinnamon#6903]
```
 * Cinnamon version: 3.4
 * Distribution:Mint 18.2
 * Graphics hardware *and* driver used: n/a
 * 32 or 64 bit: 64
 ```

**Issue**
1) Where is the documentation for Cinnamon 3.4?

2) gvfs-set-attribute "~/Desktop/IconName.desktop" metadata::nemo-icon-position x,y (where x and y are the x and y coordinates) does nothing

Sudo gvfs-set-attribute "~/Desktop/IconName.desktop" metadata::nemo-icon-position x,y results in
Error setting attribute: Setting attribute metadata::nemo-icon-position not supported

Is this a bug? Or has "gvfs-set-attribute" been replaced by another function? Or has "nemo-icon-position" been replaced by another variable name?

**Steps to reproduce**
Install Linux Mint 18.2 with Cinnamon 3.4. Attempt to set icon position as described above. 

**Expected behaviour**
The icon should move to the specified position (after pressing F5 to refresh the display).

**Other information**

**Comment by leigh123linux** [comment]
File the issue against nemo.

**Comment by cdgoldin** [comment]
It has NOTHING to do with Nemo, as all of the desktop functions are now handled by Cinnamon. 

----- Original Message -----

**Comment by jaszhix** [comment]
@cdgoldin Nemo handles all file-related things, including the desktop grid.

**Comment by cdgoldin** [comment]
Not in Linux Mint 18.2 Cinnamon. And that's the problem I was reporting.

----- Original Message -----

**Comment by leigh123linux** [comment]
Whatever

**Comment by cdgoldin** [comment]
A more reasonable reply would be, "Oh, I wasn't aware of that. Thank you
for the information". A major feature of Mint 18.2 Cinnamon is that the
desktop functions are no longer handled by nemo, which is why most of the
gvfs functions no longer work as they did before. For example, you can
still set the "Default icon zoom level" via Nemo, but it is ignored, and
Cinnamon uses the "Default Icon Size" set by the Desktop (and unknown to
nemo). And F5 no longer resets the desktop under Mint 18.2 Cinnamon. The
only way to refresh the desktop is to move the icons to another folder, and
then move them back. All this is the result of extensive experimentation,
as the developers failed to document it.
So, whatever indeed.

**Comment by leigh123linux** [comment]
@cdgoldin If you are so sure the code is in cinnamon source code you will be able to prove your claim by linking the commit.

FYI nemo was split into two processes for 3.4.x release, nemo and nemo-desktop.
nemo-desktop handles all desktop icons not cinnamon!

https://github.com/linuxmint/nemo/commit/0871c15a8f734058f70047314398afa850a9b70e

**Comment by leigh123linux** [comment]
Now move your issue to nemo!

**Comment by cdgoldin** [comment]
>@cdgoldin If you are so sure the code is in cinnamon source code you will be able to prove your claim by linking the commit.

I can only speak from imperical facts, not "commits", whatever they may be.

>FYI nemo was split into two processes for 3.4.x release, nemo and nemo-desktop. nemo-desktop handles all desktop icons not cinnamon!

If so, why does Cinnamon handle everything differently than 18.2 Mate and Nautilus, and why do many of the nemo functions no longer work? 

linuxmint/nemo@0871c15

**Comment by cdgoldin** [comment]
Why? They will just tell me to move it back to Cinnamon. Besides, it's no longer an issue. I've solved the problem. The gfvs functions and F5 no longer work. 
But thank you for your complete lack of consideration and nastiness.

----- Original Message -----

**Comment by leigh123linux** [comment]
@cdgoldin  Did you uncheck the 'auto-arrange' checkbox?

> But thank you for your complete lack of consideration and nastiness

What did you expect?, this is tame for me :-)

**Comment by leigh123linux** [comment]
@mtwebster  would you agree this is tame for me?
Also can you confirm you wouldn't move it back to cinnamon or any other package and the issue belongs to nemo.

**Comment by cdgoldin** [comment]
>@cdgoldin Did you uncheck the 'auto-arrange' checkbox?

Of course. But thank you for the irrelevant and unhelpful suggestion. How would "auto-arrange" affect the "Default Icon Zoom Level" setting, which is now ignored by the desktop manager (be it Cinnamon, Nemo, or Nemo-desktop)? How would it disable the F5 (refresh desktop)? It would simply "auto-arrange" the desktop icons after any change, which isn't the case, and isn't what I described.

>>cdg: But thank you for your complete lack of consideration and nastiness
>What did you expect?, this is tame for me :-)

Since I don't know you, I expected politeness and helpfulness. We live and learn.

I do find it curious that it took you almost two months to incorrectly decide this issue was in the wrong place, close the discussion, and then use two different aliases to attack me by email.

**Comment by cdgoldin** [comment]
@mtwebster would you agree this is tame for me?
Also can you confirm you wouldn't move it back to cinnamon or any other package and the issue belongs to nemo.

Now that I know you, yes, I can agree.
No, I can't confirm....
Perhaps you should be more careful when you address emails to the wrong person

**Comment by jaszhix** [comment]
@cdgoldin Issues generally apply to the version of Cinnamon we're working on, in this case we're working on 3.6. I think its a little combative the way you're escalating this... I don't blame you for opening it here, you didn't know, but arguing over an issue being closed is just going to waste everybody's time.

**Comment by cdgoldin** [comment]
I'm not arguing, and I'm not escalating. I'm responding to nasty emails with facts. I don't care if you've closed the issue, as you obviously are not interested in solving the problem. You needn't reply. I wouldn't want to waste any more of your time.

----- Original Message -----

**Comment by mtwebster** [comment]
As of Nemo 3.4, there are two binaries that get built, nemo and nemo-desktop.  Previously, it was just a single process always running (providing the desktop, and spawning windowed instances as required.)  Now, nemo-desktop strictly handles the desktop folders and menu, nemo is only used in window instances.

That nemo handles the desktop has never changed from day one - desktop *settings* are shown in cinnamon settings, because we consider Cinnamon and Nemo to be inexorably linked, meant to be used  together - the fact that they're separate packages and processes, etc.. are mere technicalities.

As to your issue, there is logic in the desktop handling that will ignore metadata if necessary.. auto-arrange mode ignores it, align-to-grid will prevent overlap during placement, non-overlap may ignore it as well unless it's user initiated, such as with drag-and-drop.  There are any number of reasons why you can't just set metadata and have it obeyed.

I don't think I could say 'this is intentional" - that doesn't sound right, but it behaves how we want it to (putting aside bugs.)  What you're doing isn't really a valid way to interact with the desktop, regardless of what happens in other file managers, or whatever the underlying file system supports (like the gvfs-utils.)

If there's some functionality missing, or something trying to be worked around here, I'd rather address the issue directly.

**Comment by cdgoldin** [comment]
Thank you for your email.

----- Original Message -----

**Comment by mtwebster** [comment]
The zoom level key does not work for the desktop anymore because you can have independent zoom levels on a per-monitor basis.  The desktop zoom level is stored as desktop metadata now (see ~/.config/nemo/desktop-metadata) to allow this.

gvfs utilities are shipped with gvfs.  They're mainly for troubleshooting, at least that's what I've always used them for, and for scripting purposes.  That they don't affect nemo how you think they should is immaterial.  There's no documentation for this in nemo because this is undocumented, purposely - that metadata is only useful internally to nemo, I don't care that you can't manipulate it from the command line, you were never intended to interact this way with it.

I don't see an issue with F5 - it refreshes my desktop fine.

Again, disabling 'use-desktop-grid' should get you the old desktop back.

**Comment by cdgoldin** [comment]
The zoom level key does not work for the desktop anymore because you can have independent zoom levels on a per-monitor basis. The desktop zoom level is stored as desktop metadata now (see ~/.config/nemo/desktop-metadata) to allow this.

cdg: Thankyou. That is the information I needed.

gvfs utilities are shipped with gvfs. They're mainly for troubleshooting, at least that's what I've always used them for, and for scripting purposes.

cdg: I (and others) are using them for scripting

That they don't affect nemo how you think they should is immaterial. There's no documentation for this in nemo because this is undocumented, purposely - that metadata is only useful internally to nemo, I don't care that you can't manipulate it from the command line, you were never intended to interact this way with it.

cdg: I'm not trying to manipulate anything from the command line. The only reason I issued the command from the command line was because it didn't appear to work in the script. As mentioned earlier, the problem turns out to be the F5, not gvfs-set-attribute

I don't see an issue with F5 - it refreshes my desktop fine.

cdg: I should have been more specific. Under earlier versions of Cinnamon (as well as the current versions of Mate and Nautilus), the icon positions could be changed by gvfs-set-attribute followed by F5 (either entered by the user, or xdotool in a script). Under the current Linux Mint 18.2 Cinnamon, F5 does not achieve this, but (as mentioned earlier) moving the icon to a different folder and then moving it back does.

Again, disabling 'use-desktop-grid' should get you the old desktop back.

cdg: Are you referring to the "dconf-editor > org > nemo > desktop" setting? How would I know how to disable it, if I didn't already know? But the goal isn't to "get the old desktop bacl", but rather to be able to save and restore icon positioning with the new desktop. And, as I mentioned earlier, we have found a method, albeit inelegant. Being able to determine the zoom level from a script was the missing piece.

Thank you again for the information.
