### ISSUE TITLE
cinnamon-settings: tree types inconsistant

### ISSUE THREAD

**Issue by jake1164** [linuxmint/Cinnamon#6969]
```
 * Cinnamon version 3.4
 ```

**Issue**
The new tree options in cinnamon-settings are inconsistent with the rest of the settings.
In the main section its "entry" however embedded in tree its "string" which is annoying. Other settings are:
- **Main settings** : **tree options**
- "switch" : "boolean"
- "file-select" : "file"

Yet others are the same like "keybinding"

Excerpt from demo settings-schema.json

```
    "use-custom-label" : {
        "type" : "switch",
        "default" : false,
        "description": "Check this to use a custom label",
        "tooltip": "Checking this box allows you to set a custom label in the field below - this demonstrates setting dependencies"
    },
    "tree" : {
        "type" : "list",
        "description" : "Custom tree widget",
        "columns" : [
            {"id": "name", "title": "Name", "type": "string"},
            {"id": "resident", "title": "Resident", "type": "boolean"},
            {"id": "address", "title": "Address", "type": "string", "default": "none"},
            {"id": "number", "title": "Id number", "type": "integer", "min": 0, "max": 100},
            {"id": "icon", "title": "Icon", "type": "icon"},
            {"id": "key", "title": "Shortcut key", "type": "keybinding"},
            {"id": "file", "title": "File Path", "type": "file", "select-dir": false}
        ],
        "default" : []
    }

```
**Expected behaviour**
Consistency would make it easier to work with creating new tree settings.

**Other information**

**Comment by collinss** [comment]
@jake1164 when I added this widget to the API, I did so from the perspective of the data type that would be stored, rather than the widget that would be generated to store it. From that perspective, it made more sense to use "string" rather than "entry". Also, I wanted to make this as simple as possible to use (especially since it's already more complicated than I would like), and from my perspective, that means not having to worry about which widget is used in addition to what data is stored. That's part of the reason I didn't make all of the widgets available as well. I'm not trying to say that this is the best way, by any means, but I had reasons for doing it that way. At this point, I'm not sure it's a good idea to change it either, since the api has already been established.
