### ISSUE TITLE
[Feature Request] cinnamon-settings: Expand tree types

### ISSUE THREAD

**Issue by jake1164** [linuxmint/Cinnamon#6970]
```
 * Cinnamon version 3.4
 ```

**Issue**
Expand the tree types to include:
Add "dependency" between Switch (boolean) to entry(string) fields in columns.
Add "combo-box" for a dropdown list in the columns.

**Expected behaviour**
Dependency would work the same as other settings, turn off the associated entry field when off and on allows entry into the field.

**Other information**
Rough idea of the layout:
```

    "tree" : {
        "type" : "list",
        "description" : "Custom tree widget",
        "columns" : [
            {"id": "resident", "title": "Resident", "type": "boolean"},
            {"id": "address", "title": "Address", "type": "string", "default": "none", "dependancy" : "resident"},
            {"id": "combo_demo", "title": "File Type", "type": "combobox", "default" : "option 1", "options": 
                   {
                         "First Choice": "option 1",
                         "Second Choice": "option 2",
                         "Third Choice" : "option 3",
                         "Fourth Choice" : "option 4"
                    }
            }
        ],
        "default" : []
    }
```

**Comment by collinss** [comment]
@jake1164 I'm working on the combo box right now. I'm doing it a little bit different than in your post above. You'll still use string, boolean, integer, etc, but adding the 'options' property will cause it to use a combo box rather than the usual widget for that type.

As for the dependency, I'm not sure how I feel about it. For one thing, there still needs to be something there when the data gets stored, and for another, I'm not sure if it can be hidden in the treeview without creating a new cell renderer class (and that gets really messy), so the data will still show in the list widget, even if it's invalid data.
