### ISSUE TITLE
[Bug?] System-wide Extensions not appearing in 3.6 System Settings

### ISSUE THREAD

**Issue by feren** [linuxmint/Cinnamon#7028]
```
 * Cinnamon version 3.6
 * Distribution - Mint 18.3 BETA (Mint 18.2 + 18.3 Repo, I managed to find out why System Settings wasn't working)
 * Intel
 * 64 Bit
 ```

So, I installed extensions to /usr/share/cinnamon/extensions... and they aren't appearing. (I've made sure they're fully up-to-date, and everything, to no avail. Applets seems to be fine)
![screenshot from 2017-11-16 20-00-32](https://user-images.githubusercontent.com/11057934/32913058-117ed4f6-cb09-11e7-808f-a4d82ae16bad.png)
![screenshot from 2017-11-16 20-02-55](https://user-images.githubusercontent.com/11057934/32913086-287f3100-cb09-11e7-9e6a-898ce984aec4.png)

**Comment by feren** [comment]
...also, locally installed Extensions display there just fine

**Comment by collinss** [comment]
We don't scan for extensions anywhere but ```~/.local/share/cinnamon/extensions/```. This is by design. There are no system extensions included with Cinnamon, so there is no point in scanning for them. User installed extensions should instead be installed in the user's own folder. Likewise, applets and desklets that aren't included with Cinnamon should also be installed to ```~/.local/share/cinnamon/``` as well.

**Comment by collinss** [comment]
After some discussion, we decided that it wouldn't hurt to add this so that distros can ship system extensions if they so desire. I've submitted a pull request already.
