### ISSUE TITLE
Turning off Bluetooth also turns off Wifi

### ISSUE THREAD

**Issue by AgedUser** [linuxmint/Cinnamon#7208]
```
 * Cinnamon version (cinnamon --version)   3.6.7
Kernel: 4.13.0-26-generic x86_64 (64 bit gcc: 5.4.0)

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)   Mint 18.3 64 bit
 * Graphics hardware *and* driver used
Graphics:  Card: Intel Sky Lake Integrated Graphics bus-ID: 00:02.0
           Display Server: X.Org 1.18.4 drivers: (unloaded: fbdev,vesa)
           Resolution: 3200x1800@59.70hz
           GLX Renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
           GLX Version: 3.0 Mesa 17.0.7 Direct Rendering: Yes
 ```

**Issue**

Turn off bluetooth using either menu-preferences-bluetooth or the bluetooth panel icon also turns off wifi.  Wifi will not reconnect even after a reboot.

**Steps to reproduce**

Turn on bluetooth, then see above under "Issue"

**Expected behaviour**

Bluetooth turns off normally, wifi continues to work

**Other information**

See also https://forums.linuxmint.com/viewtopic.php?f=49&t=261803

**Comment by djk-2** [comment]
I'm having the same issue.

Version: Cinnamon 3.4.6
Distribution: Mint 18.2 x64

Graphics:  Card: Advanced Micro Devices [AMD/ATI] Wrestler [Radeon HD 6320]
           bus-ID: 00:01.0 chip-ID: 1002:9806
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz
           GLX Renderer: Gallium 0.4 on AMD PALM (DRM 2.46.0 / 4.8.0-53-generic, LLVM 3.8.0)
           GLX Version: 3.0 Mesa 12.0.6 Direct Rendering: Yes

Network:   Card-1: Broadcom BCM4313 802.11bgn Wireless Network Adapter
           driver: wl bus-ID: 03:00.0 chip-ID: 14e4:4727
           IF: wlo1 state: up mac: <filter>
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: 2000 bus-ID: 07:00.0 chip-ID: 10ec:8168
           IF: eno1 state: down mac: <filter>

Network Driver: bcmwl-kernel-source
                             Version 6.30.223.271+bdcom-Oubuntu1~1.2
                             Broadcom 802.11 Linux STA  wireless driver source

**Issue**, **Steps to reproduce**, and **Expected Behavior** are the same as above.

**Other Information:** I can disable wireless without it disabling bluetooth, i.e. clicking on the wireless icon and turning it off does not turn off the bluetooth.

This is not an issue in Windows running the same system.

**Comment by leigh123linux** [comment]
Please file the issue against blueberry.

https://github.com/linuxmint/blueberry
