### ISSUE TITLE
Startup applications. Add button not exists.

### ISSUE THREAD

**Issue by armd-pro** [linuxmint/Cinnamon#7232]
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * 64 bit
 ```

**Issue**
Add button not exists in startup applications.

![_005](https://user-images.githubusercontent.com/4474900/35483754-94ed5adc-0480-11e8-885b-717cc08d9e70.png)

**Comment by NikoKrause** [comment]
Make your window fullscreen. The buttons texts are too long.

**Comment by collinss** [comment]
We had the same problem with the applet settings page. The text in certain languages is too long to fit in the space allocated, so it just vanishes. Our [work-around](https://github.com/linuxmint/Cinnamon/pull/7041) for that was to move to icons rather than text. It looks like we might have to do the same here unless we can find a better solution.

**Comment by armd-pro** [comment]
![_011](https://user-images.githubusercontent.com/4474900/35558649-96348d2a-05e3-11e8-8be7-f5fa7f419916.png)

**Comment by armd-pro** [comment]
Can reduce horizontal indent?

**Comment by armd-pro** [comment]
Or window set auto width...
Excuse my bad English)

**Comment by armd-pro** [comment]
Or slightly increase the width of the window.

**Comment by clefebvre** [comment]
I agree with @collinss, icons with tooltips are the best way to solve this.

**Comment by JosephMcc** [comment]
This has since been changed.
