### ISSUE TITLE
[FIXED, caused by Nautilus!] How to crash/mess up Nemo Desktop and your wallpaper in 2 steps

### ISSUE THREAD

**Issue by Swiftpaw** [linuxmint/Cinnamon#7293]
EDIT: Cause of problem was Nautilus being installed.  Removed that and everything is fine again!
```
 * Cinnamon version 3.6.7
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used - NVIDIA GTX 1070 w/ 390.25 driver
 * 64-bit
 ```

**Issue**
This makes your background turn black and the Nemo file browser window that opens is messed up in comparison to a normal browser window (the file, edit, view bar will be gone). You can also do this from Firefox if you right-click on show containing folder from a download.

**Steps to reproduce**
1. From a fresh login, and in particular having never opened a Nemo file browser window, have an image on your desktop and click on it to open it in Xviewer.
2. Right-click in the viewer then click on "Show Containing Folder".
If you first open a Nemo file browser window before doing the above, things will work as expected.

**Expected behaviour**
A normal window is opened, and your background and Nemo/Nemodesktop behavior doesn't get hosed.  If you first open a Nemo file browser window before doing the above steps, things will work as expected.

**Other information**
You can also do this from Firefox.  On a fresh login, open Firefox, download any file, click on the arrow to view downloads in Firefox, right click on the file and choose show in containing folder.  Again, if you aven't yet opened a normal Nemo window, doing this will mess up Nemo Desktop (I assume is where the issue lies), make y our desktop background turn black, and mess up other things with your desktop interaction and settings.

**Comment by Swiftpaw** [comment]
P.S. Also able to get it to crash sometimes later on, even after having loaded up a Nemo file browser, by doing Open Containing Folder from Firefox in particular is where I've had it happen.  Not sure why.  Does Nemo get unloaded after a while, so you'd need to leave a file browser window up at all times?

**Comment by mtwebster** [comment]
You probably have nautilus (another file browser) installed. That’s what’s causing the black background. Also it gets preferred over Nemo when using certain things such as Firefox open containing folder. This is pretty much out of our hands. 

If you don’t absolutely need nautilus you should uninstall and these issues should go away.

**Comment by Swiftpaw** [comment]
Oh, at the bottom...got it, thanks again! 🐺

**Comment by Swiftpaw** [comment]
I assume the issue is applications hard-coded to open Nautilus instead of using a XDG/freedesktop standard?  Or maybe there is a standard, but that gnome settings or dconf setting or whatever that standard is keeps being bulldozed over by both Nemo and/or Nautilus for some reason?

**Comment by mainmachine** [comment]
@Swiftpaw - I think it's just an unavoidable byproduct of the overlap in GTK backend bits that are used by Gnome and Cinnamon. I think there's a way to improve this, but I can't remember the specifics - Ubuntu is using it in 18.04 to differentiate the Ubuntu-Gnome session from the "vanilla" Gnome Shell, so that they don't step on each other's settings. If Cinnamon could use this, then it would prevent such problems and allow multiple file managers and settings to co-exist.

**Comment by Swiftpaw** [comment]
@mainmachine I was just thinking about that earlier and how you wouldn't want installing, say, the file manager for XFCE to replace the default one for Unity, just because you wanted to try out two different desktops.  But then that presents the problem of how does the user then configure the system for a different file manager should they want to use it in the "wrong" desktop environment?  That's cool that it's now possible to do in the configuration system that Gnome is using for any updated Gnome-based desktop environment, but for non-Gnome-based DEs like XFCE I don't think this could be done unless XFCE adopted the same standards (if they are or could be actual standards) as GNOME.

Having proper standards for things like preferred application settings that were also per-DE would definitely be cool regardless!  Linux needs more of that kind of stuff to advance.

**Comment by mtwebster** [comment]
The problem here is 100% caused by the org.freedesktop.FileManager1 dbus interface that is used by some programs now to launch a participating file manager and open to a particular file name.  Its problem is there is no way to tell this mechanism 'I'm running a cinnamon session, use nemo for this' or (even better) xdg/mime handlers have XXX filemanager registered for opening folders, use this one.

There is a bug or two open upstream related to this issues already.

How a provider is chosen is completely arbitrary at the moment. This only recently became an issue for us when we split up nemo into two binaries - one for the desktop, and one for windows.  When we had a single file manager binary, it *always* ran in the background, and hence this FileManager1 service was always ready and actively provided by nemo.

Now, nemo is only launched on-demand, like any other program, and goes away when no more windows are open.  This allows another program (like nautilus) - arbitrarily chosen - to fill this role. 

We're going to move this provider role to nemo-desktop, which still always runs, and can 'own' the interface for us, keeping other providers out of it.  It can then pass requests as needed to nemo.

**Comment by Swiftpaw** [comment]
@mtwebster Very cool!  Thanks for the explanation!  Glad to know there's already a solid plan both for Mint and also for freedesktop standards going forward (once the bug is resolved)!

**Comment by mainmachine** [comment]
@mtwebster thanks for curbing our speculation, and thanks for all the fine work you do on Mint, and particularly Cinnamon! :+1:
