### ISSUE TITLE
First login shows password is incorrect, second time same password is ok

### ISSUE THREAD

**Issue by alesisjoan** [linuxmint/Cinnamon#7322]
![4a798276-8cef-4f59-b6c5-54f3a8bd5dca](https://user-images.githubusercontent.com/4945724/36936995-7aeed3ce-1eeb-11e8-97c0-5fa5267e962c.jpeg)

 * Cinnamon version  Cinnamon 3.6.7
 * Distribution - Mint 18.3 Sylvia
 * 64bits
 ```

**First login shows password is incorrect, second time same password is ok**

**Steps to reproduce**
Get the login screen  by booting or suspending and enter your password


**Expected behaviour**
If the password is ok, then it logins and shows your desktop


**Result**
First attempt, it shows you that the password is incorrect. Second attempt, same password, it logins ok and show the desktop. 

**Other information**
It DOES NOT happend if the cpu is on and you close the session. It's always happend after booting or suspending.

No block mayus is ON or another keyboard configuration changed. I waited 10 seconds if it is the wifi connection that has waiting to connect, but the same result.

PS: i searched a lot of google and issues, nothing found.

EDIT: If I wait 20 seconds, it doesn't happen

**Comment by NikoKrause** [comment]
Maybe the first login password was incorrect?

**Comment by alesisjoan** [comment]
@NikoKrause it is systematic. It always happens.

**Comment by scar45** [comment]
This is bizarre, and happens to me as well. When resuming my system from standby, I give it 5-10 seconds to 'settle', then type my password in _correctly_, and it claims it is incorrect. I type it in again correctly, immediately after, and it grants me access.

_Note that this only happens to me with the Cinnamon Screensaver_, and waking from suspend. When I wake the PC from suspend using the keyboard, I hit CTRL or an arrow key, because I thought it was possibly capturing the 'space' key that I usually use. This doesn't appear to be so. Also, I use `lightdm-slick-greeter` and I have no issues logging in upon first boot.

**Comment by icarter09** [comment]
Cinnamon 3.8.7
Linux Mint 19 64bit
AMD Radeon 6520G

I put the computer into "Suspend", then entered in bad password...was unable to login. Entered in another bad password on the second attempt, and still was unable to login. I performed this several times, but was unable to reproduce the issue.

**Comment by alesisjoan** [comment]
Hasn't happened again.
