### ISSUE TITLE
Rounded Bottom Corners

### ISSUE THREAD

**Issue by fennecinspace** [linuxmint/Cinnamon#7530]
```
 * Cinnamon version 3.6.4
 * Distribution - Mint 18.3
 * Graphics hardware *and* driver used GT 740 nvidia-390
 *  64 bit
 ```

**Issue**
Hello, most themes have rounded top courners and i've been trying to add rounded bottom corners cinnamon windows, but it just doesn't work
i've tried modifying th metacity file and the gtk file 
any body have an idea on how to do so ?

**UPDATE:**
it's been 14 days since i posted this !!! nobody has an idea ?? !

**Comment by marcus-lundgren** [comment]
Hopefully this can help you: https://wiki.gnome.org/Attic/GnomeArt/Tutorials/MetacityThemes
Search for `rounded_bottom_left` and `rounded_bottom_right`.

**Comment by LogX7** [comment]
@marcus-lundgren  .. hello marcus, thnx for answering 
I've already tried what you shared before,
here's what an example of what i'm doing 

```
<frame_geometry name="normal" title_scale="medium" rounded_top_left="8" rounded_top_right="8" rounded_bottom_left="8" rounded_bottom_right="8">
	<distance name="left_width" value="1" />
	<distance name="right_width" value="1" />
	<distance name="bottom_height" value="1" />
	<distance name="left_titlebar_edge" value="5" />
	<distance name="right_titlebar_edge" value="5" />
	<distance name="title_vertical_pad" value="4" />
	<aspect_ratio name="button" value="1.0" />
	<border name="title_border" left="4" right="4" top="4" bottom="4" />
	<border name="button_border" left="0" right="0" top="4" bottom="4" />
</frame_geometry>
```

and here's what i'm getting 

<img src="https://i.stack.imgur.com/QOdsF.png">

as you can see the rounded bottom corners don't work .
here's the theme if you want to take a look 
[ARK-DARKER-MODIFIED REPO](https://github.com/LogX7/Arc-Darker-Modified)

your help is much appreciated .. I've been going at this for weeks new

**Comment by marcus-lundgren** [comment]
Yeah, I am not really getting to work either. Maybe talk to the Arc developers, since it their theme? Or is this issue specific to Cinnamon/Muffin?

**Comment by LogX7** [comment]
@marcus-lundgren  ... i've tried with everytheme imaginable ... no bottom round corners possible ... so i'm pretty sure this is a feature in Cinnamon/Muffin that needs to be added ... hopefully

**Comment by JosephMcc** [comment]
Thanks for the request but I wouldn't hold you breath on seeing work done on this. Many windows will use the area all the way down to the bottom corners for things like scrollbars. Rounding those would cause weirdness in some cases.

**Comment by LogX7** [comment]
@JosephMcc  ..i think that "weirdness" can be fixed .. many desktop environment use round bottom corners, and it looks great, i don't really know where to go from here ... but if oyu would be so kind to direct me to what i should work on to start working on this feature ?

**Comment by mfreeman72** [comment]
I'd imagine the "weirdness" would be pretty easily fixed with padding. Put a variable amount of extra space below the window content/scrollbars/whatever relative to the defined corner radius.

**Comment by Shadowblitz16** [comment]
> Thanks for the request but I wouldn't hold you breath on seeing work done on this. Many windows will use the area all the way down to the bottom corners for things like scrollbars. Rounding those would cause weirdness in some cases.

This could be worked around with rounded scrollbars in the theme.
Is this just not being added because you don't feel like it? 
There is some really cool themes that would love to use rounded bottom corners like [this..](https://cinnamon-spices.linuxmint.com/git/themes/Orchidea/screenshot.png)

**Comment by Secret-chest** [comment]
@fennecinspace Please don't force this. Only add support for it, but please don't force it.

**Comment by Secret-chest** [comment]
> Thanks for the request but I wouldn't hold you breath on seeing work done on this. Many windows will use the area all the way down to the bottom corners for things like scrollbars. Rounding those would cause weirdness in some cases.

@JosephMcc Thanks for closing it. We could make it supported so themes can use it, but it shouldn't be forced.

**Comment by Secret-chest** [comment]
> > Thanks for the request but I wouldn't hold you breath on seeing work done on this. Many windows will use the area all the way down to the bottom corners for things like scrollbars. Rounding those would cause weirdness in some cases.
> 
> This could be worked around with rounded scrollbars in the theme. or with padding. Is this just not being added because you don't feel like it? There is some really cool themes that would love to use rounded bottom corners like [this..](https://cinnamon-spices.linuxmint.com/git/themes/Orchidea/screenshot.png)

Padding would look weird, and what about the bottom-left corner? It might have a button or something in it.

**Comment by Shadowblitz16** [comment]
@Secret-chest I think the suggestion was for themes to support it, not to force it.

**Comment by mfreeman72** [comment]
@Secret-chest 
> Padding would look weird, and what about the bottom-left corner? It might have a button or something in it.

I honestly don't see why padding would look weird. As long as it's done correctly, it could look very nice. Rounded corners are done in other DE's with gorgeous results. What's the problem with Cinnamon *optionally* using them as well instead of the constantly squared (and arguably ugly) corners it currently has? Don't like them, then don't use them. But at least allowing the option for those who do want to use them seems like the most reasonable course of action here.

**Comment by JosephMcc** [comment]
It seems this issue just won't die even though it's closed :)

@Shadowblitz16 It has nothing to do with not feeling like it. The metacity theme format and the window managers that use it simply don't support having bottom rounded corners. The only way I could even really see this being possible would be to add a "dead" or padded area at the bottom of the window where the rounding would live. Of course that would involve a lot of work to implement in muffin. Not to mention it would then also have to support it's own version of the theme format. There are a lot of cons to that.

Very few themes would ever support it. Very few people would want that wasted space at the bottom of the window. Many complain if you simply add a couple extra pixels to the top of the titlebar. There is also the problem that Gtk apps using client side decorated windows wouldn't be consistent unless they use libhandy or libadwaita. 

When you add all the overhead, it's not worth what you gain. When you add to that the fact that we actually want to get away from using the metacity theme format in Cinnamon altogether, I don't see support being implemented. It's simply not something that's feasible to add as an option.

**Comment by mfreeman72** [comment]
That's unfortunate. I love Cinnamon, but I also love the look of the rounded corners on these newer themes. Some themes that I want to use just look incomplete in Cinnamon without the rounded corners that the themes are supposed to include. And there aren't "very few of them". There are quite a lot of new ones coming out now with rounded bottom corners.

**Comment by JosephMcc** [comment]
@mfreeman72 Can you show an example of a theme you are talking about?

**Comment by mfreeman72** [comment]
@JosephMcc Here are just a few:

https://www.cinnamon-look.org/p/1220749
https://www.cinnamon-look.org/p/1357889
https://www.cinnamon-look.org/p/1334194
https://www.cinnamon-look.org/p/1403328
https://www.cinnamon-look.org/p/1275087
https://www.cinnamon-look.org/p/1441725
https://www.cinnamon-look.org/p/1309214

**Comment by JosephMcc** [comment]
@mfreeman72 If you look through those screenshots you will notice something that I said above. Only SOME of the windows have rounded bottoms. Those are client side decorated and built with either libhandy or libadwaita. Cinnamon (or any other DE for that matter) has nothing to do with drawing those corners. If you use those apps, and the same versions, under any DE they will have those bottom rounded corners with those themes. That is a look that cannot be duplicated by Cinnamon itself. That is something that is done at level of the individual application.

**Comment by mfreeman72** [comment]
Interesting. I had been told by some of these theme developers that the problem was with Cinnamon not supporting rounded corners. And I've never seen any of these client-side rounded corners on any app. Could you point me to a specific example of one that I could try on my system to confirm?

**Comment by JosephMcc** [comment]
There are only a very small handful in Mint 20.3. Gnome calendar and Seahorse which come on the 20.3 iso both make some use of libhandy. But neither seems to use the rounded windows. The screenshots you were showing show much newer versions of things like Nautilus and gnome-calculator.

>  I had been told by some of these theme developers that the problem was with Cinnamon not supporting rounded corners.

Just not true. You can see even in their own screenshots in things like gnome-shell not all the windows have the bottom rounded corners.

**Comment by mfreeman72** [comment]
Ok. Good to know. Well, I still think it would be a great feature, if it could be implemented properly. But I do understand and appreciate your points and perspective.

**Comment by GingerGigiCat** [comment]
Would this possibility be reconsidered, now that Windows 11 has rounded corners? It seems like it must be able to work nicely, if a major brand like Microsoft did it. It just seems like a shame to miss this feature, since it could be driving Windows 11 users away from cinnamon due to the sharp corners, which they wouldn't be used to and may find ugly.

**Comment by Secret-chest** [comment]
The problem with window content getting cut off still applies. We should try to be better than windows.

**Comment by GingerGigiCat** [comment]
> We should try to be better than windows.

I agree, we should try to be better than windows, but the option should be available to theme creators, since currently there is nothing. It would be nice to have a theme with even a small radius on the corners, just to remove the sharpness. If content being cut off does turn out to be a problem, there should just be a way to disable it per program.

**Comment by mfreeman72** [comment]
> The problem with window content getting cut off still applies. We should try to be better than windows.

There wouldn't be a problem, if done correctly.

That said, as already mentioned, this is already implemented in GTK3/4 programs that use libhandy, and can be used right now in Linux Mint with those programs. Unfortunately, we are cursed, as always, with inconsistency. Unless every program gets updated to use that (don't hold your breath) you'll have some programs with rounded bottom corners and some with squared corners unless something is changed that allows themes to forcibly round all corners.

This CAN be done. It's done successfully in other OSes without major issues. We just have too many standards and too many opposing opinions for anything fruitful to ever happen on this front, and for things to ever be realistically consistent. It's pretty sad, in my opinion. But again, I'm just one voice among too many that disagree with that opinion.

**Comment by Secret-chest** [comment]
Maybe have rounded borders without cutting off window contents, like Windows 7, would be a good solution.
I also think windows should never have rounded corners when maximised or tiled, no matter what.

**Comment by GingerGigiCat** [comment]
> without cutting off window contents, like Windows 7

That could work, but it adds a lot of extra space to the window. It could be an option though.

> windows should never have rounded corners when maximised or tiled, no matter what

Yes, definitely, and there should be a way to temporarily disable it, for example in the right click menu for window titlebars.
Undecorated windows should remove rounded corners.

**Comment by mfreeman72** [comment]
I did some playing around, in combination with some Google searching. Implementing some of what I've found, I've been able to get an almost usable rounded corner just editing the gtk.css in Mint-X (my go-to theme). The only issue is that there's a black box hiding behind the window, and the squared corners of that black box jut out behind the rounded corners. If I could get that problem fixed, then this would be perfectly possible with just theming. And from the (admittedly) minimal testing I've done, no content is ever cut off. If there's content that's mandatory (such as full-window video), it ignores the rounded corners and extends the content to a full square (which I'm ok with in that instance). Most programs seem to respect the rounded corners, though, and there's just about always enough padding around the content that nothing ever gets cut off. Again, if only I could get rid of that annoying black box, I'll be super happy with the results.

Screenshot close-up of my rounded corner with black box jutting out:
![round-corner-with-black-box](https://user-images.githubusercontent.com/7842664/221373946-afc9947f-813d-4dbf-ab60-2356bdb3279d.png)

**Comment by JosephMcc** [comment]
@mfreeman72 This would require changes in muffin to make it work. It simply does not support drawing the bottom rounded corners. It also looks like you are using a very small radius in that case. Most themes give the bottom corners a much larger radius in things like libhandy and libadwaita and that's where you start running into more issues.

**Comment by mfreeman72** [comment]
Ok. So that black box is a hard-coded thing in muffin then, and can't be changed? That's frustrating. As far as the radius size, I don't need a huge rounded corner. I'm just looking for something like my screenshot. Something to just soften the corners a bit. What I've done in my testing is just mirror the exact same roundness that the top corners of Mint-X already have. I think much more roundness than that looks a bit silly, in my opinion. But square corners are too harsh. I just want the ability to soften the harshness of my window themes. On a side-note, I've also rounded the bottom of the drop-down menu corners, all four corners of the context menus, and made the slider bar a little darker and a little more inset away from the edges of the slider area, which improves visibility of it a ton. I just need the rounded corners, maybe add a dark-mode version of it, and this will be my ideal perfect theme!

**Comment by JosephMcc** [comment]
> As far as the radius size, I don't need a huge rounded corner.

Understandable but in most cases themes would want top and bottom corners to match. A lot of themes are using like 6 or 8px radius.

I notice in your other post you noted how libhandy windows do this and it works so well. The problem is there is a very fundamental difference between window types that make this a problem.

With a libhandy window like gnome-calculator the entire window is drawn by the toolkit, GTK in this case. You can think of it as one piece. The content, the window controls, title, even the shadow. So everything is taken into account. That's what's know as a client side decorated or CSD window.

In the case of something like Nemo it is different. It's a server side decorated or SSD window. It works differently. In this case the window is actually two separate pieces. You have the actual window content and then you have the border or frame. Muffin gets just the window content which is basically a rectangle and then draws everything else around it. So the outer frame, titlebar, window controls, and shadow are all drawn by the window manager. So to create a round bottom corner you would essentially have "clip out" a part of the applications actual window and then draw the frame around it. I'm not even sure how doable that really is. It's easy on the top of the window because that is all being drawn by the window manager in the first place.

There is another issue. I'm not sure that this would be simple to even get working but even if you did, hardly any themes would make use of it. Libhandy and Libadwaita have there own specific style classes for drawing there decorations. I don't know of any common window manager that supports bottom rounded corners like this. So it's a significant amount of work for something that would likely never be used outside of Mint's own themes.

Not sure that explanation helps at. Not the best at that :)

**Comment by mfreeman72** [comment]
> Understandable but in most cases themes would want top and bottom corners to match. A lot of themes are using like 6 or 8px radius.

The screenshot of my testing was with a 6px radius, so I don't think 6 to 8px is unreasonable. And if theme designers want to encroach on content with 10+px radius corners, why not let them? In my opinion, f it encroaches on content, that's their issue to deal with. They can add padding or whatever, or just deal with a less functional theme. Users will use what works, and these themes likely won't be as popular, and just become amateurish niche themes. So it should all come out in the wash, as the saying goes.

Otherwise, your explanation of why my css isn't working is very clear and well said. It's unfortunate, though. The way things work right now just isn't flexible enough for nice, modern, consistent theming.

**Comment by VenomMage** [comment]
It's funny how this basic aesthetic upgrade haven't been added even on 2023 and someone even closed this issue, 🤡

**Comment by GingerGigiCat** [comment]
> @mfreeman72 This would require changes in muffin to make it work. It simply does not support drawing the bottom rounded corners.

Can't somebody just edit the source code of muffin to remove the black box??

**Comment by GingerGigiCat** [comment]
I now have proof that this should in fact be possible, the cinnamon extension "Cinnamon Maximus" enables you to remove the titlebar of windows, in turn making the top corners of the window rounded.
Spotify before removing titlebar:
![image](https://github.com/linuxmint/muffin/assets/75206318/429fc50f-d462-4947-b6cf-96258a769a70)

After removing titlebar:
![image](https://github.com/linuxmint/muffin/assets/75206318/4b740179-6027-477f-a52a-b09ffe01d6d0)

Surely it can't be hard to do the same thing to the bottom corners automatically?

**Comment by GuidoBartoli** [comment]
Looking forward to this option too, I think having the possibility to enable bottom rounded corners too on windows would be really nice!

**Comment by neliavaal** [comment]
why is this closed??

**Comment by mfreeman72** [comment]
> why is this closed??

Most likely because there isn't an intention to work on this (according to @JosephMcc), which in my opinion is unfortunate. I would think it should at least be considered for being implemented as an option in Cinnamon/Muffin as well. Again, my own opinion. But I think the devs don't agree, which is their call to make.

**Comment by mfreeman72** [comment]
> I now have proof that this should in fact be possible, the cinnamon extension "Cinnamon Maximus" enables you to remove the titlebar of windows, in turn making the top corners of the window rounded.
> 
> Surely it can't be hard to do the same thing to the bottom corners automatically?

I've tried. There is a squared-off black box that is drawn behind Muffin windows that shows up behind the rounded corner when you add rounded corners in the theme CSS. The top edge of this box can apparently be rounded. The bottom edge cannot. I think this is probably hard-coded in Muffin, in order to prevent clipping the bottom corners from hiding window content or controls. In my opinion, it shouldn't be prevented. Offer the option and let people make themes that use it. Users will decide to use those themes or not, depending on their pros and cons. I think it would look and function just fine, depending on how the theme is made.

**Comment by seadx6-neo** [comment]
> I now have proof that this should in fact be possible, the cinnamon extension "Cinnamon Maximus" enables you to remove the titlebar of windows, in turn making the top corners of the window rounded. Spotify before removing titlebar: ![image](https://private-user-images.githubusercontent.com/75206318/304158868-429fc50f-d462-4947-b6cf-96258a769a70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NTk4OTEsIm5iZiI6MTczNjk1OTU5MSwicGF0aCI6Ii83NTIwNjMxOC8zMDQxNTg4NjgtNDI5ZmM1MGYtZDQ2Mi00OTQ3LWI2Y2YtOTYyNThhNzY5YTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDE2NDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZmIwMTAwODUwOTQ4YWFjNmQyZmNmZjA5NTJjMjBmMTgzODg5MTdkZTg2ODE5ZDhmM2EyMmI2ZGFjYjY3NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.twTbzBl47tJONF0cWjH1tVfq854zMW0hVLlKD5xmQzI)
> 
> After removing titlebar: ![image](https://private-user-images.githubusercontent.com/75206318/304159083-4b740179-6027-477f-a52a-b09ffe01d6d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NTk4OTEsIm5iZiI6MTczNjk1OTU5MSwicGF0aCI6Ii83NTIwNjMxOC8zMDQxNTkwODMtNGI3NDAxNzktNjAyNy00NzdmLWE1MmEtYjA5ZmZlMDFkNmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDE2NDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNGQ3ZGE2ZjdlYjYxMWE3ZGQwYzljMDc1YTYwMzYwZjlkZjMyMmFkMDE3NmJlZGU3NTFmYTM5YzE5MzIzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zti_VGweu43Jw5fCHHDarpJx87z6lxLz4c7XxhJkMhY)
> 
> Surely it can't be hard to do the same thing to the bottom corners automatically?

Gnome has the rounded window corners, since Cinnamon's compositor is based on GNOME's I think the work could be replicated in some capacity, if so I might finally be able to use Cinnamon with some GTK3 apps using Adw GTK3, Steqm with its adwaita theme and my beloved Libadwaita apps

**Comment by mfreeman72** [comment]
> Gnome has the rounded window corners, since Cinnamon's compositor is based on GNOME's I think the work could be replicated in some capacity, if so I might finally be able to use Cinnamon with some GTK3 apps using Adw GTK3, Steqm with its adwaita theme and my beloved Libadwaita apps

You can use Cinnamon right now with GTK3 apps (Cinnamon itself is built on GTK3, and all Mint apps are GTK3 apps). You can even have rounded bottom corners on some client-side decorated apps if they are made using libhandy and libadwaita. Cinnamon just doesn't show any rounded bottom corners on any windows not using libhandy or libadwaita. And neither does Gnome. Run a standard GTK2/3/4 program in Gnome, and it won't have rounded bottom corners, either.

Now, there is a hacky patch for Gnome (mutter-rounded), which also now exists for Cinnamon (as mentioned above) that forces rounded bottom corners on all windows. However, it has some downsides/bugs.
