### ISSUE TITLE
Cinnamon 3.8: skypeforlinux tray icon

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/Cinnamon#7588]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.8.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Ubuntu 18.04
 * Graphics hardware *and* driver used
Intel i5-3520 Intel graphics
 * 32 or 64 bit
64 bit
 ```

**Issue**
Starting with Cinnamon 3.8, the skypeforlinux tray icon is not centered and is duplicated.  See screenshot (this is with a slightly taller panel, but problem exists with a default panel height as well):

![selection_001](https://user-images.githubusercontent.com/2560632/40279112-a9edbc20-5c45-11e8-8480-c639854e6aa8.png)

**Comment by ovari** [comment]
skypeforlinux 8.20.0.9 is doubled in Linux Mint 18.3 Cinnamon 3.6.7. Perhaps this is a Skype bug that should be sent to Skype?
Skype --> Help --> Report a Problem...

Or you could use https://ring.cx/

**Comment by rik-shaw** [comment]
Well this is "kind of" a Skype problem because I am guessing they are not using an app-indicator but instead a "legacy tray icon".  But it is only in Cinnamon that this issue exists.

**Comment by daddy33** [comment]
I have the same issue with pcloud client tray icon, but this is (maybe) related with the panel smart-hide feature.
-- If the cinnamon panel was never hidden since the beginning of the session, the tray icon is OK.
-- But if the panel has been hidden at least once (by maximizing a window for example) the pcloud tray icon is duplicated in the same way, plus it does not change its status any more.

**Comment by ovari** [comment]
Skype has shown double since a few months ago when the Panel is enlarged. Perhaps it is a regression in Cinnamon.

1. System Settings --> Panel --> 
a) Set "Use customized panel size (otherwise it's defined by the theme)" to ON.
b) Set the "Panel height" to 'Larger'
2. Open Skype and you should alway see double.

Are you able to reproduce? Does this help solve this issue?

Thank you

**Comment by jaszhix** [comment]
The issue is this is a 16px icon being resized as a 24px icon. In `_onTrayIconAdded`, I placed this block at the beginning of the function.

```
if (role === 'skypeforlinux') {
    icon.set_width(16);
    icon.set_height(16);
}
```

Which fixes it, but is a hacky fix.

**Comment by rik-shaw** [comment]
@jaszhix I am guessing the problem is for any 16px icon?  I don't know if it is possible to programatically get a pixel size of an image but if so then just center all 16px icons instead of trying to resize?

**Comment by jaszhix** [comment]
@rik-shaw I'm guessing it has to do with the format of the icon used, Cinnamon is normally capable of up-scaling icons AFAIK. In any case, it would result in blurrier icons which is less ideal IMO. The other issue is the indicators icons had a different size than normal tray icons, and #7603 makes them look about the same size.

**Comment by clefebvre** [comment]
Did you find the icon in question? It looks like a larger icon which is cropped to me.. really weird. Anyhow, you're right it behaves in 16px, but there's no reason to make everything else tiny.

https://github.com/linuxmint/Cinnamon/commit/1e933d3c3e7a405bdd3e0295284db8a55332e6ae

**Comment by jaszhix** [comment]
@clefebvre Maybe this could be an option? I don't think they look tiny, its scaling based on panel height.

**Comment by Photon89** [comment]
Related:

https://answers.microsoft.com/en-us/skype/forum/skype_linux-skype_startms-skype_installms/system-tray-icon-in-xfce/d3f162bf-0bbf-481b-90a1-f43cae9a86cc

https://github.com/electron/electron/issues/12791

**Comment by ipolevoy** [comment]
I followed advice: https://github.com/linuxmint/Cinnamon/issues/7588#issuecomment-391990498 and it helped me. I resized the panel to a  larger size, then returned to the original size. 
![selection_003](https://user-images.githubusercontent.com/500941/50105281-e1e2e400-01f1-11e9-8440-b1b59a644c8f.png)

looking good!

**Comment by crnisamuraj** [comment]
just launch skype with following parameter or add following parameter in skypeforinux.desktop launcher found in usr/share/applications/
add it in "exec:" parameter (this line is just missing XDG_CURRENT_DESKTOP=ubuntu:GNOME because it already has launch path)

XDG_CURRENT_DESKTOP=ubuntu:GNOME skypeforlinux
OR
env XDG_CURRENT_DESKTOP=Unity skypeforlinux

**Comment by sunneo** [comment]
In XUbuntu, this can be done by configure panel preferences
* RightClick on Panel 
  *    Panel  \> 
       *  Panel Preferences...

Setting "Maximum Icon size(px)" to 16 at Property of `Notification Area` will fix it
Thanks for your suggestion.
