### ISSUE TITLE
Cinnamon 3.8.2 too many problems of stabililità related to Desklets but not only!

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/Cinnamon#7590]
Weater Desklet Sends Crash Cinnamon without even being able to log in ... and also other Desklets are causing problems and instability!!

I tried to access the site: https://cinnamon-spices.linuxmint.com/desklets

to report problem but I do not log in with Chrome, talking with Firefox?

Please make more stable releases and that do not create so many problems to the users who need the desktop. ..

Cinnamon should ensure to update more regolarmete Applets, Desklets and Extensions that many were interesting but goes back centuries ago precisely to avoid discriminating articles like the one below:

https://www.infoworld.com/article/3036600/linux/is-linux-mint-a-crude-hack-of-existing-debian-based-distributions.html

 * Cinnamon version (Cinnamon 3.8.2)
 * Distribution - (Fedora 28 X64)
 * Graphics hardware : Card-1: Intel Haswell-ULT Integrated Graphics Controller
           Card-2: Advanced Micro Devices [AMD/ATI] Mars LE [Radeon HD 8530M / R5 M240]
           Display Server: x11 (X.org 119.6 ) drivers: i915,radeon Resolution: 1366x768@60.00hz
           OpenGL: renderer: Mesa DRI Intel Haswell Mobile version: 4.5 Mesa 18.0.2

**Comment by collinss** [comment]
Hi @xzj8b3, the spices site is for 3rd party spices, which means that we don't actively develop them, and don't put much time or effort into making sure each one works, however, if it's brought to our attention that one is broken, and isn't being maintained by someone else, we do try to fix them up as we can, or else remove them if fixing is not worth it.
Instead of posting general 'x spices don't work' issues here (which will most likely be ignored), please open an issue for each spice in the respective repository for [applets](https://github.com/linuxmint/cinnamon-spices-applets), [desklets](https://github.com/linuxmint/cinnamon-spices-desklets), [extensions](https://github.com/linuxmint/cinnamon-spices-extensions), and [themes](https://github.com/linuxmint/cinnamon-spices-themes), and follow the issue template.
