### ISSUE TITLE
Panels don't hide when on full-screen

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#7614]
```
 * Cinnamon version 3.8.3
 * Distribution - Manjaro
 ```
**Issue**
Panels stay visible when some programs go full screen. They hide correctly with some programs (Chromium, VLC) but not with others (Evince, Rhythmbox, eog, Gnome Boxes!).

**Steps to reproduce**
Open Evince or eog and press F11.
Or put Evince into presentation mode.

**Expected behaviour**
Panels should hide, but they don't. They cover the content.

**Other information**
There are no errors in the log. I'm on a single-monitor setup. It isn't about CSD because it works with gedit, for example.

**Comment by mtwebster** [comment]
I think I can reproduce with evince (but not eog so far) - can you tell me does the issue 'correct' itself if you focus a different window, then come back to the fullscreened one?

**Comment by germanfr** [comment]
Yes, it does.

**Comment by mtwebster** [comment]
It is csd related - gedit exhibits this as well.

My theory is that the extra padding allocated around a csd window's visible portion is confusing our fullscreen code.  However if you *maximize* the window first, then fullscreen it, the panels hide as they should.  This is because csd windows lose their extra padding when they're maximized, and become exactly the size you see.

**Comment by germanfr** [comment]
Oh, it's true. I had gedit initially maximized. I can't reproduce in non-csd windows. It works fine with Chromium and Firefox, but I guess they are special CSDs.

**Comment by mtwebster** [comment]
Yeah they implement their own client-side decorations (because they're multi-platform I'm assuming)

**Comment by mtwebster** [comment]
Messed up commit auto-close line.. 

https://github.com/linuxmint/muffin/commit/a4801081e2e1356186fa5f24f5fdbc439bedb489
