### ISSUE TITLE
Problems with window manager.

### ISSUE THREAD

**Issue by fredvs** [linuxmint/Cinnamon#7622]
Hello.

How to fix this ?
viewtopic.php?f=208&t=251032
viewtopic.php?f=206&t=251027

Is it possible to get answers ?

Thanks.

Fre;D

**Comment by JosephMcc** [comment]
Couple things. We have an issue template for a reason. Your links also aren't really links. Not sure what we can really do with this.

**Comment by leigh123linux** [comment]
muffin is the 'window manager' for cinnamon, it was forked from mutter.

> That means that Cinnamon must be treated differently than other desktop environments which makes the construction of a cross-platform and cross-desktop GUI toolkit even more difficult.

Care to explain?

**Comment by mse2** [comment]
> Care to explain?
Other window managers notify clients of a minimized window by a UnmapNotify event. In order to track the click on '-' window frame button in a muffin environment one needs to track the property _NET_WM_STATE it seems and the only way to show a minimized window programmatically is to update the _NET_ACTIVE_WINDOW property it seems.
The necessity to construct a GUI toolkit "Mint aware" complicates the task a lot. It is no little task anyway to make a cross platform GUI toolkit which runs with the same look and feel on all supported platforms and where user code doesn't need to be modified platform specific in a single line. MSEgui ensures that.

**Comment by leigh123linux** [comment]
> Other window managers notify clients of a minimized window by a UnmapNotify event. In order to track the click on '-' window frame button in a muffin environment one needs to track the property 

So how do you deal with metacity, mutter or marco?

**Comment by mse2** [comment]
> So how do you deal with metacity, mutter or marco?

Can I read your comment as " We do not want to change anything because metacity, mutter and marco do the same."? No problem with that, I only wanted to help MSEgui users who like to use Mint as their desktop environment.

**Comment by fredvs** [comment]
>  I only wanted to help MSEgui users who like to use Mint as their desktop environment.

Hello.

I cannot imagine that my favorite desktop environment (and number one in distro.watch.com) is against any improvement, even more if those improvement could help a  forked parent to be better.

Fre;D

**Comment by leigh123linux** [comment]
@mse2  Try reading the spec

https://specifications.freedesktop.org/wm-spec/wm-spec-1.4.html

Then if you find a compliance issue you can file it against muffin package

**Comment by mse2** [comment]
> Then if you find a compliance issue you can file it against muffin package

That must be done by a Mint MSEide+MSEgui user. I don't have the time to care about the whole myriad of different Linux desktop environments and window managers so I must concentrate my energy on products with cooperative teams. I beg for your understanding.

**Comment by fredvs** [comment]
> That must be done by a Mint MSEide+MSEgui user. 

OK, Martin I understand but, like you, (and after the strange reaction to close this issue) I must concentrate on products with cooperative teams.
I am absolutely disappointed with the reaction of this Mint team.

Fre;D

**Comment by fredvs** [comment]
> ... (and number one in distrowatch.com)

Huh, Mint is not number one anymore, Manjaro is leader.
Why ?

Fre;D

**Comment by leigh123linux** [comment]
@fredvs 
I agree with  @JosephMcc decision to close this issue for the following reasons

1. It was miss filed, muffin is the 'window manager for cinnamon.
2. No template info was provided.
3. The initial report lacked info and had broken links.


> OK, Martin I understand but, like you, (and after the strange reaction to close this issue) I must concentrate on products with cooperative teams.
> I am absolutely disappointed with the reaction of this Mint team

What do you expect? this isn't our issue.
Looking at the mint forum posts it would appear he wants changes to the WM spec, this would need to be requested at freedesktop.org.

> Huh, Mint is not number one anymore, Manjaro is leader.
> Why ?

They are number 1 because they cheated and bumped the figures up using a bot.

**Comment by fredvs** [comment]
@leigh123linux 
I appreciate that you answered.

> I agree with @JosephMcc decision to close this issue for the following reason

It is your right, of course.
But in my world, where we still  communicate with humans, a minimum of politeness would have been to answer something like this:

"Your issue cannot be accepted for the following reason:... blablabla.
Would you please close this topic you created and create a new one."

> Looking at the mint forum posts it would appear he wants changes to the WM spec

Ha, ok, you did not understand-read the forum posts.

it's sad, this issue is again proof, that in this new millennium only hard and painful words receive answers.

Pity you did not understand that this issue had a positive purpose.

Good luck with Mint.

Fre;D

**Comment by leigh123linux** [comment]
@fredvs OK, you explain this as you seem to think I haven't understood the issue

https://forums.linuxmint.com/viewtopic.php?f=208&t=251032

P.S I'm team fedora :-)

https://badges.fedoraproject.org/user/leigh123linux

**Comment by JosephMcc** [comment]
My closing of your issue was completely valid and I told you why. You ignored the issue template. Your original post provided zero useful info on what the problem actually was. The links didn't actually go to anything explaining it.

I really doubt you are going to get window managers to completely change the way the work to adapt to the needs of what you are doing. It seems neither muffin or marco work with it. If I understand correctly what you want mutter likely doesn't either. That means a large majority of Linux based desktop environments.

**Comment by mse2** [comment]
Fred:
>OK, Martin I understand but, like you, (and after the strange reaction to close this issue) I must concentrate on products with cooperative teams.

If you like you can replay the mutter bug reports
https://bugzilla.gnome.org/show_bug.cgi?id=786363
https://bugzilla.gnome.org/show_bug.cgi?id=786365
on Mint in order to check if it is worth the effort to submit bug reports for Mint.
AFAIK both Mint Gnome 2 and Gnome 3 forks have similar problems with Z-order handling.
Please check if Mint Mate and Cinnamon (I hope I use the right terms) still show the bugs before submitting reports and please use the right Mint terms everywhere.

**Comment by JosephMcc** [comment]
@mse2 Thanks for providing some actually useful info. It's likely those patches can be adapted to work with muffin. I'll look a bit later though if they get in, it may not be for a bit since we are in the middle of the Linux Mint release cycle.

**Comment by fredvs** [comment]
@JosephMcc 

> My closing of your issue was completely valid and I told you why.

Ha, a answer.  OK, your closing was valid but not polite, sorry to be a human. ;)

> I'll look a bit later though if they get in

Yep, this is positive.

@leigh123linux 

> P.S I'm team fedora :-)

Ha, I will install/try it again.

P.S I'm team polYdev :-)
https://github.com/fredvs/polYdev

Fre;D

**Comment by mse2** [comment]
@leigh123linux
>@mse2 Try reading the spec
https://specifications.freedesktop.org/wm-spec/wm-spec-1.4.html
Then if you find a compliance issue you can file it against muffin package

ICCCM:
> Reparenting window managers must unmap the client's window when it is in the Iconic state, even if an ancestor window being unmapped renders the client's window unviewable.

https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#changing_window_state
Bug report:
https://github.com/linuxmint/Cinnamon/issues/7636

Interestingly Mint Mate (Metacity?) *does* unmap the client window. ;-)
