### ISSUE TITLE
Switching workspaces only works with the default shortcut

### ISSUE THREAD

**Issue by germanfr** [linuxmint/Cinnamon#7637]
```
 * Cinnamon version 3.8.3
 * Distribution - Manjaro
 * 64 bit
 ```

**Issue**
**While dragging a window**, you can't switch workspaces with custom keyboard shortcuts, only with the default shortcuts <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>⇨</kbd> and <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>⇦</kbd>. Even if you remove those shortcuts they are still the only way to switch.

**Steps to reproduce**
Start dragging a window and try to switch workspaces through a shortcut different from the default (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>⇨</kbd> and <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>⇦</kbd>).

**Expected behaviour**
All shortcuts should work, not only the default.

**Other information**
It used to work not so long ago, but I can't remember when did it stop working. It works if you are not dragging a window.

**Comment by mtwebster** [comment]
I can't reproduce this - I set my shortcuts to alt-left and alt-right and they work during a drag.

However...

You don't need to use those shortcuts to switch workspaces while dragging a window.  Simply using the arrow keys works (and is noted by the tiling heads-up-display hints):

![screenshot from 2018-06-10 14-09-10](https://user-images.githubusercontent.com/262776/41204867-26debbf8-6cb8-11e8-92a5-1dd43e858bbb.png)

**Comment by mtwebster** [comment]
Ah I see - it worked with my alternate shortcuts because they still contained left/right arrow.  While dragging, however, ordinary shortcuts don't work because muffin is in a grabbed state.  I doubt this has worked for some time, if ever, since the new tiling was implemented.

This is handled here:
https://github.com/linuxmint/muffin/blob/master/src/core/window.c#L10265-L10286

As you can see it's always been hardcoded.  I'll think about how we can maybe have it obey proper shortcuts.
