### ISSUE TITLE
Mint ICCCM compliant ?

### ISSUE THREAD

**Issue by fredvs** [linuxmint/Cinnamon#7641]
Cinnamon version (18.2)
Issue
The window manager for Cinnamon does not unmap the client window if one clicks the '_' window frame button in order to minimize the window.
ICCCM:

Reparenting window managers must unmap the client's window when it is in the Iconic state, even if an ancestor window being unmapped renders the client's window unviewable.

https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#changing_window_state

Steps to reproduce
Run the attached program in a terminal, click the '_' window frame button of the showed black window.
[minimizewindow.c.zip](https://github.com/linuxmint/Cinnamon/files/2089744/minimizewindow.c.zip)

**Other information**

Corresponding Gnome bug reports:

https://gitlab.gnome.org/GNOME/mutter/issues/185
https://bugzilla.opensuse.org/show_bug.cgi?id=1096896

**Comment by itzexor** [comment]
The reason windows are not unmapped is explained on this gnome mutter commit. The reasons are the same here.

https://github.com/GNOME/mutter/commit/aec3edb1cc5ae386efbb08ec7414173478ff0d89#diff-5d2e6395ac2f32aae711a05663b64d18

It is a design decision so that window previews always work.

**Comment by JosephMcc** [comment]
Please stop opening this same issue: https://github.com/linuxmint/Cinnamon/issues/7622 https://github.com/linuxmint/Cinnamon/issues/7636

**Comment by fredvs** [comment]
@itzexor 

Yep, finally somebody that understand the issue.

> t is a design decision so that window previews always work.

So, all modern programs that follow ICCCM directives and his modern features will have problems with Mint.
Thanks for the advice.

> Please stop opening this same issue.
Dont worry, dear JosephMcc, it is my last post for Mint.
And rest assured that the way Mint deals with developers will be known.

Fre;D

**Comment by itzexor** [comment]
To clarify things: it has nothing to do with the mint distribution itself. This was a design decision made by gnome eight or nine years ago when they were creating gnome 3, and we inherited it in cinnamon because cinnamon is a fork of gnome shell.

**Comment by itzexor** [comment]
We didn't make this decision to not follow the specification, and to change it now would break a significant portion of the desktop user experience where minimized or non-current-workspace windows are concerned:

Window list previews, overview, window switcher, etc

**Comment by fredvs** [comment]
To clarify things, the way you treated the issues has all to do with Mint.

A minimum of respect would be highly appreciated.

**Comment by JosephMcc** [comment]
> A minimum of respect would be highly appreciated. 

What do you want here? The original issue https://github.com/linuxmint/Cinnamon/issues/7622 was closed when it was closed because it was completely useless. It ignored the provided issue template, provided zero useful information on the problem, and only had a couple of what looked like were supposed to be links that actually weren't. Another issue was opened https://github.com/linuxmint/Cinnamon/issues/7636 where I said it was by design and unlikely to change. If you don't like that answer, that's fine. But instead yet another issue was opened about the same thing. Continuing to open new issues because you didn't like the answer isn't going to get you anywhere.

**Comment by Bara-Bus** [comment]
@JosephMcc 
I think what fredvs is trying to say and it's common for most people who have little experience like myself is that a simple "Thanks covered by another user" is suffice. The comments you are making is turning away users from helping LinuxMint sustain users. I am a contributor myself and any untoward comments directed at me would surely stop me from contributing at all. The point is there is no need for your over zealous attitude. If you wish to delete this comment I'm fine with that as long as you have understood what you are implying to others.

**Comment by JosephMcc** [comment]
> The comments you are making is turning away users from helping LinuxMint sustain users. I am a contributor myself and any untoward comments directed at me would surely stop me from contributing at all. The point is there is no need for your over zealous attitude. If you wish to delete this comment I'm fine with that as long as you have understood what you are implying to others.

I have no issues with constructive criticism. Until maybe that final comment I fail to see where I was rude. Your "Thanks covered by another user" suggestion doesn't really work here. He posted in both of the other already closed issues so was already well aware of them. He, in fact, opened the first one initially. I also said in both other issues why they were being closed.

The funny part is I actually spent time looking into this to confirm my answer before giving it. We have a lot of repos and a lot of issues to track. Someone constantly opening new issues about the same thing when a answer has already been given isn't going to get great responses all the time. From my side the rude behaviour here isn't actually coming from me.

**Comment by mse2** [comment]
@itzexor
Thank you very much for your kind and informative answer.
>The reason windows are not unmapped is explained on this gnome mutter commit. The reasons are the same here.
It is a design decision so that window previews always work.

That is interesting. I slowly understand why it is so difficult to make a toolkit which works well on average Linux desktops and window managers *and* Gnome and its derivatives. Design decisions! ;-)
In MSEgui I use the unmap event in conjunction wit the WM_STATE property in order to minimize the opened application windows if one minimizes the main window. After showing any window of the application the state before the minimizing will be restored.  
Minimizing also triggers TForm.OnHide, restoring TForm.OnShow what apparently does not work with Gnome and its derivatives, a difficult situation.
And how is it intended to normalize a minimized window programmatically? The only way I found is to set the _NET_ACTIVE_WINDOW property, please see
https://forums.linuxmint.com/viewtopic.php?f=208&t=251032
which also would be a little bit special if true.
Is there a list of Gnome design decisions which toolkit makers should know?

**Comment by JosephMcc** [comment]
Why not look at how Gtk and or Qt handle this? Do they not behave the way you would want?

**Comment by mse2** [comment]
Have a look on how KDE handles it. They show the window icon instead a preview for minimized windows.

**Comment by JosephMcc** [comment]
> Have a look on how KDE handles it. They show the window icon instead a preview for minimized windows.

That isn't the behaviour we want which is why it works the way it does. That's also the reason why we aren't going to change muffin to accommodate this.

**Comment by mse2** [comment]
That means you introduce a third window state despite of visible and invisible.  
Visible: update and refresh the window content in real-time which can consume much CPU-power and limit battery lifetime.  
Invisible: Do not refresh window content because it would be wasted CPU- and battery-power.  
Minimized: Show a static image for preview purpose.  
-> Applications must be built especially for Mint, no ideal situation.

**Comment by JosephMcc** [comment]
> -> Applications must be built especially for Mint, no ideal situation.

It seems applications written in toolkits like Gtk, Qt, and Electron work just fine.

**Comment by mse2** [comment]
>And how is it intended to normalize a minimized window programmatically?

I opened a separate issue for the question.
https://github.com/linuxmint/muffin/issues/325

**Comment by JosephMcc** [comment]
I'm locking this issues on the Cinnamon repo. You have the new one on muffin which is where it really belongs anyway. Even though it's closed you can still post in it and we still get notifications for it. Let's just keep it all in one place.
