### ISSUE TITLE
Wayland slowing down Cinnamon GUI on Nvidia GPUs

### ISSUE THREAD

**Issue by Futureknows** [linuxmint/Cinnamon#7669]
There are several report on systems with Nvidia GPUs of Wayland noticeably slowing down the GUI even when it is not the active GDM (x.org, Gnome, Cinnamon, etc):

[https://www.hyperborea.org/journal/2017/11/nvidia-unusable-fedora/](url)

This can be detected by issuing this command 

`ps -ef | grep -i wayland`

On all my Cinnamon distros this exposes Wayland is running. The fix under Gnome is to disable Wayland by adding **WaylandEnable=false** to **/etc/gdm/custom.conf**

Since Cinnamon doesn't create **/etc/gdm/custom.conf** I am wondering how I can disable Wayland when running Cinnamon. Many current distros install and run Wayland even when it is not the active GDM.

**Comment by clefebvre** [comment]
That's up to distros and/or gdm. It's not related to Cinnamon, there's nothing we can do on our side.

**Comment by leigh123linux** [comment]
I have never seen wayland in any of my cinnamon sessions, the issue you linked only affects gnome.

**Comment by Futureknows** [comment]
To clariify the Wayland-EGL and other modules are installed by Nvidia proprietary drivers even when running Cinnamon. The best current solution may be moving back to Nouveau for Cinnamon.

**Comment by leigh123linux** [comment]
@Futureknows  just beacause nvidia installs wayland support doesn't mean it's used.
GDM is busted by nvidia driver because it has broken wayland detection.

https://www.hyperborea.org/journal/2017/11/nvidia-unusable-fedora/

None of that affects cinnamon as it doesn't use or load wayland!

FTR I'm the rpmfusion nvidia driver maintainer, enabling nvidia modesetting was required to support Optimus hardware using Prime.
I don't care or regret breaking GDM, if the gnome devs cared they would have fixed their broken shit several releases ago.
