### ISSUE TITLE
Request: Option to fix desklet location relative to particular display

### ISSUE THREAD

**Issue by kauffy** [linuxmint/cinnamon#7674]
```
 * Cinnamon 3.6.7
 * Mint 18.3
 * Graphics:  Card-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0412
           Card-2: NVIDIA GM206 [GeForce GTX 960] bus-ID: 01:00.0 chip-ID: 10de:1401
           Display Server: X.Org 1.18.4 driver: nvidia Resolution: 1920x1200@59.95hz, 2560x1080@60.00hz
           GLX Renderer: GeForce GTX 960/PCIe/SSE2 GLX Version: 4.6.0 NVIDIA 390.30 Direct Rendering: Yes

 * 64 bit
 ```

**Issue**
Desklet location is mapped to absolute coordinates of the entire desktop. This causes the desklets to change location if monitors are added/removed.

**Steps to reproduce**
On a multi-monitor system, move (virtually) one monitor over the primary monitor. Then disable all the monitors, except the primary.

Place a desklet at the top of the screen on the primary monitor.

Enable the monitor above the primary monitor.

The desklets will have moved location, relative to their placement on the monitor they were added to.

**Expected behaviour**

That desklets will remain fixed in place on a given display, regardless of the configuration of other monitors on the same system.

**Other information**
In the attached pictures, which include the entire desktop of 2/3 monitors, you can see in the desktop with just two monitors that the desklets for disk space (the green circles on the left), appear about half-way down the desktop, and other desklets appear in the top-right.

In the picture with three monitors, the diskspace desklets appear at the top of the screen (desired location), the other desklets that had been in the top-right, are now gone (presumably moved up into the invisible area not covered by any monitor), and two other desklets (pictures and binary clock) are now visible on the bottom-right (again, presumed to be in dead space below the primary display when just two monitors are on).

This is an issue on several systems for me:
On this system (a desktop), I turn this top display on and off regularly (it is a 40" HD that is connected to many things)
![desktop_desklet_location_sony_monitor_on](https://user-images.githubusercontent.com/2880436/41943158-3c6155f2-7957-11e8-8c29-6b9146f7b3e1.png)
![desktop_desklet_placement_sony_monitor_off](https://user-images.githubusercontent.com/2880436/41943159-3c84f5d4-7957-11e8-88a8-a6ab3e335da9.png)

. If it's on, there's a fair chance that items may launch to that display, even though I may have something else displaying on that monitor (as in, it's not displaying this machine).

On my laptops, they are sometimes connected to external displays.

**Comment by BobBorges** [comment]
Agreed with ^. I'm working in academia and I move between setups with different monitor configurations and rooms with projectors multiple times a day – it would be nice not to put my system monitor and 3-day weather up on the projector for a classroom full of students or a meeting room full of colleagues.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by BobBorges** [comment]
Did anything ever happen with this? I've resolved to just not using desklets, but I miss them.

**Comment by andreacasini** [comment]
Still seems to be a problem in Mint 21, was there any progress with this?

**Comment by BobBorges** [comment]
Nothing I know of. Still using mint w/out desklets :D

**Comment by mdsakibanwar** [comment]
:(

**Comment by jahagirdar** [comment]
Why is this marked as completed? I still see this problem. I switch between 3 configurations.
1. Only laptop Display
2. Laptop +FHD Display
3. Laptop + 4K display.
My desklets are visible only in the 3rd configuration. Atleast an option to "Collect all desklets on this display" will make it useful. Right now I have no method for recovering my desklets in configuration 1 & 2

**Comment by sfrooster** [comment]
Current state of desklets in multi-monitor setups is that the desklet will simply not display. Try this:

- boot with multiple monitors; I'm using an old Macbook Pro so it has the built-in plus 2 external monitors
- add a desklet (I've tried this with two different ones)
-  the desklet won't be displayed - try whatever you want - it won't show anywhere
- shutdown the system
- disconnect the external monitors
- start the system

The added desklets now show on the primary/built-in monitor with no additional work

**Comment by jtoberling** [comment]
Same here - on cinnaom 6.2.9+wilma. 
Isn't there any magic options in settings?
Very disturbing... :(

**Comment by alexeymuranov** [comment]
A somewhat related issue: currently some of the desklets scale inconsistently with "'Monitor scale" option, which further complicates their use when switching between different display configurations.

**Comment by ajhmain** [comment]
Ridiculous that this is supposedly "closed as completed", the issue is absolutely still present in Mint 22.1 Cinnamon.  At the least it should be either still in "review" 6 years later, or "closed won't fix" if that is the actual reality.
 
I have a 3 monitor setup on a desktop, 1920x1200,  2560x1440 (2.5k) and 3840x2160 (4k) as a single desktop.  
The 4k monitor is shared between the desktop and a work laptop and so "connects" to each OS when I change the monitor input source.  When the 4k appears to the OS, it causes the Mint to  refresh each display and as a result desklets reposition themselves off the top of the smaller screens. Sometimes they can't even be seen and need to be manually restarted.  
It seems desklets still use absolute positioning, so when the higher res 4k monitor appears a desklet that was at 100px from top of the 1920x1200 screen is now well above the top of the "virtual spanned desktop".
I don't have the time or skill to fix this myself.  But to anyone who actually does care (unlike the closer of this issue) desklets need to remember both the monitor they are positioned on AND a  top / left offset as percentages, NOT an absolute offset.  So regardless of the size of the virtual desktop  (it changes when a new monitor is added, removed) a desklet will maintain its relative position on the monitor.
