### ISSUE TITLE
Adding text to panel

### ISSUE THREAD

**Issue by nurgasemetey** [linuxmint/Cinnamon#7676]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 3.0.7
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 18
 * Graphics hardware *and* driver used
** Nvidia 
 * 32 or 64 bit
64 bit
 ```

**Question**
I have a question. I want to add text to panel. Is it possible?
Currently I am only able to apply some style: 

```js
Main.getPanels().forEach(panel => {
    panel.actor.add_style_class_name('panel-semi-transparent__internal')
});
            
```

**Comment by germanfr** [comment]
Hi, that class name is from one of my extensions. If you need help with it you can open an issue [on the repo](https://github.com/germanfr/cinnamon-transparent-panels) so that we don't spam Cinnamon developers.

But a class name has nothing to do with text. If you really want to add text to the panel you'll need to create an applet (I don't know any that does just that). Here is a small tutorial: [http://developer.linuxmint.com/reference/git/cinnamon-tutorials/write-applet.html](http://developer.linuxmint.com/reference/git/cinnamon-tutorials/write-applet.html).
The method you need to call after creating the applet is `this.set_applet_label(text)` on the applet.

**Comment by nurgasemetey** [comment]
Sorry for cloning. I cloned your extension and used it for creating another extension. I just want to see text on panel. 
Does panel support adding text?

For example like this:

`panel.actor.set_applet_label('text');`

Because it seems that I didn't suppor that.

**Comment by nurgasemetey** [comment]
Forgot to mention, I have seen all tutorials and know basic about extension and appliet but it seems that Cinnamon (some functons are taken from Gnome) doesn't have proper documentation. That's why I asked this question here.

**Comment by germanfr** [comment]
> Sorry for cloning. I cloned your extension and used it for creating another extension.

Don't worry, anyone can do that as long as they keep it free as the license states.


> Does panel support adding text?

Yes, but mine is an extension and what you need is an applet. They are similar but they are different things.  Take a look at [the demo applet](https://github.com/linuxmint/Cinnamon/tree/a4792312a48eb9a00e281df436e4429ae9d86002/files/usr/share/cinnamon/applets/settings-example%40cinnamon.org). It's also in your system, try starting from there :+1: 

> For example like this:
`panel.actor.set_applet_label('text');`

No, that's wrong. You need to call it on `this` from the applet.

**Comment by nurgasemetey** [comment]
Oh I see, it creates polygon and sets text on it, not pasting text on panel. I wanted to implement this.

![addtext_com_mteynjm0mju4mzq](https://user-images.githubusercontent.com/4669437/41983767-afffdf70-7a37-11e8-8a3e-eded85c46bf9.png)

**Comment by nurgasemetey** [comment]
So text will not steal place from other elements, just imprinting.

**Comment by collinss** [comment]
You can look at the calendar applet. It's a good example of a text-only applet. You can find it on your computer at `/usr/share/cinnamon/applets/calendar@cinnamon.org`. I'd recommend using that one rather than the one here on the master branch because I don't know if it will work with your version of cjs. The current version was changed quite a bit in recent versions to support the latest javascript but I believe some of it at least requires the latest version of cjs, and yours is going to be about 2 years old.

**Comment by collinss** [comment]
Ah, if you don't want to actually take up space on your panel, you would need to use a separate actor and overlay it on top. You could do this by adding your actors directly to the uiGroup.
It would look something like:
```
const Main = imports.ui.main;
const St = imports.gi.St;

myActor = new St.Label('My Text');
main.uiGroup.add_actor(myActor);
// make sure the label is on top of the panel
```

**Comment by nurgasemetey** [comment]
@collinss , thanks for help, I can convert it to applet from extension.

**Comment by nurgasemetey** [comment]
@collinss Really, I will definitely try this.

**Comment by collinss** [comment]
You may also run into issues with it blocking mouse events to the panel if you do it that way, idk.

**Comment by NikoKrause** [comment]
There's the settings-example applet:
![screenshot-cinnamon-2018-06-27-182046](https://user-images.githubusercontent.com/8415124/41986577-d7878850-7a36-11e8-8a25-86e46e99b4fb.png)
