### ISSUE TITLE
Chrome shadow is drew before the Chrome window appears, and doesn't go when I close chrome (mint 19)

### ISSUE THREAD

**Issue by artik** [linuxmint/Cinnamon#7734]
```
nemo 3.8.4
Mint 19
Nvidia HW with nvidia 390 drivers
64 bit
 ```

**Issue**

Chrome shadow is drew before the Chrome window appears.
When I close chrome, a right shadow stay till I click on the desktop (The GIF doesn't show this last behaviour because of my recording tool.)

https://thumbs.gfycat.com/GaseousSameErin-max-1mb.gif

**Steps to reproduce**
Just launch chrome

**Expected behaviour**
That the shadow and the Chrome window appear at the same time. 

**Other information**
Is there a way to remove them like it was in mint 18.3?

**Comment by mtwebster** [comment]
What chrome version?  I do notice the slightly early shadow (maybe < 100ms though, only really noticeable if you're looking for it,) but the shadow remaining, I can't reproduce.
```
Version 67.0.3396.99 (Official Build) (64-bit)
nvidia 390.48 (NVIDIA GM107GLM [Quadro M1200 Mobile])
```
Does the lingering shadow occur if you turn off "Use system title bar and borders" in settings?

**Comment by artik** [comment]
Chrome version:

`Version 67.0.3396.99 (Official Build) (64-bit)`

> Does the lingering shadow occur if you turn off "Use system title bar and borders" in settings?

Yes, same effect. this bug on slow machine is really annoying. Even on fast ones ;)

**Comment by germanfr** [comment]
This has nothing to do with shadows because it's been happening long before they started to be drawn a few weeks ago. The window is created but the paint is kind of delayed. For a few seconds, you can click on the browser but what you see is what there was behind it just when the window was created. You see the shadow because the window is there, but it turns out it looks like transparent. I've always thought that was a Chromium issue.

**Comment by leigh123linux** [comment]
Using "system title bar and borders" clearly shows the issue is within chrome, muffin draws the bar and frame correctly.

https://leigh123linux.fedorapeople.org/pub/screenshots/simplescreenrecorder-2018-07-15_15.39.11.mp4

**Comment by artik** [comment]
As everyone seems affected, not better to remove shadow for chrome windows like it was in the previous mint? It gives a really slow OS sensation compare to before.

**Comment by leigh123linux** [comment]
The issue also reproduces in gnome-shell which points to the issue being within chrome itself.

**Comment by artik** [comment]
As chrome engine won't be re-written for a shadow issue, I doubt this bug will be fixed within the coming years. Maybe the best way was to revert this shadow's fix added between 18.3 and 19 to avoid mint users this ugly behavior.

**Comment by mtwebster** [comment]
This issue existed long before the shadow patch in muffin, it just wasn't as apparent (With window effects active, you could observe a slight distortion of the portion of desktop/underlying windows prior to the chrome window acutally appearing.  I just reproduced this with the shadow patch reverted to confirm.)  I'm also disinclined to revert the entire patch over one program, since this also occurs in environments other than Cinnamon.

I did a bit of searching and found this chromium bug report, and a recent patch:

https://bugs.chromium.org/p/chromium/issues/detail?id=554008#c26

I'm not sure what the release roadmaps are like for chrome/ium, or whether this patch is 'live' or not yet.  It definitely looks like the issue, at least the startup one.

**Comment by artik** [comment]
« I just reproduced this with the shadow patch reverted to confirm« 

mtwebster would you tell me how you did? It could be interesting.

**Comment by mtwebster** [comment]
```
# enable source code repositories in "Software Sources"
git clone https://github.com/linuxmint/muffin.git
cd muffin
git revert 9ce812547b
# in commit editor, assuming it's nano editor, ctrl-o, enter, ctrl-x
sudo apt-get build-dep muffin             # install dependencies
dpkg-buildpackage
cd ..
sudo dpkg -i *.deb
# restart cinnamon
```

As long as you have window effects turned on (particularly the 'map' effect,) when you start chrome, you'll see a distortion in front of any windows/desktop where the chrome window will appear.  It is probably helpful to make sure some random windows are visible so you can detect the distortion.  I've seen this for months, if not well over a year, in chrome, before I switched back to firefox some time back.

p.s. If you want to keep this package in your system, make sure to right-click- ignore it in MintUpdate, as apt will consider the repo version 'newer' than this one.

**Comment by mtwebster** [comment]
Here's a comparison of chrome-stable and -unstable, using a cpu slowdown program:

https://www.dropbox.com/s/x146mc005rysluw/chrome.mp4?dl=0

Looks like they've addressed at least the ugliness if not the underlying behavior of showing a window before it has content.

**Comment by artik** [comment]
Difference of speed is impressive, even if I hate their new design. I reverted the commit (I had signing key error, but it worked) Maybe providing your .deb should help?

The shadow is gone, what a great news. Thanks for all your help mtwebster!

**Comment by mtwebster** [comment]
You can ignore the signing error when building for yourself.
