### ISSUE TITLE
message boxes over-agressively line-wrap text

### ISSUE THREAD

**Issue by GitHubIsToxic** [linuxmint/Cinnamon#7838]
On my system, most message boxes have their text contents aggressively line-wrapped, making them hard to read (especially if an error message contains a file path containing spaces). Often the message box window is taller than it is wider, which also looks rather ugly. It seems the width of the message box is only defined by the width of the icon + button(s), but doesn't consider the text contents (however long or short the text string).

Run this in terminal to reproduce:
`zenity --warning --text="Please don't wrap this text so aggressively!"`
I would expect the above text to show up on one line.
![mint_msgbox](https://user-images.githubusercontent.com/6215449/44993673-abaf8a80-af9b-11e8-8b7d-9bd66633075b.png)

Perhaps this could be related to display resolution? I have a rather non-standard 5:4 monitor at the moment (1280x1024). I will check if the issue persists once I have a new monitor.

Linux Mint 19 Cinnamon (64-bit)
Cinnamon version: 3.8.8
NVIDIA GeForce GTX 1060 6GB

**Comment by mtwebster** [comment]
We have no control over zenity dialogs, nor any dialogs created by programs not under our ownership, though by default dialogs tend to be too large rather than too small (if using GtkDialog to create them.)

The zenity issue seems caused by zenity itself.  We work around this in muffin when displaying Force Close dialogs (for unresponsive windows) by forcing a wider window size:

https://github.com/linuxmint/muffin/commit/8188c391c6e2da2df69a19ac81349ff3e0129e14#diff-7d635a16510a85cdb1fa97cf83773902R650

**Comment by GitHubIsToxic** [comment]
Another workaround for this is specifying the "--no-wrap" argument, but be careful, the dialog may now become to large to display on some systems.

**Comment by smurphos** [comment]
Or use a `--width=xxx` argument.

e.g

`zenity --warning --width=200 --text="Please don't wrap this text so aggressively!"`
