### ISSUE TITLE
Power management applet doesn't show battery percentage

### ISSUE THREAD

**Issue by serrand** [linuxmint/Cinnamon#7972]
```
 * Cinnamon version: 3.8.9
 * Distribution: antergos
 * Graphics hardware and software: 00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) (Thinkpad T520) + intel graphics driver (xf86-video-intel 1:2.99.917+853+g0932a6b3-)
 * 64 bit


 ```

**Issue**
Ever since upgrading to some 4.0.0 packages, I can't see the battery percentage in my panel. 

[serrand@local ~]$ pacman -Q | grep cinnamon
cinnamon 3.8.9-1
cinnamon-control-center 4.0.0-1
cinnamon-desktop 4.0.0-1
cinnamon-menus 4.0.0-1
cinnamon-screensaver 3.8.3-1
cinnamon-session 4.0.0-1
cinnamon-settings-daemon 4.0.0-1
cinnamon-translations 3.8.2-1

**Steps to reproduce**

**Expected behaviour**
The applet showing the battery percentage.

**Other information**

[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2538375/xsession-errors.txt)

**Comment by eli-schwartz** [comment]
I did some basic tests when pushing the initial packages last night, but did not notice the missing power applet. Looks like this is due to https://github.com/linuxmint/cinnamon-settings-daemon/commit/501afc3123c1aa47751c536095e1577c2f8a65b4 requiring a corresponding patch to cinnamon itself -- https://github.com/linuxmint/cinnamon/commit/91302ec086ee2061e57dd972baaa43eb0926b150

I can push a backport of this commit while we wait for the final release of the cinnamon package, which fixed the applet for me.

**Comment by eli-schwartz** [comment]
Should be fixed now, please run the following command to upgrade to a fixed version:

`sudo pacman -Syu 'cinnamon>=3.8.9-2'`

**Comment by serrand** [comment]
@eli-schwartz thanks, that solved it for me!
