### ISSUE TITLE
Cinnamon 4: Panel icons are distorted and other icons have weird issues too

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/Cinnamon#8019]
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**
In Cinnamon 4, all the icons on the "task bar" have weird issues:

1) Panel icons (icons that are immediately to the left of the Menu button) are stretched horizontally
2) Active application icons are too large and there's no margin between them and the edge and some even have few pixels cut off
3) Applet section icons are also not sized properly and some of them look blurry. I'm guessing this is because 48x48px icons are resized.

![screenshot from 2018-11-12 12-38-13-fs8](https://user-images.githubusercontent.com/7957590/48365437-efe49880-e678-11e8-83dd-48d3483d869d.png)

**Comment by nick-s-b** [comment]
@smurphos I'm using Arc-Dark theme. I'd use Mint-y-dark if it weren't for those green highlights (don't like green).

**Comment by JosephMcc** [comment]
Mint-Y is now available in color variations on git master. Does the issue happen with Mint-Y?

**Comment by smurphos** [comment]
> @smurphos I'm using Arc-Dark theme. I'd use Mint-y-dark if it weren't for those green highlights (don't like green).

Are you using the original https://github.com/horst3180/arc-theme or the currently maintained fork https://github.com/NicoHood/arc-theme? If the former try the latter at it is at least getting updated currently, although it's still missing features introduced with  Cinnamon 3.6 and I think you'll still see the same issues.

Quick fix your end should be to open panel settings for that panel and set a fixed icon size rather than using scale optimally or scale exactly - the issue is the theme and it's use of padding and borders interfering with Cinnamon 4's icon scaling.

**Comment by smurphos** [comment]
@JosephMcc Mint-Y color variations are looking really nice

**Comment by nick-s-b** [comment]
@JosephMcc @smurphos Thanks guys! Just installed `mint-themes-git` and there's so many awesome themes. Went with the Aqua variations and there's no distortions! Awesome. Thanks again!
