### ISSUE TITLE
GWL thumbnails on click shouldn't disable thumbnails on hover

### ISSUE THREAD

**Issue by timawesomeness** [linuxmint/cinnamon#8058]
```
 * Cinnamon version - 4.0.2
 * Distribution - Arch
 * Graphics hardware *and* driver used - gtx 960, nvidia 410.78
 * 32 or 64 bit - 64 bit
 ```

**Issue**

Enabling "Open thumbnails on click" disables thumbnails on hover.

**Steps to reproduce**

Enable "Open thumbnails on click", hover over a program's icon

**Expected behaviour**

Thumbnails should still be shown on hover if that option is enabled. Having thumbnails visible on both click and hover is a desirable configuration, as it allows for the following currently impossible behavior:

* Allow click to toggle on non-grouped windows
* Disable click to toggle on grouped windows
* Still show thumbnails on non-grouped windows

**Comment by jaszhix** [comment]
For those three conditions you're suggesting, are they all suppose to work that way simultaneously? There are ways to achieve each of those, but not at the same time. From a functional point of view, it doesn't make sense to me to not respect one setting because another setting is enabled - especially when they are conflicting settings.

The option to click to open the thumbnail menu is there to keep the menu out of people's way, and by having no menu when there is only one window in a group, it reduces the clutter further. The app button would then toggle the window's focus, which would be the extent of the thumbnail's functionality when one window is open.

**Comment by timawesomeness** [comment]
Yes, ideally there would be a way for all of those to work simultaneously. Currently with thumbnails on click enabled there's no way to quickly see the content of a non-grouped window without switching to that window.

**Comment by JosephMcc** [comment]
Closing this since I don't think this is something we will be implementing.
