### ISSUE TITLE
BusName Should not be used for the player's display name

### ISSUE THREAD

**Issue by JasonLG1979** [linuxmint/Cinnamon#8061]
**Cinnamon version 3.8.9**
**Linux Mint 19 64 bit**

**Issue**

```this._busName.split('.')[3];``` Is used for a player's display name in your MPRIS panel applet. This breaks for D-Bus activatable apps with bus names like ```org.mpris.MediaPlayer2.io.github.Pithos```.

Mpris has an "Identity" prop that should be used for display purposes if available.

As a result your sound applet displays "Io" instead of "Pithos" for example.

**Steps to reproduce**

Start Pithos (or a great many media players for that matter) and note that the name in wrong in the applet.

**Expected behaviour**

The player's name be displayed correctly in the applet.

**Comment by JasonLG1979** [comment]
Looks good although I would say that ```return this._name.charAt(0).toUpperCase() + this._name.slice(1);``` is unnecessary since the "Identity" prop is non-optional and should already be formatted to how the player wants it's name displayed. i.e. if it is proper to capitalize the first letter in the players name it should already be capitalized.

**Comment by JasonLG1979** [comment]
You'd do better to capitalize ```this._busName.split('.')[3]``` in ```_dbus_acquired``` if there is no Identity value.

**Comment by JasonLG1979** [comment]
Something like:
```js
        if (this._mediaServer.Identity) {
            this._name = this._mediaServer.Identity;
        } else {
            let name = this._busName.split('.')[3];
            this._name = name.charAt(0).toUpperCase() + name.slice(1);
        }
```

**Comment by JasonLG1979** [comment]
I'm also not sure why you wouldn't just do ```this._busName.replace('org.mpris.MediaPlayer2.', '');``` instead of ```this._busName.split('.')[3];``` it would leave you better off in any case no matter the busName in the event of no Identity value.

**Comment by mtwebster** [comment]
21a089d33fe3c7c9

After dealing with bug reports for the 1,359 music players out there, I'd rather hedge my bets and keep the bus name path available as well, especially while we're in the middle of a release.

Thanks for the feedback.

**Comment by JasonLG1979** [comment]
> After dealing with bug reports for the 1,359 music players out there, I'd rather hedge my bets and keep the bus name path available as well, especially while we're in the middle of a release.

Right on. I feel your pain. I can count on 1 hand all the players that get MPRIS right. Almost all player MPRIS implementations are broken in at least some way often in mind numbingly stupid ways. Sometimes I wish I could just grab and shake the devs and be like "Did you even skim the interface docs?!?!" lol!!!

**Comment by JasonLG1979** [comment]
Was ```this._name = displayName.charAt(0).toUpperCase() + this._name.slice(1);``` intentional? Should it not be ```this._name = displayName.charAt(0).toUpperCase() + displayName.slice(1);```?

**Comment by JasonLG1979** [comment]
```this._name = displayName.charAt(0).toUpperCase() + this._name.slice(1);``` would give you "Irg.mpris.MediaPlayer2.io.github.Pithos" from "org.mpris.MediaPlayer2.io.github.Pithos".

**Comment by JasonLG1979** [comment]
```this._name = displayName.charAt(0).toUpperCase() + displayName.slice(1);``` would get you "Io.github.Pithos"

**Comment by mtwebster** [comment]
Always open to improvements - the sound applet doesn't always get much attention (until it breaks) so it's not surprising we're doing sync io there.

**Comment by JasonLG1979** [comment]
I would be interested in assisting with rewritting the logic, I like how it look for the most part.

**Comment by mtwebster** [comment]
Like I said before, things are not cut and dry with all the players out there.  They frequently don't have reliable cached proxy properties, honestly I can't remember every issue over the years, but the lists were added to solve problems, no one actually wants them.  But the bottom line is, with Cinnamon we're making a desktop for mint, we want things to work for a release, and in the past we tried to be tolerant of these issues (instead of just flat out refusing to support something because *they* won't fix it or don't have time to).  This just isn't our attitude and never has been.  So, sometimes a black- or whitelist becomes the simplest (read: least likely to regress something) fix for the short term.

Perhaps these lists aren't necessary anymore, maybe all these issues are resolved to where we can all follow the rules and things work, but it would take someone testing all of this, and it's not a high priority with a small group of devs, particularly if it's not visibly broken.

As far as blocking io being bad, trust me we know (don't get me started on the entire single-threaded desktop paradigm), but again we're a small group, things get overlooked.

**Comment by JasonLG1979** [comment]
Off the top of my head a few things I would do:

Encapsulate the DBus proxies and expose just the needed signals and properties. Much like I have done in:
https://github.com/JasonLG1979/gnome-shell-extensions-mpris-indicator-button/blob/master/mprisindicatorbutton%40JasonLG1979.github.io/dbus.js

Where the DBus proxy is wrapped and only exposes signals for adding and removing players.

And the MPRIS proxies are wrapped together to form one object from the outside.

 MprisProxyHandler exposes properties that can be bound directly to the UI with ```bind_property``` so there are no need for handler functions.

 https://github.com/JasonLG1979/gnome-shell-extensions-mpris-indicator-button/blob/master/mprisindicatorbutton%40JasonLG1979.github.io/extension.js#L354-L408

**Comment by mtwebster** [comment]
Understood, like I said, we'd definitely appreciate any effort, I just want to make sure that you understand some of why we do what we do - we tend to cater to a different crowd than shell, and not all of our users understand or care what 'this is an upstream issue' means, they just want it to work - I don't want to lose any legacy 'knowledge' accidentally.

As far as rewriting, anything can be changed.  If you think the ui might look better this or that way, don't hesitate to at least bring it up.  This applet is definitely one of the more complex but undermaintained ones and needs work. Anything at this level though probably won't make it in to Cinnamon 4.0, just because we try to avoid anything but fixes at this stage (pending a Mint release).

**Comment by JasonLG1979** [comment]
That's cool. I understand that if it means a regression it's a no-go and I know that Cinnamon tends to be a bit more conservative as far as dependencies so I'd want to make sure all the current goodies like arrow functions, proper(ish) classes and what not filter down. Basically when Lang dies,lol!!!

**Comment by JasonLG1979** [comment]
Hit me up when gets all the goodies currently available in GNOME Shell 3.30. And I'll bang it out.

**Comment by mtwebster** [comment]
That might be a long wait, we don't really keep up with shell, for various reasons, other than when necessity dictates it (since gnome drives most of the upstream libraries as well).  I'm not sure specifically what you're looking for here.

**Comment by JasonLG1979** [comment]
Basically ES6 and the ability to more proper GObject subclasses without using Lang.

**Comment by JasonLG1979** [comment]
Basically whenever you update to at least the current version of Gjs.

**Comment by itzexor** [comment]
We are on gjs 1.52

**Comment by jaszhix** [comment]
@JasonLG1979 We're using mozjs52 and have already implemented ES6 classes in a lot of Cinnamon, including the sound applet.

**Comment by JasonLG1979** [comment]
@jaszhix and @itzexor Cool. I wasn't sure where you guys were at as far as that was concerned.

**Comment by JasonLG1979** [comment]
>We're using mozjs52 and have already implemented ES6 classes

@jaszhix ES6 classes are great but I was talking about more about GObject subclasses. I see that you have ```GObject.registerClass``` in your Cjs GObject overrides which is what I really need/want.

**Comment by JasonLG1979** [comment]
I suppose I can start with an easy fix all the setting cover art nastiness.

**Comment by jaszhix** [comment]
Yeah, that's available to use. We currently don't use GObject classes much, but I recently found a reason to in #8068, so we can use vfuncs instead of signals, which might help latency a little bit. If you look at _legacy.js in cjs/gjs, there's a lot of boilerplate/overhead I've generally been wary of adding to all of our vanilla JS classes. I think exposing vfuncs to these JS classes is an OK compromise.

**Comment by JasonLG1979** [comment]
I much prefer proper (well as proper as they can get with js) over all that Lang crap...
