### ISSUE TITLE
Menu search returns unrelated results [Regression]

### ISSUE THREAD

**Issue by LingMan** [linuxmint/cinnamon#8070]
```
 * Cinnamon version: 4.0.1
 * Distribution: Manjaro
 * Graphics hardware *and* driver used: R9 390 with Kernel 4.18 and Mesa 18.2.5
 * 64 bit
 ```

**Issue**
Menu search lists unexpected items.

**Steps to reproduce**
Search for "cal".

**Expected behaviour**
The results are
- Calculator
- LibreOffice Calc
- maybe other relevant elements

**Actual behaviour**
The results are
- Calculator
- Color
- Date & Time
- Hot Corners
- LibreOffice Calc
...

**Other information**
This is a regression since Cinnamon 3.8. It feels like whatever fixed https://github.com/linuxmint/Cinnamon/issues/4053 got removed again.

**Comment by Xeronel** [comment]
I can confirm that I am also experiencing this issue. It is particularly bad for me when I type "ter" and get things like Skype, Online Accounts, Network, etc and my expected items like "Terminal" are way down at the bottom of all the unrelated items.

**Comment by Curly060** [comment]
I can confirm this, too. Commit a849090d94aa6104b638aba5150f5c317ded5198 is the culprit. That commit totally negates my original pull request https://github.com/linuxmint/Cinnamon/pull/6929.
@clefebvre Could you please have a look at this? I know this search thing is a looong ongoing story, but now we are really back to square one.

**Comment by jarq6c** [comment]
Just installed LM 19.1 and this problem persists. Search worked perfectly in 18.3. I expect to see Firefox and Firewall as the top search results if I type "f" or "fi", but this is not the case until "fir" is typed. If you type "f" or "fi", Archive Manager is the top search result.

**Comment by icarter09** [comment]
This issue is directly related to #8166, which explains why the search is actually returning correct results, but not in the intended affect that a search should be or how a user would anticipate the search to work.

**Comment by oles** [comment]
Cinnamon 4.0.8

![screenshot from 2019-01-02 10-41-11](https://user-images.githubusercontent.com/7634050/50586728-22419380-0e7b-11e9-914e-2cc82b70231d.png)

:confused:

**Comment by Curly060** [comment]
I have made another attempt at fixing this. This is still not perfect, but hopefully it respects all wishes I have seen so far with the menu search:
- by default the search only matches application names and only at word boundaries
- added a config switch to also search in keywords (this is no longer a fulltext search on the keywords text but rather looks at each keyword in turn and if the keyword starts with the search pattern, that application is included)
- added a config switch to also search in the description (only matches at word boundaries inside the description)

So there is no longer any kind of full text search in place any more at all. IMHO it makes no sense to find "starter" when you typed <kbd>t</kbd><kbd>e</kbd><kbd>r</kbd>).

Because of the new settings the dialog currently isn't quite high enough. I don't know how to fix that.

I am well aware that this is still a workaround, but IMHO with compromises for everyone. Feel free to discuss this new approach. Any constructive feedback is welcome.

Cheers, Curly060 =;->

**Comment by LingMan** [comment]
After reading a few of the related tickets I think there are two distinct issues at play here.

First, the search often returns results which most people will consider unrelated, even when taking into account keywords and the description. These get returned because the old search matches at any place in the strings and not just at word boundaries. E.g. "Firefox" is found for the search term "ter" because it has the keyword "internet".
https://github.com/linuxmint/Cinnamon/pull/6929 hid this because in most cases mentioned here a matching application was found. https://github.com/linuxmint/Cinnamon/commit/a849090d94aa6104b638aba5150f5c317ded5198 then made them visible again.

Second, even the expected search results are not sorted by their relevance. Introducing configuration options to enable or disable keyword and description searches can - at least in my opinion - only be a short term hack until https://github.com/linuxmint/Cinnamon/issues/8166 gets fixed properly.
The question of weather the search results from keywords are wanted or not is dynamic and cannot be answered by a (relatively) static user setting.

**Comment by astier** [comment]
Yes this becomes really annoying. Often it is more efficient just to grab the mouse and select the desired result manually instead of typing the whole name of the desired application.

**Comment by dalu** [comment]
This "fix" is not a fix. It's regression itself. https://github.com/linuxmint/cinnamon/commit/d40ba4f900da90f09ecda78f3b139f7bef0fd4cf is to blame
I can for instance no longer search for `ged` to find gedit.
