### ISSUE TITLE
Option to disable window-shadows

### ISSUE THREAD

**Issue by astier** [linuxmint/cinnamon#8083]
```
 * Cinnamon version 4.0.3
 * Distribution - Arch
 * Graphics hardware: Intel HD Graphics 5300, Modesetting
 * 64 bit
 ```

**Issue**
It is not possible to disable window-shadows (at least I couldn't find any option for this).

**Expected behaviour**
There should be an option for example in the Effects-Settings to disable window-shadows.

**Comment by jaszhix** [comment]
You should be able to disable shadows by setting `MUFFIN_NO_SHADOWS=1` in your environment. I agree though, it would be more user-friendly if this was in the UI.

**Comment by Odyseus** [comment]
Hello, everybody.

@astier: There is also [Custom Shadows](https://cinnamon-spices.linuxmint.com/extensions/view/43) Cinnamon extension. With it you can remove the shadows or tweak them at your liking. Although, I don't know if it works with recent versions of Cinnamon.

**Comment by astier** [comment]
I will leave this issue open because I still think that this feature should be implemented. If the devs think otherwise then close it.

**Comment by icarter09** [comment]
@jaszhix can you add the "Feature Request" label to this ticket? Thanks.

**Comment by aleex5** [comment]
cinnamon without shadows looks horrible, the corners are square and the windows practically has no borders, if there are two windows with the same color, it is not known where one ends and the other begins

to add this feature, they will also have to work on the corners and edges, because the desktop without shadows looks pretty bad

**Comment by astier** [comment]
I personally don't need this feature anymore. As far as I am concerned the devs can close it.

**Comment by aleex5** [comment]
I know that this is a lot of work, but this feature is necessary, at least to me, I always like to deactivate unnecessary shadows or transparencies, because they only waste resources

also if there is more customization in cinnamon, it is better suited to different people, because not everyone has the same needs or tastes in certain things

I love cinnamon, but I still need more customization, I'm also forced to have the shadows activated, which I do not like, because without them the desk looks horrible

**Comment by JosephMcc** [comment]
> cinnamon without shadows looks horrible, the corners are square and the windows practically has no borders, if there are two windows with the same color, it is not known where one ends and the other begins

This is up to the theme you are using. Find one that draws the borders differently.

> also if there is more customization in cinnamon, it is better suited to different people, because not everyone has the same needs or tastes in certain things

More customization also brings a lot more potential for bugs and issues. Anything that is added as an option has to have what we feel is a real a legitimate reason. Not just because one person wants it. Doesn't mean we won't make things customizable but these things have to be worth the trouble and additional work.

**Comment by aleex5** [comment]
> This is up to the theme you are using. Find one that draws the borders differently.

I'm using the mint-Y-dark theme, apparently it does not draw the edges and it has square corners
I do not know what theme to try, because there are few that I like
maybe try the numix dark theme, to see if that is solved

> More customization also brings a lot more potential for bugs and issues. Anything that is added as an option has to have what we feel is a real legitimate reason. Not just because one person wants it. Doesn't mean we won't make things customizable but these things have to be worth the trouble and additional work.

I know that everything that is added can cause errors or problems, but if they use that logic to reject suggestions, then cinnamon would not be what it is now.

is not a feature that is urgently needed, but I do not think I'm the only person who wants this in the appearance settings, I'm sure many at the time wanted to turn off the shadows and did not see the option in the configurations

before finding this post, I saw several posts where there were people asking how to turn off the shadows, there were even old posts, so I do not think it's a useless feature

**Comment by smurphos** [comment]
@aleex5 - most of these retro metacity themes draw a window border and have been specifically fixed up to work with Cinnamon 19 and later - https://github.com/smurphos/Window_Borders_Mint_19

Numix metacity themes are borderless as are the majority of newer themes....

**Comment by aleex5** [comment]
I've been trying some subjects and still look very bad the appearance of the desktop, I realize that although I use shadows the same thing happens, the shadows only hide a little the square corners and help to see the limit of the windows

but really the corners are still square and have a very bad edge, with or without shadows

**Comment by astier** [comment]
@aleex5 Then maybe you should open a separate issue for this if it bothers you.

**Comment by aleex5** [comment]
changing the theme of window borders, a decent border is displayed
the "mint-Y" theme if you improve your "window edges" theme, without shadows it would look good

![1-1](https://user-images.githubusercontent.com/35360938/58442083-a8be7200-80b5-11e9-9328-28b0b003de2c.png)
![1-2](https://user-images.githubusercontent.com/35360938/58442082-a8be7200-80b5-11e9-8c6d-3fa9edcd97bf.png)

![2-1](https://user-images.githubusercontent.com/35360938/58442081-a825db80-80b5-11e9-8b8d-27f99b3a9aa6.png)
![2-2](https://user-images.githubusercontent.com/35360938/58442080-a825db80-80b5-11e9-83cc-7b3871964068.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
