### ISSUE TITLE
panel doesn't auto-hide when i mouse over the "multi-core system monitor" applet

### ISSUE THREAD

**Issue by caelulum** [linuxmint/Cinnamon#8100]
```
 * Cinnamon 3.8.9
 * Distribution - Mint 19
 * GTX 1060; nvidia-driver-390
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

panel doesn't auto-hide when i mouse over the "multi-core system monitor" applet

**Steps to reproduce**

- install the "multi-core system monitor" applet
- set the panel it is on to auto-hide
- mouse over the system monitor and then without clicking or anything take the mouse cursor away from the panel

**Expected behaviour**

the panel to auto hide

**Other information**

**Comment by jaszhix** [comment]
That applet has to modify the panel state itself because the cairo graphs block mouse events. See https://github.com/linuxmint/cinnamon-spices-applets/issues/1938

I'm not able to reproduce this - in any case I think this should be filed in the [applets repository](https://github.com/linuxmint/cinnamon-spices-applets) instead with the complete issue template filled out (attach ~/.xsession-errors).
