### ISSUE TITLE
Replace/override Lockscreen

### ISSUE THREAD

**Issue by Valinwolf** [linuxmint/cinnamon#8138]
```
 * Cinnamon 3.8.9
 * Fedora 29
 * Intel Core i3-3360M integrated graphics with default Fedora drivers
 * x86_64 architecture
 ```

**Issue**
Cinnamon Lockscreen is out of place and very ugly. 

**Steps to reproduce**
Use cinnamon Lockscreen.

**Expected behaviour**
Use display manager instead of Cinnamon's built in Lockscreen  

**Other information**
There was a ticket open 2 years ago pertaining to this, but I propose instead of "harmonizing" the display manager and the Lockscreen, to replace the Lockscreen with the display manager's own ability to lock the system. It could be triggered by sending the switch user "command"

**Comment by itzexor** [comment]
I don't know about other display managers, but at least with lightdm that doesn't lock the session. All it does is spawn a new x server on the next tty.

If you're using lightdm try:
1. switch user
2. press ctrl+alt+f7 (may be on a different number from F1 to F7)

**Comment by Tinkerwolf** [comment]
I use GDM. I'm sure lightdm has a session lock though. Maybe give an option for advanced users that allows the override of the lockscreen using a command or something. Or maybe a compatibility based option.

**Comment by Tinkerwolf** [comment]
Hmm... Interesting. GDM does the same thing. On the other hand, lightdm has an accessory/add-in that gives it a session locker, which is why I thought it did. I've been trying to get a nice unified lock and login screen for months and I've tried many different DMs and solutions, none of which have been elegant. For example to use lightdm with light locker to replace the cinnamon lockscreen, I had to rebind the shortcut and remove the lock button from the menu, which is obviously not ideal. It'd be much better if there was a way to override the lockscreen with the light locker command. Either way, my feature request still stands. I want a way to replace or override the lockscreen with an external program, even if it was an "Advanced" or hidden setting.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Cinnamon. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
