### ISSUE TITLE
Cinnamon crashes at startup and won't restart since upgrade to Mint 19.1 Tessa

### ISSUE THREAD

**Issue by Vic1248** [linuxmint/Cinnamon#8185]
```
 * Cinnamon version (cinnamon --version)
4.0.8 wm

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19.1 Tessa

 * Graphics hardware *and* driver used
           Device-1: AMD RV200/M7 [Mobility Radeon 7500] vendor: IBM ThinkPad T4x Series 
           driver: radeon v: kernel bus ID: 01:00.0 chip ID: 1002:4c57 
           Display: x11 server: X.Org 1.19.6 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           resolution: 1024x768~60Hz 
           OpenGL: renderer: Mesa DRI R100 (RV200 4C57) x86/MMX/SSE2 DRI2 v: 1.3 Mesa 18.0.5 
           direct render: Yes 

 * 32 or 64 bit
32-bit

 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```
Dec 21 08:28:43 survivor-ThinkPad-T42 rsyslogd:  [origin software="rsyslogd" swVersion="8.32.0" x-pid="636" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Dec 21 08:29:18 survivor-ThinkPad-T42 mintreport[1530]: Cannot create a regex for all the transitions, the syntax highlighting process will be slower than usual.#012The error was: Error while compiling regular expression ((?-ix)\(gdb\)|---|Kill|Using|Program|Starting|No symbol|(?-ix)^\[(?:New |Switching to )?(?:Thread|LWP)\s+((?:(?-ix)(?:-?[1-9][0-9]*|(?:(?x-i)#012      (?<![\w\.]) 0 [xX] [0-9a-fA-F]+ (?![\w\.])#012    #012))))?.*\]$|(?-ix)^Thread \d+ \((?:Thread|LWP)\s+((?:(?-ix)(?:-?[1-9][0-9]*|(?:(?x-i)#012      (?<![\w\.]) 0 [xX] [0-9a-fA-F]+ (?![\w\.])#012    #012)))).*\):$|(?-ix)^#(\d+)\s+<(signal handler called)>$|(?-ix)^(?:(?-ix)((?P<address>(?:(?x-i)#012      (?<![\w\.]) 0 [xX] [0-9a-fA-F]+ (?![\w\.])#012    #012))\s+in\s+)?(?:(?P<function>\*?(?:(?-ix)[A-Za-z_][A-Za-z0-9_]*(?:@@[A-Za-z0-9_\.]+)?))|(?P<badfunction>\?\?))\s+\()|(?-ix)^#(?P<framenumber>-?\d+)\s+(?:(?-ix)((?P<address>(?:(?x-i)#012      (?<![\w\.]) 0 [xX] [0-9a-fA-F]+ (?![\w\.])#012    #012))\s+in\s+)?(?:(?P<function>\*?(?:(?-ix)[A-Za-z_][A-Za-z0-9_]*(?:@@[A-Za-z0-9_\.]+)?))|(?P<badfunction>\?\?))\s+\()|(?-ix)^\s+(?:at|from)\s+(?P<filename>(?:(?-ix).+?))(?P<linenumber>\:[0-9]+)?$) at char 653: two named subpatterns have the same name
Dec 21 08:30:02 survivor-ThinkPad-T42 anacron[626]: Job `cron.daily' terminated
Dec 21 08:30:02 survivor-ThinkPad-T42 anacron[626]: Normal exit (1 job run)
Dec 21 08:31:42 survivor-ThinkPad-T42 dbus-daemon[2071]: [session uid=0 pid=2069] AppArmor D-Bus mediation is enabled
Dec 21 08:31:47 survivor-ThinkPad-T42 systemd-resolved[624]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Dec 21 08:31:55 survivor-ThinkPad-T42 dbus-daemon[648]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.66' (uid=0 pid=2483 comm="/usr/bin/gdbus call --system --dest org.freedeskto" label="unconfined")
Dec 21 08:31:55 survivor-ThinkPad-T42 systemd[1]: Starting PackageKit Daemon...
Dec 21 08:31:55 survivor-ThinkPad-T42 PackageKit: daemon start
Dec 21 08:31:55 survivor-ThinkPad-T42 dbus-daemon[648]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Dec 21 08:31:55 survivor-ThinkPad-T42 systemd[1]: Started PackageKit Daemon.
Dec 21 08:36:27 survivor-ThinkPad-T42 nemo[2585]: Called "net usershare info" but it failed: 'net usershare' returned error 255: mkdir failed on directory /var/run/samba/msg.lock: Permission denied#012net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory#012Please ask your system administrator to enable user sharing.
Dec 21 08:37:25 survivor-ThinkPad-T42 xed[2629]: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
Dec 21 08:37:37 survivor-ThinkPad-T42 gvfsd-metadata[1307]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
Dec 21 08:37:37 survivor-ThinkPad-T42 gvfsd-metadata[1307]: message repeated 7 times: [ g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed]
Dec 21 08:37:40 survivor-ThinkPad-T42 systemd[1]: Starting Cleanup of Temporary Directories...
Dec 21 08:37:40 survivor-ThinkPad-T42 systemd[1]: Starting Message of the Day...
Dec 21 08:37:40 survivor-ThinkPad-T42 systemd[1]: Started Message of the Day.
Dec 21 08:37:40 survivor-ThinkPad-T42 systemd[1]: Started Cleanup of Temporary Directories.
Dec 21 08:37:52 survivor-ThinkPad-T42 gvfsd-metadata[1307]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
Dec 21 08:38:02 survivor-ThinkPad-T42 gvfsd-metadata[1307]: message repeated 7 times: [ g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed]
Dec 21 08:38:02 survivor-ThinkPad-T42 systemd[1]: proc-sys-fs-binfmt_misc.automount: Got automount request for /proc/sys/fs/binfmt_misc, triggered by 2649 (nemo)
Dec 21 08:38:02 survivor-ThinkPad-T42 systemd[1]: Mounting Arbitrary Executable File Formats File System...
Dec 21 08:38:02 survivor-ThinkPad-T42 systemd[1]: Mounted Arbitrary Executable File Formats File System.
Dec 21 08:38:03 survivor-ThinkPad-T42 gvfsd-metadata[1307]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
Dec 21 08:38:25 survivor-ThinkPad-T42 gvfsd-metadata[1307]: message repeated 123 times: [ g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed]
Dec 21 08:38:33 survivor-ThinkPad-T42 nemo[2585]: Unable to create loader for mime type audio/x-vorbis+ogg: Unrecognized image file format
Dec 21 08:38:33 survivor-ThinkPad-T42 nemo[2585]: Error creating thumbnail for file:///usr/share/sounds/freedesktop/stereo/suspend-error.oga: Unrecognized image file format
Dec 21 08:38:34 survivor-ThinkPad-T42 nemo[2585]: Unable to create loader for mime type audio/x-vorbis+ogg: Unrecognized image file format
Dec 21 08:38:34 survivor-ThinkPad-T42 nemo[2585]: Error creating thumbnail for file:///usr/share/sounds/freedesktop/stereo/dialog-error.oga: Unrecognized image file format
Dec 21 08:38:35 survivor-ThinkPad-T42 nemo[2585]: Unable to create loader for mime type audio/x-vorbis+ogg: Unrecognized image file format
Dec 21 08:38:35 survivor-ThinkPad-T42 nemo[2585]: Error creating thumbnail for file:///usr/share/sounds/LinuxMint/stereo/dialog-error.ogg: Unrecognized image file format
Dec 21 08:38:42 survivor-ThinkPad-T42 gvfsd-metadata[1307]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
Dec 21 08:39:19 survivor-ThinkPad-T42 gvfsd-metadata[1307]: message repeated 233 times: [ g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed]
Dec 21 08:40:04 survivor-ThinkPad-T42 systemd-resolved[624]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Dec 21 08:40:04 survivor-ThinkPad-T42 systemd-resolved[624]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Dec 21 08:40:41 survivor-ThinkPad-T42 gvfsd-metadata[1307]: g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed
Dec 21 08:40:41 survivor-ThinkPad-T42 gvfsd-metadata[1307]: message repeated 7 times: [ g_udev_device_has_property: assertion 'G_UDEV_IS_DEVICE (device)' failed]
Dec 21 08:40:42 survivor-ThinkPad-T42 nemo[2815]: Called "net usershare info" but it failed: 'net usershare' returned error 255: mkdir failed on directory /var/run/samba/msg.lock: Permission denied#012net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory#012Please ask your system administrator to enable user sharing.
Dec 21 08:41:31 survivor-ThinkPad-T42 xed[2831]: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
Dec 21 08:41:40 survivor-ThinkPad-T42 xed[2831]: xed_conversion_error_info_bar_get_encoding: assertion 'menu' failed
Dec 21 08:41:50 survivor-ThinkPad-T42 xed[2870]: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
Dec 21 08:42:10 survivor-ThinkPad-T42 xed[2878]: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by jaszhix** [comment]
If you open `mintreport` (System Reports in the menu), do you see an entry for cinnamon? If so, please select it, click Pastebin, and copy the link here.

**Comment by Vic1248** [comment]
Three entries.

https://termbin.com/utfj

**Comment by jaszhix** [comment]
Thanks. Can you attach ~/.xsession-errors as well? Specifically, I'm curious if you see it say `openGL version 3.1 detected (GL3 Cogl Driver)` or `cogl npot texture sizes SUPPORTED`. The RV200 is an older chip that might have compatibility issues with cogl.

**Comment by Vic1248** [comment]
I couldn't locate '~/.xsession-errors' to attach it earlier. I'm new to Linux.

**Comment by jaszhix** [comment]
In Nemo click View -> Show Hidden Files, you should see it at the root of your home directory. You can drag it to the text field in Github and it will upload it.

**Comment by Vic1248** [comment]
openGL version 1.3 Mesa 18 detected (GL Cogl Driver)
MetaSyncRing disabled: couldn't find required GL extensions, or the minimum safe openGL version was not met
failed to create drawable

**Comment by Vic1248** [comment]
It's an old laptop but it worked just fine with Linux Mint 18 and up until 19.1 Tessa.

**Comment by jaszhix** [comment]
Can you try this build attached here? 

Open the file, extract it a folder, navigate to the directory you extracted it to in Nemo, right click -> Open in Terminal -> type and enter `sudo dpkg -i *.deb`. Then try to start Cinnamon and see if it works. Thanks.

[muffin-4.0.5-cogl-rect-new-compat.tar.gz](https://github.com/linuxmint/Cinnamon/files/2703236/muffin-4.0.5-cogl-rect-new-compat.tar.gz)

https://github.com/linuxmint/muffin/commit/6f952685d2c33d1dd289c02adfaadc79b3e363bc

**Comment by Vic1248** [comment]
Still the same thing.

**Comment by Vic1248** [comment]
Re-upgraded back to the latest Windows Manager through the Update Manager after reboot.

**Comment by jaszhix** [comment]
Can you check mintreport and attach the newest trace? If its crashing in a different part of the code it might confirm the patch fixed that particular issue. 

The oldest card I have is an AGP Radeon X1650, so can't reproduce this unfortunately.

**Comment by Vic1248** [comment]
Yeah, this is a 32-bit (x86) laptop. I know it's a graphics issue with Tessa on 32-bit architecture. I have Linux Mint 19.1 Tessa installed on another old x64 laptop, and it works just fine.

BTW, how do I apply do the 'linuxmint/muffin@6f95268' script?

**Comment by jaszhix** [comment]
You would need to build muffin, the compositor. That requires setting up a build environment. The scripts on the [mint-dev-tools](https://github.com/linuxmint/mint-dev-tools) repository automates some of it.

**Comment by Vic1248** [comment]
I see. I am not in the IT, I just use IT knowledge as tools for engineering work, though I do script some in Windows. I am an electrical engineer.

**Comment by jaszhix** [comment]
No problem, not expecting that anyway. :) I have a 32-bit build this time.

[muffin_4.0.5_i386-cogl-rect-new-compat.tar.gz](https://github.com/linuxmint/Cinnamon/files/2703582/muffin_4.0.5_i386-cogl-rect-new-compat.tar.gz)

**Comment by Vic1248** [comment]
Well done my friend, it works like a charm!

**Comment by Vic1248** [comment]
Merry Christmas

**Comment by jaszhix** [comment]
Thanks, you too!

**Comment by MXarko** [comment]
Hi!
Linux Mint 19 and 19.1 Cinnamon on every boot right after login give me pop-up “Cinnamon just crashed…”. 18.3 and previous versions work fine.

I installed Debian 9.6 Cinnamon on the same PC, and there was a similar problem: right after login there was a notification that Cinnamon is running without video hardware acceleration, etc. So I looked for a package that would support my video card, Radeon RS690. And I found it in Debian repository, "firmware-amd-graphics (20161130-4) [non-free]". I installed it (in Debian), and it solved the problem completely.

So I had thought that the same will work in Mint. But when I tried to install the same package in Mint, I've got the following error message:

Unpacking firmware-amd-graphics (20161130-4) ...
dpkg: error processing archive firmware-amd-graphics_20161130-4_all.deb (--install):
 trying to overwrite '/lib/firmware/amdgpu/carrizo_ce.bin', which is also in package linux-firmware 1.173.2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)

Then I uninstalled "linux-firmware" package, and three more that depend on it, in order to install the AMD one. I succeeded at installing "firmware-amd-graphics" package, rebooted, but got the same Cinnamon crash pop-up. I installed "firmware-linux-nonfree" and "firmware-misc-nonfree" as well (both from the Debian site), but the result was the same.

I also applied the file you attached above, "muffin-4.0.5-cogl-rect-new-compat.tar.gz", but no joy.

Then I rolled everything back and continued to use Mint in Fallback Mode. Even so it has a few more unpleasant, to say the least, symptoms:
1. Every time I try to login at Yahoo mail, using Firefox, by navigating to "mail.yahoo.com" and entering my e-mail address, I get "the tab just crashed" page. I get the same crash page on some other sites. (There is not that problem in Google Chrome.)
2. I can not plot anything in Octave. I tried all of the three available graphics toolkits (fltk, gnuplot, qt), and when I issue, for example, "plot(3,2)" command Octave crashes (or freezes).


Mintreport stack trace:
https://termbin.com/yrcw

dmesg:
[dmesg.txt](https://github.com/linuxmint/Cinnamon/files/2757093/dmesg.txt)

$ inxi -F
System:
  Host: ***** Kernel: 4.15.0-43-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.0.9 Distro: Linux Mint 19.1 Tessa 
Machine:
  Type: Desktop Mobo: MICRO-STAR model: MS-7367 v: 1.0 
  serial: <root required> BIOS: American Megatrends v: 3.9 date: 01/21/2010 
CPU:
  Topology: Dual Core model: AMD Athlon 64 X2 5200+ bits: 64 type: MCP 
  L2 cache: 1024 KiB 
  Speed: 1800 MHz min/max: 1000/2700 MHz Core speeds (MHz): 1: 1800 2: 1800

$ inxi -Gxx
Graphics:
  Device-1: AMD RS690 [Radeon X1200] vendor: Micro-Star MSI K9AG Neo2 
  driver: radeon v: kernel bus ID: 01:05.0 chip ID: 1002:791e 
  Display: x11 server: X.Org 1.19.6 driver: ati,radeon 
  unloaded: fbdev,modesetting,vesa resolution: 1680x1050~60Hz 
  OpenGL: renderer: ATI RS690 v: 2.1 Mesa 18.0.5 direct render: Yes 

~/.xsession-errors:
[xsession-errors.txt](https://github.com/linuxmint/Cinnamon/files/2757118/xsession-errors.txt)

**Comment by jaszhix** [comment]
@MXarko Please don't pile on to this issue if the fix that worked for the OP doesn't work for you - that means it's a different issue. Open a new issue in the [muffin repo](https://github.com/linuxmint/muffin/issues), and install symbols (`muffin-dbg` package) if you do, the trace provided is not usable. Thanks.
