### ISSUE TITLE
Hang when GIMP starts RawTherapee

### ISSUE THREAD

**Issue by dgrisby** [linuxmint/Cinnamon#8225]
```
 * Cinnamon version 4.0.7
 * Fedora 29
 * Graphics: AMD/ATI Cape Verde PRO Radeon HD 7750/8740 / R7 250E, using the Xorg driver.
 * 64 bit
 ```

**Issue**

Whenever GIMP tries to open a raw file using RawTherapee, the desktop freezes before the RawTherapee window is shown. The mouse pointer still moves, but no windows can be focused. Alt-F2 does not bring up the command prompt. Looking at ps, I can see that the RawTherapee process is running.

If I kill -9 the cinnamon process, the display comes back to life, and a dialog offers to restart cinnamon. On choosing to restart, cinnamon restarts and the RawTherapee window is displayed and works fine.

This happens every time I try to open a raw file in GIMP. If I directly run RawTherapee from a terminal, rather than invoking it via GIMP, it opens fine.

I reverted to Cinnamon 4.0.5, and the problem has gone away, so the issue was introduced after 4.0.5.

**Comment by ac000** [comment]
I am seeing (it seems) the same issue. Although it happens when just trying to load a jpeg from gimps "Open Image" dialogue window.

Switching to a console (Ctrl-Alt-Fn) and doing DISPLAY=:0.0 cinnamon --replace& then switching back to the desktop and clicking the mouse causes things to kick in and the gimp image window is now displayed.

System is same as above except with Intel graphics

00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 

using the modesetting driver with glamor enabled (the defaults)

[517702.944] (II) modeset(0): glamor X acceleration enabled on Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)

**Comment by ac000** [comment]
Just done a couple more tests.

- If I load an image into gimp by doing 'open with' from nemo, it loads fine.
- If I run gimp from the cli and specify an image, it loads fine.

**Comment by leigh123linux** [comment]
@jaszhix I reproduced the issue and bisected and found the commit which causes the hang.

https://github.com/linuxmint/Cinnamon/commit/983c6c6fa9120858fd89f1c09fda8bca3be97561

**Comment by jaszhix** [comment]
Ah ok, that's fixed by #8180.

**Comment by leigh123linux** [comment]
@jaszhix  Thanks.

Fixed builds submitted to testing

https://bodhi.fedoraproject.org/updates/FEDORA-2018-244e6747d5
https://bodhi.fedoraproject.org/updates/FEDORA-2018-8a9d4c7804

https://koji.fedoraproject.org/koji/packageinfo?packageID=14352

**Comment by ac000** [comment]
Cool. Works for me.

Cheers.

**Comment by dgrisby** [comment]
That fixes it for me too. Thanks for the quick response!
