### ISSUE TITLE
Mint 19.1 firefox not using system Gtk theme

### ISSUE THREAD

**Issue by howdev** [linuxmint/cinnamon#8226]
```
 * Cinnamon version 4.06
 * Mint 19.1
64 bit

 ```

**Issue**
firefox build in 19.1 is not using system Gtk theme. Text highlight are in blue and scrollbar is blue also. The only exception is in preferences the theme works normal. 

It was normal in version 19

**Steps to reproduce**
upgrade to 19.1 
open firefox

**Expected behaviour**
firefox using system Gtk theme

**Other information**

**Comment by smurphos** [comment]
This is a side-effect of a change I suggested here to avoid Firefox theming web-content badly with dark themes. 

https://github.com/linuxmint/mint-19.1-beta/issues/30

**Comment by howdev** [comment]
I am not using dark theme. I am using the standard theme. The key exist, but is not deleting the key. it is setting it to use Mint-Y theme. I don't get it says it is fixed in Ubuntu-adjustments. Looks like it is a different issue.

**Comment by smurphos** [comment]
It doesn't matter what theme you are using - the fix forces Firefox to use the default GTK theme (Adwaita) to render web content to avoid dark theme users not being able to read a lot of content due to long standing bugs in Firefox implementation of GTK theme integration.  Unfortunately it appears that Firefox draws its scrollbar as web-content. This is another firefox bug in my opinion. 

Open about:config in Firefox navigate to the key `widget.content.gtk-theme-override` and delete the string # to leave the key blank. Restart firefox. This will revert firefox to the pre-fix behaviour. 

To understand why the fix was necessary temporarily set your controls theme to Mint-Y-Dark visit https://www.linuxmint.com/start/tessa/ and view how poor the text contrast is in the search box. This problem applies to all dark themes.

**Comment by JosephMcc** [comment]
I think smurphos explained this pretty well and it isn't a Cinnamon specific issue.
