### ISSUE TITLE
soundfilechooser Settings Widget restricts choice of files

### ISSUE THREAD

**Issue by pdcurtis** [linuxmint/cinnamon#8267]
* Cinnamon version (4.08)
 * Distribution - (Mint 19.1)
CPU: Quad Core Intel Core i7-4700MQ (-MT MCP-) 
speed/min/max: 1197/800/3400 MHz Kernel: 4.15.0-43-generic x86_64 
Up: 5d 15h 11m Mem: 3999.2/7896.9 MiB (50.6%) Storage: 1.14 TiB (53.6% used) 
Procs: 425 Shell: bash 4.4.19 inxi: 3.0.27 
Graphics:
  Device-1: Intel 4th Gen Core Processor Integrated Graphics driver: i915 
  v: kernel 
  Device-2: NVIDIA GK106M [GeForce GTX 765M] driver: N/A 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.0.5 
 * 64 bit

**Issue** 

soundfilechooser Settings Widget restricts choice of files to certain system folders. 
Users sound files are not available to select.

**Steps to reproduce**

The simplest way is to use the built in Settings API Demo and try to select a file. 
Most folders do not show any sound files even when they exist. 
Only sound files in /usr seem to be located and selectable

**Expected behaviour**

Any sound file with appropriate ownership should be displayed and be able to be selected and tested.

**Other information**

The description in Devhelp is also confusing:
```
  soundfilechooser
  * type: should be soundfilechooser
  * description: String describing the setting
  * default: default icon path or icon name to use
Provides a button which shows the currently selected file name and opens a file dialog when clicked.
A preview button is also provided to allow the user to test the selected sound. Stores as a string.
```

Why does default: refer to Icon Path and Name? Surely it should be a Sound File Path?

The soundfilechooser widget only seems to be used in one applet by @jake1164 which I have not been able to test as it does not load.

**Comment by claudiux** [comment]
Hi @pdcurtis,

The cause seems to be in the file `/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py`.

Line 915 and following:
```
        sound_filter = Gtk.FileFilter()
        sound_filter.add_mime_type("audio/x-wav")
        sound_filter.add_mime_type("audio/x-vorbis+ogg")
        sound_filter.set_name(_("Sound files"))
        dialog.add_filter(sound_filter)
```
Only `x-wav` and `x-vorbis+ogg` audio files!
This is a serious limit to user choice.

**Comment by pdcurtis** [comment]
@claudiux It is worse than that as even ogg files are not found in ones home folder, only in /usr. I could not see where the restriction occured

**Comment by claudiux** [comment]
@pdcurtis `.oga` and `.wav` files are found in home folder (I just tried copying some files from /usr into my home folder, successfully).
Here is a part of my `settings-schema.json` file:
```
"useSoundAlert": {
        "type": "checkbox",
        "indent": true,
        "default": false,
        "description": "Emit an audible alert when VPN shuts down.",
        "tooltip": "Checking this allows this applet to emit an audible alert when VPN shuts down."
    },
    "useSoundAlertAtBeginning": {
        "type": "checkbox",
        "indent": true,
        "default": false,
        "description": "Emit this audible alert when this Applet starts, if VPN is down.",
        "tooltip": "Check this if you want to emit this audible alert when this Applet starts, if VPN is down.",
        "dependency": "useSoundAlert"
    },
    "usedSound": {
        "type": "soundfilechooser",
        "description": "The sound to emit:",
        "default": "/usr/share/sounds/freedesktop/stereo/phone-outgoing-busy.oga",
        "dependency": "useSoundAlert"
    },
```
(The required fields for a soundfilechooser are "type", "description" and "default".)

**Comment by pdcurtis** [comment]
@claudiux It does not find either an existing .oga or .mp3 in my home folder but has found a .wav and .oga copied from /usr .  Checked owner and permissions are all the same as I expected and the .oga is one I am already using as an alert. Only difference I can see is that it is longer.

For the test I am still using the built in applet `Settings API Demo` which has an empty default field ie `"default": ""`, - this defaults to /home. 

Very odd. Are you using Cinnamon 4.0.8 and Mint 19.1

**Comment by Odyseus** [comment]
Hello, everybody.

My guess is that the MIME type limitation for audio files has a purpose. The **SoundFileChooser** widget is not only used by the xlets settings, but also by Cinnamon itself in **System Settings** > **Sound** > **Sounds** tab. Allowing all audio MIME types might lead to confusion due to Cinnamon not being able to play all audio file types.

But, due to the nature of xlets, one isn't limited to just what Cinnamon can do. Maybe a middle point can be adding a new field for the **soundfilechooser** widget, lets call it **all_mimetypes**.

```json
{
    "sound_pref": {
        "type": "soundfilechooser",
        "description": "The sound to play:",
        "all_mimetypes": true,
        "default": ""
    }
}
```

...and in the **SoundFileChooser** widget class...

```python
# If all_mimetypes is set to true in the soundfilechooser xlet widget,
# allow to display all audio files in the file selector.
if all_mimetypes_parameter:
    sound_filter.add_mime_type("audio/*")
else:
    sound_filter.add_mime_type("audio/x-wav")
    sound_filter.add_mime_type("audio/x-vorbis+ogg")
```

What do you think, @collinss?

***

P.S.: @pdcurtis: Just checking. Are you sure that the files that you cannot see, and are supposed to be displayed in the file chooser, aren't hidden files (*dot* files)?

![screenshot-window-2019-01-06-214203](https://user-images.githubusercontent.com/3822556/50743912-fb2cee00-11fb-11e9-8a6e-fd567f612f27.png)

**Comment by pdcurtis** [comment]
I think I have found the difference the .oga files not displayed are type audio/x-flac+ogg and displayed ones are audio/x-vorbis+ogg. And for reference I understand hidden files and files names do not have spaces.

@Odyseus Your suggestion of opening up the choices would be good for me - I actually wanted to access .mp3 files and only tried .oga to find out what was going on. 

So this is really turning out to be a feature request not an Issue.

**Comment by collinss** [comment]
@Odyseus Yeah, I was having the same thought. It's been long enough since I worked on this that I don't remember details about that widget. (Most likely I just used whatever was there before). However, as you pointed out, by default we probably only want the ones cinnamon can handle, but then have the option to select all sound files if the spice dev is using something other than Cinnamon to play sounds.

**Comment by pdcurtis** [comment]
@collinss I have just started to use the event-sounds:option you added in #8312 now Cinnamon 4.2 is available. 
It allows me to select any audio file as expected but the preview only seems to work for the original subset of sound files and does nothing when an .mp3 file is selected.
I am only currently using it in the batterymonitor@pdcurtis applet

**Comment by collinss** [comment]
@pdcurtis yeah, that's because the tool we're using to preview the sounds is the same one that Cinnamon uses to play the sounds, and that tool doesn't support .mp3s (I think it only handles .wav and .ogg but I'm not sure). I suppose we could disable the preview if it's unsupported, but I don't think it's worth the effort to add support for previewing sound formats that cinnamon can't even play. Also, doing so would probably add an extra dependency on Cinnamon, which is also kind of overkill imo. Even just allowing sound files that Cinnamon can't play is rather niche anyway, and I don't really see the point in putting too much into this.

**Comment by pdcurtis** [comment]
@collinss  No problem, I will add a comment somewhere next time I update so people do not raise an Issue with me.
Thanks for do it in the first place.
