### ISSUE TITLE
Disable sound icon

### ISSUE THREAD

**Issue by assabi** [linuxmint/Cinnamon#8406]
![image](https://user-images.githubusercontent.com/32370126/53030147-58fb5980-347b-11e9-8b5f-db2569302069.png)
Cinnamon 4.0.9
Linux mint 19.1 x64
GeForce 940MX ndivia-driver-390

If you disable sound (by pushing disable sound button on your keyboard) there'll be disable sound icon. But cross on the icon isn't transparent, it looks really awful.
The screenshot was taken while I was using mint-y-dark theme. But the bug appears on every theme, even on custom ones like adapta-nokto.

**Comment by brownsr** [comment]
This is because of the icon set you are using, which I presume is mint-y.  It is not theme related.  Mint-x icons don't have the cross, and there will be other 3rd party themes that you might like to consider if this icon really bothers you.  I frequently use the 'paper' icons myself.  icons have to be manually downloaded and installed if you decide not to use one of the supplied sets, as icon sets are not included in the spices repository.  They go into .icons in your home directory.

**Comment by assabi** [comment]
Yeap, you are right, it's just mint-y imperfection
