### ISSUE TITLE
[Feature Request] Mirror taskbar except open windows

### ISSUE THREAD

**Issue by MartinX3** [linuxmint/cinnamon#8478]
```
 * Cinnamon 4.0.10
 * Linux Mint 19.1
 * 64 bit
 ```

**Feature Request**

It would be nice if I can just have the same mirrored taskbar on every new attached monitor.
Every element should be the same and sync with every other taskbar, if I change the main taskbar.

At the moment I just copy the settings of my main taskbar and insert them into the others after every change.

I'm sorry, if this feature request is already buried somewhere in the 844 open issues.
I wasn't able to find it with the search function.

**Comment by JosephMcc** [comment]
You can't really do this. Because not all applets can have multiple instances. Things like the systray cannot be duplicated.

**Comment by MartinX3** [comment]
Oh, why is that the case?
And can't the same instance showed at multiple places?

**Comment by ManIVIctorious** [comment]
@josephmcc since the systray can be duplicated in kde this is obviously an implementation issue and not inherent to the systray at all. I would also highly appreciate if the cinnamon devs would start making (at least the stock) applets multi instance aware. E.g. It feels a bit awkward to have to use two different workspace switcher applets, only being able to control sound or bluetooth devices on one monitor, etc. This would be a very welcome enhancement.
