### ISSUE TITLE
Cinnamon app menu editor can no longer recognize hidden folders & files !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/cinnamon#8531]
```
 * Cinnamon version (cinnamon 4.0.10)
 * Distribution - (Fedora 28)
 * Graphics hardware *and* driver used
 * 64 bit

I stored my custom icons in:
home/myusername/.local/share/myicons
I use these custom icons to add them for launchers in my app menu.

I was able - in previous version of cinnamon - to brows (by menu editor) to navigate to the above location. However, now I noticed that menu editor can no longer recognize hidden folders & files !
I tried to unhidden them by Ctrl+H but still app menu editor navigator (browser) can no longer recognize hidden folders & files !

Please your kind care. 
 ```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by collinss** [comment]
Hi @Nokia808 I was able to reproduce your issue once, so I started debugging it and of course it worked fine 🙄. Since then, I can't reproduce it again. I'm not sure what's going on here. I'll continue to watch for it, but in the mean time, you can always hit the browse button next to the search bar. That uses the standard gtk file chooser dialog, so it should work (if it doesn't, then the problem is most likely upstream from us).

**Comment by leigh123linux** [comment]
@collinss  I believe f28 uses gtk-3.22.30 or gtk-3.22.29, as Fedora maintainer I should know but don't (no time to check old releases).

**Comment by Nokia808** [comment]
@collinss 
Hi. I'm already tried "Browse" button, & it does not working at all to recognize hidden folders/files even if I already Ctrl+H
It seem, thus, an upstream bug ...

**Comment by Nokia808** [comment]
@leigh123linux 
Hi. I'm upgraded from Fedora 28 to 30 & issue completely disappeared ! Now on Fedora 30 I can browse hidden folders & files okay. I will close this issue
