### ISSUE TITLE
Cannot bind Super key

### ISSUE THREAD

**Issue by Maaartinus** [linuxmint/cinnamon#8718]
```
Cinnamon 4.0.8
no daily builds
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
i7-9700K build-in video, no driver installed yet
64 bit
 ```

**Issue**
I configured Parcellite to use `<Super>H` for its History. This worked for me both on Ubuntu and on some older Linux Mint using xfce. With the current system, on the first press, I get a plain `h` as the first key, only the key press invokes Parcellite. This makes it pretty useless.

While holding `Super_L`, I get plain `h` on every second key press. The same for `Super_R`.

**Steps to reproduce**
Install Parcellite, configure it to use `<Super>H` for its History, open a terminal and watch getting plain `h` on the first try.

**Comment by GregPK** [comment]
Can confirm this. Had this for a while, but on an older version. Don't really remember when it started but I've done some research on this. And found a workaround. is you want a quick fix [look here](https://github.com/linuxmint/Cinnamon/issues/549#issuecomment-388763522). The workaround is not perfert, since some software distinguishes between super and hyper (ie Autokey) so you will have to change you bindings for this to work (still, just a few minutes work). Parcellite should work without changes.

**Version**

```
Desktop: Cinnamon 3.6.7 (Gtk 3.18.9-1ubuntu3.3) Distro: Linux Mint 18.3 Sylvia
Kernel: 4.20.17-042017-generic x86_64 (64 bit gcc: 8.3.0)
```

**Issue**
To add to the above findings: 
- This does not only happen with Parcellite, but with any "external" program that has a shortcut with Super (confirmed with guake, tilde, autokey). 
- Interestingly, does not happen with shortcuts build into Cinnamon and set using the `Menu > Keyboard > Shortcuts`. They work properly.
- I've also noticed, that the Super key _kind of_ causes the window to lose focus. But not entirely. See this short gif of the focus on this window, first when pressing the Super key (notice the cursor change, it actually changes back on the next key up even), then a regular focus loss (clicking outside the window).

![superfocus-2019-07-21_18 17 17 mkv](https://user-images.githubusercontent.com/687754/61593791-52b50900-abe4-11e9-85d0-f27b8e7c1234.gif)

**What I've tried**

1. Looking throught all keyboard shortcuts and unassagning any that have a Super mapping. Did not work.
2. `xlsclients -la` and killing each running process, got it down to just `cinnamon{-session}`, no luck there so this is not an external program issue mapping to super.
3. Using [gsettings](https://github.com/linuxmint/Cinnamon/issues/549#issuecomment-72319422).
4. Debugging this using `xef`. [This gist](https://gist.github.com/GregPK/644ef2d5273c58e2672c1198cb36889a) shows the comparison with and without the "Hyper is mapped to Win-keys" layout option. Those files show the result of pressing the button twice with a short pause between presses. This does not tell me anything actionable, but it's quite interesting that this with Super we can see those `Focus*` events but not a single `KeyPress`. 

**Bonus fact**
When you run parcellite via cmdline, you see this:
```
gsettings set org.cinnamon.desktop.keybindings.wm overlay-key ''
```
which, as I understand it, it a try at combating this exact issue in Mint 17, which already didn't work in 17.1 ([source](https://github.com/linuxmint/Cinnamon/issues/549#issuecomment-72319422))

**Comment by icarter09** [comment]
@Maaartinus did @GregPK suggestion fix the issue?

**Comment by Maaartinus** [comment]
@icarter09 I can't tell.... I've reinstalled in the meantime. I guess, I close this as I no more care though the @GregPK's  workaround is just a workaround. A fix is something only the devs could do.
