### ISSUE TITLE
Desperatly missing 1.5x Desktop scaling

### ISSUE THREAD

**Issue by Blackbam** [linuxmint/cinnamon#8833]
```
- All Versions
- Resolution WQHD (2.560 x 1.440), high pixel density screen
- All Graphics Cards, but especially NVidia commercial drivers as there not even hacks and workarounds are possible
 ```

**Issue**
Regarding: [https://i.stack.imgur.com/e4XvU.png](https://i.stack.imgur.com/e4XvU.png)

There are certain workarounds like changing the text scaling factor but this does not work for any apps. Double scaling is just way too much. No scaling causes extremly small text which is partly unreadable, especially in certain apps. This makes using Cinnamon a pain for WQHD displays. 

**Steps to reproduce**
Install Linux Mint Cinamon on a device with high pixel density and WQHD resolution.

**Expected behaviour**
Offer 1.5x Desktop scaling or at least give a link to the team or project which is responsible for implementing this.

**Further information**
No solution for one year on stackexchange Unix & Linux: https://unix.stackexchange.com/questions/463852/linux-mint-cinnamon-fractional-scaling-1-5x-for-wqhd-displays-missing-any-solu/524712?noredirect=1#comment999299_524712

**Comment by collinss** [comment]
Hi @Blackbam! This is something that has been requested quite a lot, and it's something we would like to support in the future, but there are some major hurdles to overcome before we can get there. The biggest is that we can't make this work as long as we're using x11 as our windowing system. X can work with integer multiple scaling (X2, X3, etc), but fractional scaling isn't possible. In order to implement this feature we'll have to switch to Wayland, and that brings a whole host of issues with it.

First off, it's going to take a lot of work. Wayland works very differently under the hood than X11 does, and many things that X11 handles are left to the window manager in Wayland. Many things that currently work just fine for us on X11 would need to be reimplemented or refactored just to get us back to a working state.

Second, none of us on the team are very experienced with window managers. While this isn't a show-stopper, it does mean that many hours of research and banging our heads against the wall will be required, and most of us have day jobs.

Third, while there are things to be gained from switching to Wayland, there are many more that will be lost. Wayland is still a very young project and so there are still a lot of bugs to be worked out. In addition, many tools (such as redshift) will no longer work at all - not just because they're written for X11, but because there is simply no DE-agnostic way to do them in Wayland.

Finally, as far as I know, Wayland still doesn't work properly with the NVidia drivers, which is pretty much a show-stopper for serious gamers (a fairly significant portion of our user base).

Rest assured that we will implement this as soon as we are able, but it may be a while before it happens due to the reasons I mentioned above, and probably many more.

**Comment by ManIVIctorious** [comment]
@collinss Please make sure to have a look into the wayland layer-shell-protocol (https://www.youtube.com/watch?v=VuRXHJu5Kmg) before you start the transition to wayland. It should dramatically simplify the transition. Its reference implementation is in a project called [wlroots](https://github.com/swaywm/wlroots).

Unfortunately wlroots does not support nvidia gpus as long as no general consensus is found for the buffer management API (between the rest of the open source world and nvidia). Nevertheless I think the protocol has been included in canonical's [MIR](https://github.com/MirServer/mir) which should handle nvidia gpus just fine. AFAIK MATE has started transitioning using exactly this route (https://www.phoronix.com/scan.php?page=news_item&px=MATE-Usable-Wayland-Mir-Video).

Additionally this would keep the defragmentation caused by the wayland transition to a minimum, which would (IMHO) be highly appreciated.
