### ISSUE TITLE
Button "Rescan for wireless networks" does nothing

### ISSUE THREAD

**Issue by ivanjermakov** [linuxmint/cinnamon#8891]
**Issue**
Pressing the button "Rescan for wireless networks" in the tray bar does nothing.

````
Cinnamon 4.2.4
Linux Mint 19.2 Tina 64 bit
````

**Comment by icarter09** [comment]
@ivanjermakov I've debugged the button and it does appear to be working. The issue seems to be that it's not properly letting the user know that it has done a scan. But I only knew that from creating logging statements when pressing the button. Maybe a feature request should be done to let the user know that a scan is in progress and then also to inform them when the scan is completed.

**Comment by RafaelKr** [comment]
@icarter09 that's a good idea. Maybe the button should be disabled and show "Scanning...", also when the scan process is started by the system.

**Comment by icarter09** [comment]
@ivanjermakov if you feel like this has resolved the issue, could you close out this issue and re-create this as a feature request? Thanks.

**Comment by mtwebster** [comment]
The button has been removed - a rescan will now be initiated automatically when the menu is opened.

There's no way for us to know when the 'scan' completes, which is why there was never any completion indicator (or disabling of the button, etc...).
