### ISSUE TITLE
grouped-window-list needs show all Windows of all Monitors iotion

### ISSUE THREAD

**Issue by NoXPhasma** [linuxmint/cinnamon#8993]
```
 * Cinnamon version 4.4.2
 * Distribution - (Mint 19.3 beta)
 * 64 bit
 ```

**Issue**

The applet now misses the option to show all windows of all monitors. This was present in 19.2 and it should come back.

**Steps to reproduce**

Update to the 19.3 beta and add Grouped Window List applet

**Expected behaviour**

There should be an option to show all Windows on all monitors.

**Comment by icarter09** [comment]
@NoXPhasma can you reopen this issue in the Mint 19.3 Beta repo? Thanks.

**Comment by NoXPhasma** [comment]
Done. https://github.com/linuxmint/mint19.3-beta/issues/32

**Comment by AndrewDavis** [comment]
I can't comment on the other issue, because it's archived (wth?)... so I'm commenting here.

I use this feature, and I really hate that you've removed it. Like, **really hate**.

> Our strategy then is to try to make it 'just work' for 90% of our users, and then offer alternatives for the other 10% in the form of 3rd party applets, etc.

Umm, what makes you say that 90% of your users don't use this feature? (again wth?)

This is really obnoxious not to be able to see all windows on all monitors, it makes me think that the window isn't open because I don't see it in the taskbar.

**Comment by AndrewDavis** [comment]
Not to mention that also, you've introduced new bugs to the taskbar this time around, and now whenever I want to open a window on a different monitor, **I have to move my mouse all the way over to the other monitor's taskbar**. That is **SO** annoying.

**Comment by Krafting** [comment]
I also used this feature, I now am forced to copy and paste the GWL so I can have all my windows showing on all monitor..
