### ISSUE TITLE
Alt-tab does not trigger if you are too fast

### ISSUE THREAD

**Issue by Jacketbg** [linuxmint/cinnamon#8994]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.2.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 19.2 Cinnamon
 * Graphics hardware *and* driver used
Intel 620 / i915
 * 32 or 64 bit
64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**

This is similar to #8852. 
Alt-tab is not triggered if you press and release both key too quickly.  

**Steps to reproduce**

Press Alt and Tab very quickly as if you just want to switch to your previously opened window without waiting for the whole alt-tab widget to show up.

**Expected behaviour**

Last used window should be focused immediately.

**Other information**

My laptop is Razer Blade Stealth i7-8550U. The screen resolution is 3200x1800 with scaling x2. At work it's hooked up to a 4k external monitoring again at x2 scaling. This could be contributing to a very slight delay of the alt-tab widget to show up. But regardless of this an alt-tab combo should always be registered no matter how quickly you mash the buttons. Coming from MacOS this issue is very noticeable. I don't remember having this issue ever with Windows too back in the day.

The Alt-Tab settings doesn't seem to have any effect. Here are my current settings:

![Screenshot from 2019-12-03 11-24-14](https://user-images.githubusercontent.com/4333497/70037634-8f940200-15bf-11ea-8a0c-81eea1aafa87.png)

**Comment by JosephMcc** [comment]
I can't reproduce this issue here. It works for switches to the other window without ever even seeing the osd show up.

**Comment by areographe** [comment]
`* Cinnamon version (cinnamon --version)`
`Cinnamon 4.4.8`
`* Distribution - (Mint 17.2, Arch, Fedora 25, etc...)`
`Manjaro Linux x86_64 (kernel 5.4.18-1-MANJARO)`
`* Graphics hardware *and* driver used`
`Intel Corporation Skylake GT2 [HD Graphics 520] with video-linux version 2018.05.04 (PCI)`
`* 32 or 64 bit`
`64 bit`

Same issue as #8852. The same pattern of keypresses that works on OS X, Windows  and on Xubuntu (a very quick press of alt followed by tab, i.e. alt keydown, tab keydown, alt keyup, tab keyup) does not trigger switching windows (nor does it open the window switcher OSD) unless the keypresses are performed noticeably slower.

Not a huge issue but it is frustrating to have to consciously slow myself down each time I go to switch windows.

Have adjusted my Alt-Tab configuration in System Settings identical to @Jacketbg but it has no effect.

Thanks!

**Comment by rhansen** [comment]
I'm experiencing the same problem (Cinnamon 4.2.4).

**Comment by hlascelles** [comment]
I am seeing this issue too, and have been for quite some time (years). Multiple installs, multiple versions, multiple machines.

It doesn't matter if there is no "follow up" key or not. 

It is just: "Sometimes ALT+TAB does nothing if pressed quickly (but fully!)".

This doesn't (and shouldn't) have anything to do with the switcher pop-up - this is just quickly switching back to an app.

**Reproducible**: effectively always. I can bring up a `xed` window (to show if I am hitting tab on its own) then try ALT-TAB quickly, many times in a row. No window switch happens, and no tabs appear in the document.

Is there some debug I can run to help on this?

**Comment by andrask** [comment]
This has been driving me crazy since I switched to Tina. Slowing down the pushes helps. But then it's more probable that the Alt+Tab switcher comes up (which I would be happy to get rid of completely). So I increased the switcher time and try to slow down the pushes.
**For the reproducibility**: it's not definite how often the error happens. If I push fast enough, 50-60% of the pushes may have no effect.

**Comment by NanashiNoGombe** [comment]
Can confirm. Can reproduce any time I don't consciously retard my typing speed.

Had the same issue in prior versions of Linux Mint Cinnamon but has now become very problematic due to adopting a dual-monitor setup and often typing in the wrong window.

`RELEASE=19.3
CODENAME=tricia
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 19.3 Tricia"`

**Comment by mrashad10** [comment]
Same issue happens to me
my system is
RELEASE=20
CODENAME=ulyana
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 20 Ulyana"
DESKTOP=Gnome
TOOLKIT=GTK

**Comment by julius** [comment]
Happens to me as well. Just found out, this is a long standing bug. I assume there is no known workaround, right?

```
RELEASE=20
CODENAME=ulyana
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 20 Ulyana"
DESKTOP=Gnome
TOOLKIT=GTK
```

Personal Bug Severity: I will switch from Cinnamon to something else as soon as I have a few hours.

**Comment by maximvl** [comment]
Yup, have this one too, quite discouraging the whole system works blazingly fast and somehow Alt-Tab needs to be pressed slowly, also I noticed I can press the combo not-so-fast and see a ~1 second delay while windows list stays on a screen before switching the window. It seems only solution so far is to switch away from Cinnamon

```
RELEASE=20
CODENAME=ulyana
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 20 Ulyana"
DESKTOP=Gnome
TOOLKIT=GTK
```

**Comment by hlascelles** [comment]
I will cautiously report that after going to Mint Linux Cinnamon 20 Ulyana, and "System Settings > Windows > Alt-Tab > Set the delay to 0ms" this has become much rarer though I can't quite shake off the feeling it still sometimes occurs.

Picking one Mint Linux team member at random (apologies @mtwebster), can someone on the Mint Linux team weigh in on this?

**Comment by marben** [comment]
I just migrated from Ulyana to PopOS (based on the same Ubuntu 20.04 and Gnome) and the problem disappeared.
Likely the problem is in some library, that mint forked from gnome. libmutter/muffin seems to have some keyboard related code...

**Comment by hlascelles** [comment]
Hmm, I am going to retract my report that it is fixed. I have definitely had it occur a few more times.

**Comment by igogo** [comment]
The way to reproduce it without relying on someone's quick fingers is by using xdotool. For me `xdotool key alt+Tab` would almost never switch a window. But something like `xdotool key --delay=100 alt+Tab` would. Delay 45 would sometimes succeed to switch and sometimes fail.

Other shortcuts, like alt+F2, work with an arbitrarily small delay. 

Seems like the deciding factor is the delay between the **Tab press** and **Alt release**. In this script making either SLEEP2 or SLEEP3 large enough (say 0.2) would make it switch windows; SLEEP1 doesn't matter.

```
#!/bin/bash

SLEEP1=0.001
SLEEP2=0.001
SLEEP3=0.001

xdotool keydown alt &
sleep $SLEEP1
xdotool keydown Tab &
sleep $SLEEP2
xdotool keyup Tab &
sleep $SLEEP3
xdotool keyup alt &
```

**Comment by alkemyst** [comment]
Definitely my problem. Thanks for making it reproducible.
I tested it and I can reproduce the problem. FIY, the simple python code below using `pynput` is able to catch the "fast" alt+tab :
```
#!//usr/bin/python3

from pynput import keyboard

def on_alt_tab():
    print('<alt>+<tab>')

with keyboard.GlobalHotKeys({
        '<alt>+<tab>': on_alt_tab}) as h:
    h.join()
```

**Comment by alkemyst** [comment]
@igogo I just realized that your script is not doing what you intended to. In your script each command is sent and put in parallel, so the next one is sent immediately. I.e. the sleep are useless.
You have to remove the last '&' from the commands to make it effective.

**Comment by alkemyst** [comment]
As a temporary workaround one can run the following script, that reads a "fast" super+tab and generates an alt+tab that is understood correctly by cinnamon:
```
#!/usr/bin/python3

from pynput import keyboard
from pynput.keyboard import Key, Controller
import time
import subprocess

controller = Controller()

def on_alt_tab():
    print('<super>+<tab> pressed, generating <alt>+<tab>')
    subprocess.run(["/usr/bin/xdotool", "keydown", "alt"])
    time.sleep(0.04)
    subprocess.run(["/usr/bin/xdotool", "key", "Tab"])
    time.sleep(0.04)
    subprocess.run(["/usr/bin/xdotool", "keyup", "alt"])

with keyboard.GlobalHotKeys({
        '<cmd>+<tab>': on_alt_tab}) as h:
    h.join()
```

**Comment by igogo** [comment]
If we're doing workarounds, a script like this can be used to switch to the most recent window, and you can bind a hotkey in cinnamon settings. This is faster than sending key ups and downs and relying on the slow alt-tab.
```
#!/bin/bash

workspace=$(wmctrl -d | grep '\*' | cut -d ' ' -f1)
active=$(xprop -root | grep "^_NET_ACTIVE_WINDOW(WINDOW)" | awk '{ print $5 }')
win_list=$(wmctrl -lx | grep " $workspace " | awk '{print $1}')
IDs=$(xprop -root | grep "^_NET_CLIENT_LIST_STACKING" | tr "," " ")
IDs=(${IDs##*#})
for (( idx=${#IDs[@]}-1; idx>=0 ; idx-- )) ; do
    for i in $win_list; do
        if [ $((i)) = $((IDs[idx])) ] && [ $((i)) != $((active)) ]; then
            wmctrl -ia $i
            exit 0
        fi
    done
done
exit 1
```
It's still terrible experience as it only switches between the two windows. A proper long-term solution would be to switch to KDE :D

**Comment by alkemyst** [comment]
It might be helpful, but to me the extension Win7 Alt-Tab fixes the problem! :-)

**Comment by dandv** [comment]
Related: #9792.

**Comment by LinuxOnTheDesktop** [comment]
Just now on Mint 20.0 the alt-tab window (set to the '2d' version, because of bug #9172) failed to appear. I made a few attempts. Then I waited a few seconds and did it again and it did work. I don't know whether this is a _different_ bug to the one to which this issue is dedicated.

Does Mint 20.1 bring any alt-tab relief?

**Comment by dandv** [comment]
For folks who can only reproduce sometimes: what if the slowness happens when you press Alt-Tab during a [micro-freeze](https://forums.linuxmint.com/viewtopic.php?f=208&t=339538)?

To rule out micro-freezes, you can watch this [YouTube video](https://www.youtube.com/watch?v=u_P83LcI8Oc), and/or a simple [locally-generated sine wave](https://codepen.io/iondrimba/pen/opOvjo), and make sure the playback is smooth and continuous for longer than 2 minutes. (I see the micro-freezes if I look at the System Monitor charts, but the other two options are more enjoyable to watch).

**Comment by LinuxOnTheDesktop** [comment]
@dandv 

I am sorry, but, what? How do these 'micro-freezes' relate to the problem at issue, namely (though this seems open to some interpretation), 'Alt-tab does not trigger if you are too fast'?

**Comment by dandv** [comment]
@LinuxOnTheDesktop: some people reported being able to reproduce the Alt+Tab not triggering only some time. What if a sequence of events like this happens:

1. You press Alt
2. You press Tab
3. Micro-freeze-happens
4. You depress Tab but Cinnamon hasn't registered that due to the micro-freeze, so it won't trigger the window switching?

Just a hunch. I've seen the Alt+Tab issue myself, but can't reproduce it consistently.

**Comment by LinuxOnTheDesktop** [comment]
@dandv 

Thank you for the clarification. You are hypothesizing that a 'micro-freeze' prevents the depression of the tab key from registering and that for that reason the expected result of alt-tab does not occur.

**Comment by kergma** [comment]
I can confirm this very annoying issue on Debian, Cinnamon 4.6.7, and it's here for a long time (years)

**Comment by dandv** [comment]
This issue has been quite annoying, but I guess I got used to it. However, since switching to KDE Plasma, I really enjoy how fast Alt+Tab is, and how it always triggers.

**Comment by LinuxOnTheDesktop** [comment]
There are some rather fundamental bugs that for some reason the Mint developers seem not to care about. This is one of them.

**Comment by mtwebster** [comment]
> There are some rather fundamental bugs that for some reason the Mint developers seem not to care about. This is one of them.

Things are more likely to be fixed if they can be reproduced.

I have a 'blind' fix to try if anyone is interested..meaning, I still can't reproduce this but I am theorizing a cause and solution. This only affects the normal app switcher (thumbnails and/or icons in a row) - not the fancy ones, I didn't even check those.

[classicSwitcher.js.zip](https://github.com/linuxmint/cinnamon/files/6004020/classicSwitcher.js.zip)
(It's only zipped because github is strict about attachments)

Download and unzip that, copy the file over the system's version:
```
sudo cp classicSwitcher.js /usr/share/cinnamon/js/ui/appSwitcher
```
Then restart cinnamon (alt-f2, r, enter).

The change if anyone's interested:
```
diff --git a/js/ui/appSwitcher/classicSwitcher.js b/js/ui/appSwitcher/classicSwitcher.js
index 00ada96bd..fcebaa89e 100644
--- a/js/ui/appSwitcher/classicSwitcher.js
+++ b/js/ui/appSwitcher/classicSwitcher.js
@@ -55,9 +55,12 @@ ClassicSwitcher.prototype = {

         Main.uiGroup.add_actor(this.actor);

-        if (!this._setupModal())
+        if (!this._setupModal()) {
+            this._currentIndex = (this._currentIndex + 1) % this._windows.length;
+            this._activateSelected();
             return;
-
+        }
```

Whether or not the alt-tab succeeds is predicated on cinnamon being able to 'grab' (take control over) the keyboard and/or mouse.  Conditions that may cause this to fail include things like some application window having its own exclusive grab already - this can include popup menus from apps as well.

Currently when this fails, the 'ui' part of the switcher won't work and the attempt is simply aborted.

This change causes a switch to occur even if the grab fails. It only performs a single switch, meaning, if this condition was to repeatedly occur, you would only ever be able to switch between the two most recent windows (as what happens when you alt-tab-release, alt-tab-release, etc...).

Thanks

**Comment by igogo** [comment]
Hi Michael, did you try to reproduce with xdotool? Namely, for me, `xdotool key --delay=10 alt+Tab` always reproduces the bug. Your change doesn't seem to fix it.

**Comment by mtwebster** [comment]
Ah yes that does thanks - I must have skimmed over that previous mention of it.

Try this instead:
[appSwitcher.js.zip](https://github.com/linuxmint/cinnamon/files/6004936/appSwitcher.js.zip)

Same command to install as above. If you overwrite that previous file, reinstall cinnamon (in mint, simply do `apt reinstall cinnamon`) - I should have recommended backing up the original, sorry.

**Comment by igogo** [comment]
I THINK YOU DID IT MAN. xdotool can't repro the bug with your last patch, neither can I with my bare fingers no matter how mad pianist I go.

**Comment by LinuxOnTheDesktop** [comment]
'Mad pianist'? Hah! It's great if this bug is fixed. I presume though that bug #9172 remains. And that bug is worse (than this one) because it freezes the desktop pretty much permanently.

**Comment by andrask** [comment]
@mtwebster YOU DID IT! Really works.

**Comment by alkemyst** [comment]
@mtwebster That's great! Can you make a pull request with this patch?

**Comment by LinuxOnTheDesktop** [comment]
@mtwebster

_Is_ this patch likely to do anything for bug #9172? I could  wait for the patch to land and then see whether #9172 persists, but so doing would take a while, partly because that bug is intermittent. (Also: I would rather not hang my desktop if I can avoid it.) Thanks.

**Comment by mtwebster** [comment]
I played around with trying to reproduce that but no luck so far. I doubt this fix would have any effect, however.

**Comment by JamesTheAwesomeDude** [comment]
This was a really nasty bug that ruined my day every day. I naively applied that commit patch onto my running Cinnamon 4.6.7 (Fedora 32) system and **it fixed it instantly** (well, after I restarted Cinnamon).

Now I don't have to wait for my OS vendor _or_ an upstream release. Thanks so much for that patch. I hope it makes it into release as soon as possible.

Posting the link here so the next guy doesn't have to rifle through the thread:  
https://github.com/linuxmint/cinnamon/commit/31e9341ae9305c1f1e54837396163a8b117fdcac.patch
