### ISSUE TITLE
Menu applet: md5 at the end of the config file is wrong

### ISSUE THREAD

**Issue by SethosII** [linuxmint/cinnamon#9050]
```
Cinnamon 4.4.5 (no daily build)
Mint 19.3 64 bit
 ```

**Issue**

After the upgrade to Linux Mint 19.3 and Cinnamon 4.4.5 the md5 value at the end of the menu config file in `~/.cinnamon/configs/menu@cinnamon.org/0.json` has like two md5 hashes. For me it looks like this: `"__md5__": "cdf1aadcba32c461f6e1b3b7647f8411b899c7f9a6067037eeeabecd7e9fa0d8"`.

**Steps to reproduce**

Look at the end of the file `~/.cinnamon/configs/menu@cinnamon.org/0.json`.

**Expected behaviour**

The hash should be 32 characters long but is twice as long.

**Other information**

All other applets have a md5 hash with the correct length.

By the way, what is this md5 hash for and what is it calculated from so I can check what the correct value should be?

**Comment by collinss** [comment]
This is intended behavior. The applet config (such as the 0.json file you mentioned above is obviously where the settings are stored for a particular instance of the applet. It is auto-generated and updated from a template `settings-schema.json` file in the applet's own folder. The __md5__ field has always  been used to check if the template has changed (ie when there's an update) so that we can update the config file as needed.

The latest version of cinnamon introduced the ability to override settings at the distro level through a separate file in the applet's directory. In order to make sure that the settings get updated when there's a change to the override file, the md5 hash for the override file gets appended to the one that we've already been generating. The reason you see the extra md5 hash for the menu applet is because Mint includes an override file for that applet that includes Mint-specific settings parameters.
