### ISSUE TITLE
Unneeded Python2 Dependency

### ISSUE THREAD

**Issue by Nicholas-Baron** [linuxmint/cinnamon#9137]
```
 * Cinnamon version 4.4.8
   - Daily Build PPA: not used
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds)
 * Distribution - Mint 19.3
 * Intel UHD Graphics (i5-8265U) | Driver: i965-va-driver
 * 64 bit
 ```

**Issue**
I cannot find where python2 is needed in this repository, yet `apt rdepends python` shows both cinnamon and cinnamon-common as needing python2.

**Steps to reproduce**
A small script which shows the dependency
``` bash
REASONS=$(mktemp XXXXX)
HAVE=$(mktemp XXXXX)

apt rdepends "$1" | awk '{$1=$1};1' | tr -d '|' | sort -u > "$REASONS"
apt-mark showmanual | sort -u > "$HAVE"

printf "%s is used by:\n" "$1"
comm -12 "$REASONS" "$HAVE" | tee "$1".txt

rm "$REASONS" "$HAVE"
```
**Expected behavior**
Python2 should not be a dependency as
1. Python2 is [being "sunsetted"](https://www.python.org/doc/sunset-python-2/)
2. No `.py` seems to explicitly need Python2.

**Other information**
Other cinnamon packages installed:
```
cinnamon
cinnamon-common
cinnamon-control-center
cinnamon-control-center-data
cinnamon-desktop-data
cinnamon-l10n
cinnamon-screensaver
cinnamon-session
cinnamon-session-common
cinnamon-settings-daemon
```
**Configuration info, if applicable**
N/A

**Comment by collinss** [comment]
It's not a direct dependency, but Cinnamon does depend on gir1.2-gtk-3.0, which depends on python-gi, which finally depends on python2. Since we don't control any of these except cinnamon, and cinnamon really needs gir1.2-gtk-3.0, it's out of our hands, so I'm going to close this.

**Comment by eli-schwartz** [comment]
Why does the gtk gir depend on python-gi anyway? I don't see this on packages.debian.org, which makes sense to me because typelibs are not tied to python at all -- quite the reverse.

**Comment by collinss** [comment]
I'm guessing it's because the typelib packages are usually shipped with some python specific overrides to make certain behaviors more 'pythonic' or provide functionality that is equivalent to existing methods in c, but are not introspected/introspectible, or at least not in python (this is certainly the case with gtk). Iterators in particular are commonly overridden in python so that they can be looped over in a pythonic way. It's possible that since it's shipping with python files, whoever packaged the gir package decided that it should depend on the python-gi package (especially since python is usually the reason for using introspection, and it won't work without python-gi). It's probably not strictly necessary, but most people are probably going to need python-gi if they install the gir anyway.

**Comment by eli-schwartz** [comment]
Well, that would be totally wrong, then. :/

"Not strictly necessary" ends up being "depends on python2 when people want to use it from python, but specifically version 3.x".

Anyway, I'm still curious why I don't see this on packages.debian.org -- is this specific to Linux Mint's repositories? Which version of Debian/Ubuntu is it imported from, otherwise?

It seems like this is a packaging bug which should be fixed.

**Comment by collinss** [comment]
So I just did a bit more investigating, and it seems I was wrong. While python-gi is listed in the dependencies of the gtk gir package, it's just a breaking dep on older versions of python-gi, not an actual dep. I then ran through all the dependencies of cinnamon (and their dependencies, etc) and there are no explicit dependencies on python2 packages - only python3, so I'm really not sure why it's showing up as a dep of cinnamon. That being said, if I try to remove the python package in synaptic it doesn't try to remove cinnamon. It could be that logic of the redepends command is broken, or else it's including recommends as well as depends. Either way, cinnamon doesn't seem to actually depend on python2.
