### ISSUE TITLE
[Feature Request] Could you add "Run with Nvidia" to Cinnamon menu for nvidia-prime's new on-demand mode

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/cinnamon#9292]
Hi,

Could you add "Run with Nvidia" to Cinnamon menu's context menu for nvidia-prime's new on-demand mode. This feature is already available for Bumblebee on Cinnamon menu, so it can be easy to adapt it to nvidia-prime's on-demand mode.

Feature can be activated according to output of the command below and application can be run with the nvidia-optimus-offload-glx command.

```
prime-slecet query
on-demand
```

You can look following link for cross distro solution. Gnome Shell's switcheroo-control feature can be implamanted to Cinnamon

http://www.hadess.net/2020/05/dual-gpu-support-launch-on-discrete-gpu.html

Best regards
Gökhan Gökkaya

**Comment by clefebvre** [comment]
Thanks, this is planned for the next release already.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/3958272ec3d4767fcab12a64a349731c19f13c31

**Comment by kelebek333** [comment]
Thanks  a lot.

Also, could you add discrete AMD GPU support for context menu. As you know, hybrid AMD GPU devices uses with following command.

`dri_prime=1 command`

Thank you very much for your interest

@clefebvre  @mtwebster

**Comment by Leopard1907** [comment]
Yes , in fact that `DRI_PRIME` variable was only working with OpenGL apps , while Vulkan ones within DXVK context always picks up gpu1 automatically ( not 0) , native game ports like Feral Interactive offers a device selection on their launcher but games like Doom 2016 etc were problematic in this regard and it was only possible to dgpu on AMD systems with layers like this.

https://github.com/aejsmith/vkdevicechooser

However , with Mesa 20.1 this is not a problem anymore asince this commit.

https://cgit.freedesktop.org/mesa/mesa/commit/?id=9bc5b2d169d3a3c9d52fc30987eaba52e3b7dc00

https://www.phoronix.com/scan.php?page=news_item&px=Mesa-20.1-Vulkan-Dev-Selection

So extending this " Run with dgpu ( nvidia ) " feature to AMD systems also would be great. 

I'm aware Mint 20 probably won't be shipping with Mesa 20.1 but since people does gaming on Ubuntu based distros are used to add ppa's to their systems for staying up-to-date , it won't be a problem.

https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa
