### ISSUE TITLE
Mint 20, Cinnamon, "normal" fractional scaling 2 issues. Pixelated fonts and screen tearing.

### ISSUE THREAD

**Issue by nfm886** [linuxmint/cinnamon#9429]
```
 * Cinnamon 4.6.6
   - No daily builds PPA
 * Linux Mint 20 Cinnamon
 * Graphics hardware *and* driver used
   - VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
	Subsystem: Huawei Technologies Co., Ltd. UHD Graphics 620
	Kernel driver in use: i915
	Kernel modules: i915
 * 64 bit
 ```

**Issue**
When interface scale is set to normal and 200%, fonts are pixelated and there is horrible screen tearing. Setting double HiDPI makes fonts smooth but interface is not scaled properly. I will show it on print screens.

Double HiDPI: https://imgur.com/a/4f4wjnT
Normal 200%: https://imgur.com/a/tXQ7rTB

As you can see, UI is scaled much better with normal 200%.
I love how normal 200% scaling everything. It's work beautiful except fonts and screen tearing.
There is shots showing fonts, I hope you will see the difference:

Double HiDPI: https://imgur.com/a/0NPHG2n
Normal 200%: https://imgur.com/a/GVYGKFS

The second issue is horrible screen tearing. Unfortunately I can't show it. I will try to record a video later and show you. No matter what v-sync method is set. It looks like screen is teared in one spot.

**Steps to reproduce**

Go to Settings > Display > set Interface Scale to Normal > Enable Fractional Scaling and set it to 200%.

**Expected behaviour**

Beautiful fonts and no screen tearing.

**Other information**

There is also difference between touchpad acceleration and speed. But I don't think this is an issue.

My screen resolution: 3000x2000
Screen ratio 3:2
Screen size: 13,9"

**Comment by howdev** [comment]
the 200% scaling from fractional scaling settings which is a screen scaling differs to Double HiDPi Gtk scaling.  Gtk scaling is the best option for 2x scaling. The Mint 20 fractional scaling is found to be very blurry with fonts and images. It looks like low resolution on a high resolution screen.  The result looks worst than Ubuntu 20.04 fractional scaling that I tried.

**Comment by nfm886** [comment]
There is a video showing screen tearing: https://streamable.com/kchp0b

`Gtk scaling is the best option for 2x scaling.`

Gtk scaling is not best option, what you can see on pictures from gimp above. Controls, icons and text are scaled better with 200% scaling. Controls and icons are smaller with Gtk scaling. And it's a main reason why 200% scaling is better in my opinion. 
The only problems to solve is with pixelated fonts (images are not that blurry) and screen tearing.

**Comment by howdev** [comment]
best is to mean best in sharpness maintaning the resolution quality and Gtk does this well because of integer scale. If you lose the sharpness in text, image quality is also lost. The fractional scaling is same result as using a lower resolution. There is bit of blurry in MacOS too but the quality is near unscaled. 

I also can confirmed the tearing is terrible, it is as though the vsync is turned off in cinnamon settings.

**Comment by Zaharid** [comment]
I have a similar problem with screen tearing. When I turn on "Fractional Scaling" from the Display options the tearing is very noticeable and none of the options regarding VSync in "Refresh Rate" or System Settings > General > "Compositor Options" appear to have any effect. My graphic settings are

```
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
  resolution: 2560x1440~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 20.2.6 
```

**Comment by abdulbasetbasher** [comment]
Can this be fixed even with workaround?

**Comment by JosephMcc** [comment]
I think @howdev above explained the issue fairly well. Integer scaling (the User interface scale) setting is best because a lot of toolkits support it natively. Some, like Gtk2 which  Gimp uses, do not support it and don't work well with it. 

The fractional scaling works much the same way as scaling an image in Gimp. You cannot scale it and expect it to look the same. And it's done on the fly so is going to come with performance issues. How it looks and performs can vary between hardware setups and what each individual finds acceptable, as well as the specific settings you choose to use.

This is noted in the tooltip for the setting as well as the fact that it's experimental.
