### ISSUE TITLE
option to disable /var/log/installer/telemetry during install

### ISSUE THREAD

**Issue by smerdysmerdy** [linuxmint/cinnamon#9467]
Mint 20

option to disable and not write nor transmit /var/log/installer/telemetry for installing Mint 20

You can move this issue to the Mint installer repository, I cannot find it

I do not wish to write nor transmit this file at all

I saw no disclosure (nor a choice) for this during the installation UI, I saw nothing at all until I discovered it after the fact in the log folder and that pissed me off big time, I didn't install Mint to be spied upon and things done behind my back without my knowledge or approval, I don't care if it is anonymised or not, I simply want rid of this shit

Spare me the arguments it is Ubuntu or it goes to improve Linux Mint, I simply will respond with sending shite data back and blaming it on Mint

Anybody asks me if Mint is good, I say sure, but watch out, Mint spies on you during install

**Comment by clefebvre** [comment]
This looks like a non-issue to me.

- The file is created by ubiquity (the installer)
- It is stored locally in the installed system.
- It isn't uploaded or transmitted anywhere.
- It doesn't contain any sensitive data.

I wasn't aware of this file and I have to say I find it very useful for troubleshooting installation problems. I wish we had known about it during BETA. We often ask people what choices they made during the installation to be able to reproduce an issue (what language they picked, whether or not they chose the codecs etc..) and this seems to have this logged.

Unless you choose to upload it, that data is yours only and it doesn't seem to contain anything sensitive. I'm not asking you to upload it here, but if there's something in that file that you think shouldn't be logged for privacy reasons, then please mention it and explain why.

PS: As requested, I spared you the argument of this being added by Ubuntu (https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1755456). You don't need to respond to that. We don't spy on people. Anybody says we do, we tell them to check the source code and we call them liars. This is blunt because it's not nice not to be given the benefit of the doubt, especially here when the doubt was easily cleared up. I leave this open in case the data isn't OK.

**Comment by clefebvre** [comment]
Link to the relevant source code: https://github.com/linuxmint/ubiquity/tree/20.04.15.
