### ISSUE TITLE
Keybinds of Super+1 (2, 3, 4, etc) are ignored

### ISSUE THREAD

**Issue by alexgv99** [linuxmint/cinnamon#9481]
```
 * Cinnamon version 4.6.6
 * Distribution - Mint 20 - Ulyana
 * Graphics hardware *and* driver used: Nvidia-driver-440.100-0ubuntu0.20.04.1
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
```
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/4967596/xsession-errors.zip)

**Issue**
I mapped Super+1, Super+2, Super+3, Super+4 to Switch to workspace 1 to 4 respectively. However, the default mapping is the one actively working yet. When I press Super+1 it opens the first app in Panel (Chrome), when I press Super+2 it opens the second app in Panel (Firefox) and so on... 

**Steps to reproduce**
Open keyboard in Mint Menu;
Switch to shortcuts tab;
Select Workspaces in categories;
then Direct Navigation (inner category);
Select Switch to workspace 1 on the top right panel;
Double click the first keyboard binding in the bottom right panel;
Press Super + 1

repeat the sequence for Switch to workspace 2, 3 and 4, replacing the mapping for Super + 2, 3 and 4, respectively.

Then, close the keyboard app and press Super + 2

**Expected behaviour**
It should change to the workspace 2, but instead, it opens the second app pinned in the Panel (aside of Mint Menu)

**Other information**
Upgrade from 19.3 to 20 yesterday.

**Comment by mtwebster** [comment]
These shortcuts are used by the grouped window list applet (which is why it's activating apps in your panel).

Unfortunately we can't currently detect keybinding collisions between applets and built-in functions.  You can disable this feature in the grouped window list applet by opening its preferences, and disabling it in the General tab.  This should allow your workspace shortcuts to function.

**Comment by alexgv99** [comment]
Thanks... disable that option solve the problem.
