### ISSUE TITLE
Cinnamon menu only searches on start of text

### ISSUE THREAD

**Issue by netjerykhet** [linuxmint/cinnamon#9502]
Typing `tooth` into Cinnamon's search bar results in no found objects in the menu.

Typing `blue` into Cinnamon's search bar results in finding the Bluetooth object in the menu.

The observed behaviour is that Cinnamon's menu only looks at the start of words found in the object's properties.

The only way around this limitation is to manually edit the entries and add the desired search terms to the Comments property.

The expected behaviour is that Cinnamon's menu finds all objects with the typed word contained anywhere in the object's properties, not just the start of words in those properties.

**Comment by leigh123linux** [comment]
Please reformat your issue 

```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
 ```

**Issue**



**Steps to reproduce**



**Expected behaviour**



**Other information**


**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by NikoKrause** [comment]
Fixed by https://github.com/linuxmint/cinnamon/pull/9598
