### ISSUE TITLE
Cannot assign numpad keys as shortcut keys

### ISSUE THREAD

**Issue by Signum** [linuxmint/cinnamon#9518]
```
 * Cinnamon version 4.6.7
 * Distribution - Mint 20
 * 64 bit
 ```

**Issue**

Numpad keys cannot be used as keyboard shortcuts without keys like Ctrl, Alt or Super. Cinnamon considers them dangerous to use as shortcuts.

**Steps to reproduce**

Open the Settings. Go to Keyboard. Try to assign a numpad key to an action.
A dialog appears telling that this shortcut cannot be assigned because it would make it impossible to type.

I found a workaround by installing "dconf-editor" and going to /org/cinnamon/desktop/keybindings/wm/ and change the assigned key manually. I consider this not user-friendly though.

**Expected behaviour**

I would like to use numpad keys for shortcuts.

**Other information**

For the past 15 years I have been using the numpad to switch between virtual desktops. I assign each desktop to a number key.  This refers to the "switch-to-workspace-1" action for example. I do not use the numpad for any other purpose so the keys are perfect for workspace switching. I find pressing a qualifier key like "Super" annoying. Other desktop environments do not mind assigning numpad keys. I wish that Cinnamon in Mint would allow that to. Maybe issue a warning but let the use do it anyway.
Thank you for considering that.

**Comment by doug-last** [comment]
I was about to request the same.

Use case:
I was trying to use numpad as a virtual "stream deck" when numlock is off, and regular numpad when numlock is on.

Other:
I never used the numpad with numlock off for nothing.
Why not ctrl+something ? because while i'm streaming i'm also playing and it becomes too much keys to find and press at once and disrupts the stream, or i have to stop walking or doing the game related action to perform desktop/obs related action.
