### ISSUE TITLE
Adding a Duration to the Video folder

### ISSUE THREAD

**Issue by Ubuntu-2020** [linuxmint/cinnamon#9615]
In the **Nemo** file Manager **Linux Mint 20 Cinnamon**, we can select a **List View**.
We can also add the columns we need. But the item **Duration** is missing from this list:
![Linux-Mint-20-Cinnamon-Nemo-List View](https://user-images.githubusercontent.com/65112331/95204192-6b5f0e00-07ec-11eb-9d1b-5989d60bdffa.gif)

Here is an example of a similar list in **Windows**:
![windows-10-select-detail-columns](https://user-images.githubusercontent.com/65112331/95204229-75810c80-07ec-11eb-82ec-69fc82dc9802.png)

So please add the item **Duration**.
I suggest adding the **Duration** column to the table in the **Video folder** by default.

In **Windows** if you make a table view in the **Video folder** you can see that the **Duration** is enabled by default!

**Comment by mtwebster** [comment]
You can install the 'nemo-media-columns' plugin, which will give you a number of additional columns you can turn on (including 'length')

**Comment by Ubuntu-2020** [comment]
@mtwebster Why not add a Default **Duration/Length**? Why do users need to reinstall something?

**Comment by mtwebster** [comment]
Because these additional specialized properties add extra specialized packages that aren't needed for a majority of users, not to mention it can incur a performance penalty, so it's something users opt into. The same holds for other media types.

**Comment by Ubuntu-2020** [comment]
@mtwebster I think that users should decide which columns they want to see in the table. So you can create a **poll**?

**Comment by mtwebster** [comment]
They already can decide. To see additional columns specific to various different media types, nemo-media-columns needs to be installed. The one thing I can see we could improve upon is making this simpler to discover and/or install from nemo itself.

Sorry but I don't see the need for a poll. We've discussed having these extras installed from the outset and decided against it in the past due to reasons I already mentioned.
