### ISSUE TITLE
Chrome tabs unresponsive, glitching, erratic

### ISSUE THREAD

**Issue by MNT2020** [linuxmint/cinnamon#9700]
```
 * Cinnamon 4.6.7
 * Mint 20
 * Intel 2nd Generation Core Processor Family Integrated Graphics (driver: i915)
 * 64 bit
 ```

**Issue**
Top of the tabs in Google Chrome (86.0.4240.198) often doesn't respond to mouse click (can't switch, move, etc.). Firefox works fine

**Steps to reproduce**
Open two or more tabs and try to switch tabs clicking on the top of them

**Expected behaviour**
Normal, like it was in Mint 19 and Chrome 84

**Other information**
https://streamable.com/rg85f7
```

**Comment by Lurux** [comment]
HOW IS THIS RELATED TO CINNAMON IN ANY WAY ?

Gosh, people should stop posting completely useless or irrelevant issues so developers can actually concentrate on getting actual work done !

**Comment by JosephMcc** [comment]
@Lurux There is no reason to be rude.

@MNT2020 From your video it looks like the problem is it doesn't respond to mouse click when you are at the very top of the screen. It looks like it works fine when you click on the actual tab. Essentially though @Lurux is correct. This doesn't look like an issue with Cinnamon but with Chrome.
