### ISSUE TITLE
Spices management improvements

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/cinnamon#9912]
There are a couple of issues in regards to spice management which need to be addressed.

It's not clear to users that they're installing software which isn't core. It's also not really clear what they're installing. When browsing for spices, these are shown in English with some icons... once installed they're translated and can even use a different icon... so they're hard to find and hard to match and thus hard to identify.

We also want to show authors (who don't necessarily match the uuid) so that users can filter and search by author. If they like a particular spice they might want to see what else a particular author worked on.

- [x] Tag all maintainers so they're aware of the changes going on
- [x] Show uuids
- [x] Show author
- [x] Ensure the icon is the same everywhere
- [x] Translate download tab:
- DRAFT for metadata.pot: https://github.com/NikoKrause/cinnamon-spices-applets/tree/metadata-pot/.metadata-translations
- [x] Add CI validation to github
- [x] Fix page switcher in CI website

**Comment by clefebvre** [comment]
To show UUIDs: https://github.com/linuxmint/cinnamon/pull/9911

**Comment by NikoKrause** [comment]
- [x] Same icon everywhere for applets: https://github.com/linuxmint/cinnamon-spices-applets/pull/3514
- [ ] Same icon everywhere for desklets
- [ ] Same icon everywhere for extensions

**Comment by clefebvre** [comment]
Tagging all maintainers:

@AleksiMagner @bpivaty @brownsr @cardsurf @centurix @claudiux @Cobinja @collinss @ctrlesc @Driglu4it @edaubert @fahrinh @feuerfuchs @foobar-beer @germanfr @gfreeau @gnemonix @hernejj @Hukuta @hulygun @hyOzd @icarter09 @imDeprecated @jake1164 @jamesmorgan @Jeremy Gillula @lauritsriple @lerc @linux-man @marvel4u @mockturtl @mohammad-sn @narutrey @Nicolas01 @nicoulaj @NikoKrause @omidmaldar @orcuscz @pdcurtis @pixunil @PrimaMateria @raphaelquintao @SamBurgos @Shatur95 @simonwiles @spacy01 @stefan12O @sumo @szlldm @tuuxx @vitaliis @willurd @wrouesnel @zablotski @zeripath

**Comment by clefebvre** [comment]
@zablotski @zeripath

**Comment by clefebvre** [comment]
### Rationale for the icons

Here's the current situation:

- The icon of the applet is needed both by Cinnamon and by the website.
- Cinnamon looks for an icon name in UUID/metadata.json or failing that for UUID/icon.png.
- The website cannot use icon names, so it requires a mandatory /icon.png.

Here's the problem:

- When /icon.png and UUID/icon.png differ the icon on the website and in Cinnamon differ.
- When an icon name is used in the metadata, the icons also differ.
- Before an applet is actually downloaded, Cinnamon doesn't have access to the UUID directory content (i.e. the content of the ZIP file) so it shows the same icon as used by the website. This means that when the icon differs between the website and cinnamon's management tab, it also differs between cinnamon's download and management tabs!

Here's the solution we're implementing:

- We're abandoning icon names (in metadata).
- We're making UUID/icon.png mandatory and getting rid of /icon.png on github (this is to make it easier for maintainers to work on their local copy).
- The website will use UUID/icon.png instead of /icon.png.

On the maintainer's side of thing (on github), there should only be one icon.png and it should be in the files/UUID directory. The validator is being modified to check that.

If people want to include an icon.svg, that's fine but it needs to remain in /... and not be included in the ZIP.

**Comment by clefebvre** [comment]
Another quick note on icon.png, there's no need to duplicate it in each multiversion. The only file you need now is in UUID/files/UUID/icon.png.

**Comment by Drugwash2** [comment]
For what it's worth I would like to draw everyone's attention upon a certain issue that may seem minor but not in all situations.
While working to improve an applet I noticed an odd behavior related to its tray icon. When the tray icon is a SVG image (as opposed to a PNG) the tooltip - when icon is hovered with the mouse cursor - stays on for a very limited amount of time and then vanishes, while the cursor tip is over a transparent/empty area. However, when the cursor hovers a solid area of the icon  the tooltip stays on indefinitely.

Now, I don't know which behavior is the correct one, but at least from the point of view of the applet I've been working on the latter would be preferrable because the tooltip should provide real-time feedback on the scrolling action happening over the icon. And ideally the entire icon area regardless of its size should be reacting to mouse hover, regardless of the solid and transparent areas that compose it.

I have no idea where this issue stems from and if it can be fixed - easily or ever - but for the very least, since you're dealing with icons at this very moment - you may wanna notify all spices developers about this issue and recommend that whenever possible they should use PNG images for tray icons instead of SVG, at least until the issue is fixed. Thank you.

**Comment by Drugwash2** [comment]
Actually after more testing it turns out the tooltip also dissapears shortly when hovering transparent areas of PNG icons and even text fields. So it's not only a problem with SVG but with the way the system interprets the relation between cursor movement, pixel under cursor's hotspot, actual icon area, and highlighted area around icon.

Let's take as example an icon similar to this: [ ▀ ] Upper half is solid color, lower half is blank/transparent. Square brackets represent the hilighted area around the icon. Now, when cursor hotspot enters for the first time the highlighted area, the tooltip is shown. If the hotspot is moved (fast enough) to the top solid area and movement remains confined to it the tooltip keeps showing indefinitely. Which is good. However, if the hotspot is moved to the bottom blank area or outside the icon area but still inside the highlight area the tooltip dissapears. Now, while hotspot remains over such blank area any slight subsequent movement seems to trigger a toggle-like response: first move shows the tooltip, next one hides it, next one shows it again, and so on.

As mentioned above, ideally the tooltip would stay on unconditionally for as long as the cursor hotspot remains or moves anywhere inside the highlighted area (which comprises the icon), regardless of any pixel transparency.

Hopefully the issue has been explained properly. If it's already known then I apologyze - can't find my way around this site.

**Comment by clefebvre** [comment]
All done here, closing. Everything's been pushed.

@Drugwash2 create an issue for this since it's separate. Don't hesitate to put screenshots and which applet you're using to reproduce the issue, make it easy for devs to reproduce it themselves.
